### ISSUE TITLE
How to close LettuceListCommands.bLPop gracefully 

### ISSUE THREAD

**Issue by youngerier** [lettuce-io/lettuce-core#1012]
I had write this following code but  `redisTemplate.opsForList().leftPop(addContactListCacheKey1, 3, TimeUnit.MINUTES);` this line of code stop program exit gracefully  .I had asked for help on `https://jira.spring.io/browse/DATAREDIS-961?focusedCommentId=182689&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-182689`  and add  synchronized block but It not work . Can someone help Thanks a lot
```java
  private final AtomicInteger FLAG = new AtomicInteger(0);

    @PostConstruct
    public void init() {
        executorService
                .submit(() -> {
                    for (; ; ) {
                        try {
                            synchronized (FLAG) {
 
                                String val;
                                val = redisTemplate.opsForList().leftPop(addContactListCacheKey1, 3, TimeUnit.MINUTES);
                                if (!Strings.isNullOrEmpty(val)) {
                                    List<ContactParam> params = objectMapper.readValue(val, new TypeReference<List<ContactParam>>() {
                                    });
                                    this.insertContact0(params);
                                    rateLimiter.acquire();
                                }
                            }
                        } catch (Exception e) {
                            log.error(e.getMessage(), e);
                        }
                    }
                });
    }
```

```java
[2019-04-10 17:06:57.951] [#ContactConsumer - 0 ] ERROR c.o.d.s.impl.WxContactServiceImpl.lambda$init$0 - Redis exception; nested exception is io.lettuce.core.RedisException: Connection is closed
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: Connection is closed
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
        at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:257)
        at org.springframework.data.redis.connection.lettuce.LettuceListCommands.convertLettuceAccessException(LettuceListCommands.java:490)
        at org.springframework.data.redis.connection.lettuce.LettuceListCommands.bLPop(LettuceListCommands.java:382)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.bLPop(DefaultedRedisConnection.java:471)
        at org.springframework.data.redis.connection.DefaultStringRedisConnection.bLPop(DefaultStringRedisConnection.java:189)
        at org.springframework.data.redis.core.DefaultListOperations$3.inRedis(DefaultListOperations.java:84)
        at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:59)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
        at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
        at org.springframework.data.redis.core.DefaultListOperations.leftPop(DefaultListOperations.java:80)
        at com.oucloud.data.service.impl.WxContactServiceImpl.lambda$init$0(WxContactServiceImpl.java:118)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisException: Connection is closed
        at io.lettuce.core.protocol.DefaultEndpoint.validateWrite(DefaultEndpoint.java:195)
        at io.lettuce.core.protocol.DefaultEndpoint.write(DefaultEndpoint.java:137)
        at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:187)
        at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:152)
        at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:467)
        at io.lettuce.core.AbstractRedisAsyncCommands.blpop(AbstractRedisAsyncCommands.java:151)
        at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:57)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy264.blpop(Unknown Source)
        at org.springframework.data.redis.connection.lettuce.LettuceListCommands.bLPop(LettuceListCommands.java:380)
        ... 13 common frames omitted
[2019-04-10 17:06:57.951] [#ContactConsumer - 0 ] ERROR c.o.d.s.impl.WxContactServiceImpl.lambda$init$0 - Redis exception; nested exception is io.lettuce.core.RedisException: Connection is closed
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: Connection is closed
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
        at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:257)
        at org.springframework.data.redis.connection.lettuce.LettuceListCommands.convertLettuceAccessException(LettuceListCommands.java:490)
        at org.springframework.data.redis.connection.lettuce.LettuceListCommands.bLPop(LettuceListCommands.java:382)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.bLPop(DefaultedRedisConnection.java:471)
        at org.springframework.data.redis.connection.DefaultStringRedisConnection.bLPop(DefaultStringRedisConnection.java:189)
        at org.springframework.data.redis.core.DefaultListOperations$3.inRedis(DefaultListOperations.java:84)
        at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:59)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
        at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
        at org.springframework.data.redis.core.DefaultListOperations.leftPop(DefaultListOperations.java:80)
        at com.oucloud.data.service.impl.WxContactServiceImpl.lambda$init$0(WxContactServiceImpl.java:118)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


```

**Comment by mp911de** [comment]
Your `for`-loop is unconditional. You need to exit it on application termination. This is not a general programming advice forum, but specific to Lettuce. Check out programming resources and learn how to properly develop multi-threaded code.

**Comment by youngerier** [comment]
I am sorry ,but even code following . The process can not exit  ,I am confused
```  
  @Override
    public void run() {

        String s = stringRedisTemplate.opsForList().leftPop(cacheKey, 3, TimeUnit.SECONDS);
    }
```
and if I replase with following ,process can exit 
```  
  @Override
    public void run() {

        String s = stringRedisTemplate.opsForList().leftPop(cacheKey, 3, TimeUnit.SECONDS);
    }
```
