### ISSUE TITLE
how to find cause of RedisCommandTimeoutException by log?

### ISSUE THREAD

**Issue by wufengqiyun** [lettuce-io/lettuce-core#1028]
【lettuce-version】5.1.2.RELEASE
【redis-version】3.2.9
【spring-data-redis】2.1.2 RELEASE
## Question Report
Hello~ I am a rookie in using lettuce, when using lettuce in the project and set timeout= 150ms, sometimes I can see QueryTimeoutException as below, and I don't know why it happened...I have tried to change the configurations like socket、 tcp-keepalive and use a connection pool to solve it but failed.
The Exception is：
```
[GET]Failed.key=xxxxxx
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 150 millisecond(s)
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
        at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
        at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
        at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:68)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:253)
        at org.springframework.data.redis.connection.DefaultStringRedisConnection.get(DefaultStringRedisConnection.java:377)
        at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57)
        at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:59)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
        at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
        at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53)
        at com.netease.mail.yanxuan.rms.cache.redis.spring.AbstractRedisClient.get(AbstractRedisClient.java:496)
       。。。。。。
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 150 millisecond(s)
        at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
        at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
        at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy69.get(Unknown Source)
        at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:66)
        ... 66 common frames omitted
```
after checking the debug log, it seems that the timeout happened after
```
00:57:43.525 [lettuce-nioEventLoop-4-6] DEBUG i.l.core.protocol.CommandHandler - [channel=0x833d0c11, /10.200.169.160:29547 -> /10.200.177.13:16380, chid=0x1e] write(ctx, ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=5], promise)
```
after this log, the next log is printed at 00:57:44.113, means timeout
happened. I can see other commands without timeout  have two more logs with prefix like lettuce-nioEventLoop-a-b (together 3 logs) , such as:
```
00:57:43.525 [lettuce-nioEventLoop-4-8] DEBUG i.l.core.protocol.CommandHandler - [channel=0x742eb139, /10.200.169.160:50634 -> /10.200.169.225:16380, chid=0x20] Received: 11 bytes, 1 commands in the stack
00:57:43.525 [lettuce-nioEventLoop-4-8] DEBUG i.l.core.protocol.CommandHandler - [channel=0x742eb139, /10.200.169.160:50634 -> /10.200.169.225:16380, chid=0x20] Stack contains: 1 commands
```
but the command which caused timeout not (just 1 log), so .. how can I find why timeout happened?

## Another question
the log stack contains is always 1 command, is it normal? For example 
```
1 commands in the stack
Stack contains: 1 commands
```
Sorry my English is pool, thank for your time to look at my question~

**Comment by mp911de** [comment]
Command timeouts are usual to happen. If Redis responds with a lot of data, Redis Cluster issues redirects, you have very small timeouts or if you set `setAutoFlushCommands(…)`, then timeouts are likely to happen.

The log above contains multiple times the exact same time value (`00:57:43.525`) for different connections. It's easy to tell these are different connections because different connections typically run on different event loop threads. Also, channel Id's are different. When analyzing a command message flow, make sure to group same channelId's.

> the log stack contains is always 1 command, is it normal? For example

Yes, if there is a single command that was sent, a single command awaits response processing. On systems with higher loads, these numbers are higher.

> how can I find why timeout happened?

You need to analyze the log to reconstruct the command flow to see which command took a long time to execute.

There's nothing more we can do from our side, therefore closing this ticket.

**Comment by wufengqiyun** [comment]
Thank you for your help~ what I mean is [lettuce-nioEventLoop-4-6] and [lettuce-nioEventLoop-4-8] happens at the same time, and [lettuce-nioEventLoop-4-8] is normal which has three logs, the [lettuce-nioEventLoop-4-6] is one of timeout commands so it just has 1 log, because of the timeout it didn't have the log including 'Received:'. 
I will check If Redis responds with a lot of data and the `setAutoFlushCommands` , thank you

**Comment by mp911de** [comment]
The log event above indicates that the command was written to the transport. So it's now outside of the client and somewhere between your network interface and your Redis server. If there was no received log event this means that Redis didn't respond.

**Comment by wufengqiyun** [comment]
> The log event above indicates that the command was written to the transport. So it's now outside of the client and somewhere between your network interface and your Redis server. If there was no received log event this means that Redis didn't respond.

Thank you very much!
