### ISSUE TITLE
CommandHanlder's stack out of sync after EncoderException

### ISSUE THREAD

**Issue by fangwentong** [lettuce-io/lettuce-core#1029]
#### Current Behavior

I am using lettuce 5.1.4.RELEASE,  submitted an async zadd command which cause EncoderException, the unexpected thing is that all the following correct command throws TimeoutException

After debug, it turns out CommandHandler's stack out of sync, the encode failed command was added to stack, but no corresponding netty channelRead callback.  since the stack has an unwanted command, all the following callback will always mismatch with the command poll from the stack.

<details>
<summary>Stack trace</summary>

```java
io.lettuce.core.RedisException: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:129)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy0.zadd(Unknown Source)
	at test.LettuceEncoderExceptionTest.main(LettuceEncoderExceptionTest.java:24)
Caused by: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:93)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:75)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:414)
	at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1104)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1151)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1075)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:271)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at io.lettuce.core.codec.StringCodec.encodeValue(StringCodec.java:39)
	at io.lettuce.core.protocol.CommandArgs$ValueArgument.encode(CommandArgs.java:702)
	at io.lettuce.core.protocol.CommandArgs.encode(CommandArgs.java:346)
	at io.lettuce.core.protocol.Command.encode(Command.java:119)
	at io.lettuce.core.protocol.AsyncCommand.encode(AsyncCommand.java:185)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:90)
	... 20 more

io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at test.LettuceEncoderExceptionTest.main(LettuceEncoderExceptionTest.java:33)

io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at test.LettuceEncoderExceptionTest.main(LettuceEncoderExceptionTest.java:33)

io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at test.LettuceEncoderExceptionTest.main(LettuceEncoderExceptionTest.java:33)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
    public static void main(String[] args) {
        RedisClient client = RedisClient.create("redis://127.0.0.1:6479");
        StatefulRedisConnection<String, String> connection = client.connect();

        try {
            // async zadd an ScoredValue with wrong value type
            connection.async().zadd("test_zadd", ScoredValue.just(1, 100)).get();
        } catch (Exception e) {
            System.err.println(ExceptionUtils.getStackTrace(e));
        }

        for (int i = 0; i < 3; i++) {
            try {
                RedisFuture<String> future = connection.async().get("test_get_" + i);
                // command always timeout, connection unavailable
                LettuceFutures.awaitOrCancel(future, 5, TimeUnit.SECONDS);
            } catch (Exception e) {
                System.err.println(ExceptionUtils.getStackTrace(e));
            }
        }
    }
```

when I get

</details>

#### Expected behavior/code

Since many command share the same lettuce connection,  I think the EncoderException of single command should not break the following command. That is, the following command should not time out.

#### Environment

- Lettuce version(s): 5.1.4.RELEASE
- Redis version: 5.0.4

#### Possible Solution

We can check the command's exception in `CommandHandler.AddToStack#operationComplete`, before add it to stack. If the command was completeExceptionally with EncoderException, discard the command, rather than put it to stack

**Comment by mp911de** [comment]
Thanks for looking into that. 

Adding fallback behavior for single commands causes inconsistency between command batches and single commands. We moved command encoding to the EventLoop for improved buffer pooling behavior (i.e. guarantee that we do not leak buffers. Encoding happens after processing the command in `CommandHandler`.

We also have code paths for `void` commands (i.e. where we expect no response) and these would not be handled, too.

All in all, command encoders must ensure to not fail. If they fail, then you need to fix that problem and not work around it. Therefore, we won't add any workaround.
