### ISSUE TITLE
Unexpected RedisCommandTimeoutException thrown at RedisCommands.blpop(0, someKey) with master/slave config

### ISSUE THREAD

**Issue by federico-peralta-schaffner** [lettuce-io/lettuce-core#1038]
#### Current Behavior

The caller thread crashes while blocked on a `blpop(0, someKey)` operation.

Redis config is master/slave, redis setup as per [this article](https://linuxtechlab.com/configuring-redis-master-slave-setup/). 

There are no other requests, i.e. the database is under no load, there are no other connections.

`StatefulRedisMasterSlaveConnection` is used and both master and slave's URIs are passed as arguments to the `MasterSlave.connect(client, codec, uris)` method (`uris` contains both uris).

<details>

<summary>Stack trace</summary>

```java
Exception in thread "main" io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy13.blpop(Unknown Source)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java

RedisClient client = RedisClient.create();
List<RedisURI> uris = Arrays.stream(redisUris)
        .map(RedisURI::create)
        .collect(Collectors.toList());
StatefulRedisMasterSlaveConnection<String, String> connection = MasterSlave.connect(
        client,
        new Utf8StringCodec(),
        uris);
connection.setReadFrom(ReadFrom.MASTER_PREFERRED);
RedisCommands<String, String> commands = connection.sync();

KeyValue<String, String> result = commands.blpop(0L, someKey);
```

</details>

#### Expected behavior/code

The call to `blpop(0, someKey)` should block forever or return `null` (or an array of `null` values) on timeout. Even though, it would be quite surprising for a blocking call to return with no data. 

As the consumer of the API, I shouldn't be required to surround the call to a blocking operation i.e. with a loop until a valid result is returned, or a non-timeout exception is thrown. Or, if this is what I'm actually expected to do, it should be clearly documented.

#### Environment

- Lettuce version(s): [5.1.6.RELEASE]
- Redis version: [Redis server v=5.0.4 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=41bb26706ca79d57]

**Comment by mp911de** [comment]
Lettuce's `RedisURI` defaults to a 60-second timeout (see [`RedisURI`](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/RedisURI.java#L161-L162)). This is an I/O setting that is not affected by individual commands that may be equipped with a timeout parameter. 

If you require unlimited timeouts, you can configure a [`TimeoutSource`](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/TimeoutOptions.java#L245) through `ClientOptions` and `TimeoutOptions` to control timeout behavior on a per-command basis.

**Comment by federico-peralta-schaffner** [comment]
Hi Mark, thank you very much for your feedback. Would you like me to post this as a question in SO, so you or someone else can answer it?

**Comment by mp911de** [comment]
Feel free to do so and cross-link.

**Comment by asherbar** [comment]
I had the same issue with BLPOP throwing `RedisCommandTimeoutException` and got to this thread. So, following @mp911de instructions, I did the following:
```
client = RedisClient.create();
TimeoutOptions.TimeoutSource timeoutSource = new TimeoutOptions.TimeoutSource() {
	@Override
	public long getTimeout(RedisCommand<?, ?, ?> redisCommand) {
		// Allow BLPOP to block forever
		if (redisCommand != null && CommandType.BLPOP.equals(redisCommand.getType())) {
			return 0;
		}
		// The rest of the commands have the default 60 second timeout
		return 60;
	}

	@Override
	public TimeUnit getTimeUnit() {
		return TimeUnit.SECONDS;
	}
};
client.setOptions(ClientOptions.builder()
		.timeoutOptions(
				TimeoutOptions.builder()
						.timeoutSource(timeoutSource)
						.build())
		.build());
```

But after 60 seconds I still get the exception:
```
Exception in thread "Thread-5" io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy53.blpop(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:210)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy53.blpop(Unknown Source)
        ...
```
What am I missing?

**Comment by mp911de** [comment]
The timeout is created from  `FutureSyncInvocationHandler`. Can you check the outcome of `FutureSyncInvocationHandler.getTimeoutNs`?

**Comment by asherbar** [comment]
I don't know how to check the outcome of `FutureSyncInvocationHandler.getTimeoutNs` but when I add logging to my implementation of `TimeoutOptions.TimeoutSource` I see that indeed the `getTimeout` method is called and returns 0 for `BLPOP` commands.
