### ISSUE TITLE
Invalid first byte: 74 with lettuce-core-5.1.5

### ISSUE THREAD

**Issue by zjw2011** [lettuce-io/lettuce-core#1045]
```
2019-05-28 10:27:52.538  INFO 76934 --- [xecutorLoop-1-3] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /127.0.0.1:3306
2019-05-28 10:27:52.549  INFO 76934 --- [ioEventLoop-4-2] i.l.core.protocol.ReconnectionHandler    : Reconnected to 127.0.0.1:3306
2019-05-28 10:27:52.556  WARN 76934 --- [ioEventLoop-4-2] io.lettuce.core.protocol.CommandHandler  : null Unexpected exception during request: io.lettuce.core.RedisException: Invalid first byte: 74

io.lettuce.core.RedisException: Invalid first byte: 74
	at io.lettuce.core.protocol.RedisStateMachine.readReplyType(RedisStateMachine.java:233) ~[lettuce-core-5.1.5.RELEASE.jar:na]
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:113) ~[lettuce-core-5.1.5.RELEASE.jar:na]
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:77) ~[lettuce-core-5.1.5.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:704) ~[lettuce-core-5.1.5.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.consumeResponse(CommandHandler.java:732) ~[lettuce-core-5.1.5.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:570) ~[lettuce-core-5.1.5.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:556) ~[lettuce-core-5.1.5.RELEASE.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by zjw2011** [comment]
[gateway-demo.zip](https://github.com/lettuce-io/lettuce-core/files/3236203/gateway-demo.zip)
this a sample!!!

**Comment by zjw2011** [comment]
I know it!!! Thank you!!!

**Comment by mp911de** [comment]
Your configuration for Redis port differs from the Redis standard which is 6379. Your config uses 3306 which is the default port for MySQL. Please make sure your Redis instance also uses 3306 to work with this configuration. Switching the port to 6370 works for me.
