### ISSUE TITLE
io.lettuce.core.RedisException: Connection is deallocated and cannot be used anymore.

### ISSUE THREAD

**Issue by caochuangui** [lettuce-io/lettuce-core#1047]
my java program onlining on 2019-05-30 14:51:00, but encounter a lettuce problem that crash my server on 2019-05-30 23:18:00. the exception description as follow：

io.lettuce.core.RedisException: Connection is deallocated and cannot be used anymore.
  at io.lettuce.core.support.ConnectionPoolSupport$ReturnObjectOnCloseInvocationHandler.handleInvocation(ConnectionPoolSupport.java:280)
  at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
  at io.lettuce.core.support.$Proxy71.async(Unknown Source)
  at com.vipkid.oceandata.transport.lettuce.RedisTemplate.async(RedisTemplate.java:25)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.updateMysql(ApiLogPond.java:85)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.triggerWater(ApiLogPond.java:68)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.triggerWater(ApiLogPond.java:28)
  at com.vipkid.oceandata.transport.core.structure.BasePond.trigger(BasePond.java:55)
  at com.vipkid.oceandata.transport.core.trigger.TransportTrigger$1.run(TransportTrigger.java:18)
  at java.util.TimerThread.mainLoop(Timer.java:5

my lettuce redis client maven version：
<dependency>
      <groupId>io.lettuce</groupId>
      <artifactId>lettuce-core</artifactId>
      <version>5.0.4.RELEASE</version>
      <exclusions>
        <exclusion>
          <groupId>io.projectreactor</groupId>
          <artifactId>reactor-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

**Comment by mp911de** [comment]
Can you please attach a bit of code how you're calling Lettuce?

**Comment by caochuangui** [comment]
@mp911de this is my redis configuration.

![image](https://user-images.githubusercontent.com/16460297/58771633-ca54b780-85e7-11e9-9f20-8101d5d961ef.png)


import io.lettuce.core.RedisURI;
import io.lettuce.core.cluster.RedisClusterClient;
import io.lettuce.core.cluster.api.StatefulRedisClusterConnection;
import io.lettuce.core.support.ConnectionPoolSupport;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.pool2.impl.GenericObjectPool;
import org.apache.commons.pool2.impl.GenericObjectPoolConfig;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.util.Assert;
import org.springframework.util.StringUtils;

@Configuration
@EnableConfigurationProperties(RedisProperties.class)
public class RedisAutoConfiguration {

  @Bean
  public RedisClusterClient redisClusterClient(RedisProperties redisProperties) {
    return RedisClusterClient.create(getRedisUri(redisProperties.getRedisCluster()));
  }

  @Bean
  public StatefulRedisClusterConnection<String, String> statefulRedisClusterConnection(
      RedisClusterClient client)
      throws Exception {
    final GenericObjectPool<StatefulRedisClusterConnection<String, String>> pool = ConnectionPoolSupport
        .createGenericObjectPool(() ->
            client.connect(), new GenericObjectPoolConfig());
    return pool.borrowObject();
  }

  @Bean
  public RedisTemplate redisTemplate(StatefulRedisClusterConnection<String, String> connection) {
    return new RedisTemplate(connection);
  }

  List<RedisURI> getRedisUri(String cluster) {
    Assert.notNull(cluster, "Redis cluster can not be null.");
    List<RedisURI> nodes = new ArrayList<>();
    for (String node : StringUtils.commaDelimitedListToStringArray(cluster)) {
      try {
        String[] parts = StringUtils.split(node, ":");
        Assert.state(parts.length == 2, "Must be defined as 'host:port'");
        nodes.add(RedisURI.create(parts[0], Integer.valueOf(parts[1])));
      } catch (RuntimeException ex) {
        throw new IllegalStateException(
            "Invalid redis cluster" + "property '" + node + "'", ex);
      }
    }

    return nodes;
  }
}

@ConfigurationProperties(prefix = "spring.lettuce.redis")
public class RedisProperties {

  private String redisCluster;

  public String getRedisCluster() {
    return redisCluster;
  }

  public void setRedisCluster(String redisCluster) {
    this.redisCluster = redisCluster;
  }
}

import io.lettuce.core.cluster.api.StatefulRedisClusterConnection;
import io.lettuce.core.cluster.api.async.RedisAdvancedClusterAsyncCommands;
import io.lettuce.core.cluster.api.reactive.RedisAdvancedClusterReactiveCommands;
import io.lettuce.core.cluster.api.sync.RedisAdvancedClusterCommands;

public class RedisTemplate {

  private StatefulRedisClusterConnection<String, String> connection;

  public RedisTemplate() {
  }

  public RedisTemplate(
      StatefulRedisClusterConnection<String, String> connection) {
    this.connection = connection;
  }

  public RedisAdvancedClusterCommands<String, String> sync() {
    return connection.sync();
  }

  public RedisAdvancedClusterAsyncCommands<String, String> async() {
    return connection.async();
  }

  public RedisAdvancedClusterReactiveCommands<String, String> reactive() {
    return connection.reactive();
  }
}

**Comment by caochuangui** [comment]
@mp911de  is my redis configuration or redis call wrong ?

**Comment by caochuangui** [comment]
@mp911de 
2019-05-30/23:10:26.539||||^_^|[Timer-2] ERROR com.vipkid.oceandata.transport.gateway.ApiLogPond 122 - updateMysql error: od_api_log入参 start_unix_time:1559228460, cluster_uuid:dfdkujuv6cglpyuwjugz3jxdtdndebim, project_uuid:jyxkhi9ofsymwhz8mjzwk8zvuxlomps2, api_uuid:flp2apkaau8ch0zeudhl4ruyzk3h1whr, status:0
io.lettuce.core.RedisException: Connection is deallocated and cannot be used anymore.
  at io.lettuce.core.support.ConnectionPoolSupport$ReturnObjectOnCloseInvocationHandler.handleInvocation(ConnectionPoolSupport.java:280)
  at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
  at io.lettuce.core.support.$Proxy71.async(Unknown Source)
  at com.vipkid.oceandata.transport.lettuce.RedisTemplate.async(RedisTemplate.java:25)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.updateMysql(ApiLogPond.java:85)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.triggerWater(ApiLogPond.java:68)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.triggerWater(ApiLogPond.java:28)
  at com.vipkid.oceandata.transport.core.structure.BasePond.trigger(BasePond.java:55)
  at com.vipkid.oceandata.transport.core.trigger.TransportTrigger$1.run(TransportTrigger.java:18)
  at java.util.TimerThread.mainLoop(Timer.java:5

**Comment by caochuangui** [comment]
@mp911de 
2019-05-30/23:10:26.539||||^_^|[Timer-2] ERROR com.vipkid.oceandata.transport.gateway.ApiLogPond 122 - updateMysql error: 
io.lettuce.core.RedisException: Connection is deallocated and cannot be used anymore.
  at io.lettuce.core.support.ConnectionPoolSupport$ReturnObjectOnCloseInvocationHandler.handleInvocation(ConnectionPoolSupport.java:280)
  at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
  at io.lettuce.core.support.$Proxy71.async(Unknown Source)
  at com.vipkid.oceandata.transport.lettuce.RedisTemplate.async(RedisTemplate.java:25)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.updateMysql(ApiLogPond.java:85)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.triggerWater(ApiLogPond.java:68)
  at com.vipkid.oceandata.transport.gateway.ApiLogPond.triggerWater(ApiLogPond.java:28)
  at com.vipkid.oceandata.transport.core.structure.BasePond.trigger(BasePond.java:55)
  at com.vipkid.oceandata.transport.core.trigger.TransportTrigger$1.run(TransportTrigger.java:18)
  at java.util.TimerThread.mainLoop(Timer.java:5

**Comment by mp911de** [comment]
There's a lot of code but the interesting part `RedisTemplate` is missing.

**Comment by caochuangui** [comment]
@mp911de  you look carefully， I already show you the redis template
import io.lettuce.core.cluster.api.StatefulRedisClusterConnection;
import io.lettuce.core.cluster.api.async.RedisAdvancedClusterAsyncCommands;
import io.lettuce.core.cluster.api.reactive.RedisAdvancedClusterReactiveCommands;
import io.lettuce.core.cluster.api.sync.RedisAdvancedClusterCommands;

public class RedisTemplate {

private StatefulRedisClusterConnection<String, String> connection;

public RedisTemplate() {
}

public RedisTemplate(
StatefulRedisClusterConnection<String, String> connection) {
this.connection = connection;
}

public RedisAdvancedClusterCommands<String, String> sync() {
return connection.sync();
}

public RedisAdvancedClusterAsyncCommands<String, String> async() {
return connection.async();
}

public RedisAdvancedClusterReactiveCommands<String, String> reactive() {
return connection.reactive();
}
}

**Comment by mp911de** [comment]
Thanks a lot. That was an oversight from my end. 

It looks as if you're calling `.close()` somewhere and this releases the pooled connection back to the connection pool.

Apart from that, using connection pooling with a single connection does not make sense. It makes much more sense to just keep a single connection and remove the pooling code.

**Comment by mp911de** [comment]
Closing this one as we have no progress here and there's nothing left to do.
