### ISSUE TITLE
io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.

### ISSUE THREAD

**Issue by suvanakar** [lettuce-io/lettuce-core#1057]
## Bug Report
I am getting an EncoderException while trying to perform delete operation for multiple keys. The use case is I am first calling the keys() API to get all the matching key and then on top of it I am applying thenApplyAsync() within which I am calling the del() API with list of keys.

Note: I am using ObjectCodec i.e. RedisAsynvCommand<Object, Object>

#### Current Behavior

If i directly call the del() API it works fine but as soon as I put it inside the applyAsync of the response received from the keys() API it throws this exception. 

<details>
<summary>Stack trace</summary>

```java
Caused by: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:93)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:75)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:415)
	at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.lettuce.core.protocol.CommandArgs$ByteBufferArgument.writeByteBuffer(CommandArgs.java:457)
	at io.lettuce.core.protocol.CommandArgs$KeyArgument.encode(CommandArgs.java:662)
	at io.lettuce.core.protocol.CommandArgs.encode(CommandArgs.java:344)
	at io.lettuce.core.protocol.Command.encode(Command.java:119)
	at io.lettuce.core.protocol.AsyncCommand.encode(AsyncCommand.java:184)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:90)
```

</details>

#### Environment

- Lettuce version(s): 5.1.0.RELEASE

**Comment by suvanakar** [comment]
CommandArgs<K, V> args = new CommandArgs<>(codec).addKeys(keys);

--Method threw 'java.lang.NullPointerException' exception. Cannot evaluate io.lettuce.core.protocol.CommandArgs.toString()

-- this is what I can found out from the lettuce code. The class CommandArgs is throwing NullPointerException while adding the keys with ObjectCodec.

My key is of String type.

**Comment by mp911de** [comment]
What is ObjectCodec? Can you post some code?

**Comment by suvanakar** [comment]
public class ObjectCodec implements RedisCodec<Object, Object> {

    /** The charset. */
    private Charset charset = Charset.forName(RedisConstants.UTF_8_STANDARD);

    /* (non-Javadoc)
     * @see io.lettuce.core.codec.RedisCodec#decodeKey(java.nio.ByteBuffer)
     */
    @Override
    public Object decodeKey(ByteBuffer bytes) {
        return charset.decode(bytes);
    }

    /* (non-Javadoc)
     * @see io.lettuce.core.codec.RedisCodec#decodeValue(java.nio.ByteBuffer)
     */
    @Override
    public Object decodeValue(ByteBuffer bytes) {
        try {
            byte[] array = new byte[bytes.remaining()];
            bytes.get(array);
            ObjectInputStream is = new ObjectInputStream(new ByteArrayInputStream(array));
            return is.readObject();
        } catch (Exception e) {
            return null;
        }
    }

    /* (non-Javadoc)
     * @see io.lettuce.core.codec.RedisCodec#encodeKey(java.lang.Object)
     */
    @Override
    public ByteBuffer encodeKey(Object key) {
        if(key instanceof String) {
            return charset.encode((String)key);
        }
        return null;
    }

    /* (non-Javadoc)
     * @see io.lettuce.core.codec.RedisCodec#encodeValue(java.lang.Object)
     */
    @Override
    public ByteBuffer encodeValue(Object value) {
        try {
            ByteArrayOutputStream bytes = new ByteArrayOutputStream();
            ObjectOutputStream os = new ObjectOutputStream(bytes);
            os.writeObject(value);
            return ByteBuffer.wrap(bytes.toByteArray());
        } catch (IOException e) {
            return null;
        }
    }

**Comment by mp911de** [comment]
Encode methods must never return `null` and that's why you see the `EncoderException`/`NullPointerException`.

There's nothing we can do on our side. (see [Javadoc](https://lettuce.io/core/release/api/io/lettuce/core/codec/RedisCodec.html#encodeKey-K-)).

**Comment by suvanakar** [comment]
So you mean to say it should not return null for key and value, rather the application should handle it separately

**Comment by suvanakar** [comment]
I am able to fix the issue. Thanks for your response

**Comment by Mukund2900** [comment]
How did you fix this issue @suvanakar ?
