### ISSUE TITLE
the call on zadd with wrong type may cause all subsequent operations fail

### ISSUE THREAD

**Issue by areyouok** [lettuce-io/lettuce-core#1071]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
java.util.concurrent.ExecutionException: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at EncoderTest.main(EncoderTest.java:19)
Caused by: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:93)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:75)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
	at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:421)
	at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1102)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1149)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:263)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at io.lettuce.core.codec.StringCodec.encodeValue(StringCodec.java:39)
	at io.lettuce.core.protocol.CommandArgs$ValueArgument.encode(CommandArgs.java:702)
	at io.lettuce.core.protocol.CommandArgs.encode(CommandArgs.java:346)
	at io.lettuce.core.protocol.Command.encode(Command.java:119)
	at io.lettuce.core.protocol.AsyncCommand.encode(AsyncCommand.java:185)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:90)
	... 21 more
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
import java.time.Duration;

import io.lettuce.core.ClientOptions;
import io.lettuce.core.RedisClient;
import io.lettuce.core.TimeoutOptions;
import io.lettuce.core.api.StatefulRedisConnection;
import io.lettuce.core.api.async.RedisAsyncCommands;

public class EncoderTest {

    public static void main(String[] args) {
        RedisClient client = RedisClient.create("redis://localhost");
        client.setOptions(ClientOptions.builder().timeoutOptions(
                TimeoutOptions.builder().fixedTimeout(Duration.ofMillis(1000)).build()).build());
        StatefulRedisConnection<String, String> connection = client.connect();
        RedisAsyncCommands<String, String> commands = connection.async();
        try {
            commands.zadd("ZADD_KEY", 1.0, "V1", 2.0, "V2",
                    3.0, 4.0/*wrong type*/).get();
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        while (true) {
            try {
                commands.set("K", "V").get();
                System.out.println(commands.get("K").get());
                break;
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        connection.close();
        client.shutdown();
    }
}
```

</details>

#### Expected behavior/code

The zadd method has no generics type so it is easy to make a mistake. The business application server may crash since we have only one lettuce connection.

We hope current opereation may fail when this case happens, but the subsequent operations should be success.

#### Environment

- Lettuce version(s): 5.1.X, 5.2.0-SNAPSHOT

#### Possible Solution

CommandEncoder.java
```java
    private void encode(ChannelHandlerContext ctx, ByteBuf out, RedisCommand<?, ?, ?> command) {

        try {
            out.markWriterIndex();
            command.encode(out);
        } catch (RuntimeException e) {
            out.resetWriterIndex();
            /*
             * throw the ex, then
             * 1, netty wrap the ex to an EncoderException
             * 2, the MessageToByteEncoder.write method send nothing to server
             * 3, the EncoderException will cause promise set to failure.
             * 4, DefaultEndpoint.RetryListener.doComplete will not requeue the command for EncoderException
             * 5, CommandHandler.AddToStack.operationComplete will not add the 
             *        command(which is not send to server) to stack since future(promise) is not success. 
             */
            throw e;
            // the original code
            /*
            command.completeExceptionally(new EncoderException(
                    "Cannot encode command. Please close the connection as the connection state may be out of sync.",
                    e));
             */
        }

        if (debugEnabled) {
            logger.debug("{} writing command {}", logPrefix(ctx.channel()), command);
            if (traceEnabled) {
                logger.trace("{} Sent: {}", logPrefix(ctx.channel()), out.toString(Charset.defaultCharset()).trim());
            }
        }
    }
```

**Comment by areyouok** [comment]
see #1029

**Comment by mp911de** [comment]
Thanks for reporting the issue. The proposed approach works for single commands but not for batching.

**Comment by areyouok** [comment]
@mp911de you are right

or could we fix this issue like this?

https://github.com/fangwentong/lettuce-core/commit/0600ebbb2eabf648b8aff6e29db079a2ddf38d12

**Comment by mp911de** [comment]
This does not fix the issue and adding convenience API isn't the right approach.
I'm closing this PR because we are not able to find a real fix for a programming problem.
