### ISSUE TITLE
ClassCastException occurs when using RedisCommandFactory with custom commands

### ISSUE THREAD

**Issue by mdebellefeuille** [lettuce-io/lettuce-core#1075]
#### Current Behavior

when RedisCommandFactory(connection) creates a custom command generates a class cast exception when trying to cast the reactive object to AbstractRedisReactiveCommands because the reactive object has been proxied (((StatefulRedisClusterConnection) connection).reactive() is a proxy)
<details>
<summary>Stack trace</summary>

```java
java.lang.ClassCastException: com.sun.proxy.$Proxy67 cannot be cast to io.lettuce.core.AbstractRedisReactiveCommands
	at io.lettuce.core.dynamic.RedisCommandFactory$CompositeCommandLookupStrategy.<init>(RedisCommandFactory.java:254)
	at io.lettuce.core.dynamic.RedisCommandFactory.getCommands(RedisCommandFactory.java:188)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
public interface CustomCommands extends Commands {
	@Command("SET :key :value EX :ex")
	RedisFuture<String> setex(@Param("key") String key, @Param("ex") Long ttl, @Param("value") byte[] value);
}

```

```java
final int REDIS_CONNECTION_POOL_SIZE = 3;
final int REDIS_CONNECTION_MAX_WAIT_MILLIS = 5000;
final Duration redisClusterRefreshPeriod = Duration.ofMinutes(1);
final Duration redisClusterEventEmitInterval = Duration.ofMinutes(1);
final ClientResources res = DefaultClientResources.builder().commandLatencyPublisherOptions(DefaultEventPublisherOptions.builder().eventEmitInterval(redisClusterEventEmitInterval).build()).build();
final ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder().enablePeriodicRefresh(redisClusterRefreshPeriod).enableAllAdaptiveRefreshTriggers().build();

final RedisClusterClient redisClient = RedisClusterClient.create(res, getRedisClusterDbUri());
redisClient.setOptions(ClusterClientOptions.builder().topologyRefreshOptions(topologyRefreshOptions).cancelCommandsOnReconnectFailure(true).validateClusterNodeMembership(false).disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS).build());

final GenericObjectPoolConfig redisConnectionPoolConfig = new GenericObjectPoolConfig();
redisConnectionPoolConfig.setMaxWaitMillis(REDIS_CONNECTION_MAX_WAIT_MILLIS);
redisConnectionPoolConfig.setMaxIdle(REDIS_CONNECTION_POOL_SIZE);
redisConnectionPoolConfig.setMaxTotal(REDIS_CONNECTION_POOL_SIZE);
final GenericObjectPool<StatefulRedisClusterConnection<String, String>> redisConnectionPool = ConnectionPoolSupport.createGenericObjectPool(redisClient::connect,redisConnectionPoolConfig);

try (final StatefulRedisClusterConnection<String, String> connect = redisConnectionPool.borrowObject()) {
final CustomCommands commands = new RedisCommandFactory(connect).getCommands(CustomCommands.class);
}
```

</details>

#### Expected behavior/code

The object interface should be initialized
#### Environment

- Lettuce version(s): 5.1.7.RELEASE
- Redis version: 3.2.12

**Comment by mp911de** [comment]
Thanks for report. That's fixed now.
