### ISSUE TITLE
Zadd with scoreAndValues overshadows zadd with scoredValues

### ISSUE THREAD

**Issue by showmeyourcode** [lettuce-io/lettuce-core#1084]
## Bug Report
https://github.com/lettuce-io/lettuce-core/blob/c98108dd7fbe9bee8702e468efff4b085a976374/src/main/java/io/lettuce/core/api/sync/RedisSortedSetCommands.java#L79
Zadd with scoreAndValues 

overshadows

https://github.com/lettuce-io/lettuce-core/blob/c98108dd7fbe9bee8702e468efff4b085a976374/src/main/java/io/lettuce/core/api/sync/RedisSortedSetCommands.java#L91
zadd with scoredValues

#### Current Behavior

Thorws ```IllegalArgumentException```
<details>
<summary>Stack trace</summary>

```java
Exception in thread "main" java.lang.IllegalArgumentException: ScoresAndValues.length must be a multiple of 2 and contain a sequence of score1, value1, score2, value2, scoreN, valueN
	at io.lettuce.core.internal.LettuceAssert.isTrue(LettuceAssert.java:131)
	at io.lettuce.core.RedisCommandBuilder.zadd(RedisCommandBuilder.java:2400)
	at io.lettuce.core.AbstractRedisAsyncCommands.zadd(AbstractRedisAsyncCommands.java:1630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:57)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy0.zadd(Unknown Source)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
        List<ScoredValue<String>>  values = redisClient.getCommands().zpopmax(PQ_KEY, count);
        if(values != null) {
            redisClient.getCommands().zadd(PROCESSING_KEY, values);
        }
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

#### Additional context
Commit introducing this feature
https://github.com/lettuce-io/lettuce-core/commit/0daf5ad16c9374fca578c1938616c16184b71c6c

**Comment by showmeyourcode** [comment]
Surprisingly getting same stack trace for update code

```java
List<ScoredValue<String>>  values = redisClient.getCommands().zpopmin(PQ_KEY, count);
List<Object> scoreAndValues = new ArrayList<>();
if(values != null) {
        values.forEach( v -> {
                scoreAndValues.add(v.getScore());
                scoreAndValues.add(v.getValue());
        });
       redisClient.getCommands().zadd(PROCESSING_KEY, scoreAndValues);
} 
```

Stacktrace

```java
Exception in thread "main" java.lang.IllegalArgumentException: ScoresAndValues.length must be a multiple of 2 and contain a sequence of score1, value1, score2, value2, scoreN, valueN
	at io.lettuce.core.internal.LettuceAssert.isTrue(LettuceAssert.java:131)
	at io.lettuce.core.RedisCommandBuilder.zadd(RedisCommandBuilder.java:2400)
	at io.lettuce.core.AbstractRedisAsyncCommands.zadd(AbstractRedisAsyncCommands.java:1630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:57)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy0.zadd(Unknown Source)
```

**Comment by rajatmathur** [comment]
I have also realised that argument needs to be an ‘’’Array’’’ hence I have tried using ‘’’toArray()’’’ on my Lists as well. same result.

**Comment by showmeyourcode** [comment]
toArray() wroks closing this.
