### ISSUE TITLE
NoClassDefFoundError for io/lettuce/core/protocol/CommandArgs$StringArgument

### ISSUE THREAD

**Issue by somguyth** [lettuce-io/lettuce-core#1139]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
Exception in thread "main" java.lang.NoClassDefFoundError: io/lettuce/core/protocol/CommandArgs$StringArgument
        at io.lettuce.core.protocol.CommandArgs.add(CommandArgs.java:188)
        at io.lettuce.core.RedisCommandBuilder.xadd(RedisCommandBuilder.java:2097)
        at io.lettuce.core.AbstractRedisAsyncCommands.xadd(AbstractRedisAsyncCommands.java:1489)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:57)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy48.xadd(Unknown Source)
        at .........RedisPusher.xadd(RedisPusher.java:....) -> see xadd method in below code

...

Caused by: java.lang.ClassNotFoundException: io.lettuce.core.protocol.CommandArgs$StringArgument
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 23 more

```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
import java.util.Collections;
import io.lettuce.core.RedisClient;
import io.lettuce.core.api.StatefulRedisConnection;
import io.lettuce.core.api.sync.RedisCommands;
import io.lettuce.core.api.sync.RedisStreamCommands;


public class RedisPusher {
	
	private static RedisPusher redisPusher;
	
	RedisClient client;
	StatefulRedisConnection<String, String> sender;
	RedisCommands<String, String> sync;
	RedisStreamCommands<String, String> streamCommands;
	
	private RedisPusher() {
		client = RedisClient.create("redis://" + "localhost");
		sender = client.connect();
		sync = sender.sync();
		streamCommands = sender.sync();
	}
	
	public static RedisPusher get() {
		if(redisPusher == null) {
			redisPusher = new RedisPusher();
		}
		return redisPusher;
	}
	
	public void xadd(String channel, String message) {
		streamCommands.xadd(channel, Collections.singletonMap("data", message));
	}
	
}

```

</details>

#### Environment

- Lettuce version: lettuce-core-5.1.8.RELEASE.jar (with reactor-core-3.2.12.RELEASE.jar)

#### Description of problem

I have a large project with lettuce 5.1.8.RELEASE as a dependency. The project runs perfectly well and calls xadd(... , ...) many times successfully. However then suddenly the above exception is thrown.

I checked my build path and I only have a single Lettuce dependency - 5.1.8.RELEASE.

I checked where it's throwing and it's at ```StringArgument.of``` in the below code snippet (this is pulled from CommandArgs.java)
```
    public CommandArgs<K, V> add(String s) {

        singularArguments.add(StringArgument.of(s));
        return this;
    }
```

**Comment by mp911de** [comment]
The issue looks like either a corrupt jar as if there were multiple versions of Lettuce on the class path.

**Comment by somguyth** [comment]
I think this is a problem on my end, unrelated to Lettuce, as I have noticed the same error happening all over the place. Thank you.
