### ISSUE TITLE
Lettuce cluster topology refresh querying known failed nodes

### ISSUE THREAD

**Issue by karlvr** [lettuce-io/lettuce-core#1142]
## Bug Report

Two of the nodes in our cluster were marked as failed on several of the nodes and handshake on the others. These nodes had been replaced with new nodes, so they were gone and never coming back, but not yet forgotten.

I expected that Lettuce would filter out known failed nodes (or suspicious) from the information it gets from the cluster.

#### Current Behavior

Currently Lettuce appears to attempt to query known failed nodes when refreshing the cluster topology:

<details>
<summary>Stack trace</summary>

```java
io.lettuce.core.cluster.topology.ClusterTopologyRefresh - Unable to connect to 10.0.2.191:6379
 java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: No route to host: /10.0.2.191:6379
 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
 	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:329)
 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:629)
 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:648)
 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:522)
 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:407)
 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:317)
 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.lang.Thread.run(Thread.java:748)
 Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: No route to host: /10.0.2.191:6379
 Caused by: java.net.ConnectException: finishConnect(..) failed: No route to host
 	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:112)
 	at io.netty.channel.unix.Socket.finishConnect(Socket.java:269)
 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:665)
 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:642)
 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:522)
 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:407)
 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:317)
 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.lang.Thread.run(Thread.java:748)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
        .enablePeriodicRefresh(Duration.of(60, ChronoUnit.SECONDS))
        .enableAllAdaptiveRefreshTriggers()
        .build();
client.setOptions(ClusterClientOptions.builder()
		.autoReconnect(true)
		.pingBeforeActivateConnection(true)
		.topologyRefreshOptions(topologyRefreshOptions)
		.build());
```

</details>

#### Expected behavior/code

I expected Lettuce would exclude the nodes that are known to be failed, or not yet known to be good (handshaking) from its probes.

I have my Redis cluster running in Docker Swarm and nodes may fail and be replaced automatically, but remain in the `CLUSTER NODES` list until I get around to forgetting them.

#### Environment

- Lettuce version(s): 5.1.4, 5.2.0
- Redis version: 5.0.5

#### Possible Solution

Perhaps add a check for `RedisClusterNode.NodeFlag.FAIL` and `RedisClusterNode.NodeFlag.HANDSHAKE` to `ClusterTopologyRefresh.validNode`?

Note that after I `CLUSTER FORGET <node>` each of the failed nodes lettuce recovered by itself and stopped looking for those bad nodes and the stack traces went away.

**Comment by mp911de** [comment]
The current behavior is a matter of perspective. One node's view on another one is very likely to be different from the view from the application perspective. Nodes can e.g. be distributed across data networks and one server might not be able to connect to another one while your application is able to connect to both nodes.

**Comment by karlvr** [comment]
@mp911de thanks for your quick response. Yes, I agree about the perspective. In this case no node saw the failed nodes as good—could that not be a signal that it's rogue?

I'm not sure that this actually caused a disturbance in our app, apart from the stack traces, although we observed some odd but not reproduced behaviour.

Would it be bad for Lettuce to talk to a Redis node that was denied by the bulk of the cluster?

**Comment by mp911de** [comment]
Lettuce tries to do its best without applying filters. 

Let's dig a bit into detail.

If we consider how we learn that a node is probably failed then what needs to happen first is fetching the topology first, including attempting to query the failed node. Once the topology refresh has finished, we have the indication that nodes have seen the failed node and likely that we weren't able to connect to that node.

On the next attempt, that happens after the previous one (that can be seconds, minutes or hours) in terms of time-dependency, we know that a particular node was considered a failed node back then. We don't know whether that assumption is still valid. What do we want to do now? 

* Do we reach out to that node? 
* Do we exclude it? 
* What if that node is down? 
* What if it is back up in the meantime?

There are plenty of approaches. One could be of interest which is `dynamicRefreshSources`. That is, Lettuce discovers the topology from the initial seed nodes and tries to reach out to the discovered nodes. If you have a known set of nodes, that remains intact, then you could disable `dynamicRefreshSources` and topology refresh uses only the seed nodes to discover the topology.

Another option, which is already in place, is overriding `RedisClusterClient.determinePartitions` so you clean up `Partitions` yourself to avoid reaching out to a particular node. `determinePartitions` receives the old `Partition` and `Map<RedisURI, Partitions>` as input parameters so you could hook into filtering yourself.

I could also think of an approach using filtering by applying a `Predicate` so you can hand in a filter to prevent nodes from being contacted. Such a feature isn't available (yet).

**Comment by karlvr** [comment]
Related to this; we've found that when we start our application, if there are failed redis nodes, our application spends a lot of time trying to contact them and timing out, which impacts all of our queries. We are using `ANY` for the cluster node to connect to. Applications that were running at the time of the Redis node failure still log the topology error (as above) but their general usage of Redis is unaffected. We are doing more investigation of this...

**Comment by mp911de** [comment]
There's no good pattern to approach this pattern than reducing `dynamicRefreshSources` and if you have topological information available, then you might want to override `RedisClusterClient.getTopologyRefreshSource()` for increased control.

Closing this ticket without a change. We can revisit this ticket once we have found an approach that works.
