### ISSUE TITLE
Fail to reconnect to using sentinel in kubernetes after reinstall redis-ha helm charts

### ISSUE THREAD

**Issue by fzhangtj** [lettuce-io/lettuce-core#1147]
#### Current Behavior

My program is running in kubernetes environment, to reproduce the issue we use minikube. It connect's to redis via sentinel,
the uri is `redis-sentinel://redis-ha.default.svc.cluster.local:26379/0#mymaster`

The redis is setup via helm chart [redis-ha](https://github.com/helm/charts/tree/master/stable/redis-ha). It runs 3 pods,
1 pod running redis master and sentinel, 2 pods running replica and sentinel. We then redeploy redis, via delete
and install the redis again. Below are the commands:
```
helm del --purge redis-ha

helm install \
  --name redis-ha \
  --set hardAntiAffinity=false \
    stable/redis-ha
```
After the redeployment, the program fail to reconnect to redis. The uri of sentinel the program connected to does not change, 
but IP of master/replica changed. The program is still trying to reconnect to the old IP.

<details>
<summary>Stack trace</summary>

```java
Oct 12, 2019 3:13:53 AM io.lettuce.core.protocol.ConnectionWatchdog run
INFO: Reconnecting, last destination was /10.96.208.211:6379
Oct 12, 2019 3:13:53 AM io.lettuce.core.protocol.ReconnectionHandler lambda$null$4
INFO: Reconnected to 10.96.208.211:6379
java.util.concurrent.ExecutionException: java.io.IOException: Connection reset by peer
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at com.example.lettucesample.Main.main(Main.java:19)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Oct 12, 2019 3:14:03 AM io.lettuce.core.protocol.ConnectionWatchdog run
INFO: Reconnecting, last destination was /10.96.208.211:6379
Oct 12, 2019 3:14:03 AM io.lettuce.core.protocol.ReconnectionHandler lambda$null$4
INFO: Reconnected to 10.96.208.211:6379
java.util.concurrent.ExecutionException: java.io.IOException: Connection reset by peer
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at com.example.lettucesample.Main.main(Main.java:19)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Oct 12, 2019 3:14:13 AM io.lettuce.core.protocol.ConnectionWatchdog run
INFO: Reconnecting, last destination was /10.96.208.211:6379
Oct 12, 2019 3:14:13 AM io.lettuce.core.protocol.ReconnectionHandler lambda$null$4
INFO: Reconnected to 10.96.208.211:6379
java.util.concurrent.ExecutionException: java.io.IOException: Connection reset by peer
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at com.example.lettucesample.Main.main(Main.java:19)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Oct 12, 2019 3:14:23 AM io.lettuce.core.protocol.ConnectionWatchdog run
INFO: Reconnecting, last destination was /10.96.208.211:6379
Oct 12, 2019 3:14:23 AM io.lettuce.core.protocol.ReconnectionHandler lambda$null$4
INFO: Reconnected to 10.96.208.211:6379
java.util.concurrent.ExecutionException: java.io.IOException: Connection reset by peer
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at com.example.lettucesample.Main.main(Main.java:19)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Oct 12, 2019 3:14:33 AM io.lettuce.core.protocol.ConnectionWatchdog run
INFO: Reconnecting, last destination was /10.96.208.211:6379
Oct 12, 2019 3:14:33 AM io.lettuce.core.protocol.ReconnectionHandler lambda$null$4
INFO: Reconnected to 10.96.208.211:6379
java.util.concurrent.ExecutionException: java.io.IOException: Connection reset by peer
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at com.example.lettucesample.Main.main(Main.java:19)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Oct 12, 2019 3:14:44 AM io.lettuce.core.protocol.ConnectionWatchdog run
INFO: Reconnecting, last destination was /10.96.208.211:6379
Oct 12, 2019 3:14:44 AM io.lettuce.core.protocol.ReconnectionHandler lambda$null$4
INFO: Reconnected to 10.96.208.211:6379

```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
package com.example.lettucesample;

import io.lettuce.core.RedisURI;
import io.lettuce.core.codec.StringCodec;
import io.lettuce.core.masterreplica.MasterReplica;

import java.util.concurrent.TimeUnit;

public class Main {

    public static void main(String[] args){

        var url = args[0]; // url is redis-sentinel://redis-ha.default.svc.cluster.local:26379/0#mymaster in this case
        io.lettuce.core.RedisClient redisClient = io.lettuce.core.RedisClient.create();
        var connection = MasterReplica.connect(redisClient, new StringCodec(), RedisURI.create(url));
        while (true) {
            try {
                connection.async().set("testkey", "1").toCompletableFuture().get(10, TimeUnit.SECONDS);
                System.out.println("success");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            try {
                Thread.sleep(5000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }
}
```

</details>

#### Expected behavior/code

After redis redeployed, lettuce should be able to reconnect to new nodes.

#### Environment

- Lettuce version(s): [5.2.0.RELEASE]
- Redis version: [5.0.5]

#### Possible Solution

In this case, lettuce don't receive message from sentinel and doesn't update the topology to the latest. Adding option to
allow periodic update the topology from sentinel could solve the problem. I checked the lettuce code, can't find a way
to update the topology periodically so far.

**Comment by mp911de** [comment]
`MasterReplica` relies on a Sentinel node to publish Pub/Sub notifications. If you exchange a Sentinel with an entirely new one and sentinel failover is a matter of disconnect/reconnect without sending a pub/sub message about the topology, then the client is not able to react to that change.

In such a case, restart your application to reinitialize the topology.

**Comment by fzhangtj** [comment]
What if the sentinel fail to notify the client? Let's say a topology change occurs, and the sentinel try to notify the client. But there're some intermittent network errors, so the sentinel fail to notify the client. When the intermittent errors are gone, client  will never knows the change, and still try to connect the old nodes. 
I think it would be nice if lettuce have an option to periodically get the latest topology from sentinel.

**Comment by mp911de** [comment]
This is a good point: Periodic refresh in Redis Cluster causes already some struggle and isn't a reliable approach. It would rather make sense to expose a `refreshTopology()` method. If your application needs to compensate for failing sentinels where the topology changes in between, you could use the event bus notifications (connect and disconnect events) and issue a topology refresh yourself.

**Comment by gopal229** [comment]
@mp911de Excuse my ignorance, I m running into a similar issue with the helm redis chart. However, its not an un-install/re-install of chart, whenever the chart is upgraded the  IP address of master/slave is getting changed that's causing the connection issues.

Restarting the client app is solving the problem, but we want to achieve without a restart.  I see 'refresh topology'  option but that's available only ClusterTopologyRefreshOptions.  

Is ClusterTopologyRefreshOptions are applicable for Redis master/slave with Sentinel as well?

**Comment by mp911de** [comment]
> Is ClusterTopologyRefreshOptions are applicable for Redis master/slave with Sentinel as well?

No, there's no such utility available. Master/Replica assumes that the IP addresses of Redis Sentinel do not change.

**Comment by gopal229** [comment]
Ok, so the only option available is to restart the app?

**Comment by abknanda** [comment]
Hi @mp911de ,

Is ClusterTopologyRefreshOptions still not available for Redis Sentinel ?
We use bitnami redis helm chart with sentinel in a Kubernetes cluster and the redis clients (_Lettuce with Springboot 3.3_)  get the below error when a redis-node with sentinel is restarted.

`Caused by: io.lettuce.core.RedisReadOnlyException: READONLY You can't write against a read only replica`

Is the only option available is to fallback to Redis Cluster without Sentinel ?

Thanks

**Comment by tishun** [comment]
> 
> Is the only option available is to fallback to Redis Cluster without Sentinel ?

No option is available right now and the driver depends on the Sentinel to publish topology updates.
