### ISSUE TITLE
IllegalStateException: null

### ISSUE THREAD

**Issue by Bam4d** [lettuce-io/lettuce-core#1151]
#### Current Behavior

This has happened a few times in a production environment where a box will fail a large number of redis commands with the below exception. The failures do not recover unless the box is stopped.

We have never seen this issue during load testing and unfortunately cannot provide a way of reproducing the issue because it appears to just randomly happen.

This behaviour tends to happen at very high load.

Additionally we are using about 100 redundant lettuce connections, and we randomly choose a connection for every command we perform.  (we are using no transactions).

What do you suggest we try to stop this from happening?

<details>
<summary>Stack trace</summary>

```java
java.lang.IllegalStateException: null
at io.lettuce.core.output.CommandOutput.set(CommandOutput.java:85) ~[lettuce-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:357) ~[lettuce-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:138) ~[lettuce-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:714) ~[lettuce-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:678) ~[lettuce-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:664) ~[lettuce-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:594) ~[lettuce-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:563) ~[lettuce-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[netty-transport-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[netty-transport-native-epoll-4.1.33.Final-linux-x86_64.jar!/:4.1.33.Final]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[netty-transport-native-epoll-4.1.33.Final-linux-x86_64.jar!/:4.1.33.Final]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[netty-transport-native-epoll-4.1.33.Final-linux-x86_64.jar!/:4.1.33.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-common-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.42.Final.jar!/:4.1.42.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar!/:4.1.42.Final]
```

</details>

#### Expected behavior/code

If there is some sort of failure in the underlying protocol, the connection should reset it's state so that no subsequent errors can happen.

#### Environment

Using Lettuce 5.2.0, netty native epoll linux 4.1.33

**Comment by mp911de** [comment]
This sounds like a state mismatch issue as in race conditions. These cases typically occur if a connection state gets out of sync and commands are decoded with a decoder that does not match the previously sent command. It's hard to reproduce these issues because the timing needs to be right to hit the out of sync moment. 

The only thing that can fix these kind of effects is ensuring the connection state is only changed by a single thread and the transaction is completed on a single thread.

**Comment by Bam4d** [comment]
So how can I ensure this? We're in a highly concurrent system using project reactor which uses a thread pool. 

The lettuce library has it's own threads with netty in order to handle this does it not?

**Comment by mp911de** [comment]
Transactions, threads and Reactor are typical arrangements that ask for trouble. Redis transactions and reactive API aren't the best fit as `Publisher`s after `MULTI` do not complete until calling `EXEC`. I suggest using at least the async API for better control so that you make sure to call the command sequence for your use-case (`MULTI`, `<commands>`, `EXEC`). From that method, you return either the command futures or the `EXEC` future that allows for controlling the execution.

Once `EXEC` is finished, you would return the connection back to the pool.

**Comment by Bam4d** [comment]
I think I was not very clear in my original report. We are not using any transactions at all for the reason stated in the documentation. We avoid any blocking operations (`BLRPOP` etc) and any `MULTI`/`EXEC`

We use scripts where we require atomicity.

**Comment by mp911de** [comment]
Sorry, I missed entirely that aspect. Then we need to investigate what's going on. Are you able to use a custom build of Lettuce to introduce debug code for further tracing? It would make sense to modify `CommandOutput` and `RedisStateMachine.safeSet` to introduce debug logging to debug which commands failed and with what value. This should give some clues about which command is affected and what payload was attempted to get decoded.

**Comment by Bam4d** [comment]
Yes I think it should be possible, but it might take a while for this bug to appear again. We're also generally doing thousands of redis ops per second, so trace logging for this might be detrimental to our production environment. I'll keep you updated.

Can you send a branch or suggestions of the logging that you want us to keep? (if we only log stuff when the error happens is this OK, for example just logging while catching? or do you need all the information up to that point?)

**Comment by Bam4d** [comment]
If it helps, There were not single commands that were failing, we saw large incorrect values coming from a large number of different commands. We did not throw Illegal state every time, but sometimes the value coming back would just be garbage. As an example we monitor some values in redis such as queue sizes (using `scard` or `zcard`) and we would sometimes have queue sizes returning with 1000000x the value that they should have been. This happend on multiple different queues.

**Comment by Bam4d** [comment]
Just another thought here... If we are using scripts with the `MULTI` ScriptOutputType is this related to using `MULTI` in transactions? Will the script return multiple results in a way that could cause the desyncronization?:

**Comment by mp911de** [comment]
`MULTI` uses the `NestedMultiOutput` for output capturing. Typically, responses are hierarchical in one or the other way. A single response produces either a simple output or an array. Arrays can contain simple elements or nested arrays. So, therefore, Lua should not be able to break this pattern as Lua return values are constrained by the Redis API.

Regarding the logging: It should log the name of the command that runs into an exception branch.
I recommend leaving traffic logging as-is as debug logging imposes quite some performance drag.

It's hard from the outside to determine where desynchronization happens or what causes it. Large amounts of traffic make it harder but maybe you could add a ring-buffer like data structure that keeps track of the last 50 to 100 commands so when you detect a response mismatch, then you can look backward in history to see which commands were fired and whether responses fit to the actual command until you get to the one that caused the issue.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by Bam4d** [comment]
I think we can close this ticket for now and I will re-open if we see it again and have some more information!
