### ISSUE TITLE
spring-boot-2.1.7.RELEASE.jar use this driver lettuce-core-5.0.5.RELEASE.jar   appear a problem

### ISSUE THREAD

**Issue by gxwanmei** [lettuce-io/lettuce-core#1169]
## Bug Report
spring-boot-2.1.7.RELEASE use this driver lettuce-core-5.0.5.RELEASE.  appear a problem
#### Current Behavior
Project running a time，when some request come in this web project，the project has some exception。
<details>
<summary>Stack trace</summary>
```java
Exception:Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to ***:***
```</details>
#### Input Code
<details>
<summary>Input Code</summary>
```java
 @Autowired
 public StringRedisTemplate stringRedisTemplate
```
</details>

#### Environment

- Lettuce version(s): lettuce-core-5.0.5.RELEASE
- Redis version:

**Comment by 748142366** [comment]
### I have a same problem，springboot 2.1.5.RELEASE+spring-boot-starter-data-redis(lettuce-core-5.1.5RELEASE) connect to redis cluster

**- my codes:**

redisTemplate.opsForValue().set("test-key", "value");

**- error log:**

2025-04-21 22:39:25.836 DEBUG 6420 --- [ioEventLoop-6-7] i.l.core.protocol.RedisStateMachine      : Decoded ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], empty stack: false
2025-04-21 22:39:25.842 ERROR 6420 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect] with root cause

java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:148) ~[na:1.8.0_441]
	at java.util.AbstractList.add(AbstractList.java:108) ~[na:1.8.0_441]
	at io.lettuce.core.output.ArrayOutput.set(ArrayOutput.java:54) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:357) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:138) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:708) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:672) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:667) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:587) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:556) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_441]

I need to reopen this issue for supports
