### ISSUE TITLE
Intermittent RedisCommandTimeoutException when making watch commands to AWS Elasticache

### ISSUE THREAD

**Issue by apilling6317** [lettuce-io/lettuce-core#1172]
Hi there

I'm seeing the following RedisCommandTimeoutException intermittently when watch commands are executing.  I've enabled TRACE level logging and the behaviour appears to be that an initial SELECT 0 command is executed and decoded then the service hangs for 1m until the timeout.

```

Nov 04 15:15:00.715 | ERROR | 
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.watch(LettuceConnection.java:738)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.watch(DefaultStringRedisConnection.java:1289)
	at org.springframework.data.redis.core.RedisTemplate.lambda$watch$24(RedisTemplate.java:1049)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.watch(RedisTemplate.java:1048)...

-- | -- | -- | --
  | Nov 04 15:14:00.707  | DEBUG | Decoded TransactionalCommand [type=SELECT, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true
  | Nov 04 15:14:00.707  | DEBUG | Decode TransactionalCommand [type=SELECT, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand]
  | Nov 04 15:14:00.707  | DEBUG | [channel=0xcd5c32e4, /10.0.5.99:35448 -> XXX.euw2.cache.amazonaws.com/10.0.5.175:6379, chid=0x2] Stack contains: 1 commands
  | Nov 04 15:14:00.707  | TRACE | [channel=0xcd5c32e4, /10.0.5.99:35448 -> XXX.euw2.cache.amazonaws.com/10.0.5.175:6379, chid=0x2] Buffer: +QUEUED
  | Nov 04 15:14:00.707  | DEBUG | [channel=0xcd5c32e4, /10.0.5.99:35448 -> XXX.euw2.cache.amazonaws.com/10.0.5.175:6379, chid=0x2] Received: 9 bytes, 1 commands in the stack
  | Nov 04 15:14:00.706  | TRACE | [channel=0xcd5c32e4, /10.0.5.99:35448 -> XXX.euw2.cache.amazonaws.com/10.0.5.175:6379] Sent: *2 $6 SELECT $1 0
  | Nov 04 15:14:00.706  | DEBUG | [channel=0xcd5c32e4, /10.0.5.99:35448 -> XXX.euw2.cache.amazonaws.com/10.0.5.175:6379] writing command TransactionalCommand [type=SELECT, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand]
  | Nov 04 15:14:00.706  | DEBUG | [channel=0xcd5c32e4, /10.0.5.99:35448 -> XXX.euw2.cache.amazonaws.com/10.0.5.175:6379, chid=0x2] write(ctx, TransactionalCommand [type=SELECT, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], promise)
  | Nov 04 15:14:00.706  | DEBUG | [channel=0xcd5c32e4, /10.0.5.99:35448 -> XXX.euw2.cache.amazonaws.com/10.0.5.175:6379, epid=0x2] write() done
  | Nov 04 15:14:00.706  | DEBUG | [channel=0xcd5c32e4, /10.0.5.99:35448 -> XXX.euw2.cache.amazonaws.com/10.0.5.175:6379, epid=0x2] write() writeAndFlush command TransactionalCommand [type=SELECT, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand]
  | Nov 04 15:14:00.706  | DEBUG | dispatching command TransactionalCommand [type=SELECT, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand]
```
The only configuration that I am aware of is the following

```
spring:
  redis:
    host: <OUR AWS HOST>
    port: 6379
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-wait: 10000ms
        max-active: -1
        max-idle: 8
        min-idle: 2
```

spring-boot-starter-data-redis 2.1.5.RELEASE
spring-data-redis 2.1.8.RELEASE
lettuce-core 5.1.6.RELEASE
AWS Elasticache cluster disabled

**Comment by mp911de** [comment]
Please do not use `SELECT` with transactions, they do not play well together. Please `SELECT` before starting any transactional work. Please also make sure to use a dedicated connection for a transaction. When a connection gets shared across threads that operates on transactions, then the connection gets out of sync and the results are timeouts.

**Comment by apilling6317** [comment]
Perhaps I can provide a bit of extra context, I'm using a Spring SessionCallback and the watch command results in a call to LettuceConnection.getDedicatedConnection which creates a connection via StandaloneConnectionProvider.masterReplicaConnection and invokes `((StatefulRedisConnection<byte[], byte[]>) asyncDedicatedConn).sync().select(dbIndex);`.  All of this is within the spring libraries.
