### ISSUE TITLE
spring boot2.1.11 upgrade to spring boot2.2.2 stucked when server setups

### ISSUE THREAD

**Issue by sparkcai** [lettuce-io/lettuce-core#1192]
spring boot2.1.x's lettuce version is  5.1.x  and   spring boot2.2.x‘s lettuce version is 5.2.x.
when i use    lettuce version is  5.1.x  is ok, but when i use  lettuce version is 5.2.x,  is stucked.
below is thread dump info:
    "main" #1 prio=5 os_prio=0 tid=0x0000000002cdc800 nid=0x36fc waiting on condition [0x0000000002cce000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000e5f18978> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.lettuce.core.DefaultConnectionFuture.get(DefaultConnectionFuture.java:68)
        at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:227)
        at io.lettuce.core.RedisClient.connect(RedisClient.java:207)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider$$Lambda$829/996955574.get(Unknown Source)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.doGetAsyncDedicatedConnection(LettuceConnection.java:1002)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.getDedicatedConnection(LettuceConnection.java:985)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.getConnection(LettuceConnection.java:942)
        at org.springframework.data.redis.connection.lettuce.LettuceServerCommands.getConnection(LettuceServerCommands.java:567)
        at org.springframework.data.redis.connection.lettuce.LettuceServerCommands.getConfig(LettuceServerCommands.java:305)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.getConfig(DefaultedRedisConnection.java:1319)
        at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.getNotifyOptions(ConfigureNotifyKeyspaceEventsAction.java:76)
        at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.configure(ConfigureNotifyKeyspaceEventsAction.java:57)
        at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$EnableRedisKeyspaceNotificationsInitializer.afterPropertiesSet(RedisHttpSessionConfiguration.java:333)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$162/1076641925.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        - locked <0x0000000082f3b330> (a java.util.concurrent.ConcurrentHashMap)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        - locked <0x00000000829b5e70> (a java.lang.Object)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at com.gpform.UserApplication.main(UserApplication.java:20)

is debug the code,i get a  exception there (the same project use lettuce 5.1.x is ok,but upgrade to 5.2.x it is always had been stucking)
![image](https://user-images.githubusercontent.com/37604542/71319373-6d174980-24d8-11ea-9735-8bb05cd3c476.png)
![image](https://user-images.githubusercontent.com/37604542/71319375-7d2f2900-24d8-11ea-98ed-98f8382e136a.png)

after all,the main thread  had been stucking

**Comment by mp911de** [comment]
The setup and thread dump do not contain any obvious details why the commands get stuck. It's likely that the Lettuce upgrade fails because of underlying dependencies (Project Reactor, Netty). Please make sure to not mix dependencies and please enable debug logging.

Without further information, there's nothing we can do here.

**Comment by sparkcai** [comment]
below is debug info,the main thread get stuck here.
[debug.txt](https://github.com/lettuce-io/lettuce-core/files/3993346/debug.txt)

**Comment by sparkcai** [comment]
is related zipkin .

**Comment by Comven** [comment]
It happend  when using  zipkin and lettuce at the same time (spring-boot-2.2.x+spring-cloud-hoxton), Has it been fixed？ @mp911de

**Comment by mp911de** [comment]
Here's the ticket from Spring Cloud Sleuth that refers to the issue: spring-cloud/spring-cloud-sleuth#1557
