### ISSUE TITLE
Cannot retrieve initial cluster partitions from initial URIs with AWS ElastiCache Cluster with transit encryption enabled

### ISSUE THREAD

**Issue by bruno-chavez** [lettuce-io/lettuce-core#1226]
Lettuce is not able to connect to the cluster when transit encryption is enabled, I'm using Spring Data Redis.

Configuration beans:

```
@Bean
    public LettuceConnectionFactory redisConnectionFactory() {
        LettuceConnectionFactory connectionFactory = new LettuceConnectionFactory(new RedisClusterConfiguration(nodes));
        connectionFactory.setUseSsl(true);
        connectionFactory.setStartTls(true);
        connectionFactory.setPassword("XXXXXXXXXXXXXXXXXXX");
        connectionFactory.setVerifyPeer(false);
        return connectionFactory;
    }

    @Bean
    public RedisTemplate<String, ?> redisTemplate(RedisConnectionFactory factory) {
        RedisTemplate<String, ?> template = new RedisTemplate<>();
        template.setConnectionFactory(factory);
        return template;
    }
```
Where nodes is a list of strings of all the nodes as host:port.

Stack Trace:
```
com.lambdaworks.redis.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='terraform-test-cluster-0001-001.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0001-002.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0001-003.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0002-001.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0002-002.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0002-003.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0003-001.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0003-002.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0003-003.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0004-001.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0004-002.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0004-003.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0005-001.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0005-002.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379], RedisURI [host='terraform-test-cluster-0005-003.terraform-test-cluster.sol3oi.cac1.cache.amazonaws.com', port=6379]]
	at com.lambdaworks.redis.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:853)
	at com.lambdaworks.redis.cluster.RedisClusterClient.initializePartitions(RedisClusterClient.java:824)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectClusterImpl(RedisClusterClient.java:570)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connect(RedisClusterClient.java:356)
	at org.springframework.data.redis.connection.lettuce.LettuceClusterConnection.doGetAsyncDedicatedConnection(LettuceClusterConnection.java:1224)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.getDedicatedConnection(LettuceConnection.java:3991)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.getConnection(LettuceConnection.java:3951)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.hGet(LettuceConnection.java:2866)
	at org.springframework.data.redis.core.DefaultHashOperations$1.doInRedis(DefaultHashOperations.java:52)
	at org.springframework.data.redis.core.DefaultHashOperations$1.doInRedis(DefaultHashOperations.java:49)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:207)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:91)
	at org.springframework.data.redis.core.DefaultHashOperations.get(DefaultHashOperations.java:49)
```

Versions:
+ Spring Data Redis Starter: 1.5.4.RELEASE
+ Spring Data Redis: 1.8.4.RELEASE
+ Lettuce: 4.4.1.Final
+ Netty Transport 4.1.15.Final

Yes this are pretty old, but as the documentation says, ssl with a cluster shoud be possible since Lettuce 4.2.0, however I have found no success with it, any guidance is greatly appreciated

**Comment by mp911de** [comment]
Lettuce 4 misses a proper mechanism to report the actual cause why partitions weren't loaded. Can you enable debug/trace logging for `com.lambdaworks.redis` to inspect the traffic and the actual cause? Without these, we're not able to further diagnose the issue.
