### ISSUE TITLE
Can't connect to ElastiCache cluster when transit encryption is on

### ISSUE THREAD

**Issue by bruno-chavez** [lettuce-io/lettuce-core#1227]
Lettuce is not able to connect to the cluster when transit encryption is enabled, I'm using Spring Data Redis.

Configuration beans:

```
   @Bean
    public LettuceConnectionFactory connectionFactory() {
        LettuceClientConfiguration clientConfiguration = LettuceClientConfiguration.builder()
                .useSsl()
                .startTls()
                .disablePeerVerification()
                .build();

        return new LettuceConnectionFactory(new RedisClusterConfiguration(nodes), clientConfiguration);
    }

    @Bean
    public RedisTemplate<String, ?> redisTemplate(RedisConnectionFactory factory) {
        RedisTemplate<String, ?> template = new RedisTemplate<>();
        template.setConnectionFactory(factory);
        return template;
    }
```
Where nodes is a list of strings of all the nodes as host:port.

Stack Trace:
```
2020-02-12 18:02:14.567  INFO 14212 --- [           main] c.t.c.s.SpringRedisExampleApplication    : Starting SpringRedisExampleApplication on NBCLPC0Y5GJ6 with PID 14212 (C:\Development\Programs\spring-redis-example-master\target\classes started by bxc200 in C:\Development\Programs\spring-redis-example-master)
2020-02-12 18:02:14.570  INFO 14212 --- [           main] c.t.c.s.SpringRedisExampleApplication    : No active profile set, falling back to default profiles: default
2020-02-12 18:02:15.297  INFO 14212 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-02-12 18:02:15.301  INFO 14212 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2020-02-12 18:02:15.355  INFO 14212 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 23ms. Found 0 Redis repository interfaces.
2020-02-12 18:02:15.837  INFO 14212 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8082 (http)
2020-02-12 18:02:15.847  INFO 14212 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-02-12 18:02:15.847  INFO 14212 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.30]
2020-02-12 18:02:16.006  INFO 14212 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-02-12 18:02:16.006  INFO 14212 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1378 ms
2020-02-12 18:02:16.280 DEBUG 14212 --- [           main] i.l.c.resource.DefaultClientResources    : -Dio.netty.eventLoopThreads: 8
2020-02-12 18:02:16.288 DEBUG 14212 --- [           main] i.l.c.r.DefaultEventLoopGroupProvider    : Creating executor io.netty.util.concurrent.DefaultEventExecutorGroup
2020-02-12 18:02:16.341 DEBUG 14212 --- [           main] i.l.c.resource.DefaultClientResources    : LatencyUtils/HdrUtils are not available, metrics are disabled
2020-02-12 18:02:16.366  INFO 14212 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService
2020-02-12 18:02:16.551  INFO 14212 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-02-12 18:02:16.660 DEBUG 14212 --- [           main] i.l.c.r.DefaultEventLoopGroupProvider    : Creating executor io.netty.util.concurrent.DefaultEventExecutorGroup
2020-02-12 18:02:16.661 DEBUG 14212 --- [           main] i.l.c.resource.DefaultClientResources    : LatencyUtils/HdrUtils are not available, metrics are disabled
2020-02-12 18:02:16.871  INFO 14212 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8082 (http) with context path ''
2020-02-12 18:02:16.874  INFO 14212 --- [           main] c.t.c.s.SpringRedisExampleApplication    : Started SpringRedisExampleApplication in 2.803 seconds (JVM running for 5.406)
2020-02-12 18:03:20.007  INFO 14212 --- [nio-8082-exec-3] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-02-12 18:03:20.007  INFO 14212 --- [nio-8082-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-02-12 18:03:20.013  INFO 14212 --- [nio-8082-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
2020-02-12 18:03:20.241  INFO 14212 --- [nio-8082-exec-3] io.lettuce.core.EpollProvider            : Starting without optional epoll library
2020-02-12 18:03:20.242  INFO 14212 --- [nio-8082-exec-3] io.lettuce.core.KqueueProvider           : Starting without optional kqueue library
2020-02-12 18:03:20.244 DEBUG 14212 --- [nio-8082-exec-3] i.l.c.r.DefaultEventLoopGroupProvider    : Allocating executor io.netty.channel.nio.NioEventLoopGroup
2020-02-12 18:03:20.245 DEBUG 14212 --- [nio-8082-exec-3] i.l.c.r.DefaultEventLoopGroupProvider    : Creating executor io.netty.channel.nio.NioEventLoopGroup
2020-02-12 18:03:20.264 DEBUG 14212 --- [nio-8082-exec-3] i.l.c.r.DefaultEventLoopGroupProvider    : Adding reference to io.netty.channel.nio.NioEventLoopGroup@784eab1c, existing ref count 0
2020-02-12 18:03:20.281 DEBUG 14212 --- [nio-8082-exec-3] io.lettuce.core.RedisClient              : Connecting to Redis at cluster-test-0001-001.amazonaws.com:6379
2020-02-12 18:03:22.840 DEBUG 14212 --- [nio-8082-exec-3] io.lettuce.core.RedisClient              : Connecting to Redis at cluster-test-0002-001.amazonaws.com:6379
2020-02-12 18:03:23.433 DEBUG 14212 --- [ioEventLoop-6-1] io.lettuce.core.protocol.CommandHandler  : [channel=0xb29513f7, [id: 0xc735efaf] (inactive), chid=0x2] channelRegistered()
2020-02-12 18:03:23.433 DEBUG 14212 --- [ioEventLoop-6-2] io.lettuce.core.protocol.CommandHandler  : [channel=0x2e2a284a, [id: 0x24c8a0b0] (inactive), chid=0x1] channelRegistered()
2020-02-12 18:03:33.449 DEBUG 14212 --- [ioEventLoop-6-2] io.lettuce.core.RedisClient              : Connecting to Redis at cluster-test-0002-001.amazonaws.com:6379: cluster-test-0002-001.amazonaws.com:6379

io.netty.channel.ConnectTimeoutException: connection timed out: cluster-test-0001-001.amazonaws.com/*IP*:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:150) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]

2020-02-12 18:03:33.448 DEBUG 14212 --- [ioEventLoop-6-1] io.lettuce.core.RedisClient              : Connecting to Redis at cluster-test-0001-001.amazonaws.com:6379: cluster-test-0001-001.amazonaws.com:6379

io.netty.channel.ConnectTimeoutException: connection timed out: cluster-test-0001-001.amazonaws.com/*IP*:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:150) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]

2020-02-12 18:03:33.450 DEBUG 14212 --- [ioEventLoop-6-2] io.lettuce.core.RedisChannelHandler      : close()
2020-02-12 18:03:33.450 DEBUG 14212 --- [ioEventLoop-6-1] io.lettuce.core.RedisChannelHandler      : close()
2020-02-12 18:03:33.450 DEBUG 14212 --- [ioEventLoop-6-2] io.lettuce.core.RedisChannelHandler      : closeAsync()
2020-02-12 18:03:33.450 DEBUG 14212 --- [ioEventLoop-6-1] io.lettuce.core.RedisChannelHandler      : closeAsync()
2020-02-12 18:03:33.451 DEBUG 14212 --- [ioEventLoop-6-2] i.lettuce.core.protocol.DefaultEndpoint  : [unknown, epid=0x2] closeAsync()
2020-02-12 18:03:33.451 DEBUG 14212 --- [ioEventLoop-6-1] i.lettuce.core.protocol.DefaultEndpoint  : [unknown, epid=0x1] closeAsync()
2020-02-12 18:03:33.453 DEBUG 14212 --- [ioEventLoop-6-2] i.l.c.c.topology.ClusterTopologyRefresh  : Unable to connect to [cluster-test-0002-001.amazonaws.com:6379]: connection timed out:cluster-test-0002-001.amazonaws.com/*IP*:6379

io.netty.channel.ConnectTimeoutException: connection timed out: cluster-test-0001-001.amazonaws.com/*IP*:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:150) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]

2020-02-12 18:03:33.454 DEBUG 14212 --- [ioEventLoop-6-1] i.l.c.c.topology.ClusterTopologyRefresh  : Unable to connect to [cluster-test-0001-001.amazonaws.com:6379]: connection timed out: cluster-test-0001-001.amazonaws.com/*IP*:6379

io.netty.channel.ConnectTimeoutException: connection timed out: cluster-test-0001-001.amazonaws.com/*IP*:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:150) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]

2020-02-12 18:03:33.457 DEBUG 14212 --- [ioEventLoop-6-2] io.lettuce.core.protocol.CommandHandler  : [channel=0x2e2a284a, [id: 0x24c8a0b0] (inactive), chid=0x1] channelUnregistered()
2020-02-12 18:03:33.457 DEBUG 14212 --- [ioEventLoop-6-1] io.lettuce.core.protocol.CommandHandler  : [channel=0xb29513f7, [id: 0xc735efaf] (inactive), chid=0x2] channelUnregistered()
2020-02-12 18:03:33.477 ERROR 14212 --- [nio-8082-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='cluster-test-0001-001.amazonaws.com', port=6379], RedisURI [host='cluster-test-0002-001.amazonaws.com', port=6379]]] with root cause

io.netty.channel.ConnectTimeoutException: connection timed out: cluster-test-0001-001.amazonaws.com/*IP*:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:150) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
```

Repository:
```
@Repository
public class CacheDaoImpl implements CacheDao {

    private HashOperations<String, String, ServiceResponse> hashOperations;
    private RedisTemplate<String, ServiceResponse> redisTemplate;

    public CacheDaoImpl(RedisTemplate<String, ServiceResponse> redisTemplate) {
        this.hashOperations = redisTemplate.opsForHash();
        this.redisTemplate = redisTemplate;
    }

    @Override
    public void save(String identifier, String orchestration, Body response) {
        this.hashOperations.put(identifier, orchestration, response);
    }
}
```

Versions:
+ Spring Data Redis Starter: 2.2.4.RELEASE
+ Spring Data Redis: 2.2.4.RELEASE
+ Lettuce: 5.2.1.Final

**Comment by mp911de** [comment]
`startTls` isn't required with AWS Redis. The log says: 

```
ConnectTimeoutException: connection timed out: cluster-test-0001-001.amazonaws.com/*IP*:6379
```

This is an infrastructure issue, potentially related to firewall rules. There's nothing we can do from our side.

**Comment by bruno-chavez** [comment]
< This is an infrastructure issue, potentially related to firewall rules. There's nothing we can do from our side

I don't think it is, using this exact same setup but with encryption in transit turned-off everything works. Im trying to figure out why I cant reach to the cluster.

**Comment by mp911de** [comment]
Make sure you can connect via redis-cli or OpenSSL sclient to reported endpoints.

**Comment by bruno-chavez** [comment]
If anyone else encounters this problem, make sure to not only open the security groups for the redis port itself (eg: 6379) but also that port +10000, [reference](https://redis.io/topics/cluster-tutorial)

Working config class:
```
@Bean
    public LettuceConnectionFactory connectionFactory() {
        LettuceClientConfiguration clientConfiguration = LettuceClientConfiguration.builder().useSsl().build();

        return new LettuceConnectionFactory(new RedisClusterConfiguration(nodes), clientConfiguration);
    }
```

**Comment by ptanwar27** [comment]
@bruno-chavez @mp911de  I am also facing same issue. As redis documentation clearly says that cluster will not work properly if 16739 port is not open. But when I try to connect using StatefulRedisConnection provided by lettuce API , then connection work but does it mean it is not utilizing cluster properly?

**Comment by daviddelucca** [comment]
@bruno-chavez what is `nodes ` in your example? Is the cluster endpoint? I don't want to map nodes directly.

**Comment by bruno-chavez** [comment]
@daviddelucca its a list with url:port combination for each node, AFAIK you dont have to list each node as the driver is able to discovery other nodes if at least one is provided but it may take longer than just simply listing all the nodes.

**Comment by deepdmistry** [comment]
@bruno-chavez - i am actually using Spring boot 2.3.2 and using lettuce that comes bundled with it, i tried opening all ports and copying your configuration but still facing same issue. Do you have any ideas ?

**Comment by namila007** [comment]
@deepdmistry  did u find any fix for this?

**Comment by hooverhe** [comment]
Pls remove all of the above configurations. Just set the following configurations in properties. Meanwhile, notice to use stringRedisTemplate in your codes. Aws Elasticache Redis Cluster is exampled as below. 

spring.redis.cluster.nodes = clustercfg.xxx.yyy.use1.cache.amazonaws.com:6379
spring.redis.cluster.max-redirects=3
spring.redis.password=pwd
spring.redis.ssl=true

**Comment by rahul6941** [comment]
@hooverhe 
Do we required SSL certificate for this property "spring.redis.ssl=true" ?
