### ISSUE TITLE
Redis lua script execution failed using ReadFrom.REPLICA_PREFERRED in redis cluster

### ISSUE THREAD

**Issue by pkgonan** [lettuce-io/lettuce-core#1244]
## Bug Report
https://jira.spring.io/browse/DATAREDIS-908

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR Error running script (call to f_6ff916cd466ee4837030a29a731f0d857b8abd57): @user_script:1: @user_script: 1: -READONLY You can't write against a read only replica.   
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:54)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveRedisConnection.lambda$translateException$0(LettuceReactiveRedisConnection.java:293)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6442)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:247)
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onError(RedisPublisher.java:890)
	at io.lettuce.core.RedisPublisher$State.onError(RedisPublisher.java:687)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onError(RedisPublisher.java:344)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.onError(RedisPublisher.java:800)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.complete(RedisPublisher.java:736)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:59)
	at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:63)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:59)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:654)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:614)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:139)
		at reactor.core.publisher.Mono.blockOptional(Mono.java:1709)
		at com.yanolja.cp.application.stock.domain.StockHandler.tryDecrease(StockHandler.java:31)
		at com.yanolja.cp.application.distribution.domain.DistributionStockHandler.tryDecrease(DistributionStockHandler.java:36)
		at com.yanolja.cp.application.distribution.domain.Distribution.tryConsumingStock(Distribution.java:175)
		at com.yanolja.cp.application.distributor.domain.AbstractDistributorFactory$CouponDistributor.tryDistributing(AbstractDistributorFactory.java:59)
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
		at com.yanolja.cp.application.distributor.service.VisitDistributorService.distribute(VisitDistributorService.java:56)
		at com.yanolja.cp.application.distributor.service.VisitDistributorService$$FastClassBySpringCGLIB$$5a1ec3bb.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
		at com.yanolja.cp.application.distributor.service.VisitDistributorService$$EnhancerBySpringCGLIB$$a646a3aa.distribute(<generated>)
		at com.yanolja.cp.application.distributor.service.UserCouponDistributorService.distributeWithoutLock(UserCouponDistributorService.java:48)
		at com.yanolja.cp.application.distributor.service.UserCouponDistributorService.distribute(UserCouponDistributorService.java:39)
		at com.yanolja.cp.application.distributor.service.UserCouponDistributorService.distributeIgnoreException(UserCouponDistributorService.java:30)
		at com.yanolja.cp.application.issue.service.CouponInstanceService.distributeCoupons(CouponInstanceService.java:121)
		at com.yanolja.cp.application.issue.service.CouponInstanceService.listByUserId(CouponInstanceService.java:48)
		at com.yanolja.cp.application.issue.service.CouponInstanceService$$FastClassBySpringCGLIB$$295a310e.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
		at com.yanolja.cp.application.issue.service.CouponInstanceService$$EnhancerBySpringCGLIB$$85725783.listByUserId(<generated>)
		at com.yanolja.cp.application.issue.CouponInstanceController.listByUserId(CouponInstanceController.java:57)
		at com.yanolja.cp.application.issue.CouponInstanceController$$FastClassBySpringCGLIB$$35eadc8a.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
		at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:120)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
		at com.yanolja.cp.application.issue.CouponInstanceController$$EnhancerBySpringCGLIB$$db956e69.listByUserId(<generated>)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
		at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
		at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
		at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		... 1 common frames omitted
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR Error running script (call to f_6ff916cd466ee4837030a29a731f0d857b8abd57): @user_script:1: @user_script: 1: -READONLY You can't write against a read only replica.   
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:135)
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:108)
	... 23 common frames omitted
```

</details>

#### Expected behavior/code
```
It seems that io.lettuce.core.ReadFrom setting is affected Redis Lua script execution.
ReadFrom.MASTER or ReadFrom.MASTER_PREFERRED setting is succeed, but ReadFrom.REPLICA_PREFERRED setting is failed.
```

#### Lua Script Code
test.lua
```
local current = redis.call('DECR', KEYS[1])
if tonumber(current) >= 0 then
  return true
end
redis.call('INCR', KEYS[1])
return false
```
#### Environment

- Lettuce version(s): lettuce-core:5.2.2.RELEASE
- Redis version (Cluster): 5.0.5

**Comment by mp911de** [comment]
We cannot tell from a client perspective whether a Lua script can be executed on a master on a replica as we do not parse or inspect scripts for read or write commands. Lua scripts are enabled for replica dispatch to not prevent replica reads using Lua scripts.

**Comment by pkgonan** [comment]
If so, is there any other solution about that ?

**Comment by mp911de** [comment]
The only solution I see is using `ReadFrom.MASTER`. In a Spring Data setup, you might want to use a dedicated `LettuceConnectionFactory` that is intended for this kind of Lua script execution if you require replica reads for all other operations.

**Comment by ben905713861** [comment]
Hello boss:
Using "ReadFrom.MASTER_PREFERRED" configuration is most inportant in high concurrency project.Most times, we use lue script to write data,not read data. Could you consider to set up a configuration in "ClusterTopologyRefreshOptions" to control using master or slave to run the  lua script?

`var clientConfig = LettucePoolingClientConfiguration.builder()
	.readFrom(ReadFrom.REPLICA_PREFERRED)
	.clientOptions(clientOptions)
	.build();`

**Comment by ben905713861** [comment]
@mp911de 
Hello boss:
Using "ReadFrom.MASTER_PREFERRED" configuration is most inportant in high concurrency project.Most times, we use lue script to write data,not read data. Could you consider to set up a configuration in "ClusterTopologyRefreshOptions" to control using master or slave to run the lua script?Or change the default configuration to running lua script in slave node?
```java
var clientConfig = LettucePoolingClientConfiguration.builder() 
    .readFrom(ReadFrom.REPLICA_PREFERRED)
    .clientOptions(clientOptions)
    .build();
```

**Comment by choigiseong** [comment]
In the current version lettuce-core-6.5.5.RELEASE, Lua scripts are executed on the master node.
Since the script type is classified as Write, Lettuce acquires a write connection, which points to the master.
You can start debugging from the following line of code:
https://github.com/redis/lettuce/blob/c898733464a8dba0ff13bb718901a347cac22bc5/src/main/java/io/lettuce/core/cluster/ClusterDistributionChannelWriter.java#L179

**Comment by tishun** [comment]
By introducing [EVAL_RO](https://redis.io/docs/latest/commands/eval_ro/) and [EVALSHA_RO](https://redis.io/docs/latest/commands/evalsha_ro/) in #1987 and specifically with https://github.com/redis/lettuce/commit/0caf1e7441d295e3ea0e244eca7af07e13b08c6e the users of the library are able to use   `ReadFrom.REPLICA_PREFERRED` and still have their scripts executed on the master since there are two separate commands that could be used for execting read-only and write LUA scripts
