### ISSUE TITLE
io.lettuce.core.RedisCommandInterruptedException: Command interrupted

### ISSUE THREAD

**Issue by Marviszhao** [lettuce-io/lettuce-core#1248]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
Exception in thread "pool-1-thread-6" io.lettuce.core.RedisCommandInterruptedException: Command interrupted
	at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:87)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:112)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy67.set(Unknown Source)
	at com.example.service.impl.LettuceServiceImpl.lock(LettuceServiceImpl.java:39)
	at com.example.controller.LettuceLockController$1.run(LettuceLockController.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
private static final Logger log = LoggerFactory.getLogger(LettuceServiceImpl.class);
    @Autowired
    private StatefulRedisClusterConnection<String, String> clusterConnection;
    private static final String LOCK_SUCCESS = "OK";
    private static final Long RELEASE_SUCCESS = 1L;
    private static final long expireTime = 3000;
    private long timeout = 90000;

    @Override
    public boolean lock(String key, String uuid) {
        RedisAdvancedClusterCommands clusterCommands = clusterConnection.sync();
        long start = System.currentTimeMillis();
        try {
            while (true){
                String result = clusterCommands.set(key, uuid, SetArgs.Builder.nx().px(expireTime));
                if (LOCK_SUCCESS.equals(result)) {
                    return true;
                }
                long time = System.currentTimeMillis() - start;
                if (time >= timeout) {
                    return false;
                }
//                Thread.sleep(1);
            }
        } catch (Exception e) {
            log.error("redis竞争锁失败");
            throw e;
        }
    }

// this is my test main class
@RequestMapping(value = "/redisLockTest")
    public void redisLockTest() {
        trainNum = 5000;
        ThreadPoolExecutor exec = ( ThreadPoolExecutor ) Executors.newFixedThreadPool( 100 );
        for (int i = 0; i < 200; i++) {
            exec.execute(new Runnable() {
                @Override
                public void run() {
                  String uuid =  UUID.randomUUID().toString();
                    lettuceService.lock("train_test", uuid);
                    System.out.println(curTimeStamp2Str() + " " +Thread.currentThread().getName() + "got ticket：" + trainNum-- + ",uuid:" + uuid);
                    lettuceService.unlock("train_test", uuid);
                }
            });
        }
        exec.shutdownNow( );
    }
```

</details>

#### Expected behavior/code

every one get the redis lock to by his ticket !!! 
#### Environment

- Lettuce version(s): [e.g. 5.2.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by Marviszhao** [comment]
exec.shutdownNow( );   make this error occured！

**Comment by beyondhc** [comment]
> exec.shutdownNow( ); make this error occured！

Can you explain the reason in detail here? I also encountered the same problem, thank you

**Comment by mp911de** [comment]
That is expected. If you shut down the underlying executor, then threads are being interrupted and the result for Redis commands being ran on the executor is `RedisCommandInterruptedException`.
