### ISSUE TITLE
ConcurrentModificationException iterating over partitions

### ISSUE THREAD

**Issue by johnny-costanzo** [lettuce-io/lettuce-core#1252]
## Bug Report

I'm calling the `readonly` method on an async commands instance to select some nodes and hit a ConcurrentModificationException. It looked like a topology refresh happened at the same time and modified the partitions. Looking into the code, `Partitions.getPartitions` offers up access to its internal list of partitions (which is otherwise synchronized on in all internal methods), but client code that calls `getPartitions` is not protected. The `StaticNodeSelection` constructor calls this method and iterates over the list can potentially result in this issue when the list changes. Consider using a CopyOnWriteArrayList or some other mechanism so that clients of the `getPartitions` call can safely iterate over the list.

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1660)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.lettuce.core.cluster.StaticNodeSelection.<init>(StaticNodeSelection.java:51)
        at io.lettuce.core.cluster.RedisAdvancedClusterAsyncCommandsImpl.nodes(RedisAdvancedClusterAsyncCommandsImpl.java:542)
        at io.lettuce.core.cluster.RedisAdvancedClusterAsyncCommandsImpl.readonly(RedisAdvancedClusterAsyncCommandsImpl.java:522)
```

</details>

#### Environment

- Lettuce version(s): 5.2.0.RELEASE

**Comment by johnny-costanzo** [comment]
or possibly this use case should have been querying from `Partitions` internal `nodeReadView` instead of calling `getPartitions()` since it doesn't look like that collection mutates

**Comment by mp911de** [comment]
Thanks for the report. The described approach is exactly what we need to do here. `StaticNodeSelection` (and a couple other places) use the mutable collection while they should consume the read-only one that is not mutated once returned from the `Partitions` object.

**Comment by mp911de** [comment]
That's fixed now.
