### ISSUE TITLE
xpending(K, Consumer, Range, Limit) fails with ERR syntax error using Limit.unlimited()

### ISSUE THREAD

**Issue by nagaran1** [lettuce-io/lettuce-core#1302]
I am creating an application which operates on Redis streams using the commands Add, ReadGroup, Del, Ack, Pending and Claim using the dependency ```spring-boot-starter-data-redis-reactive``` and i have configured a bean for ReactiveRedisConnectionFactory as below
```
@Bean
    @Primary
    public ReactiveRedisConnectionFactory connectionFactory(RedisStandaloneConfiguration redisStandaloneConfiguration) {

        LettuceClientConfiguration configuration = LettuceClientConfiguration.builder()
                .clientOptions(clientOptions()).build();
        return new LettuceConnectionFactory(redisStandaloneConfiguration, configuration);
    }
@Bean
    @Primary
    ReactiveRedisOperations<String, String> redisOperations(ReactiveRedisConnectionFactory factory) {
        RedisSerializationContext.RedisSerializationContextBuilder<String, String> builder =
                RedisSerializationContext.newSerializationContext(new StringRedisSerializer());
        RedisSerializationContext<String, String> context = builder.build();
        return new ReactiveRedisTemplate<String, String>(factory, context);
    }
```

Then using the opsForStream, I am able to add/delete/ack/read/readgroup the message

```
this.reactiveRedisOperations
                .opsForStream()
                .add(streamName, Collections.singletonMap("body", message))
                .subscribe();
```

But, the below snippet throws ERR syntax errror. where i am expecting PendingMessages, so that i can reclaim it.

```
this.reactiveRedisOperations
                            .opsForStream()
                            .pending("mystream", Consumer.from("mygroup", "myservice"))
                            .subscribe(pendingMessages -> System.out.println(pendingMessages.size()));

Exception Trace:

2020-06-01 19:59:01.773  WARN 38696 --- [ioEventLoop-7-1] io.lettuce.core.protocol.CommandHandler  : null Unexpected exception during request: reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR syntax error

reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR syntax error
Caused by: org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR syntax error
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:54) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveRedisConnection.lambda$translateException$0(LettuceReactiveRedisConnection.java:293) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6504) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:247) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:106) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onError(RedisPublisher.java:890) ~[lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.lettuce.core.RedisPublisher$State.onError(RedisPublisher.java:687) ~[lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.lettuce.core.RedisPublisher$RedisSubscription.onError(RedisPublisher.java:344) ~[lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.onError(RedisPublisher.java:800) ~[lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.complete(RedisPublisher.java:736) ~[lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:654) [lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:614) [lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565) [lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_251]
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR syntax error
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:135) ~[lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:108) ~[lettuce-core-5.3.0.RELEASE.jar:5.3.0.RELEASE]
	... 20 common frames omitted
```

#### Environment

- Lettuce version(s): 5.3.0.RELEASE
- Redis version: 6.0.2 and 5.0.6

#### Additional context

The below XPending commands works fine which produces PendingMessageSummary.
```
this.reactiveRedisOperations
                .opsForStream()
                .pending("mystream", "mygroup")
                .subscribe((pendingMessagesSummary -> {
                    long totalPendingMessages = pendingMessagesSummary.getTotalPendingMessages();
                 }));
```

**Comment by nagaran1** [comment]
This issue happens in 5.0.x versions of Redis
