### ISSUE TITLE
Unable to connect to AWS Elasticache clustered mode Redis with in-transit encryption enabled.

### ISSUE THREAD

**Issue by umang92** [lettuce-io/lettuce-core#1315]
#### Current Behavior
I am using lettuce-core-5.3.0.RELEASE. When I connect with AWS Elasticache clustered mode Redis with in-transit encryption disabled then the everything works fine. But using the same set up when I try to connect with AWS Elasticache clustered mode Redis with in-transit encryption enabled, then I see the error:  "Cannot retrieve initial cluster partitions from initial URIs"

<details>
<summary>Stack trace</summary>

```java
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.adobe.cpfstreamingabstraction.connection.redis.RedisConnectionPool]: Factory method 'redisConnectionPool' threw exception; nested exception is io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='clustercfg.redis-test-cluster.z5b0fq.euw1.cache.amazonaws.com', port=6379]]
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
... 45 common frames omitted\n

Caused by: io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='clustercfg.redis-test-cluster.z5b0fq.euw1.cache.amazonaws.com', port=6379]]
at io.lettuce.core.cluster.RedisClusterClient.doLoadPartitions(RedisClusterClient.java:874)
at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:844)
at io.lettuce.core.cluster.RedisClusterClient.initializePartitions(RedisClusterClient.java:819)
at io.lettuce.core.cluster.RedisClusterClient.connectPubSub(RedisClusterClient.java:419)\n
at com.abc.abcstreamingabstraction.connection.redis.RedisClusterConnection.getPubSubConnection(RedisClusterConnection.java:49)
at com.abc.abcstreamingabstraction.connection.redis.RedisClusterConnection.<init>(RedisClusterConnection.java:100)
at com.adobe.cpfstreamingabstraction.init.Initializer.redisConnectionPool(Initializer.java:66)
at com.abc.abcstreamingabstraction.init.Initializer$$EnhancerBySpringCGLIB$$9fc7bed2.CGLIB$redisConnectionPool$0(<generated>)
at com.abc.abcstreamingabstraction.init.Initializer$$EnhancerBySpringCGLIB$$9fc7bed2$$FastClassBySpringCGLIB$$286b0c2a.invoke(<generated>)
tat org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
at com.abc.abcstreamingabstraction.init.Initializer$$EnhancerBySpringCGLIB$$9fc7bed2.redisConnectionPool(<generated>)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)\n\t... 46 common frames omitted\n"}
```

</details>

#### Input Code

```
 logger.info(redisDetails.toString());
        RedisURI redisURI = RedisURI.create(redisDetails.getHost(), redisDetails.getPort());
        if(properties.getIsRedisEncrypted()){
            redisURI.setSsl(Boolean.TRUE);
            redisURI.setStartTls(Boolean.TRUE);
        }
        RedisClusterClient redisClusterClient = RedisClusterClient.create(redisURI);
        if (redisClusterClient == null) {
            logger.info("Could not create Redis connection.");
            throw new Exception("Could not create redis connection.");
        } else
            logger.info("Redis connection created successfully.");

        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enablePeriodicRefresh(Duration.ofMinutes(properties.getRedisTopologyRefreshInterval()))
                .enableAllAdaptiveRefreshTriggers()
                .build();

        redisClusterClient.setOptions(ClusterClientOptions.builder()
                .topologyRefreshOptions(topologyRefreshOptions)
                .build());

        this.connection = redisClusterClient.connectPubSub(new StreamRedisCodec());
<details>
<summary>Input Code</summary>


```
The exception is thrown in this line 
``` 
this.connection = redisClusterClient.connectPubSub(new StreamRedisCodec());
```
</details>

#### Expected behavior/code

The connection should go through as expected as I have set the SSL configuration correctly in the client code. 
#### Environment

- Lettuce version(s): [5.3.0.RELEASE]
- Redis version: [5.0.6]

**Comment by mp911de** [comment]
Can you attach the debug log? That should reveal why the client wasn't able to connect to your redis host.

**Comment by umang92** [comment]
Sure. I have set my rootLogger level to DEBUG. Still don't see any DEBUG logs from lettuce. How do I enabled them?

**Comment by umang92** [comment]
Also, I found a related issues https://github.com/lettuce-io/lettuce-core/issues/1321
Here the user is able to connect in-transit encryption enabled Redis, but rather than using lettuce-core directly, he is using LettuceConnectionFactory and spring data redis. Is there any difference between the two approaches?

**Comment by umang92** [comment]
Attaching DEBUG logs here
[lettuce-debug-1.txt](https://github.com/lettuce-io/lettuce-core/files/4840629/lettuce-debug-1.txt)

**Comment by mp911de** [comment]
Thanks a lot. The SSL handshake succeeds:

```
{"timestamp":"2020-06-27T14:04:49.468+00:00","logger_name":"i.l.c.p.ConnectionWatchdog","thread_name":"lettuce-nioEventLoop-6-2","level":"DEBUG","serviceArchPath":"CC.Sensei.core","process":"NA","message":"[channel=0x84c02f89, /172.16.15.31:44390 -> …, last known addr=…] userEventTriggered(ctx, SslHandshakeCompletionEvent(SUCCESS))"}
```

Later on, the topology retrieval fails due to authentication: `NOAUTH Authentication required.`

Please configure authentication via `RedisURI`.

**Comment by vinaysdeveloper** [comment]
@umang92  can you please share your complete code
