### ISSUE TITLE
Consider remove LettuceCdiExtension.LOGGER or defer creating it

### ISSUE THREAD

**Issue by quaff** [lettuce-io/lettuce-core#1351]
Open Liberty will create `LettuceCdiExtension` instance before application initialization, it cause underlying logging like log4j2 initialize too early.
see also https://github.com/spring-projects/spring-framework/issues/25427

**Comment by mp911de** [comment]
So how are we supposed to log the initialization in the constructor:

https://github.com/lettuce-io/lettuce-core/blob/b978238db8a33c8860819b73e528f016f940e992/src/main/java/io/lettuce/core/support/LettuceCdiExtension.java#L88

Or is it just that the logger is `static`?

**Comment by quaff** [comment]
I'm afraid that removing `static` like [`StandardWebSocketHandlerAdapter`](https://github.com/spring-projects/spring-framework/commit/64f4703445c57adba37477394f2c3217d0af99cb) is not enough, jboss weld will new instance of `LettuceCdiExtension` not only load it.
here is stack trace:
```
[err] 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
[err] 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
[err] 	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
[err] 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
[err] 	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
[err] 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
[err] 	at io.netty.util.internal.logging.Slf4JLoggerFactory.newInstance(Slf4JLoggerFactory.java:49)
[err] 	at io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(InternalLoggerFactory.java:43)
[err] 	at io.netty.util.internal.logging.InternalLoggerFactory.getDefaultFactory(InternalLoggerFactory.java:67)
[err] 	at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:93)
[err] 	at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:86)
[err] 	at io.lettuce.core.support.LettuceCdiExtension.<clinit>(LettuceCdiExtension.java:79)
[err] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[err] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[err] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[err] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[err] 	at org.jboss.weld.util.ServiceLoader.createInstance(ServiceLoader.java:313)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[err] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mp911de** [comment]
We'd like to keep the logging feature to indicate the extension was activated as in the past it was difficult to diagnose which CDI extensions got activated. That being said, there's nothing we can do here.
