### ISSUE TITLE
Redis sentinel works wrong when configuring ReadFrom strategy on switching master

### ISSUE THREAD

**Issue by liuyalou1996** [lettuce-io/lettuce-core#1364]
## Bug Report
I'm using spring data redis to configure Redis Sentinel,everything works well when I doesn't setup "ReadFrom" option on swtching master by sentinel. But when I setup the "ReadFrom" option,I find lettuce client cannot connect the newest master and keep the old master address.

#### Current Behavior
```
2020-07-28 14:23:59.768  INFO 18088 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /122.51.151.130:6382
2020-07-28 14:24:00.866  WARN 18088 --- [ioEventLoop-6-4] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [122.51.151.130:6382]: Connection refused: no further information: /122.51.151.130:6382
2020-07-28 14:24:05.767  INFO 18088 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 122.51.151.130:6382
2020-07-28 14:24:06.102  WARN 18088 --- [ioEventLoop-6-4] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [122.51.151.130:6382]: java.util.concurrent.CancellationException

org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.util.concurrent.CancellationException

	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:53)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:43)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.set(LettuceStringCommands.java:148)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.set(DefaultedRedisConnection.java:287)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.set(DefaultStringRedisConnection.java:973)
	at org.springframework.data.redis.core.DefaultValueOperations$3.inRedis(DefaultValueOperations.java:240)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:236)
	at com.netease.redis.sentinel.RedisSentinelTest.automaticFailoverTest(RedisSentinelTest.java:28)
	
```

#### Input Code
```
@Configuration
public class RedisSentinelConfig {

	@Bean
	public RedisConnectionFactory redisConnectionFactory() {
		LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
						.readFrom(ReadFrom.REPLICA_PREFERRED)
						.build();
		RedisSentinelConfiguration sentinelConfig = new RedisSentinelConfiguration()
						.master("mymaster")
						.sentinel("122.51.151.130", 26380)
						.sentinel("122.51.151.130", 26381)
						.sentinel("122.51.151.130", 26382);
		return new LettuceConnectionFactory(sentinelConfig, clientConfig);
	}
}

@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class)
public class RedisSentinelTest {

	@Autowired
	private StringRedisTemplate stringRedisTemplate;

	/**
	 * 期间关掉master，哨兵会进行自动故障切换，客户端重连到新的master
	 * @throws InterruptedException
	 */
	@Test
	public void automaticFailoverTest() throws InterruptedException {
		int count = 0;
		while (true) {
			stringRedisTemplate.opsForValue().set("count", String.valueOf(++count));
			System.out.println("修改count的值，当前值为：" + count);
			Thread.sleep(1000);
		}
	}
}
```

#### Environment

- Lettuce version(s): 5.3.2.RELEASE
- Redis version: 6.0.4
- There are 3 sentinels and 3 redis instances(1 master and 2 replicas)

**Comment by mp911de** [comment]
This is pretty normal behavior. The old master address gets reported by Redis Sentinel until the failover is finished. Once the failover is finished, the old master connection gets closed and all pending commands get canceled (therefore you see `CancellationException`). After failover, commands will be ran on the new master node. Please note that `ReadFrom` isn't applicable to write commands such as `SET`.

**Comment by liuyalou1996** [comment]
But if I don't configure the "ReadFrom"，I will never see ``CancellationException at all and client successfully reconnect to the new master.

**Comment by mp911de** [comment]
Connections are handled differently. Without `ReadFrom`, you have a single Redis connections. Upon failover, typically the master node disconnects on the TCP level. Commands are queued and retried upon reconnect to the new master.

With `ReadFrom`, Spring Data Redis uses `MasterReplica` which maintains individual connections to each node in the replica set. That also means, that commands get routed to different connections and remain there. Connections are not internally rebound to a different host but remain sticky to the host/port combination. Upon failover, the actual connection gets closed and commands get cancelled, regardless of whether the target node closed the connection or not.

We don't have means to know whether a previous connection was pointing to a master or a replica and therefore we need to cancel all commands.

The alternative would be requeueing commands and sending these according to `ReadFrom` to the new connections with the potential risk that those commands would have already been processed.

**Comment by liuyalou1996** [comment]
At first,thanks for your explanation.But I still have doubt that if automic failover happens and conenctions get closed,I have to restart the program and make client reconnect to sentinel for new reported address. Are there any other solutions?

**Comment by mp911de** [comment]
Your app does not require a restart. After failover, the old master connection gets closed but  a new one is already active at that time. That means, that commands get routed to the new master.
