### ISSUE TITLE
"RedisCommandTimeoutException: Command timed out" report on one of redis cluster nodes severely

### ISSUE THREAD

**Issue by 2339478391** [lettuce-io/lettuce-core#1388]
lettuce's version 4.5.0.Final
the redis cluster has 8 nodes
every backends(switched jedis to lettuce) visit the 7th node(get setex) will time out all the time
but jedis is ok

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by 2339478391** [comment]
com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out after 15000 MILLISECONDS
at com.lambdaworks.redis.ExceptionFactory.createTimeoutException(ExceptionFactory.java:39)
at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:118)
at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:96)
at com.lambdaworks.redis.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:117)
at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
at com.sun.proxy.$Proxy46.setex(Unknown Source)

**Comment by 2339478391** [comment]
it's not reproduced by simple unit test
but,if I deploy the backend with lettuce, the time out occur

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
