### ISSUE TITLE
RedisClient.shutdown  Cannot connect, Event executor group is terminated.

### ISSUE THREAD

**Issue by MurderWind** [lettuce-io/lettuce-core#1399]
#### Current Behavior

  i pop list  from redis . but i shutdown my application .when i restart my application .i find the stack message. 
it is fixed  the problem via #998 , why do it comes again?

<details>
<summary>Stack trace</summary>

java.lang.IllegalStateException: Cannot connect, Event executor group is terminated.
	at io.lettuce.core.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:290)
	at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:293)
	at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:273)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:206)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.3.2.RELEASE]
- Redis version: [e.g. 3.3.0]

**Comment by mp911de** [comment]
The bug within Lettuce was fixed with #998. However, your application must not create a new connection after shutting down `RedisClient`. That's something that must be fixed on your side.
