### ISSUE TITLE
readAddress(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by uzdz** [lettuce-io/lettuce-core#1403]
Hello developer:
  At present, when my program uses lettuce, the following exception will be thrown in the next request after a long time of no operation.

Here is my client configuration and exception information.For security, IP information has been erased.

```yaml
spring:
  redis:
    # redis数据库索引（默认为0）
    database: 1
    # redis服务器地址（默认为localhost）
    host: xxx.xxx.xx
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: 123456
    # redis连接超时时间（单位为毫秒）
    timeout: 10000
    # redis连接池配置
    lettuce:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: -1
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: -1
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
```
```txt
exception; nested exception is io.lettuce.core.RedisException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.setEx(LettuceStringCommands.java:232)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.setEx(DefaultedRedisConnection.java:308)
	at org.springframework.data.redis.core.DefaultValueOperations$4.potentiallyUsePsetEx(DefaultValueOperations.java:268)
	at org.springframework.data.redis.core.DefaultValueOperations$4.doInRedis(DefaultValueOperations.java:261)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:256)
```

I can't find the exception, so what is the reason for this situation?

**Comment by uzdz** [comment]
However, after an exception occurs, the following log will be output. It seems that a reconnection operation has occurred, and subsequent business operations can normally request redis.

```text
2020-08-31 16:39:25.171 [lettuce-eventExecutorLoop-1-2] INFO  i.l.c.p.ConnectionWatchdog [log:171]     - Reconnecting, last destination was xxx.xx.xx.xx/xxx.xx.xx.xx:6379
2020-08-31 16:39:25.177 [lettuce-epollEventLoop-6-1] INFO  i.l.c.p.ReconnectionHandler [lambda$null$4:188]     - Reconnected to xxx.xx.xx.xx:6379
```

**Comment by uzdz** [comment]
The version of springboot we use is:

```xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.0.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
    </parent>
```
The version of lettuce used internally is:

```txt
5.3.0.RELEASE
```

**Comment by mp911de** [comment]
`Connection reset by peer` is a server-side state change without following the full TCP close procedure. Typically, that is when the server process dies or if active network components terminate the connection because of inactivity. See https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean for further reference. There's nothing really we can do from our side.

**Comment by Wuxiy** [comment]
You can try to set `factory.setValidateConnection(true)`

If you enable validate, it will validate every time you get, and its validate method not only judges isOpen, but also judges ping. If it times out, it will release/return the connection and get it again (if you use a connection pool, then Borrow again)

**Comment by BigChanChanMan** [comment]
看下redis的配置：
config get timeout
config get tcp-keepalive
是不是timeout比tcp-keepalive设置的大了。
timeout之后，lettuce会打印，Reconnecting日志。

**Comment by BigChanChanMan** [comment]
> However, after an exception occurs, the following log will be output. It seems that a reconnection operation has occurred, and subsequent business operations can normally request redis.
> 
> ```
> 2020-08-31 16:39:25.171 [lettuce-eventExecutorLoop-1-2] INFO  i.l.c.p.ConnectionWatchdog [log:171]     - Reconnecting, last destination was xxx.xx.xx.xx/xxx.xx.xx.xx:6379
> 2020-08-31 16:39:25.177 [lettuce-epollEventLoop-6-1] INFO  i.l.c.p.ReconnectionHandler [lambda$null$4:188]     - Reconnected to xxx.xx.xx.xx:6379
> ```

I also encountered the exact same issue. How did you eventually handle it? Did you adjust the Redis server's configuration?

**Comment by renatomameli** [comment]
Would also be interested in a solution

**Comment by tishun** [comment]
> Would also be interested in a solution

I suggest you start from the server and the network stack. The client cannot do anything meaningful if the connection was terminated. The only thing it could do is attempt to reconnect, but if the issue persists it would simply lead to more conneciton drops.

Examine the network stack and the server for any abnormalities or misconfigurations to try and understand better what the issue is.
