### ISSUE TITLE
Reactive retry() failing to reconnect to remote azure redis instance

### ISSUE THREAD

**Issue by ijmac3** [lettuce-io/lettuce-core#1419]
#### Current Behavior

We have created a reactive stream to listen for messages that are added to a queue. We found that a sudden redis outage caused the listener to break and be unable to reconnect, repeatedly hitting our `doOnError` block even after redis recovered. We are able to replicate this behaviour by putting a firewall rule in place to block our connection to redis. 

Strangely, we have found that it _does_ reconnect successfully if we use `retryBackoff()` instead of `retry()`. While the log spam is understandable, we aren't sure why `retry()` is unable to reconnect when `retryBackoff()` can.

While creating a sample project to allow this issue to be reproduced, I noticed that Lettuce was throwing the following internal error when using `retry()`:

<details>
<summary>Stack trace - retry</summary>

```java
An existing connection was forcibly closed by the remote host
Sep 15, 2020 1:57:10 PM io.lettuce.core.protocol.DefaultEndpoint$RetryListener doComplete
WARNING: Unexpected exception during request: java.io.IOException: An existing connection was forcibly closed by the remote host
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726)
	at io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:2023)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:796)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:773)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:788)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:756)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:806)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
	at io.lettuce.core.protocol.DefaultEndpoint.channelWriteAndFlush(DefaultEndpoint.java:342)
	at io.lettuce.core.protocol.DefaultEndpoint.writeToChannelAndFlush(DefaultEndpoint.java:282)
	at io.lettuce.core.protocol.DefaultEndpoint.write(DefaultEndpoint.java:142)
	at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:187)
	at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:171)
	at io.lettuce.core.masterslave.MasterSlaveChannelWriter.writeCommand(MasterSlaveChannelWriter.java:91)
	at io.lettuce.core.masterslave.MasterSlaveChannelWriter.write(MasterSlaveChannelWriter.java:73)
	at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:187)
	at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:171)
	at io.lettuce.core.RedisPublisher$RedisSubscription.dispatchCommand(RedisPublisher.java:382)
	at io.lettuce.core.RedisPublisher$CommandDispatch$1.dispatch(RedisPublisher.java:452)
	at io.lettuce.core.RedisPublisher$RedisSubscription.checkCommandDispatch(RedisPublisher.java:377)
	at io.lettuce.core.RedisPublisher$State$2.request(RedisPublisher.java:518)
	at io.lettuce.core.RedisPublisher$RedisSubscription.request(RedisPublisher.java:235)
	at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:102)
	at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:102)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2007)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1881)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:171)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:145)
	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:64)
	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:64)
	at io.lettuce.core.RedisPublisher$State$1.subscribe(RedisPublisher.java:497)
	at io.lettuce.core.RedisPublisher$RedisSubscription.subscribe(RedisPublisher.java:218)
	at io.lettuce.core.RedisPublisher.subscribe(RedisPublisher.java:125)
	at reactor.core.publisher.MonoFromPublisher.subscribe(MonoFromPublisher.java:55)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:113)
	at reactor.core.publisher.MonoRepeatPredicate.subscribeOrReturn(MonoRepeatPredicate.java:47)
	at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:66)
	at reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:110)
	at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:94)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:1876)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251)
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onError(RedisPublisher.java:890)
	at io.lettuce.core.RedisPublisher$State.onError(RedisPublisher.java:687)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onError(RedisPublisher.java:344)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.onError(RedisPublisher.java:800)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.completeExceptionally(RedisPublisher.java:794)
	at io.lettuce.core.protocol.CommandHandler.exceptionCaught(CommandHandler.java:233)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:271)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at io.lettuce.core.SslConnectionBuilder$SslChannelInitializer$2.exceptionCaught(SslConnectionBuilder.java:237)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:271)
	at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:1090)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:271)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

Meanwhile, with `retryBackoff()` it repeatedly logs the following:
<details>
<summary>Stack trace - retryBackoff</summary>

```java
Sep 15, 2020 3:25:30 PM io.lettuce.core.protocol.ConnectionWatchdog run
INFO: Reconnecting, last destination was {redisHost}/{hostIP}:6380
Sep 15, 2020 3:25:40 PM io.lettuce.core.protocol.ConnectionWatchdog lambda$run$4
WARNING: Cannot reconnect to [{redisHost}:6380]: connection timed out: {redisHost}/{hostIP}:6380
```

</details>

With retryBackoff, it will eventually reconnect, logging the following message:
`INFO: Reconnected to {redisHost}:6380`
#### Input Code

A sample class similar to our listener which should demonstrate this issue.

Start the listener then place a firewall rule in place to block connection to the remote redis instance. Note the difference in behaviour between `retry()` and `retryBackoff()`

<details>
<summary>Input Code</summary>

```java
public class LettuceTest {
    
    private final StatefulRedisMasterReplicaConnection<String, String> connection;
    private final String channelName;

    public LettuceTest() {
        channelName = "azure_lettuce_reactive_retry_channel";
        RedisClient redisClient = RedisClient.create(getRedisURI());
        connection = MasterReplica.connect(redisClient, StringCodec.UTF8, getRedisURI());
        connection.reactive().rpush(channelName, "test")
                .doOnError(Throwable::printStackTrace)
                .subscribe();
        Executors.newSingleThreadExecutor().submit(this::initListener);
    }

    private void initListener() {
        try {
            connection.reactive().blpop(Integer.MAX_VALUE, channelName)
                    .doOnError(e -> System.out.println(e.getMessage()))
                    .doOnNext(s -> System.out.println(s.getValue()))
                    .repeat()
                    .retry()
                    //.retryBackoff(Integer.MAX_VALUE, Duration.ofSeconds(10), Duration.ofMinutes(10))
                    .subscribe();
        } catch (Exception e) {
            System.out.println("CAUGHT " + e.getMessage());
        }
    }

    private RedisURI getRedisURI() {
        return RedisURI.Builder.redis(getHost())
                .withSsl(true)
                .withPassword(getPassword())
                .withPort(6380)
                .build();
    }
}
```

</details>

#### Expected behavior/code

We would have expected similar behaviour from both retry and retryBackoff
#### Environment

- Lettuce version(s): io.lettuce:lettuce-core:5.2.2.RELEASE
- Redis version: 4.0.14 (Azure redis cache)

**Comment by mp911de** [comment]
Both methods are provided by Project Reactor. Unless commands get completed with an I/O exception, they get retried upon reconnect. Reconnects happen regardless of which API or what operators are used.

Not quite sure how to proceed since the use of Reactor operators is not tied to how Lettuce works internally.

**Comment by ijmac3** [comment]
Interesting. Were you able to replicate the behaviour we're seeing or was retry() reconnecting successfully for you?

**Comment by AlbozDroid** [comment]
@mp911de Did you investigate this more? By using the reproducer code  above this issue can be reproduced quite easily.

**Comment by mp911de** [comment]
Not yet, I need to get an Azure subscription first all this is open source sponsored by the free time of maintainers.

**Comment by ijmac3** [comment]
I think this should be reproducible without azure specifically. I think any remote instance of redis that suddenly has a firewall rule put in place to block connections should be able to reproduce this.

**Comment by mp911de** [comment]
Closing due to lack of activity and we cannot really do here anything. If you would like us to look at this issue, please provide additional information and we will re-open the issue.
