### ISSUE TITLE
Lettuce client connection issue with Redis 6 

### ISSUE THREAD

**Issue by salujasarab** [lettuce-io/lettuce-core#1446]
Hi,
We are running Redis in cluster mode with password. We use Redis Server version 6.0.5. 
We are fetching data using Lettuce client. The client version is 5.0.3. The instantiation of client and fetching data works fine with client version 5.0.3. We run this system at a very high scale.
 
Recently we tried to upgrade the Lettuce client to Version 5.3.3. The client instantiation went fine and it was fetching data successfully. All of a sudden the client lost the password and was not able to connect to Redis. The exception we saw was "NOAUTH Authentication required".
We did not see this issue for all the client instances, only some instances had this issue. Has this issue been reported earlier? 

Here is the stack trace for the Exception:

Caused by: io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required.
        at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:118)
        at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:109)
        at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:57)
        at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:63)
        at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:601)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:559)
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:511)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

Thanks.

**Comment by mp911de** [comment]
Can you isolate the issue to a particular cluster node or when the issue starts to happen (at startup, after refreshing the topology, after adding a node to the cluster)? We generally have integration tests verifying cluster with SSL and password usage so we need additional details to find out what happened.

**Comment by salujasarab** [comment]
The topology refresh happened and the host was serving traffic successfully. We saw the following in the log just before we started getting the NOAUTH exception:

2020-10-05 20:29:04,755 INFO [lettuce-eventExecutorLoop-4-10] io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /<HOST_IP>:<port>
2020-10-05 20:29:04,765 INFO [lettuce-nioEventLoop-6-2] io.lettuce.core.protocol.ReconnectionHandler - Reconnected to <HOST_IP>/<unresolved>:<port>

Note that: "the HOST_IP:port" - this node was already part of the topology.

**Comment by mp911de** [comment]
Closing due to lack of activity. If you would like us to look at this issue, please let us know and we will re-open the issue.
