### ISSUE TITLE
Lettuce doesn't handle deleted stream items (NullPointerException)

### ISSUE THREAD

**Issue by chemist777** [lettuce-io/lettuce-core#1474]
## Bug Report

When I try to read pending messages via XREADGROUP I get the following NullPointerException.

It occurs when a pending message is already deleted from the stream due to its size limit.

The issue is related to the Redis behavior described in this comment https://github.com/redis/redis/blob/5.0.2/src/t_stream.c#L1031.

Also, Python client faced the same issue the previous year https://github.com/andymccurdy/redis-py/issues/1116

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
java.lang.NullPointerException: null
	at io.lettuce.core.codec.ByteArrayCodec.getBytes(ByteArrayCodec.java:84)
	at io.lettuce.core.codec.ByteArrayCodec.decodeKey(ByteArrayCodec.java:59)
	at io.lettuce.core.codec.ByteArrayCodec.decodeKey(ByteArrayCodec.java:28)
	at io.lettuce.core.output.StreamReadOutput.set(StreamReadOutput.java:73)
	at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:810)
	at io.lettuce.core.protocol.RedisStateMachine.handleNull(RedisStateMachine.java:392)
	at io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:206)
	at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:334)
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:295)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:799)
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:750)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:733)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:618)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:560)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

</details>

#### Expected behavior/code

No NPE.

#### Environment

- Lettuce version(s): 6.0.0.RELEASE
- Redis version: 6.0.8

Also, I use `ByteArrayCodec` for keys & values.

**Comment by mp911de** [comment]
Thanks a lot for letting us know. That's fixed and backported now.
