### ISSUE TITLE
Blocking call detected  in io.lettuce.core.metrics.DefaultCommandLatencyCollector

### ISSUE THREAD

**Issue by amrynsky** [lettuce-io/lettuce-core#1513]
- Lettuce version(s): 5.3.2.RELEASE
- Redis version: 5.0.10

While testing we detected a blocking call in lettuce client. Unfortunately, it's not happening on every run 

```
Suppressed: reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
		at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
		at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:714)
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:937)
		at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base/java.util.concurrent.LinkedBlockingQueue.signalNotEmpty(LinkedBlockingQueue.java:175)
		at java.base/java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:423)
		at java.base/java.util.AbstractQueue.add(AbstractQueue.java:95)
		at org.LatencyUtils.PauseDetector.addListener(PauseDetector.java:57)
		at org.LatencyUtils.PauseDetector.addListener(PauseDetector.java:46)
		at org.LatencyUtils.LatencyStats$PauseTracker.<init>(LatencyStats.java:469)
		at org.LatencyUtils.LatencyStats.<init>(LatencyStats.java:185)
		at org.LatencyUtils.LatencyStats$Builder.build(LatencyStats.java:390)
		at io.lettuce.core.metrics.DefaultCommandLatencyCollector$Latencies.<init>(DefaultCommandLatencyCollector.java:268)
		at io.lettuce.core.metrics.DefaultCommandLatencyCollector.lambda$recordCommandLatency$0(DefaultCommandLatencyCollector.java:112)
		at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
		at io.lettuce.core.metrics.DefaultCommandLatencyCollector.recordCommandLatency(DefaultCommandLatencyCollector.java:109)
		at io.lettuce.core.protocol.CommandHandler.recordLatency(CommandHandler.java:814)
		at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:696)
		at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:622)
		at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:591)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		... 13 more
```

**Comment by mp911de** [comment]
Lettuce initializes the `PauseDetector` lazily. There's nothing right now we could do about it without rewriting the entire code for latency collection. Please exclude this method in BlockHound.
