### ISSUE TITLE
RedisCommandTimeoutException issue with AWS Elasticache

### ISSUE THREAD

**Issue by ercancelik** [lettuce-io/lettuce-core#1516]
**spring-boot:2.3.1**
**lettuce-core:5.3.1.RELEASE**
**aws elasticache redis:** 
     instance: cache.t3.medium
     nodes: 2
     shards: 1
     encryption in-transit: enabled
     encryption at-rest: enabled

Cache Configurations:
```
@Bean
  public RedisTemplate<String, Serializable> redisTemplate(LettuceConnectionFactory redisConnectionFactory) {
    RedisTemplate<String, Serializable> redisTemplate = new RedisTemplate<>();
    redisTemplate.setConnectionFactory(redisConnectionFactory);

    StringRedisSerializer srs = new StringRedisSerializer();
    redisTemplate.setKeySerializer(srs);
    redisTemplate.setHashKeySerializer(srs);
    redisTemplate.setDefaultSerializer(new RedisObjectSerializer());
    redisTemplate.afterPropertiesSet();

    return redisTemplate;
  }

  @Bean
  public RedisConnectionFactory redisConnectionFactory() {
    RedisStandaloneConfiguration config = new RedisStandaloneConfiguration();
    config.setHostName(hostname);
    config.setPort(port);

    LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
        .commandTimeout(Duration.ofMillis(redisCacheExpireSeconds))
        .build();

    return new LettuceConnectionFactory(config, clientConfig);
  }
```

**pom.xml**
```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
      <exclusions>
        <exclusion>
          <groupId>redis.clients</groupId>
          <artifactId>jedis</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

As spring boot 2.3 supports lettuce as default redis client, I exclude jedis dependency from pom.xml.

I can connect my local redis server(both redis 5 and 6) that runs docker successfully, and do cache operations without any issue.

But when I try to connect to AWS Elasticache, it connects successfully, but when I started to do cache operations, it starts to throw connection timeout exceptions. 

I enabled lettuce logs in debug level. You can find stack trace below. I masked IP addresses and dns names for security:

```
...
2020-11-13 10:30:42.122 DEBUG 6 --- [ main] io.lettuce.core.RedisClient : Resolved SocketAddress master.xxx.cache.amazonaws.com:7443 using RedisURI [host='master.xxx.cache.amazonaws.com', port=7443]
2020-11-13 10:30:42.125 DEBUG 6 --- [ main] io.lettuce.core.RedisClient : Connecting to Redis at master.xxx.cache.amazonaws.com:7443
2020-11-13 10:30:42.618 DEBUG 6 --- [ioEventLoop-6-1] io.lettuce.core.protocol.CommandHandler : [channel=0x5761db59, [id: 0x51b245d0] (inactive), chid=0x1] channelRegistered()
2020-11-13 10:30:42.633 DEBUG 6 --- [ioEventLoop-6-1] io.lettuce.core.protocol.CommandHandler : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, chid=0x1] channelActive()
2020-11-13 10:30:42.636 DEBUG 6 --- [ioEventLoop-6-1] i.lettuce.core.protocol.DefaultEndpoint : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, epid=0x1] activateEndpointAndExecuteBufferedCommands 0 command(s) buffered
2020-11-13 10:30:42.636 DEBUG 6 --- [ioEventLoop-6-1] i.lettuce.core.protocol.DefaultEndpoint : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, epid=0x1] activating endpoint
2020-11-13 10:30:42.636 DEBUG 6 --- [ioEventLoop-6-1] i.lettuce.core.protocol.DefaultEndpoint : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, epid=0x1] flushCommands()
2020-11-13 10:30:42.637 DEBUG 6 --- [ioEventLoop-6-1] i.lettuce.core.protocol.DefaultEndpoint : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, epid=0x1] flushCommands() Flushing 0 commands
2020-11-13 10:30:42.637 DEBUG 6 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, last known addr=master.xxx.cache.amazonaws.com/10.157.x.y:7443] channelActive()
2020-11-13 10:30:42.638 DEBUG 6 --- [ioEventLoop-6-1] io.lettuce.core.protocol.CommandHandler : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, chid=0x1] channelActive() done
2020-11-13 10:30:42.640 DEBUG 6 --- [ioEventLoop-6-1] io.lettuce.core.RedisClient : Connecting to Redis at master.xxx.cache.amazonaws.com:7443: Success
2020-11-13 10:30:42.647 DEBUG 6 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, last known addr=master.xxx.cache.amazonaws.com/10.157.x.y:7443] userEventTriggered(ctx, io.lettuce.core.ConnectionEvents$Activated@e3134ea)
2020-11-13 10:30:42.651 DEBUG 6 --- [ main] io.lettuce.core.RedisChannelHandler : dispatching command AsyncCommand [type=KEYS, output=KeyListOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
2020-11-13 10:30:42.706 DEBUG 6 --- [ main] i.lettuce.core.protocol.DefaultEndpoint : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, epid=0x1] write() writeAndFlush command AsyncCommand [type=KEYS, output=KeyListOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
2020-11-13 10:30:42.712 DEBUG 6 --- [ioEventLoop-6-1] io.lettuce.core.protocol.CommandHandler : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, chid=0x1] write(ctx, AsyncCommand [type=KEYS, output=KeyListOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], promise)
2020-11-13 10:30:42.721 DEBUG 6 --- [           main] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, epid=0x1] write() done
2020-11-13 10:30:42.721 DEBUG 6 --- [ main] i.lettuce.core.protocol.DefaultEndpoint : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443, epid=0x1] write() done
2020-11-13 10:30:42.729 DEBUG 6 --- [ioEventLoop-6-1] io.lettuce.core.protocol.CommandEncoder : [channel=0x5761db59, /10.157.a.b:59782 -> master.xxx.cache.amazonaws.com/10.157.x.y:7443] writing command AsyncCommand [type=KEYS, output=KeyListOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]

...
2020-11-13 10:30:46.313 ERROR 6 --- [ main] c.g.s.config.redis.CacheConfiguration : Error: clear data on cache
	org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 3600 millisecond(s)
    at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
    at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
    at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
    at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
    at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273)
    at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.convertLettuceAccessException(LettuceKeyCommands.java:809)
    at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.keys(LettuceKeyCommands.java:226)
    at org.springframework.data.redis.connection.DefaultedRedisConnection.keys(DefaultedRedisConnection.java:110)
    at org.springframework.data.redis.cache.DefaultRedisCacheWriter.lambda$clean$4(DefaultRedisCacheWriter.java:182)
    at org.springframework.data.redis.cache.DefaultRedisCacheWriter.execute(DefaultRedisCacheWriter.java:242)
    at org.springframework.data.redis.cache.DefaultRedisCacheWriter.clean(DefaultRedisCacheWriter.java:171)
    at org.springframework.data.redis.cache.RedisCache.clear(RedisCache.java:193)
    at org.springframework.cache.interceptor.AbstractCacheInvoker.doClear(AbstractCacheInvoker.java:122)
    at org.springframework.cache.interceptor.CacheAspectSupport.performCacheEvict(CacheAspectSupport.java:489)
    at org.springframework.cache.interceptor.CacheAspectSupport.processCacheEvicts(CacheAspectSupport.java:477)
...


```

**Comment by mp911de** [comment]
Looking at the log, your Redis server doesn't respond within the timeout. There are `write(ctx, AsyncCommand [type=KEYS` log lines but no `Received: %d bytes` or `Completing command`. Closing since a non-responding Redis server is beyond of what we can do.

**Comment by ercancelik** [comment]
Sorry it was my fault. I shouldn't use master endpoint url as redis url. Instead I should use primary node's url.
