### ISSUE TITLE
Under sudden increase of load getting RedisCommandTimeoutException

### ISSUE THREAD

**Issue by shivlakhanpatel** [lettuce-io/lettuce-core#1525]
#### Current Behavior

Under sudden increase of load (100K RPM) we are getting **RedisCommandTimeoutException: Command timed out after 500 millisecond(s)** 

API flow is as below.

1. API get list of keys 70-100 in request
2. Borrows a connection
3. It looks for the keys using mget ()
4. If found returns the data 
5. Otherwise fetched the data from DB
6. Populates the cache with mset()
7. Sets the TTL
8. Close the connection(returns to the pool)

#### Stack trace
<details>
<summary>Stack trace</summary>

```java
at ...services.cache.LettuceCluster.mget(LettuceCluster.java:25)
	at com.sun.proxy.$Proxy79.mget(Unknown Source)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:190)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
	at com.sun.proxy.$Proxy79.mget(Unknown Source)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 500 millisecond(s)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// Pool property
GenericObjectPool<StatefulRedisClusterConnection<String, String>> redisClusterPool = ConnectionPoolSupport
                .createGenericObjectPool(() -> clusterClient.connect(), new GenericObjectPoolConfig());


        GenericObjectPoolConfig genericObjectPoolConfig = new GenericObjectPoolConfig();
        genericObjectPoolConfig.setMaxTotal(350);
        genericObjectPoolConfig.setMaxIdle(350);
        genericObjectPoolConfig.setMinIdle(250);
        genericObjectPoolConfig.setTestWhileIdle(true);
        genericObjectPoolConfig.setTimeBetweenEvictionRunsMillis(1000*60*60);
        genericObjectPoolConfig.setBlockWhenExhausted(configuration.getRedisConfig().getRedisPoolConfig().getBlockWhenExhausted());
        redisClusterPool.setConfig(genericObjectPoolConfig);

        try {
            redisClusterPool.preparePool();
        } catch(Exception ex) {
            logger.error("Got exception while preparing redis connection pool", ex);
        }
```

```java
// mget to get list of keys
public List<KeyValue<String, String>> mget(String... keys) {
             return connection.sync().mget(keys);
}

// mset to populate cache and set TTL
public String mset(Map<String, String> cacheEntries, Integer ttl) {
        try {
            RedisAdvancedClusterCommands<String, String> syncCommands = this.connection.sync();
            syncCommands.mset(cacheEntries);
            cacheEntries.keySet().stream().forEach((key) -> {
                syncCommands.expire(key, (long)ttl);
            });
            return "OK";
        } catch (Throwable th) {
            return "ERROR";
        }
    }
```

</details>

#### Expected behavior/code

mget(keys) should not throw RedisCommandTimeoutException and 500 ms is expected to be big number to get response.

#### Environment

- Lettuce version(s): 5.1.0
- Redis version: 4.0.10

- Client 
EC2 - CPU: 1024 
Memory: 1200mb

#### Thread dump
<details>
<summary>Thread dump</summary>

```java
at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
       Local Variable: java.util.concurrent.CountDownLatch$Sync#119
       Local Variable: java.util.concurrent.locks.AbstractQueuedSynchronizer$Node#267
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
    at io.lettuce.core.cluster.PipelinedRedisFuture.await(PipelinedRedisFuture.java:79)
    at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:112)
       Local Variable: io.lettuce.core.cluster.PipelinedRedisFuture#59
    at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
    at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
    at com.sun.proxy.$Proxy46.mget(<unknown string>)
    at sun.reflect.GeneratedMethodAccessor19.invoke(<unknown string>)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:190)
    at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
    at com.sun.proxy.$Proxy46.mget(<unknown string>)
    at ...services.cache.LettuceCluster.mget(LettuceCluster.java:25)
```

```java
java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c64f4148> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:587)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:440)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:121)
	at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:117)
	at ...services.cache.LettuceCluster.<init>(LettuceCluster.java:19)
```
</details>

**Comment by shivlakhanpatel** [comment]
@mp911de if possible can you please have look at this issue?

**Comment by mp911de** [comment]
This is likely a congestion/overload scenario where the Redis client runs at capacity. That isn't a bug, but rather a consequence. Hard to tell anything beyond that without profiling and benchmarking your system.

**Comment by shivlakhanpatel** [comment]
@mp911de thank you for your response, however we are not seeing any memory, CPU spike. We are using AWS managed Redis so all available stats not showing anything unusual. Why mget() has to wait ?

**Comment by mp911de** [comment]
I guess you refer to `awaitOrCancel` and `LockSupport.parkNanos` elements in the stack trace.

Lettuce is a non-blocking Redis client where all I/O operations happen on an EventLoop. The I/O thread is different from the thread calling `mget(…)` (or any other Redis command). Therefore, the calling thread needs to await command completion before continuing.

**Comment by mp911de** [comment]
Closing due to lack of activity. If you would like us to look at this issue, please provide additional information and we will re-open the issue.
