### ISSUE TITLE
Reactive stream spec violation when using command timeout

### ISSUE THREAD

**Issue by martin-tarjanyi** [lettuce-io/lettuce-core#1576]
## Bug Report

Related issue: #1274

#### Current Behavior

When a `RedisCommandTimeoutException` happens it is possible (depending on CPU task scheduling) that the timeout error will be triggered after the underlying command is completed thus violating reactive spec. Futhermore, this error causes the `DefaultEventExecutor` to terminate which leaves most subsequent Redis commands in a stuck state when `publishOnScheduler(true)`.

<details>
<summary>Stack trace</summary>

```java
Thread=[lettuce-eventExecutorLoop-5-7] Logger=io.netty.util.concurrent.SingleThreadEventExecutor Type=WARN Unexpected exception from an event executor: 
reactor.core.Exceptions$BubblingException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 100 millisecond(s)
	at reactor.core.Exceptions.bubble(Exceptions.java:173) ~[reactor-core-3.3.9.RELEASE.jar!/:3.3.9.RELEASE]
	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:635) ~[reactor-core-3.3.9.RELEASE.jar!/:3.3.9.RELEASE]
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:83) ~[reactor-core-3.3.9.RELEASE.jar!/:3.3.9.RELEASE]
	at io.lettuce.core.RedisPublisher$OnComplete.run(RedisPublisher.java:1094) ~[lettuce-core-5.3.3.RELEASE.jar!/:5.3.3.RELEASE]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.51.Final.jar!/:4.1.51.Final]
```

</details>

#### Input Code

https://github.com/martin-tarjanyi/lettuce-executor-reject-repro

#### Expected behavior/code

No violation of reactive stream spec, no terminated executor, no stuck Redis commands

#### Environment

- Lettuce version: 5.3.5.RELEASE
- Redis version: any

#### Possible Solution

As pointed out by @mp911de ` SubscriptionCommand` and `CommandWrapper` do not ensure single completion. Fixing that will fix this issue.

**Comment by mp911de** [comment]
That's fixed now.

**Comment by martin-tarjanyi** [comment]
We appreciate the really quick turnaround. Thank you @mp911de!

**Comment by mp911de** [comment]
The releases 6.0.2 respective 5.3.6 are now available from Maven Central
