### ISSUE TITLE
Constant deserialization into wrong types that happens rarely and sporadically

### ISSUE THREAD

**Issue by VeronikaGaivoronskaiaDH** [lettuce-io/lettuce-core#1597]
## Bug Report

Cannot find anything that looks like an our issue.

#### Current Behavior

We have a very strange issue that happens sporadically. Once in a while at one of our pods we start to get org.springframework.data.redis.serializer.SerializationException
for every call. Like lettuce try do deserialize values into wrong types of objects. And the only way to stop it is killing the pod. I cannot find any correlations between keys eviction or memory issues, for example, and this problem. Could lettuce cause this strange behaviour and what can be possibly done to eliminate it?

<details>
org.springframework.data.redis.serializer.SerializationException: Could not read JSON: Unrecognized token 'OK': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"OK"; line: 1, column: 3]; nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'OK': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"OK"; line: 1, column: 3]
	at org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer.deserialize(Jackson2JsonRedisSerializer.java:75)
	at org.springframework.data.redis.serializer.DefaultRedisElementReader.read(DefaultRedisElementReader.java:49)

org.springframework.data.redis.serializer.SerializationException: Could not read JSON: Unrecognized token 'zvRSnh': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"zvRSnh*["; line: 1, column: 8]; nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'zvRSnh': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"zvRSnh*["; line: 1, column: 8]
	at org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer.deserialize(Jackson2JsonRedisSerializer.java:75)
	at org.springframework.data.redis.serializer.DefaultRedisElementReader.read(DefaultRedisElementReader.java:49)
	at org.springframework.data.redis.serializer.RedisSerializationContext$SerializationPair.read(RedisSerializationContext.java:272)
	at org.springframework.data.redis.core.DefaultReactiveValueOperations.readValue(DefaultReactiveValueOperations.java:365)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:281)
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:860)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:99)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:136)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:136)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.lambda$onNext$0(TracingSubscriber.java:38)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.withActiveSpan(TracingSubscriber.java:60)
	at datadog.trace.instrumentation.reactor.core.TracingSubscriber.onNext(TracingSubscriber.java:38)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onNext(RedisPublisher.java:918)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:291)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.complete(RedisPublisher.java:782)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:59)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:704)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:639)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:560)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:832)
</details>

#### Environment

- Lettuce version(s): 6.0.1.RELEASE
- Redis version: 2.4.1

**Comment by mp911de** [comment]
There's no Jackson support in Lettuce.
