### ISSUE TITLE
NullPointerException in BoundedAsyncPool.createIdle() when availableCapacity=0

### ISSUE THREAD

**Issue by fbotis** [lettuce-io/lettuce-core#1611]
## Bug Report
Looks like there's a null pointer exception if createIdle() is called from different threads and availableCapacity becomes 0 while createIdle() is executed.

#### Current Behavior

The  bug appears in the below method and the scenario is described below:
   Thread 1: calls createIdle(): toCreate = 1  
   Thread 2: calls createIdle(): toCreate =1  
   Thread 1: reaches the line where makeObject0(future); is called 
   Thread 2: the if(getAvailableCapacity()) returns 0 thus it breaks . That means the futures array will contain one null element

```java
 @SuppressWarnings("rawtypes")
    CompletableFuture<Void> createIdle() {

        int potentialIdle = getMinIdle() - getIdle();
        if (potentialIdle <= 0 || !isPoolActive()) {
            return CompletableFuture.completedFuture(null);
        }

        int totalLimit = getAvailableCapacity();
        int toCreate = Math.min(Math.max(0, totalLimit), potentialIdle);

        CompletableFuture[] futures = new CompletableFuture[toCreate];
        for (int i = 0; i < toCreate; i++) {

            if (getAvailableCapacity() <= 0) {
                break;
            }

            CompletableFuture<T> future = new CompletableFuture<>();
            futures[i] = future;
            makeObject0(future);

            future.thenAccept(it -> {

                if (isPoolActive()) {
                    idleCount.incrementAndGet();
                    cache.add(it);
                } else {
                    factory.destroy(it);
                }
            });
        }

        return CompletableFuture.allOf(futures);
    }
```

<details>
<summary>Stack trace</summary>

```java
Caused by: java.lang.NullPointerException: null
        at java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1306)
        at java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1303)
        at java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2225)
        at io.lettuce.core.support.BoundedAsyncPool.createIdle(BoundedAsyncPool.java:184)
        at io.lettuce.core.support.BoundedAsyncPool.acquire0(BoundedAsyncPool.java:236)
        at io.lettuce.core.support.BoundedAsyncPool.acquire(BoundedAsyncPool.java:197)
        at io.lettuce.core.support.AsyncConnectionPoolSupport$1.acquire(AsyncConnectionPoolSupport.java:186)
        at RedisCacheService.setCacheAsync(RedisCacheService.java:232)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

The code where this NPE is thrown is
```java
asyncConnectionPool.acquire()
   .thenCompose(connection -> connection.async().setex(key, ttlSeconds, value)
	.whenComplete((s, throwable) -> {
		asyncConnectionPool.release(connection);
	}));
```

</details>

#### Expected behavior/code

There shouldn't be any Exception thrown when the available capacity becomes 0

#### Environment

- Lettuce version(s): 6.0.2.RELEASE
- Redis version: 6.0

#### Possible Solution

The method with the fix (see changes in between **<>**)
```java
 @SuppressWarnings("rawtypes")
    CompletableFuture<Void> createIdle() {

        int potentialIdle = getMinIdle() - getIdle();
        if (potentialIdle <= 0 || !isPoolActive()) {
            return CompletableFuture.completedFuture(null);
        }

        int totalLimit = getAvailableCapacity();
        int toCreate = Math.min(Math.max(0, totalLimit), potentialIdle);

        **List<CompletableFuture> futures = new ArrayList(toCreate);**
        for (int i = 0; i < toCreate; i++) {

            if (getAvailableCapacity() <= 0) {
                break;
            }

            CompletableFuture<T> future = new CompletableFuture<>();
            **futures.add(future);**
            makeObject0(future);

            future.thenAccept(it -> {

                if (isPoolActive()) {
                    idleCount.incrementAndGet();
                    cache.add(it);
                } else {
                    factory.destroy(it);
                }
            });
        }

        **return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]));**
    }
```

**Comment by mp911de** [comment]
Thanks for report, that's fixed now.

**Comment by fbotis** [comment]
Thanks for the quick fix:)
