### ISSUE TITLE
Unable to read from Redis Cluster replica with Cluster topology refresh

### ISSUE THREAD

**Issue by terryyylim** [lettuce-io/lettuce-core#1616]
Hello, 

I think this is more of a query and perhaps not an issue, just wanted to understand if this behaviour I’m experiencing is expected.

I’m currently using the following configurations for cluster topology update. And, I’m trying to simulate a failover and node restart for Redis cluster.  
```
ClusterTopologyRefreshOptions clusterTopologyRefreshOptions =
    ClusterTopologyRefreshOptions.builder()
        .enablePeriodicRefresh(Duration.ofSeconds(config.getTopologyRefreshPeriod()))
        .enableAllAdaptiveRefreshTriggers()
        .adaptiveRefreshTriggersTimeout(Duration.ofSeconds(config.getAdaptiveRefreshTimeout()))
        .refreshTriggersReconnectAttempts(config.getRefreshTriggerReconnectionAttempts())
        .build();

io.lettuce.core.cluster.RedisClusterClient clusterClient = io.lettuce.core.cluster.RedisClusterClient.create(redisURIList);
clusterClient.setOptions(
    ClusterClientOptions.builder()
        .topologyRefreshOptions(clusterTopologyRefreshOptions)
        .timeoutOptions(TimeoutOptions.builder().fixedTimeout(Duration.ofMillis(2000)).build())
        .build());
```

I’ve attempted using these `readFrom` options (MASTER, MASTER_PREFERRED, REPLICA and REPLICA_PREFERRED).

Specifically for `REPLICA` and `REPLICA_PREFERRED`, I tested 2 scenarios:

Scenario 1
When master goes down first, the replica takes over as master, and READ operations occur in the master instance. Then, when replica instance returns, READ operations occur back in the new replica instance.

Scenario 2
When replica goes down first, READ operations occur in master instance. Then, when replica instance returns, READ operations (using `hmget`) are unable to go through and I receive the following error.

```
[ioEventLoop-4-3] i.l.c.c.t.ClusterTopologyRefresh         : Unable to connect to [127.0.0.1:7005]: Connection refused: /127.0.0.1:7005
[xecutorLoop-1-4] i.l.c.p.ConnectionWatchdog               : Reconnecting, last destination was 127.0.0.1:7005
[xecutorLoop-1-5] i.l.c.p.ConnectionWatchdog               : Reconnecting, last destination was localhost:7005
[ioEventLoop-4-9] i.l.c.p.ConnectionWatchdog               : Cannot reconnect to [127.0.0.1:7005]: Connection refused: /127.0.0.1:7005
[ioEventLoop-4-8] i.l.c.p.ConnectionWatchdog               : Cannot reconnect to [localhost:7005]: Connection refused: localhost/127.0.0.1:7005
[xecutorLoop-1-6] i.l.c.p.ConnectionWatchdog               : Reconnecting, last destination was 127.0.0.1:7005
[xecutorLoop-1-7] i.l.c.p.ConnectionWatchdog               : Reconnecting, last destination was localhost:7005
[oEventLoop-4-11] i.l.c.p.ConnectionWatchdog               : Cannot reconnect to [localhost:7005]: Connection refused: localhost/127.0.0.1:7005
[oEventLoop-4-10] i.l.c.p.ConnectionWatchdog               : Cannot reconnect to [127.0.0.1:7005]: Connection refused: /127.0.0.1:7005
[ecutorLoop-1-10] i.l.c.p.ConnectionWatchdog               : Reconnecting, last destination was localhost:7005
[ecutorLoop-1-11] i.l.c.p.ConnectionWatchdog               : Reconnecting, last destination was 127.0.0.1:7005
[ioEventLoop-4-7] i.l.c.p.ReconnectionHandler              : Reconnected to localhost:7005
[ioEventLoop-4-6] i.l.c.p.ReconnectionHandler              : Reconnected to 127.0.0.1:7005

Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 2 second(s)
        at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
        at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:167)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
```
My understanding is that cluster topology refresh should work if replica goes down first, is there something I'm missing here?

**Comment by mp911de** [comment]
`REPLICA` uses replicas only. Meaning, that if you don't have any replicas to use, then the command would fail immediately.

Here it looks as if the command was issued to the connection before it got disconnected. In that case, commands are pinned to the connection because we no longer know why the command was routed to the node.

The routing itself receives a collection of candidates that can be used for a specific command and the component checks whether the selected node is connected. If not, then the command gets sent to the next connected node.

Happy to give further guidance if required.

**Comment by terryyylim** [comment]
Hello, thank you for the update! 

Specifically for the case of `REPLICA_PREFERRED`, that error was thrown for a request that was sent **after** the reconnection has happened. Thus, the command was not issued to the connection before it got disconnected. I'm puzzled as to why the timeout error continues to occur even after reconnection has happened.

**Comment by BigDataHunter** [comment]
have same problem
 WARN 1 --- [llEventLoop-8-3] i.l.c.c.topology.ClusterTopologyRefresh  : Unable to connect to [10.233.90.31:6379]: readAddress(..) failed: Connection reset by peer
