### ISSUE TITLE
BoundedAsyncPool.acquire() throws NullPointerException

### ISSUE THREAD

**Issue by checky** [lettuce-io/lettuce-core#1624]
#### Current Behavior
BoundedAsyncPool.acquire() throws NullPointerException in race condition. In that situation, BoundedAsyncPool already acquired a cached connection, but it can not return it because of the exception. So the connection can not be released to the pool.

```java
java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1445)
	at java.base/java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2337)
	at io.lettuce.core.support.BoundedAsyncPool.createIdle(BoundedAsyncPool.java:184)
	at io.lettuce.core.support.BoundedAsyncPool.acquire0(BoundedAsyncPool.java:236)
	at io.lettuce.core.support.BoundedAsyncPool.acquire(BoundedAsyncPool.java:197)
	at io.lettuce.core.support.AsyncConnectionPoolSupport$1.acquire(AsyncConnectionPoolSupport.java:184)
	at reactor.core.publisher.Mono.lambda$fromCompletionStage$0(Mono.java:420)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:91)
	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:38)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2267)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2075)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1949)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:178)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

#### Input Code

<details>
<summary>Input Code</summary>

```java
return Mono.fromCompletionStage(this.asyncPool::acquire)
```

</details>

#### Expected behavior/code

NullPointerException should not be occured in acquire().

#### Environment

- Lettuce version(s): 5.3.6.RELEASE
- Redis version: 5.0.4

**Comment by checky** [comment]
same issue : https://github.com/lettuce-io/lettuce-core/issues/1611
