### ISSUE TITLE
org.springframework.data.redis.connection.RedisPipelineException: Pipeline contained one or more invalid commands; nested exception is io.lettuce.core.RedisCommandInterruptedException: Command interrupted.

### ISSUE THREAD

**Issue by sandpmd** [lettuce-io/lettuce-core#1687]
## Bug Report

io.lettuce.core.RedisCommandInterruptedException: Command interrupted exception is causing data loss.

#### Current Behavior

Try to read data from redis for a given key. If server is stopped forcefully while data is fetching from redis it leads to "io.lettuce.core.RedisCommandInterruptedException" which results in loss of data from redis for that given key 

```java stack trace;
org.springframework.data.redis.connection.RedisPipelineException: Pipeline contained one or more invalid commands; nested exception is io.lettuce.core.RedisCommandInterruptedException: Command interrupted
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.closePipeline(LettuceConnection.java:571)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.closePipeline(DefaultStringRedisConnection.java:3152)
	at org.springframework.data.redis.core.RedisTemplate.lambda$executePipelined$1(RedisTemplate.java:329)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:320)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:310)
	at com.abc.devicedataprocessor.utilities.Utilities.getDataFromRedis(Utilities.java:85)
	at com.abc.devicedataprocessor.processor.DeviceStatProcessor.readFromRedis(DeviceStatProcessor.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisCommandInterruptedException: Command interrupted
	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:92)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.closePipeline(LettuceConnection.java:528)
	... 22 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:70)
	... 23 more
```

</details>

```
@Configuration
public class RedisConfiguration {

    @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        return new LettuceConnectionFactory();
    }

   @Bean
    public StringRedisTemplate stringRedisTemplate() {
        StringRedisTemplate stringRedisTemplate = new StringRedisTemplate(redisConnectionFactory());
        stringRedisTemplate.setEnableTransactionSupport(true);
        stringRedisTemplate.setExposeConnection(true);
        return stringRedisTemplate;
    }
}



@Component
public class Utilities {

    private static final Logger LOGGER = LoggerFactory.getLogger(Utilities.class);

    @Autowired
    private StringRedisTemplate stringRedisTemplate;


    public List<Object> getDataFromRedis(String redisKey) {
        
            try {                
                long finalRedisMessageCount = 65000;
                return stringRedisTemplate.executePipelined(
                        (RedisConnection connection) -> {
                            StringRedisConnection stringRedisConn = (StringRedisConnection) connection;
                            for (int index = 0; index < finalRedisMessageCount; index++) {
                                stringRedisConn.lPop(redisKey);
                            }
                            return null;
                        });
            } catch (NullPointerException e) {
                LOGGER.error("EXCEPTION WHILE UNWRAPPING LONG SIZE FROM REDIS KEY :::", e);
                return null;
            }
        
    }
}
```

</details>

#### Expected behavior/code

When this exception is thrown redis should retain the data for the given key

#### Environment

- spring-data-redis-2.1.4.RELEASE
- Redis server v=4.0.9

**Comment by mp911de** [comment]
`InterruptedException` happens when the underlying thread pool is being shut down. There's nothing we can do here as shutting down the application has thread shutdown as consequence.
