### ISSUE TITLE
Connection Pooling Not working as expected

### ISSUE THREAD

**Issue by dennisnexmo** [lettuce-io/lettuce-core#1731]
#### Current Behavior

 I am trying to migrate our code base from using Jedis and Redis to using Elasticache with lettuce. I have a lettuce connection pooling settings show below. This setup works, can read and write to Elasticache. However, under increased load, the lettuce will stop connecting to the cluster with exception message `Caused by: io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh$CannotRetrieveClusterPartitions: Cannot retrieve cluster partitions from` and ` Caused by: java.net.ConnectException: connect(..) failed: Cannot assign requested address`. It appears that the connection pool is not working as I expected.

<details>
<summary>Stack trace</summary>

```java
io.lettuce.core.RedisConnectionException: Unable to establish a connection to Redis Cluster
        at io.lettuce.core.cluster.RedisClusterClient.lambda$assertInitialPartitions$26(RedisClusterClient.java:885)
        at io.lettuce.core.cluster.RedisClusterClient.get(RedisClusterClient.java:904)
        at io.lettuce.core.cluster.RedisClusterClient.assertInitialPartitions(RedisClusterClient.java:884)
        at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:396)
        at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:373)
        at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.create(ConnectionPoolSupport.java:211)
        at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.create(ConnectionPoolSupport.java:201)
        at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:58)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:918)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:431)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:356)
        at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:121)
        at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:117)
        at com.tokbox.common.storage.redis.LettuceCache.getUpStreamConnection(LettuceCache.java:452)
        at com.tokbox.common.storage.redis.LettuceCache.readAndExtendExpiration(LettuceCache.java:158)
        at com.tokbox.anvil.data.SessionCache.get(SessionCache.java:66)
        at com.tokbox.anvil.api.Session.read(Session.java:351)
        at com.tokbox.anvil.session.SessionServiceImpl.readSession(SessionServiceImpl.java:241)
        at com.tokbox.anvil.session.SessionServiceImpl.getSession(SessionServiceImpl.java:232)
        at com.tokbox.anvil.session.SessionServiceImpl.getSessionInfo(SessionServiceImpl.java:163)
        at com.tokbox.anvil.api.SessionResource.getSessionInfo(SessionResource.java:119)
        at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:365)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh$CannotRetrieveClusterPartitions: Cannot retrieve cluster partitions from [redis://anvil-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com]

Details:
        [redis://anvil-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com]: connect(..) failed: Cannot assign requested address: anvil-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com/10.0.0.106:6379

        Suppressed: io.lettuce.core.RedisConnectionException: Unable to connect to [anvil-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com/10.0.0.106:6379]: connect(..) failed: Cannot assign requested address: anvil-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com/10.0.0.106:6379
                at io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh.lambda$openConnections$11(DefaultClusterTopologyRefresh.java:353)
                at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
                at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
                at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
                at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
                at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$6(AbstractRedisClient.java:424)
                at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
                at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
                at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
                at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
                at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
                at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
                at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:637)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
                at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
                at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
                at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
                at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:748)
        Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Cannot assign requested address: anvil-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com/10.0.0.106:6379
        Caused by: java.net.ConnectException: connect(..) failed: Cannot assign requested address
                at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
                at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
                at io.netty.channel.unix.Socket.connect(Socket.java:270)
                at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
                at io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:138)
                at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
                at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
                at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
                at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
                at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
                at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:748)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
package com.xxx.common.storage.redis;


import io.lettuce.core.ClientOptions;
import io.lettuce.core.RedisURI;
import io.lettuce.core.SocketOptions;
import io.lettuce.core.TimeoutOptions;
import io.lettuce.core.cluster.ClusterClientOptions;
import io.lettuce.core.cluster.ClusterTopologyRefreshOptions;
import io.lettuce.core.cluster.RedisClusterClient;
import io.lettuce.core.cluster.api.StatefulRedisClusterConnection;
import io.lettuce.core.resource.DefaultClientResources;
import io.lettuce.core.resource.DirContextDnsResolver;
import io.lettuce.core.support.ConnectionPoolSupport;
import org.apache.commons.pool2.impl.GenericObjectPool;
import org.apache.commons.pool2.impl.GenericObjectPoolConfig;

import java.time.Duration;
import java.time.temporal.ChronoUnit;

public class LettuceConnector {
    private final LettuceClusterConfig config;
    private static final int CONNECT_TIMEOUT = 30000;

    public LettuceConnector(LettuceClusterConfig config) {
        this.config = config;
    }

    public GenericObjectPool<StatefulRedisClusterConnection<String, String>> getPool() {
        int threadPoolSize = Runtime.getRuntime().availableProcessors();
        threadPoolSize *= 2;
        RedisURI redisURI =
            RedisURI.create(config.getClusterUri());

        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
            .enablePeriodicRefresh(Duration.ofMinutes(config.getClusterReFreshDuration()))
            .enableAllAdaptiveRefreshTriggers()
            .closeStaleConnections(true)
            .build();
        
        ClusterClientOptions clientOptions = ClusterClientOptions.builder()
            .topologyRefreshOptions(topologyRefreshOptions)
            .autoReconnect(true)
            .timeoutOptions(TimeoutOptions.builder()
                .timeoutCommands().fixedTimeout(Duration.ofSeconds(30)).build())
            .disconnectedBehavior(ClientOptions.DisconnectedBehavior.ACCEPT_COMMANDS)
            .socketOptions(SocketOptions.builder()
                .keepAlive(true)
                .connectTimeout(Duration.of(CONNECT_TIMEOUT, ChronoUnit.MILLIS))
                .build())
            .build();

        DefaultClientResources clientResources = DefaultClientResources.builder()
            .dnsResolver(new DirContextDnsResolver())
            .ioThreadPoolSize(threadPoolSize)
            .computationThreadPoolSize(threadPoolSize)
            .build();
        
        RedisClusterClient redisClient = RedisClusterClient.create(clientResources, redisURI);

        redisClient.setOptions(clientOptions);
        GenericObjectPool<StatefulRedisClusterConnection<String, String>> pool = ConnectionPoolSupport
            .createGenericObjectPool(redisClient::connect, new GenericObjectPoolConfig<>());
        pool.setMaxTotal(10);
        pool.setMaxIdle(10);
        pool.setMaxWaitMillis(CONNECT_TIMEOUT);
        return pool;
    }
}

```

</details>

#### Environment

- Lettuce version(s): [6.1.1.RELEASE]
- Redis version: [AWS Elasticache 6.0.5]

**Comment by duxing** [comment]
I'm working on a project using same version of lettuce and using same Redis backend (AWS EC, cluster mode + redis 6) recently, and I've played around several different implementation recently to compare performance, one of which is almost the same as yours (synchronous connection pooling).

from the error log you sent, seems like the issue is caused by cluster topology refresh unable to bind to local socket (probably port in use already). I haven't checked `GenericObjectPool ` implementation, but a few thoughts that are maybe worth trying:
 - how does `GenericObjectPool` handle pool exhaustion? not sure if this exception is related to pool being exhausted.
 - would it work for you if you use a single connection?
 - would it work for you if you replace `GenericObjectPool` with async implementation? (`AsyncPool`)
 - would it work if you use an array of connection object (`StatefulRedisClusterConnection[]`) instead of a connection pool? 
 - would `lettuce-core:6.0.x` work?

every configured amount of time (5s default), `lettuce-core` spins up a new connection to cluster just to run the cluster topology update task (executed on the "compute" thread pool). It should be independent from the connections you specified.

**Comment by dennisnexmo** [comment]
I have not tried a single connection and AsyncPool yet. but I tried `lettuce-core:6.0.x` I have the same problem. 
This is my current code sample.

```
public String read(String prefix, String id) {
    final String key = key(prefix, id);
    String result = null;
    GenericObjectPool<StatefulRedisClusterConnection<String, String>> pool = lettuceConnector.getPool();
    StatefulRedisClusterConnection<String, String> connection = null;
    try  {
        connection = pool.borrowObject();
        RedisAdvancedClusterCommands<String, String> commands = connection.sync();
        connection.setReadFrom(ReadFrom.UPSTREAM);
        result = commands.get(key);
        String finalResult = result;
        LOG.debug(LoggingHelper.getFlow(), READ_MASTER_CACHE, Step.SUCCESS,
            LoggingHelper.loggable(), (mdc, level) -> {
                mdc.put("key", key);
                mdc.put("result", finalResult);
            });
        pool.returnObject(connection);
    } catch (Exception exception) {
        LOG.error(LoggingHelper.getFlow(), CONNECT_TO_PRIMARY, Step.FAILURE, exception,
            LoggingHelper.loggable(), (mdc, level) -> {
                mdc.put("msg", "Unable to get connection to Elasticache primary");
            });
    }
    return result;
```

When enabled trace logging I saw the stack trace below:


while event log from lettuce is as show below
```
2021-04-22 23:13:51,519  WARN   [globalEventExecutor-2-25]      topology.DefaultClusterTopologyRefresh  Unable to connect to [xxx-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:13:51,519  WARN   [globalEventExecutor-2-25]      cluster.ClusterTopologyRefreshScheduler Cannot refresh Redis Cluster topology
2021-04-22 23:14:30,569 DEBUG   [java-sdk-http-connection-reaper]       conn.PoolingHttpClientConnectionManager Closing connections idle longer than 60000 MILLISECONDS
2021-04-22 23:14:33,770 DEBUG   [lettuce-eventExecutorLoop-25-6]        cluster.ClusterTopologyRefreshScheduler ClusterTopologyRefreshScheduler.run()
2021-04-22 23:14:33,770 DEBUG   [lettuce-eventExecutorLoop-25-4]        cluster.ClusterTopologyRefreshScheduler ClusterTopologyRefreshTask requesting partitions
2021-04-22 23:14:33,771 DEBUG   [lettuce-eventExecutorLoop-25-4]        core.AbstractRedisClient        Connecting to Redis at 10.0.0.106:6379
2021-04-22 23:14:33,771 DEBUG   [lettuce-eventExecutorLoop-25-4]        core.AbstractRedisClient        Connecting to Redis at 10.0.0.200:6379
2021-04-22 23:14:33,771 DEBUG   [lettuce-eventExecutorLoop-25-4]        core.AbstractRedisClient        Connecting to Redis at 10.0.0.26:6379
2021-04-22 23:14:33,772 DEBUG   [lettuce-eventExecutorLoop-25-4]        core.AbstractRedisClient        Connecting to Redis at 10.0.2.104:6379
2021-04-22 23:14:33,772 DEBUG   [lettuce-eventExecutorLoop-25-4]        core.AbstractRedisClient        Connecting to Redis at 10.0.2.160:6379
2021-04-22 23:14:33,772 DEBUG   [lettuce-eventExecutorLoop-25-4]        core.AbstractRedisClient        Connecting to Redis at 10.0.2.236:6379
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.AbstractRedisClient        Connecting to Redis at 10.0.0.106:6379: {}
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        close()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      protocol.DefaultEndpoint        [unknown, epid=0x769] closeAsync()
2021-04-22 23:14:33,772  WARN   [globalEventExecutor-2-26]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.0.106:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.AbstractRedisClient        Connecting to Redis at 10.0.0.200:6379: {}
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        close()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      protocol.DefaultEndpoint        [unknown, epid=0x76a] closeAsync()
2021-04-22 23:14:33,772  WARN   [globalEventExecutor-2-26]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.0.200:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.AbstractRedisClient        Connecting to Redis at 10.0.0.26:6379: {}
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        close()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      protocol.DefaultEndpoint        [unknown, epid=0x76b] closeAsync()
2021-04-22 23:14:33,772  WARN   [globalEventExecutor-2-26]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.0.26:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.AbstractRedisClient        Connecting to Redis at 10.0.2.104:6379: {}
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        close()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      protocol.DefaultEndpoint        [unknown, epid=0x76c] closeAsync()
2021-04-22 23:14:33,772  WARN   [globalEventExecutor-2-26]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.2.104:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.AbstractRedisClient        Connecting to Redis at 10.0.2.160:6379: {}
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        close()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      protocol.DefaultEndpoint        [unknown, epid=0x76d] closeAsync()
2021-04-22 23:14:33,772  WARN   [globalEventExecutor-2-26]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.2.160:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.AbstractRedisClient        Connecting to Redis at 10.0.2.236:6379: {}
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        close()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:33,772 DEBUG   [globalEventExecutor-2-26]      protocol.DefaultEndpoint        [unknown, epid=0x76e] closeAsync()
2021-04-22 23:14:33,772  WARN   [globalEventExecutor-2-26]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.2.236:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:33,773 DEBUG   [globalEventExecutor-2-26]      core.AbstractRedisClient        Connecting to Redis at xxx-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com:6379
2021-04-22 23:14:33,773 DEBUG   [globalEventExecutor-2-26]      core.AbstractRedisClient        Connecting to Redis at xxx-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com:6379: {}
2021-04-22 23:14:33,773 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        close()
2021-04-22 23:14:33,773 DEBUG   [globalEventExecutor-2-26]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:33,773 DEBUG   [globalEventExecutor-2-26]      protocol.DefaultEndpoint        [unknown, epid=0x76f] closeAsync()
2021-04-22 23:14:33,773  WARN   [globalEventExecutor-2-26]      topology.DefaultClusterTopologyRefresh  Unable to connect to [xxx-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:33,774  WARN   [globalEventExecutor-2-26]      cluster.ClusterTopologyRefreshScheduler Cannot refresh Redis Cluster topology
2021-04-22 23:14:34,146 DEBUG   [lettuce-eventExecutorLoop-28-6]        cluster.ClusterTopologyRefreshScheduler ClusterTopologyRefreshScheduler.run()
2021-04-22 23:14:34,146 DEBUG   [lettuce-eventExecutorLoop-28-2]        cluster.ClusterTopologyRefreshScheduler ClusterTopologyRefreshTask requesting partitions
2021-04-22 23:14:34,146 DEBUG   [lettuce-eventExecutorLoop-28-2]        core.AbstractRedisClient        Connecting to Redis at 10.0.0.106:6379
2021-04-22 23:14:34,147 DEBUG   [lettuce-eventExecutorLoop-28-2]        core.AbstractRedisClient        Connecting to Redis at 10.0.0.200:6379
2021-04-22 23:14:34,147 DEBUG   [lettuce-eventExecutorLoop-28-2]        core.AbstractRedisClient        Connecting to Redis at 10.0.0.26:6379
2021-04-22 23:14:34,147 DEBUG   [lettuce-eventExecutorLoop-28-2]        core.AbstractRedisClient        Connecting to Redis at 10.0.2.104:6379
2021-04-22 23:14:34,147 DEBUG   [lettuce-eventExecutorLoop-28-2]        core.AbstractRedisClient        Connecting to Redis at 10.0.2.160:6379
2021-04-22 23:14:34,147 DEBUG   [lettuce-eventExecutorLoop-28-2]        core.AbstractRedisClient        Connecting to Redis at 10.0.2.236:6379
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at 10.0.0.106:6379: {}
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        close()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      protocol.DefaultEndpoint        [unknown, epid=0x770] closeAsync()
2021-04-22 23:14:34,148  WARN   [globalEventExecutor-2-27]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.0.106:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at 10.0.0.200:6379: {}
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        close()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      protocol.DefaultEndpoint        [unknown, epid=0x771] closeAsync()
2021-04-22 23:14:34,148  WARN   [globalEventExecutor-2-27]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.0.200:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at 10.0.0.26:6379: {}
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        close()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      protocol.DefaultEndpoint        [unknown, epid=0x772] closeAsync()
2021-04-22 23:14:34,148  WARN   [globalEventExecutor-2-27]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.0.26:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at 10.0.2.104:6379: {}
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        close()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      protocol.DefaultEndpoint        [unknown, epid=0x773] closeAsync()
2021-04-22 23:14:34,148  WARN   [globalEventExecutor-2-27]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.2.104:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at 10.0.2.160:6379: {}
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        close()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      protocol.DefaultEndpoint        [unknown, epid=0x774] closeAsync()
2021-04-22 23:14:34,148  WARN   [globalEventExecutor-2-27]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.2.160:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at 10.0.2.236:6379: {}
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        close()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:34,148 DEBUG   [globalEventExecutor-2-27]      protocol.DefaultEndpoint        [unknown, epid=0x775] closeAsync()
2021-04-22 23:14:34,148  WARN   [globalEventExecutor-2-27]      topology.DefaultClusterTopologyRefresh  Unable to connect to [10.0.2.236:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:34,149 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at xxx-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com:6379
2021-04-22 23:14:34,149 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at xxx-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com:6379: {}
2021-04-22 23:14:34,149 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        close()
2021-04-22 23:14:34,149 DEBUG   [globalEventExecutor-2-27]      core.RedisChannelHandler        closeAsync()
2021-04-22 23:14:34,149 DEBUG   [globalEventExecutor-2-27]      protocol.DefaultEndpoint        [unknown, epid=0x776] closeAsync()
2021-04-22 23:14:34,149  WARN   [globalEventExecutor-2-27]      topology.DefaultClusterTopologyRefresh  Unable to connect to [xxx-tbdev-noencrypt.wdvht1.clustercfg.usw2.cache.amazonaws.com:6379]: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
2021-04-22 23:14:34,149  WARN   [globalEventExecutor-2-27]      cluster.ClusterTopologyRefreshScheduler Cannot refresh Redis Cluster topology
2021-04-22 23:14:34,286 DEBUG   [lettuce-eventExecutorLoop-31-6]        cluster.ClusterTopologyRefreshScheduler ClusterTopologyRefreshScheduler.run()
2021-04-22 23:14:34,287 DEBUG   [lettuce-eventExecutorLoop-31-3]        cluster.ClusterTopologyRefreshScheduler ClusterTopologyRefreshTask requesting partitions
2021-04-22 23:14:34,287 DEBUG   [lettuce-eventExecutorLoop-31-3]        core.AbstractRedisClient        Connecting to Redis at 10.0.0.106:6379
2021-04-22 23:14:34,287 DEBUG   [globalEventExecutor-2-27]      core.AbstractRedisClient        Connecting to Redis at 10.0.0.106:6379: {}
2021-04-22 23:14:34,287 DE
```

**Comment by duxing** [comment]
I don't see the error log for `Cannot assign requested address`. is that still a problem for you?

you're creating 1 cluster client object per call and this is totally redundant.

try move the code inside `LettuceConnector .getPool()` to `LettuceConnector` constructor, having a `pool` object as a member for the class, and return `pool` from `getPool()` implementation.

when you have increased load, current implementation creates many cluster client objects with one pool bind to each. resourced on your client end may exhaust quickly

**Comment by dennisnexmo** [comment]
@duxing 
Thanks for your help. Your suggestion worked.
