### ISSUE TITLE
Lettuce bug(RedisCommandTimeoutException) in spring-boot-autoconfigure 2.3.10

### ISSUE THREAD

**Issue by farsunset** [lettuce-io/lettuce-core#1752]
Redis version:4.0 mode:Standalone
springboot-data-redis:2.3.9.REALESE
lettuce version:5.3.7.REALESE

The lettuce is default redis client. Autoconfigure in LettuceConnectionConfiguration may be has a bug like this

`
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:275)
at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.convertLettuceAccessException(LettuceSetCommands.java:520)
at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:245)
at org.springframework.data.redis.connection.DefaultedRedisConnection.sMembers(DefaultedRedisConnection.java:791)
at org.springframework.data.redis.core.DefaultSetOperations.lambda$members$10(DefaultSetOperations.java:214)
at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
at org.springframework.data.redis.core.DefaultSetOperations.members(DefaultSetOperations.java:214)
at org.springframework.data.redis.core.DefaultBoundSetOperations.members(DefaultBoundSetOperations.java:152)
`

This Exception is occasional use RedisTemaple or StringRedisTemplate  
Use Jedis can be solved but not the best.

**Comment by mp911de** [comment]
Can you attach a thread dump? Likely, a thread is blocked so Lettuce cannot decode the Redis response.

**Comment by farsunset** [comment]
That is Minimal probability。config code look this

```
spring.redis.host = xxxxxxxxxx.redis.rds.aliyuncs.com
spring.redis.port = 6379
spring.redis.password = xxxxxxx
spring.redis.timeout = 1000
spring.redis.lettuce.pool.min-idle = 100
spring.redis.lettuce.pool.max-active = 100
spring.redis.lettuce.pool.max-idle = 100
spring.redis.lettuce.pool.max-wait = 1500
```

```
@Bean
    public LettuceConnectionFactory redisConnectionFactory(LettuceClientConfiguration clientConfiguration,RedisProperties properties) {


        RedisStandaloneConfiguration configuration = new RedisStandaloneConfiguration();
        configuration.setHostName(properties.getHost());
        configuration.setPort(properties.getPort());
        configuration.setPassword(RedisPassword.of(properties.getPassword()));

        return new LettuceConnectionFactory(configuration, clientConfiguration);
    }

    @Bean
    LettuceClientConfiguration lettuceClientConfiguration(ObjectProvider<LettuceClientConfigurationBuilderCustomizer> builderCustomizers,
                                                          RedisProperties properties){

        GenericObjectPoolConfig<?> genericObjectPoolConfig = new GenericObjectPoolConfig<>();
        genericObjectPoolConfig.setMaxIdle(properties.getLettuce().getPool().getMaxIdle());
        genericObjectPoolConfig.setMinIdle(properties.getLettuce().getPool().getMinIdle());
        genericObjectPoolConfig.setMaxTotal(properties.getLettuce().getPool().getMaxActive());
        genericObjectPoolConfig.setMaxWaitMillis(properties.getLettuce().getPool().getMaxWait().toMillis());

        SocketOptions socketOptions = SocketOptions.builder().keepAlive(true).tcpNoDelay(true).connectTimeout(properties.getTimeout()).build();

        LettuceClientConfiguration.LettuceClientConfigurationBuilder builder = LettucePoolingClientConfiguration.builder()
                .commandTimeout(properties.getTimeout())
                .shutdownTimeout(properties.getLettuce().getShutdownTimeout())
                .clientOptions(ClientOptions.builder().socketOptions(socketOptions).build())
                .clientResources(DefaultClientResources.create())
                .poolConfig(genericObjectPoolConfig);

        builderCustomizers.orderedStream().forEach((customizer) -> customizer.customize(builder));

        return builder.build();
    }
```

**Comment by farsunset** [comment]
At the same time. i hava 8 times commonds to execute

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
