### ISSUE TITLE
lettuce-eventExecutorLoop are still in blocking state when my application is idle

### ISSUE THREAD

**Issue by parshant13** [lettuce-io/lettuce-core#1760]
My application has connected to three different redis clusters. we have created three redisClusterClient corresponds to every redis cluster.

Machine config:- 8 core
Lettuce client version :- 5.2.2.RELEASE

**When there was traffic on server:-**
1. There were total 128 threads those prefix is "lettuce". 
 
2. Total number of threads whose prefeix is lettuce-nioEventLoop = 64(All are in runnable state)

Stack trace for lettuce-nioEventLoop :-

stackTrace:
java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
- locked <0x00000005cc93e520> (a io.netty.channel.nio.SelectedSelectionKeySet)
- locked <0x00000005cc93e510> (a java.util.Collections$UnmodifiableSet)
- locked <0x00000005cc93e4c8> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:803)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- None
 
3. Total number of threads whose prefeix is lettuce-eventExecutorLoop = 64(56 in WAITING state , and 8 in TIMED_WAITING)

Stack trace for lettuce-eventExecutorLoop :-

stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000005ccebcf78> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at io.netty.util.concurrent.SingleThreadEventExecutor.takeTask(SingleThreadEventExecutor.java:243)
at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:64)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- None

**When there was no traffic(for almost 20 hours) on server:-**

1. There were total 128 threads those prefix is "lettuce". 

2. Total number of threads whose prefeix is lettuce-nioEventLoop = 64(All are in runnable state)
stack trace is same as above
 
3. Total number of threads whose prefeix is lettuce-eventExecutorLoop = 64(56 in WAITING state , and 8 in TIMED_WAITING)
stack trace is same as above

Questions:-

1. Why even after no traffic on server "lettuce-eventExecutorLoop"  threads are in wating state ?? May be because of this  RedisCommandTimeoutException exception if we make it live again with out restarting this machine.
2. How many number of event-loop, ettuce-eventExecutorLoop threads(maximum) will be created if connected with three redis cluster and have three redisClusterClient?

**Comment by mp911de** [comment]
> There were total 128 threads those prefix is "lettuce".

Lettuce creates up to 2 x (CPU Count) Threads (I/O and computation thread pools). You can tweak these settings through `ClientResources`. Generally, when creating multiple `RedisClient` instances, make sure to reuse `ClientResources` to avoid excessive resource usage. See also https://lettuce.io/core/release/reference/index.html#advanced-usage.

> Why even after no traffic on server "lettuce-eventExecutorLoop" threads are in wating state

Because that's how netty works. Event loop threads poll on their work queue.

**Comment by laluvjohntx** [comment]
@mp911de, sorry to bring this up, I have a simple spring boot app locally that just has a controller, and its connecting to Redis running on Docker. I have `spring-boot-starter-data-redis`, and not using any custom ClientResource. I am using VisualVM to monitor my threads. Once the app has started, i see that a couple of lettuce-nioEventLoops exist for the redis connection. But when i restart redis (while the app is running), more threads (lettuce-nioEventLoop) are created. This is fine. However, is it expected behavior for the old threads to remain? My assumption was that lettuce would close the old threads.
