### ISSUE TITLE
Exception thrown during RedisClusterClient shutdown

### ISSUE THREAD

**Issue by jdeppe-pivotal** [lettuce-io/lettuce-core#1800]
#### Current Behavior

While using lettuce against a cluster where nodes are being stopped and restarted, the following exception is thrown when the test shuts down the `RedisClusterClient`

```java
    java.util.NoSuchElementException
        at java.util.concurrent.ConcurrentHashMap$KeyIterator.next(ConcurrentHashMap.java:3453)
        at io.lettuce.core.AbstractRedisClient.closeResources(AbstractRedisClient.java:551)
        at io.lettuce.core.AbstractRedisClient.shutdownAsync(AbstractRedisClient.java:540)
        at io.lettuce.core.cluster.RedisClusterClient.shutdownAsync(RedisClusterClient.java:1058)
        at io.lettuce.core.AbstractRedisClient.shutdown(AbstractRedisClient.java:504)
        at io.lettuce.core.AbstractRedisClient.shutdown(AbstractRedisClient.java:472)
        at org.apache.geode.redis.internal.executor.CrashAndNoRepeatDUnitTest.cleanup(CrashAndNoRepeatDUnitTest.java:110)```
```

#### Input Code

The `RedisClusterClient` is configured as follows:

```java
    clusterClient = RedisClusterClient.create("redis://localhost:" + redisServerPort1);

    ClusterTopologyRefreshOptions refreshOptions =
        ClusterTopologyRefreshOptions.builder()
            .enableAllAdaptiveRefreshTriggers()
            .enablePeriodicRefresh(Duration.ofSeconds(5))
            .build();

    clusterClient.setOptions(ClusterClientOptions.builder()
        .topologyRefreshOptions(refreshOptions)
        .validateClusterNodeMembership(false)
        .build());
```

#### Expected behavior/code

`shutdown` should not produce any errors.

#### Environment

- Lettuce version(s): 6.1.3.RELEASE
- Redis version: custom

**Comment by mp911de** [comment]
I'm currently not sure where the bug is. `shutdown` isn't thread-safe to be called by multiple threads concurrently. We could copy over the closeable resources to an independent list instead of operating on the actual holder.

**Comment by jdeppe-pivotal** [comment]
Just to be clear - `shutdown` is only being called by a single thread.

**Comment by mp911de** [comment]
That's fixed now. Care to run tests against the latest snapshots (via https://oss.sonatype.org/content/repositories/snapshots/)?

**Comment by jdeppe-pivotal** [comment]
Looks like it's good now. Thanks again @mp911de !!
