### ISSUE TITLE
unable to connect to aws elasticcache with cluster mode enabled

### ISSUE THREAD

**Issue by tannaga** [lettuce-io/lettuce-core#1827]
## Bug Report

I have an AWS Redis ElasticCache with Cluster Mode enabled. I am trying to connect to it from my local machine via **ssh tunnel**.  I am able to connect to it using `redis-cli` but not via the lettuce sdk

#### Code
```
        StatefulRedisClusterConnection<String, String> connection;

        RedisURI redisUri = RedisURI.Builder.redis("localhost", 6379).build();
        List<RedisURI> redisURI = Arrays.asList(redisUri);

        RedisClusterClient redisClusterClient = RedisClusterClient.create(redisURI);

        // enable topology refresh
        ClusterTopologyRefreshOptions clusterTopologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enablePeriodicRefresh(true)
                .enableAllAdaptiveRefreshTriggers()//
                .build();

        ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder()//
                .topologyRefreshOptions(clusterTopologyRefreshOptions)//
                .build();

        redisClusterClient.setOptions(clusterClientOptions);

        connection = redisClusterClient.connect();
        System.out.println(connection);
```

#### Stacktrace
```
2021/08/16 21:34:22.861 WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [10.0.0.210:6379]: connection timed out: /10.0.0.210:6379
2021/08/16 21:34:22.861 WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [10.0.1.87:6379]: connection timed out: /10.0.1.87:6379
2021/08/16 21:34:22.861 WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [10.0.0.44:6379]: connection timed out: /10.0.0.44:6379
2021/08/16 21:34:22.861 WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [10.0.0.5:6379]: connection timed out: /10.0.0.5:6379
2021/08/16 21:34:22.861 WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [10.0.0.206:6379]: connection timed out: /10.0.0.206:6379
2021/08/16 21:34:22.861 WARN  i.l.c.c.t.DefaultClusterTopologyRefresh - Unable to connect to [10.0.1.120:6379]: connection timed out: /10.0.1.120:6379
2021/08/16 21:34:32.944 WARN  i.l.core.cluster.RedisClusterClient - connection timed out: /10.0.1.87:6379
2021/08/16 21:34:42.948 WARN  i.l.core.cluster.RedisClusterClient - connection timed out: /10.0.0.206:6379
2021/08/16 21:34:52.954 WARN  i.l.core.cluster.RedisClusterClient - connection timed out: /10.0.0.210:6379
2021/08/16 21:35:02.961 WARN  i.l.core.cluster.RedisClusterClient - connection timed out: /10.0.0.44:6379
2021/08/16 21:35:12.967 WARN  i.l.core.cluster.RedisClusterClient - connection timed out: /10.0.1.120:6379
2021/08/16 21:35:22.975 WARN  i.l.core.cluster.RedisClusterClient - connection timed out: /10.0.0.5:6379
Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to connect
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:94)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:352)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:400)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:375)
	at com.intuit.o11y.dimcardinality.local.O11yDimCardReadLocal.connectToRedis(O11yDimCardReadLocal.java:61)
	at com.intuit.o11y.dimcardinality.local.O11yDimCardReadLocal.main(O11yDimCardReadLocal.java:21)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.0.0.5:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 1

```
#### Environment

- Lettuce version(s):  6.1.4.RELEASE
- Redis version:  6.0.5

Thanks in advance

**Comment by mp911de** [comment]
Looks pretty much like a SSL issue or network issue. In any case, that isn't something that we can solve in the driver as the driver cannot SSH into a machine.
