### ISSUE TITLE
Single threaded unit tests - test hangs and thread is in waiting state

### ISSUE THREAD

**Issue by rdehuyss** [lettuce-io/lettuce-core#1832]
#### Current Behavior

Probably a newbie error but I did not find a comparable issue here or on stackoverflow.com.

I'm the author of [JobRunr](https://github.com/jobrunr/jobrunr)  and I try to support Redis with Lettuce as a client to store Job information.

I used connection pooling with commons-pool2 and all was working well. A user asked me why the dependency to commons-pool2 is needed as, according to the docs, Lettuce should be thread-safe. 

> Note: I'm using the synchronous api (long live project loom :smile: )

I converted my class so that it reuses the same connection (and does not close it off-course). Yet, now after 3/4 tests, they hang and only after some timeout the test continues. 

I made sure that:
- I open only one connection from my code (I tested this with a breakpoint in `AbstractRedisClient.initializeChannelAsync0(ConnectionBuilder connectionBuilder, CompletableFuture<Channel> channelReadyFuture, SocketAddress redisAddress)`)
- I do not close the connection from my code (expect after all tests finished) (also tested with a breakpoint)

<details>
<summary>Thread dump</summary>

```java
Full thread dump

"Test worker@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	  at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1798)
	  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	  at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1868)
	  at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	  at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:83)
	  at io.lettuce.core.internal.Futures.awaitOrCancel(Futures.java:244)
	  at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:75)
	  at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	  at com.sun.proxy.$Proxy36.zrange(Unknown Source:-1)
	  at org.jobrunr.storage.nosql.redis.LettuceRedisStorageProvider.getBackgroundJobServers(LettuceRedisStorageProvider.java:156)
	  at org.jobrunr.storage.StorageProviderTest.testRemoveTimedOutBackgroundJobServers(StorageProviderTest.java:139)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	  at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	  at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	  at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	  at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	  at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$197.1803306804.apply(Unknown Source:-1)
	  at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	  at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall$$Lambda$198.148377842.apply(Unknown Source:-1)
	  at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	  at org.junit.jupiter.engine.execution.ExecutableInvoker$$Lambda$491.1716423607.apply(Unknown Source:-1)
	  at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	  at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	  at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$723.540692943.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$260.1714507758.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$259.1106755629.invoke(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$258.179437727.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$286.1366832221.accept(Unknown Source:-1)
	  at java.util.ArrayList.forEach(ArrayList.java:1541)
	  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$260.1714507758.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$259.1106755629.invoke(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$258.179437727.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$286.1366832221.accept(Unknown Source:-1)
	  at java.util.ArrayList.forEach(ArrayList.java:1541)
	  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$260.1714507758.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$259.1106755629.invoke(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$258.179437727.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	  at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	  at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	  at org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda$234.1859555837.accept(Unknown Source:-1)
	  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	  at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	  at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	  at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	  at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	  at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	  at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	  at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	  at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	  at com.sun.proxy.$Proxy5.stop(Unknown Source:-1)
	  at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	  at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	  at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	  at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	  at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	  at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	  at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	  at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	  at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

"/127.0.0.1:47610 to /127.0.0.1:37433 workers Thread 3@1959" prio=5 tid=0x1b nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.EPoll.wait(EPoll.java:-1)
	  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
	  - locked <0x1b3a> (a sun.nio.ch.EPollSelectorImpl)
	  - locked <0x1b3b> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
	  at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:185)
	  at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	  at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	  at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
	  at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:82)
	  at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:64)
	  at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	  at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	  at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
	  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	  at java.lang.Thread.run(Thread.java:829)

"docker-java-stream-115232061@4470" daemon prio=5 tid=0x1e nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.github.dockerjava.transport.DomainSocket.read(DomainSocket.java:-1)
	  at com.github.dockerjava.transport.DomainSocket.read(DomainSocket.java:79)
	  at com.github.dockerjava.transport.DomainSocket.access$200(DomainSocket.java:35)
	  at com.github.dockerjava.transport.DomainSocket$DomainSocketInputStream.read(DomainSocket.java:162)
	  at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.io.LoggingInputStream.read(LoggingInputStream.java:81)
	  at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
	  at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	  at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
	  at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
	  at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:147)
	  at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.io.EofSensorInputStream.read(EofSensorInputStream.java:118)
	  at org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:30)
	  at org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
	  at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
	  at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$412.1120864417.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:829)

"lettuce-nioEventLoop-4-1@5734" daemon prio=5 tid=0x23 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.EPoll.wait(EPoll.java:-1)
	  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
	  - locked <0x1b3d> (a sun.nio.ch.EPollSelectorImpl)
	  - locked <0x1b3e> (a io.netty.channel.nio.SelectedSelectionKeySet)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
	  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:810)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:829)

"/127.0.0.1:47610 to /127.0.0.1:37433 workers@1901" prio=5 tid=0x19 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	  at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
	  at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:403)
	  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	  at java.lang.Thread.run(Thread.java:829)

"/127.0.0.1:47610 to /127.0.0.1:37433 workers Thread 2@1957" prio=5 tid=0x1a nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	  at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
	  at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:322)
	  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	  at java.lang.Thread.run(Thread.java:829)

"ducttape-0@3732" daemon prio=5 tid=0x1c nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
	  at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
	  at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.lang.Thread.run(Thread.java:829)

"process reaper@3976" daemon prio=10 tid=0x1d nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
	  at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
	  at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.lang.Thread.run(Thread.java:829)

"testcontainers-ryuk@4592" daemon prio=5 tid=0x1f nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:196)
	  at org.testcontainers.utility.ResourceReaper$$Lambda$432.1120560222.run(Unknown Source:-1)
	  at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	  at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:185)
	  at org.testcontainers.utility.ResourceReaper$$Lambda$431.1380026145.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:829)

"Common-Cleaner@6967" daemon prio=8 tid=0x13 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	  at jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
	  at java.lang.Thread.run(Thread.java:829)
	  at jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)

"lettuce-timer-3-1@5210" daemon prio=5 tid=0x22 nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:566)
	  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:462)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:829)

"Reference Handler@6964" daemon prio=10 tid=0x2 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.lang.ref.Reference.waitForReferencePendingList(Reference.java:-1)
	  at java.lang.ref.Reference.processPendingReferences(Reference.java:241)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"Finalizer@6965" daemon prio=8 tid=0x3 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Signal Dispatcher@6966" daemon prio=9 tid=0x4 nid=NA runnable
  java.lang.Thread.State: RUNNABLE


```

</details>

#### Input Code

Github project: https://github.com/jobrunr/jobrunr/
Branch: _lettuce-hangs_
Test: `core/src/test/java/org/jobrunr/storage/nosql/redis/LettuceRedisStorageProviderTest.java`
Prerequisites to run test:
- docker (via TestContainers)

#### Expected behavior/code

Thread not to be in waiting state.

#### Environment

- Lettuce version(s): 6.1.4.RELEASE
- Redis version: 6.2.5

#### Possible Solution

No idea... I can't even understand how you would get Lettuce thread-safe

**Comment by rdehuyss** [comment]
Hmmm, I'm using Redis transactions (multi) so that's probably the reason.
