### ISSUE TITLE
Command timed out after

### ISSUE THREAD

**Issue by liangjf85** [lettuce-io/lettuce-core#1955]
#### Current Behavior
1、Spring cloud gateway integrates spring-session-data-redis to implement session storage redis
2、Use ReactiveRedisTemplate to operate redis read and write

<details>
<summary>Stack trace</summary>
2022-01-05 17:13:54.891 DEBUG [lettuce-nioEventLoop-5-3] i.l.c.support.ConnectionPoolSupport: Validation failed
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 20 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:119)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:75)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:79)
	at com.sun.proxy.$Proxy193.ping(Unknown Source)
	at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.validateObject(ConnectionPoolSupport.java:234)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:477)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at io.lettuce.core.support.ExtConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:127)
	at io.lettuce.core.support.ExtConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:1)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:102)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1211)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.validateConnection(LettuceConnectionFactory.java:1246)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1196)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedReactiveConnection(LettuceConnectionFactory.java:975)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:502)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:1)
	at org.springframework.data.redis.core.ReactiveRedisTemplate.lambda$doInConnection$0(ReactiveRedisTemplate.java:198)
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:85)
	at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:80)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:155)
	at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:99)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
	at reactor.core.publisher.MonoIgnorePublisher.subscribe(MonoIgnorePublis
</details>

#### Input Code

<details>
<summary>Input Code</summary>

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.server.ServerWebExchange;

import reactor.core.publisher.Mono;

@Controller
public class IndexController {

	@RequestMapping("/")
	public Mono<String> index() {
		return Mono.create(monoSink -> monoSink.success("index"));
	}
	
	
	@RequestMapping("/test")
	public Mono<String> test(ServerWebExchange exchange) {
		return exchange.getSession().flatMap(webSession -> {
			webSession.getAttributes().put("session", "kkk");
			return Mono.create(monoSink -> monoSink.success("index"));
		});
	}
	
}
</details>

#### Expected behavior/code

Command timed out after xxx second(s)

#### Environment

- Lettuce version(s): 5.3.2.RELEASE
- Redis version: 4.0.6

#### Possible Solution
Set the shareNativeConnection of LettuceConnectionFactory to false

**Comment by mp911de** [comment]
The usage above indicates a mix of reactive and imperative usage and effectively, the event loop gets blocked. Please disable connection validation and enable early connection initialization in Spring Data.

**Comment by liangjf85** [comment]
thank you,my test is ok
