### ISSUE TITLE
SSL connection issue

### ISSUE THREAD

**Issue by BruceChen2017** [lettuce-io/lettuce-core#1968]
I try to connect redis with TLS enabled by lettuce. cert and keys are generated by [redis/utils/gen-test-certs.sh](https://github.com/redis/redis/blob/unstable/utils/gen-test-certs.sh).  
Then I start the redis server
```sh
./src/redis-server --tls-port 6379 --port 0 \
    --tls-cert-file ./tests/tls/redis.crt \
    --tls-key-file ./tests/tls/redis.key \
    --tls-ca-cert-file ./tests/tls/ca.crt
```

In the java code(redis.key has been converted PKCS#8 format by openssl `openssl pkcs8 -topk8 -inform PEM -in tests/tls/redis.key -out redis.key -nocrypt`)
```java
RedisClient redisClient() {
    String host = "127.0.0.1";
    RedisURI url = RedisURI.Builder.redis(host, 6379)
                .withSsl(true)
                .build();

    SslOptions sslOptions = SslOptions.builder()
        .truststore(new File("./src/main/resources/ca.crt"))
        .keyManager(new File("./src/main/resources/redis.crt"), new File("./src/main/resources/redis.key"), null)
        .build();
    
    ClientOptions clientOptions = ClientOptions.builder().sslOptions(sslOptions).build();

    RedisClient redisClient = RedisClient.create(url);
    redisClient.setOptions(clientOptions);
    return redisClient;
}
```
when `redisClient.connect`, it throws the below error:

```sh
java.io.IOException: toDerInputStream rejects tag type 45
	at java.base/sun.security.util.DerValue.toDerInputStream(DerValue.java:873) ~[na:na]
DerValue.java:873
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1974) ~[na:na]
PKCS12KeyStore.java:1974
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222) ~[na:na]
KeyStoreDelegator.java:222
	at java.base/java.security.KeyStore.load(KeyStore.java:1479) ~[na:na]
KeyStore.java:1479
	at io.lettuce.core.SslOptions.getKeyStore(SslOptions.java:779) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
SslOptions.java:779
	at io.lettuce.core.SslOptions.createTrustManagerFactory(SslOptions.java:789) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
SslOptions.java:789
	at io.lettuce.core.SslOptions.access$1600(SslOptions.java:51) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
SslOptions.java:51
	at io.lettuce.core.SslOptions$Builder.lambda$truststore$16(SslOptions.java:568) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
SslOptions.java:568
	at io.lettuce.core.SslOptions.createSslContextBuilder(SslOptions.java:638) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
SslOptions.java:638
	at io.lettuce.core.SslConnectionBuilder$SslChannelInitializer.initializeSSLEngine(SslConnectionBuilder.java:164) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
SslConnectionBuilder.java:164
	at io.lettuce.core.SslConnectionBuilder$SslChannelInitializer.initChannel(SslConnectionBuilder.java:147) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
SslConnectionBuilder.java:147
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
ChannelInitializer.java:129
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
ChannelInitializer.java:112
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
AbstractChannelHandlerContext.java:938
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
DefaultChannelPipeline.java:609
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
DefaultChannelPipeline.java:46
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
DefaultChannelPipeline.java:1463
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
DefaultChannelPipeline.java:1115
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
DefaultChannelPipeline.java:650
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
AbstractChannel.java:514
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
AbstractChannel.java:429
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
AbstractChannel.java:486
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
AbstractEventExecutor.java:164
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
SingleThreadEventExecutor.java:469
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
NioEventLoop.java:503
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
SingleThreadEventExecutor.java:986
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
ThreadExecutorMap.java:74
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
FastThreadLocalRunnable.java:30
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Thread.java:834
```

**Comment by mp911de** [comment]
The default keystore uses `PKCS12` and DER encoding.
