### ISSUE TITLE
ClusterTopologyRefresh SSL fails with private IP

### ISSUE THREAD

**Issue by andrijaperovic** [lettuce-io/lettuce-core#1998]
## Bug Report

ClusterTopologyRefresh does not handle SSL connection properly in 6.0.2.RELEASE io.lettuce.lettuce-core when connecting to private DNS/IP.

#### Current Behavior

We have a Redis server which is reachable via private link from within our Kubernetes cluster.
We are leveraging `RedisClusterClient` to connect to the master on SSL port via a stateful redis connection.
The `ClusterTopologyRefresh` seems to fail initially, subsequently the commands that are issued go through successfully.

<details>
<summary>Stack trace</summary>

```java
llEventLoop-4-2] i.l.c.c.t.ClusterTopologyRefresh         : Unable to connect to [10.x.x.x:15000]: No subject alternative names matching IP address 10.240.0.7 found
```

```
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 10.x.x.x found
	at java.base/sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:165)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:101)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:429)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:283)
	at java.base/sun.s
```

</details>

#### Input Code

https://github.com/feast-dev/feast-java-old

<details>
<summary>Input Code</summary>

Have tried to mitigate the problem by using a self-signed certificate and leveraging `SslOptions` with `jdkSslProvider` but am encountering the same error:

```java
    List<RedisURI> redisURIList =
        Arrays.stream(config.getConnectionString().split(","))
            .map(
                hostPort -> {
                  String[] hostPortSplit = hostPort.trim().split(":");
                  RedisURI redisURI =
                      RedisURI.create(hostPortSplit[0], Integer.parseInt(hostPortSplit[1]));
                  if (!config.getPassword().isEmpty()) {
                    redisURI.setPassword(config.getPassword());
                  }
                  if (config.getSsl()) {
                    redisURI.setSsl(true);
                  }
                  return redisURI;
                })
            .collect(Collectors.toList());

    ClientResources clientResources =
        ClientResources.builder()
            .nettyCustomizer(
                new NettyCustomizer() {
                  @Override
                  public void afterBootstrapInitialized(Bootstrap bootstrap) {
                    bootstrap.option(EpollChannelOption.TCP_KEEPIDLE, 15);
                    bootstrap.option(EpollChannelOption.TCP_KEEPINTVL, 5);
                    bootstrap.option(EpollChannelOption.TCP_KEEPCNT, 3);
                    // Socket Timeout (milliseconds)
                    bootstrap.option(EpollChannelOption.TCP_USER_TIMEOUT, 60000);
                  }
                })
            .build();

    SslOptions sslOptions =
        SslOptions.builder()
            .jdkSslProvider()
            .truststore(new File("keystore.jks"), "password")
            .build();

    io.lettuce.core.cluster.RedisClusterClient client =
        io.lettuce.core.cluster.RedisClusterClient.create(clientResources, redisURIList);
    client.setOptions(
        ClusterClientOptions.builder()
            .sslOptions(sslOptions)
            .socketOptions(SocketOptions.builder().keepAlive(true).tcpNoDelay(true).build())
            .timeoutOptions(TimeoutOptions.enabled(config.getTimeout()))
            .pingBeforeActivateConnection(true)
            .topologyRefreshOptions(
                ClusterTopologyRefreshOptions.builder().enableAllAdaptiveRefreshTriggers().build())
            .build());

    StatefulRedisClusterConnection<byte[], byte[]> connection =
        client.connect(new ByteArrayCodec());
    connection.setReadFrom(config.getReadFrom());

    return new Builder(connection).build();
```

</details>

#### Expected behavior/code

ClusterTopologyRefresh should have been handled properly.

#### Environment

- Lettuce version(s): 6.0.2.RELEASE
- Redis version: 6.0.14

#### Possible Solution

Use custom SslOptions with self-signed cert (should work theoretically).

#### Additional context

N/A

**Comment by mp911de** [comment]
You either need to provide a valid certificate containing the entire topology/addressing or disable SSL peer verification via `RedisURI`.
