### ISSUE TITLE
RedisCluster fails to refresh the new node IP during aws cluster modification

### ISSUE THREAD

**Issue by mandeepjain** [lettuce-io/lettuce-core#2000]
#### Current Behavior
Hey, 

while the AWS Redis cluster is modifying, the Redis client fails to reconnect to the new IP.

ConnectionWatchdog attempts to reconnect to the previous IP and eventually times out.
<details>
<summary>Stack trace</summary>

```java
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.cluster.UnknownPartitionException: Connection to 10.43.8.209:6379 not allowed. This partition is not known in the cluster view.
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:272) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.convertLettuceAccessException(LettuceKeyCommands.java:810) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.del(LettuceKeyCommands.java:129) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.connection.DefaultedRedisConnection.del(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.core.RedisTemplate.lambda$delete$2(RedisTemplate.java:708) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:222) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:189) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at org.springframework.data.redis.core.RedisTemplate.delete(RedisTemplate.java:708) ~[spring-data-redis-2.4.2.jar!/:2.4.2]
        at com.gamezy.teamselection.repositories.redis.SelectedTeamRepositoryImpl.deleteLock(SelectedTeamRepositoryImpl.java:537) ~[classes!/:0.0.1-SNAPSHOT]
        at com.gamezy.teamselection.repositories.redis.SelectedTeamRepositoryImpl$$FastClassBySpringCGLIB$$1917d46c.invoke(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.2.jar!/:5.3.2]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.3.2.jar!/:5.3.2]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.2.jar!/:5.3.2]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.3.2.jar!/:5.3.2]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.2.jar!/:5.3.2]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.2.jar!/:5.3.2]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.3.2.jar!/:5.3.2]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.3.2.jar!/:5.3.2]
        at com.gamezy.teamselection.repositories.redis.SelectedTeamRepositoryImpl$$EnhancerBySpringCGLIB$$1ef18a0c.deleteLock(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
        at com.gamezy.teamselection.cron.StatRefreshScheduler.refreshStats(StatRefreshScheduler.java:116) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.2.jar!/:5.3.2]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.2.jar!/:5.3.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_302]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_302]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_302]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_302]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: io.lettuce.core.cluster.UnknownPartitionException: Connection to 10.43.8.209:6379 not allowed. This partition is not known in the cluster view.
        at io.lettuce.core.cluster.PooledClusterConnectionProvider.connectionAttemptRejected(PooledClusterConnectionProvider.java:621) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.cluster.PooledClusterConnectionProvider.beforeGetConnection(PooledClusterConnectionProvider.java:469) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.cluster.PooledClusterConnectionProvider.getConnectionAsync(PooledClusterConnectionProvider.java:446) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.cluster.ClusterDistributionChannelWriter.doWrite(ClusterDistributionChannelWriter.java:144) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.cluster.ClusterDistributionChannelWriter.write(ClusterDistributionChannelWriter.java:102) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:58) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598) ~[lettuce-core-6.1.5.RELEASE.jar!/:6.1.5.RELEASE]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
        ... 1 more
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enablePeriodicRefresh(Duration.ofSeconds(30))
                .enableAllAdaptiveRefreshTriggers()
                .build();

ClientOptions options = ClusterClientOptions.builder()
                .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                .autoReconnect(true)
                .topologyRefreshOptions(topologyRefreshOptions)
                .build();

GenericObjectPoolConfig genericObjectPoolConfig = new GenericObjectPoolConfig();
        genericObjectPoolConfig.setMinIdle(8);
        genericObjectPoolConfig.setMaxIdle(16);
        genericObjectPoolConfig.setMaxTotal(16);

LettucePoolingClientConfiguration build = LettucePoolingClientConfiguration.builder()
                .poolConfig(genericObjectPoolConfig)
                .clientOptions(options)
                .clientResources(clientResources)
                .build();

RedisClusterConfiguration config = new RedisClusterConfiguration(REDIS_NODES);
LettuceConnectionFactory lettuceConnectionFactory = new LettuceConnectionFactory(config, lettucePoolConfig);
```

</details>

#### Environment

- Lettuce version(s): [6.1.5.RELEASE]
- Redis version: [5.0.6]

**Comment by jhmartin** [comment]
> This partition is not known in the cluster view.

How large is this cluster, greater than 40 nodes? It sounds like Lettuce is complaining that you are being redirected to a node not listed in the cluster topology. You might try disableing ValidateClusterNodeMembership:

https://lettuce.io/core/release/api/io/lettuce/core/cluster/ClusterClientOptions.html#isValidateClusterNodeMembership--
_Validate the cluster node membership before allowing connections to a cluster node. Defaults to true._

**Comment by mp911de** [comment]
After disabling `validateClusterNodeMembership`, the rejection code is not used at all, so either there's misconfiguration of your side or the error is a different one.

**Comment by mandeepjain** [comment]
@mp911de I have tried disabling ,the results are the same..

Similar issue to the attached link: 

https://stackoverflow.com/questions/53116926/spring-boot-always-try-to-reconnect-the-failed-node-in-redis-cluster-enviroment

Can you please help?

**Comment by mandeepjain** [comment]
@mp911de thanks, there were some configuration issues.
Closing this issue,

**Comment by vbabenkoru** [comment]
@mandeepjain What were the configuration issues? We're experiencing something similar I think.

**Comment by smallersoup** [comment]
@mandeepjain What were the configuration issues? We're experiencing something similar I think.

**Comment by micMalloc** [comment]
@mandeepjain Pls 🙏 Let me know What were the configuration issues 😂
