### ISSUE TITLE
Intermittent Redis command timed out 

### ISSUE THREAD

**Issue by sahilkr** [lettuce-io/lettuce-core#2006]
Hello, We are using spring-boot-starter-data-redis version 2.3.4. We have observed that, on some days, we get Redis Timeout Exception in our production environment. It happens for some time then it starts working again. We checked the network and redis logs, everything looked okay. We are unable to figure out why this is happening. Any help would be greatly appreciated. I have pasted error logs below:

Caused by: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 30 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:270)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.convertLettuceAccessException(LettuceKeyCommands.java:809)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.exists(LettuceKeyCommands.java:77)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.exists(DefaultedRedisConnection.java:62)
	at org.springframework.data.redis.core.RedisTemplate.lambda$hasKey$6(RedisTemplate.java:773)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.RedisTemplate.hasKey(RedisTemplate.java:773)
	at com.tatadigital.sso.validatetoken.service.ValidateTokenServiceImpl.retrieveFromCache(ValidateTokenServiceImpl.java:267)
	at com.tatadigital.sso.validatetoken.service.ValidateTokenServiceImpl.tokenPresentInRedis(ValidateTokenServiceImpl.java:186)
	at com.tatadigital.sso.validatetoken.service.ValidateTokenServiceImpl.validateToken(ValidateTokenServiceImpl.java:75)
	... 147 common frames omitted
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 30 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy214.exists(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.exists(LettuceKeyCommands.java:75)
	... 155 common frames omitted

**Comment by mp911de** [comment]
See https://lettuce.io/core/release/reference/#faq.timeout.
