### ISSUE TITLE
Responses getting out of sync with requests

### ISSUE THREAD

**Issue by jkern888** [lettuce-io/lettuce-core#2012]
#### Current Behavior
We've recently updated lettuce to 6.1.1.RELEASE and after running it in our production environment for a week we ran into a troubling issue. At some point it looks like lettuce worked itself into a state where commands were receiving responses to different requests. This manifested as lots of deserialization errors (e.g. `java.lang.UnsupportedOperationException: io.lettuce.core.output.ValueOutput does not support set(long)`), but also more seriously as incorrect data being returned to the caller.

Restarting the service brought things back to a working state. Prior to this happening the only other thing we observed were some `RedisCommandTimeoutException` being thrown, but not at an anomalous level.

For the meantime we've added some more aggressive checking for this happening, so if it does reoccur I'd be happy to try and gather more information, but not sure what would be helpful? 

#### Environment

- Lettuce version(s): 6.1.1.RELEASE
- Redis version: 3.2.10

**Comment by mp911de** [comment]
Hum, when using Jackson as Codec, then encoding errors may bring the protocol out of sync. Please check whether you can see some exceptions prior to getting out of sync.

**Comment by jkern888** [comment]
@mp911de Interesting. Here's the code for the codec we're using. Should we be swallowing the exception and returning null?

```
public class JacksonRedisCodec<T> implements RedisCodec<String, T> {

    private final ObjectWriter writer;
    private final ObjectReader reader;

    // Encoding used for the key string.
    private static final Charset UTF_8 = Charsets.UTF_8;

    public JacksonRedisCodec(ObjectWriter writer, ObjectReader reader) {
        this.writer = writer;
        this.reader = reader;
    }

    @Override
    public String decodeKey(ByteBuffer byteBuffer) {
        ByteBufferBackedInputStream inputStream = new ByteBufferBackedInputStream(byteBuffer);
        StringWriter writer = new StringWriter();
        try {
            IOUtils.copy(inputStream, writer, UTF_8.name());
        }
        catch (IOException e) {
            throw new RuntimeException(e);
        }
        return writer.toString();
    }

    @Override
    public T decodeValue(ByteBuffer byteBuffer) {
        ByteBufferBackedInputStream inputStream = new ByteBufferBackedInputStream(byteBuffer);
        try {
            return reader.readValue(inputStream);
        }
        catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public ByteBuffer encodeKey(String string) {
        return ByteBuffer.wrap(string.getBytes(UTF_8));
    }

    @Override
    public ByteBuffer encodeValue(T t) {
        try {
            return ByteBuffer.wrap(writer.writeValueAsBytes(t));
        }
        catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }
} 
```

**Comment by mp911de** [comment]
Any exceptions that happen on the codec level affect directly what is being sent to the Redis server. If you have say a command sequence of `SET` -> `SET` -> `GET` and the second `SET` throws an exception (`SET` -> 💥 -> `GET`), then the client is no longer synchronized to the protocol as the second command was never sent to the Redis server. 

We try to recover as much as possible upon encoding/decoding but there's always a fair chance that exceptions during encoding/decoding may impact the protocol synchronization.

I strongly suggest moving the encoding/decoding part into a higher level component so that you can handle exceptions properly.

**Comment by jkern888** [comment]
The same issue has just re-occurred. Digging into our logging I'm seeing no exceptions around the codecs. The only thing I do see is a command timeout:
 ```
 io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
	at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:53)
	at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:172)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
Immediately after that we start getting many errors due to responses being de-synced. We see that same timeout exception at other times with no ill effect, but maybe it's occasionally triggering this bad state?

**Comment by bytestreme** [comment]
Possible result of being out of sync https://github.com/lettuce-io/lettuce-core/issues/2175

**Comment by rndmania** [comment]
@jkern888 
I have a question. I meet same problem but not related with codec.
you said problem was occured when upgrade to 6.1.1.
So, I Wondering which version is your last succeed version?

previously, I use lettuce v2.5.x and this version does not have this problem.

* My environment
 - Spring Boot Webflux 2.7.2
 - ReactiveRedisTemplate
 - lettuce 6.1.9.RELEASE

**Comment by qinchunabng** [comment]
We have got the same problem. And I reproduced the problem by using below codes:
```
@SpringBootTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class RedisTest {

    @Autowired
    private ReactiveRedisTemplate redisTemplate;

    private ExecutorService executorService = Executors.newFixedThreadPool(20);

    @Test
    public void testRedis() throws Exception{
        Random random = new Random();
        AtomicInteger counter = new AtomicInteger(0);
        for (int i = 0; i < 100000; i++) {
            int finalI = i;
            executorService.submit(() -> {
                redisTemplate.opsForValue().set("testkey", "testvalue" + finalI)
                        //.publishOn(Schedulers.boundedElastic())
                        .flatMap(r1 -> {
                            System.out.println(Thread.currentThread().getName() + " : result1 = " + r1);
                            return redisTemplate.opsForHash().get("test_hash", "hash_field") //, "test_value" + finalI)
                                   // .publishOn(Schedulers.boundedElastic())
                                    .defaultIfEmpty("")
                                    .flatMap(r2 -> {
                                        if(random.nextInt() % 2 == 0 && counter.get() < 100){
                                            counter.incrementAndGet();
                                            throw new OutOfMemoryError("test out of memory error");
                                        }
                                        System.out.println(Thread.currentThread().getName() + " : result2 = " + r2);
                                        return redisTemplate.opsForHash().put("test_hash", "hash_field", "hash_value" + finalI)
                                                //.publishOn(Schedulers.boundedElastic())
                                                .flatMap(r3 -> {
                                                            System.out.println(Thread.currentThread().getName() + " : result3 = " + r3);
                                                            return redisTemplate.opsForValue()
                                                                    .get("testkey")
                                                                    //.publishOn(Schedulers.boundedElastic())
                                                                    .map(r4 -> {
                                                                        System.out.println(Thread.currentThread().getName() + " : result4 = " + r4);
                                                                        return r4;
                                                                    });
                                                        });

                                    });
                        })
//                        .subscribeOn(Schedulers.boundedElastic())
                        .subscribe();
            });
            TimeUnit.MILLISECONDS.sleep(10);

        }
        System.in.read();
    }

}
```
My environment is:

- Spring Boot 2.6.8
- ReactiveRedisTemplate
- lettuce 6.1.8.RELEASE

I found if my business codes throw errors, it will be catched by the lettuce pool thread.While this will finally lead to `java.lang.UnsupportedOperationException: io.lettuce.core.output.ValueOutput does not support set(long)` exception. 
And If I indicate a thread pool to my business codes by publishOn, the error won't be caught by lettuce thread.This can void the  exception happening.

**Comment by rndmania** [comment]
@qinchunabng 
Thanks for sharing.
I have one question.
You example code has two comments. one is 'publishOn' and other  is 'subscribeOn'
To avoid exception happening, needs uncomment both?

**Comment by qinchunabng** [comment]
Just uncomment 'publishOn'. 'subscribeOn' is testing code.

**Comment by qinchunabng** [comment]
> @qinchunabng Thanks for sharing. I have one question. You example code has two comments. one is 'publishOn' and other is 'subscribeOn' To avoid exception happening, needs uncomment both?

Just uncomment 'publishOn'. 'subscribeOn' is testing code.

**Comment by KamToHung** [comment]
> > @qinchunabng感谢分享。我有一个问题。示例代码有两个注释。一个是“publishOn”，另一个是“subscribeOn” 为了避免异常发生，需要取消注释吗？
> 
> 只需取消注释“发布”。“订阅”正在测试代码。

hi bro, how to resolve

**Comment by KamToHung** [comment]
> > @qinchunabng Thanks for sharing. I have one question. You example code has two comments. one is 'publishOn' and other is 'subscribeOn' To avoid exception happening, needs uncomment both?
> 
> Just uncomment 'publishOn'. 'subscribeOn' is testing code.

hi bro, how to resolve

**Comment by qinchunabng** [comment]
> > > @qinchunabng Thanks for sharing. I have one question. You example code has two comments. one is 'publishOn' and other is 'subscribeOn' To avoid exception happening, needs uncomment both?
> > 
> > 
> > Just uncomment 'publishOn'. 'subscribeOn' is testing code.
> 
> hi bro, how to resolve
Using publishOn indicates the business code in flatMap executing in other thread pool not in lettuce's thread pool.  Through my test if your code run in lettuce's thread pool and it has some exceptions of Error occuring,there will probably result out of sync.

**Comment by wqq0712** [comment]
Our team also encountered this sporadic issue, which occurs approximately once every 1-2 weeks. Through our testing, we found that this problem only occurs on aarch64 servers and is not observed on X86-64 servers. We were able to resolve this issue by adjusting the version of the JDK.

Here is the environmental information:
Redis Server: 6.2.5
spring-data-redis: 2.1.20.RELEASE
springboot: 2.1.17.RELEASE
Lettuce: 6.0.7 Release

Test Result:
Oracle JDK 8u131 ---> Exception
Oracle JDK 8u201 ---> Exception
Oracle JDK 8u251 ---> OK

Open JDK 8u352 ---> OK
Open JDK 8u292 ---> OK

**Comment by mp911de** [comment]
I do not think that the JDK version is involved. Rather, out of sync happens either if a codec fails encoding/decoding or an output fails (or any other exotic condition happens).

Happy to provide support if you can provide a reliable reproducer.

**Comment by FULaBUla** [comment]
> > 
> 
> @wqq0712 Thanks for good information.
> 
> I have meet this problem with x86-64 server and Open JDK 8u222
> 
> So, I think aarch64 and x86-64 is not important condigion. I will try test with various Open JDK version.
> 
> Thank you.



> > 
> 
> @wqq0712 Thanks for good information.
> 
> I have meet this problem with x86-64 server and Open JDK 8u222
> 
> So, I think aarch64 and x86-64 is not important condigion. I will try test with various Open JDK version.
> 
> Thank you.

@rndmania 

I think maybe there is a bug in the 222 version, which I also use on the aarch64 platform. The problem stopped when I upgraded to 341.

**Comment by tishun** [comment]
Hey @jkern888 ,

Did you manage to resolve the issue? 
What is the last version of Lettuce that you used successfully, before trying to bump to 6.1.1.RELEASE?

**Comment by khisamutdinov** [comment]
> I do not think that the JDK version is involved. Rather, out of sync happens either if a codec fails encoding/decoding or an output fails (or any other exotic condition happens).
> 
> Happy to provide support if you can provide a reliable reproducer.

I've created a [reliable reproducer](https://github.com/khisamutdinov/lettuce-mismatch-test/tree/main) based on [qinchunabng](https://github.com/qinchunabng) comment - the project uses testcontainers and springboottest. It has 2 test - [the first one](https://github.com/khisamutdinov/lettuce-mismatch-test/blob/ac674dfb26b1fe195e044792efc6bcbfdad42fde/src/test/java/com/example/lettuce/mismatch/LettuceMismatchReproductorApplicationTests.java#L52) reproduces the cache mismatch issue, [the second one](https://github.com/khisamutdinov/lettuce-mismatch-test/blob/ac674dfb26b1fe195e044792efc6bcbfdad42fde/src/test/java/com/example/lettuce/mismatch/LettuceMismatchReproductorApplicationTests.java#L155) publish exception throwing on a separate thread pool, thus the cache mismatch doesn't occure.

**Comment by tishun** [comment]
> 
> I've created a [reliable reproducer](https://github.com/khisamutdinov/lettuce-mismatch-test/tree/main) based on [qinchunabng](https://github.com/qinchunabng) comment ...

Amazing, thank you for that. Will try to work on it as soon as time permits

**Comment by sinrimin** [comment]
I reproduced this issue in async mode using the following code:
```java
    @Test
    public void test01() throws Exception {
        String VALUE = "value";
        String KEY = "key";
        try (RedisClient redisClient = RedisClient.create(uri)) {
            var asyncCommands = redisClient.connect().async();

            for (int i = 0; i < 10; i++) {
                final String key = KEY + i;
                final String value = VALUE + i;
                asyncCommands.set(key, value).whenComplete((respSet, throwable) -> {
                    if (throwable != null) {
                        System.out.println(Thread.currentThread().getName() + ": set " + key + " = " + value + ":" + throwable.getMessage());
                    } else {
                        System.out.println(Thread.currentThread().getName() + ": set " + key + " = " + value + ":" + respSet + ("OK".equals(respSet) ? "" : " MISMATCH!"));
                    }
                });
                asyncCommands.get(key).whenComplete((respGet, throwable) -> {
                    if (throwable != null) {
                        System.out.println(Thread.currentThread().getName() + ": get " + key + " = " + value + ":" + throwable.getMessage());
                    } else {
                        System.out.println(Thread.currentThread().getName() + ": get " + key + " = " + value + ":" + respGet + (value.equals(respGet) ? "" : " MISMATCH!"));
                    }
                });
                if (i == 3) {
                    CommandArgs<String, String> args = new CommandArgs<>(StringCodec.UTF8) {
                        @Override
                        public void encode(ByteBuf buf) {
                            throw new RuntimeException("ERROR");
                        }
                    };
                    args.addKey(key);
                    ValueOutput<String, String> valueOutput = new ValueOutput<>(StringCodec.UTF8){
                        // connection will recreate
//                        @Override
//                        public void complete(int depth) {
//                            throw new RuntimeException("ERROR");
//                        }
                    };
                    asyncCommands.dispatch(CommandType.GET, valueOutput, args).whenComplete((respGet, throwable) -> {
                        if (throwable != null) {
                            System.out.println(Thread.currentThread().getName() + ": get " + key + " = " + value + ":" + throwable.getMessage());
                        } else {
                            System.out.println(Thread.currentThread().getName() + ": get " + key + " = " + value + ":" + respGet);
                        }
                    });
                }
            }
            System.in.read();
        }
    }
```
[netty#14637](https://github.com/netty/netty/pull/14637) or an OOM (Out of Memory) error can cause `CommandEncoder#encode` to fail, so I simulated this scenario in the code above. I think disconnecting the connection when `CommandEncoder#encode` fails could be a reasonable way to handle this.

**Comment by tishun** [comment]
@sinrimin awesome, this seems an even easier to reproduce scenario
I hope we can schedule some time for fixing this with the next minor release.

**Comment by biltusamanta123** [comment]
Hi @tishun we are facing similar issue where we are getting response of different key. after getting 
`com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'OK': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`
Not sure why even getting OK as response. Any idea

**Comment by tishun** [comment]
> Hi [@tishun](https://github.com/tishun) we are facing similar issue where we are getting response of different key. after getting `com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'OK': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')` Not sure why even getting OK as response. Any idea

Can you provide the full stack trace or some more information about what API you are calling?

**Comment by biltusamanta123** [comment]
Hi [@tishun we dont have full stack trace. But we are receving this while making get call to redis. am trying to understand is that fragmented response while client(lettuce) is thinking a full response and try to deserilize it. By seeing "OK" i am guessing it just receive http status code and try to parse

**Comment by biltusamanta123** [comment]
Hi @tishun @khisamutdinov  as you reproduced the isssue do you know root cause of response out of sync issue? Please help me we are also facing same issue.

**Comment by tishun** [comment]
Can you try and see if there is some other exception logged before the out-of-order response?
One possibility is that when parsing the response from a previous command, using an implementation of the RedisOutput, is throwing an exception and this causes the out-of-order.

**Comment by biltusamanta123** [comment]
Ya we see redia wxception out of memory heap space exception

*Regards,*
*Biltu Samanta*
*9738337822*

**Comment by tishun** [comment]
> Ya we see redia wxception out of memory heap space exception

Then this is the root cause of the issue.

[3132](https://github.com/redis/lettuce/issues/3132) aims to fix this

But until then you should try to avoid your app running out of memory.

**Comment by biltusamanta123** [comment]
Thanks but do we know why it happens

*Regards,*
*Biltu Samanta*
*9738337822*

**Comment by tishun** [comment]
> Thanks but do we know why it happens

In short : if an unhandled exception is thrown during the processing of data the even loop would skip processing this entry, but it would remain in the stack an the new response would be incorrectly associated with the old command (whose reply crashed).

**Comment by biltusamanta123** [comment]
Thanks @tishun . So for now as remediation is closing that connection would help solving the issue

**Comment by yangy0000** [comment]
@tishun  We proposed a fix for the encoding exception specifically. Do you mind taking a look and sharing your thoughts? thx https://github.com/redis/lettuce/pull/3443

**Comment by tishun** [comment]
I will try to catch up with this review on Friday

**Comment by tishun** [comment]
> [@tishun](https://github.com/tishun) We proposed a fix for the encoding exception specifically. Do you mind taking a look and sharing your thoughts? thx [#3443](https://github.com/redis/lettuce/pull/3443)

Hey @yangy0000 ,

your solution seems to be based on securing the encoding mechanism (used to encode the command and its arguments), while most cases here fail when the decoding happens (parsing the result of the command execution).

I will spend some time to consider a more complete solution, perhaps based on yours.

**Comment by yangy0000** [comment]
We didn't see out of sync issue for decoding, but encoding error will 100% lead to the issue
