### ISSUE TITLE
How to increase only the initial connection setup timeout (HELLO commands) without modifying the global command timeout

### ISSUE THREAD

**Issue by JoseLora** [lettuce-io/lettuce-core#2024]
Hi,

we are getting timeout errors when initializing our Spring Boot applications which make use of a Redis cache via Spring Data Redis. We're using `eager-initialization` and we try to connect to a Redis cluster (a stateful set of 3 pods in a kubernetes environment).

We can also reproduce the timeout in a local environment with Docker, using ToxiProxy to simulate a 500ms latency in every connection to a local Docker Redis cluster.

#### Current Behavior

The timeouts are 100ms for commands and a `connect-timeout` of 2s.

<details>
<summary>Debug trace</summary>

```
2022-02-24 14:23:28,300 [main] DEBUG io.lettuce.core.resource.AddressResolverGroupProvider - Starting with netty's non-blocking DNS resolver library
2022-02-24 14:23:28,503 [main] DEBUG io.lettuce.core.resource.KqueueProvider - Starting without optional kqueue library
2022-02-24 14:23:28,505 [main] DEBUG io.lettuce.core.resource.IOUringProvider - Starting without optional io_uring library
2022-02-24 14:23:28,522 [main] DEBUG io.lettuce.core.resource.EpollProvider - Starting with epoll library
2022-02-24 14:23:28,540 [main] DEBUG io.lettuce.core.resource.DefaultClientResources - -Dio.netty.eventLoopThreads: 2
2022-02-24 14:23:28,611 [main] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Creating executor io.netty.util.concurrent.DefaultEventExecutorGroup
2022-02-24 14:23:28,830 [main] DEBUG io.lettuce.core.event.jfr.EventRecorderHolder - Starting with JFR support
2022-02-24 14:23:29,737 [main] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Allocating executor io.netty.channel.epoll.EpollEventLoopGroup
2022-02-24 14:23:29,738 [main] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Creating executor io.netty.channel.epoll.EpollEventLoopGroup
2022-02-24 14:23:29,807 [main] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Adding reference to io.netty.channel.epoll.EpollEventLoopGroup@3f8090db, existing ref count 0
2022-02-24 14:23:29,928 [main] DEBUG io.lettuce.core.AbstractRedisClient - Connecting to Redis at redis-cluster.amgjplayg.svc.cluster.local.:6379
2022-02-24 14:23:30,129 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xbe5438c6, [id: 0xcb6a0c04] (inactive), epid=0x1, chid=0x1] channelRegistered()
2022-02-24 14:23:30,345 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xbe5438c6, /10.254.10.24:60884 -> redis-cluster.amgjplayg.svc.cluster.local./10.254.51.82:6379, epid=0x1, chid=0x1] write(ctx, AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
2022-02-24 14:23:30,348 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandEncoder - [channel=0xbe5438c6, /10.254.10.24:60884 -> redis-cluster.amgjplayg.svc.cluster.local./10.254.51.82:6379] writing command AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2022-02-24 14:23:30,348 [lettuce-epollEventLoop-4-1] TRACE io.lettuce.core.protocol.CommandEncoder - [channel=0xbe5438c6, /10.254.10.24:60884 -> redis-cluster.amgjplayg.svc.cluster.local./10.254.51.82:6379] Sent: *2
$5
HELLO
$1
3
2022-02-24 14:23:30,351 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.AbstractRedisClient - Connecting to Redis at redis-cluster.amgjplayg.svc.cluster.local.:6379, initialization: redis-cluster.amgjplayg.svc.cluster.local.:6379
io.lettuce.core.RedisCommandTimeoutException: Connection initialization timed out. Command timed out after 100 millisecond(s)
	at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:71)
	at io.lettuce.core.protocol.RedisHandshakeHandler.lambda$channelRegistered$0(RedisHandshakeHandler.java:62)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-02-24 14:23:30,351 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.RedisChannelHandler - closeAsync()
2022-02-24 14:23:30,351 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.cluster.ClusterNodeEndpoint - [unknown, epid=0x1] closeAsync()
2022-02-24 14:23:30,351 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.DefaultEndpoint - [unknown, epid=0x1] closeAsync()
2022-02-24 14:23:30,352 [lettuce-epollEventLoop-4-1] WARN  io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh - Unable to connect to [redis-cluster.amgjplayg.svc.cluster.local.:6379]: Connection initialization timed out. Command timed out after 100 millisecond(s)
io.lettuce.core.RedisCommandTimeoutException: Connection initialization timed out. Command timed out after 100 millisecond(s)
	at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:71)
	at io.lettuce.core.protocol.RedisHandshakeHandler.lambda$channelRegistered$0(RedisHandshakeHandler.java:62)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-02-24 14:23:30,359 [main] WARN  org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amigaBeanValidatorProcessor' defined in class path resource [com/inditex/aqsw/framework/common/core/config/CommonBeanValidationConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.sleuth.autoconfig.SleuthAnnotationConfiguration': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.inditex.aqsw.framework.common.cache.autoconfigure.ReactiveAwareProxyCachingConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cacheHelper' defined in class path resource [com/inditex/aqsw/framework/common/cache/autoconfigure/CacheReactiveAutoConfiguration.class]: Unsatisfied dependency expressed through method 'cacheHelper' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'primaryCacheManager' defined in class path resource [com/inditex/aqsw/framework/common/cache/autoconfigure/CacheManagementAutoConfiguration.class]: Unsatisfied dependency expressed through method 'primaryCacheManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisCacheManager' defined in class path resource [com/inditex/aqsw/framework/common/cache/redis/config/CacheRedisCacheManagerConfiguration.class]: Unsatisfied dependency expressed through method 'redisCacheManager' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisConnectionFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisException: Cannot obtain initial Redis Cluster topology
2022-02-24 14:23:30,359 [main] DEBUG io.lettuce.core.resource.DefaultClientResources - Initiate shutdown (0, 2, SECONDS)
2022-02-24 14:23:30,359 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xbe5438c6, /10.254.10.24:60884 -> redis-cluster.amgjplayg.svc.cluster.local./10.254.51.82:6379, epid=0x1, chid=0x1] channelInactive()
2022-02-24 14:23:30,360 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.DefaultEndpoint - [unknown, epid=0x1] deactivating endpoint handler
2022-02-24 14:23:30,360 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xbe5438c6, /10.254.10.24:60884 -> redis-cluster.amgjplayg.svc.cluster.local./10.254.51.82:6379, epid=0x1, chid=0x1] channelInactive() done
2022-02-24 14:23:30,361 [main] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Initiate shutdown (0, 2, SECONDS)
2022-02-24 14:23:30,361 [main] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Release executor io.netty.channel.epoll.EpollEventLoopGroup@3f8090db
2022-02-24 14:23:30,361 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.ConnectionWatchdog - [unknown, last known addr=null] channelInactive()
2022-02-24 14:23:30,361 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.ConnectionWatchdog - [unknown, last known addr=null] ConnectionWatchdog not armed
2022-02-24 14:23:30,361 [lettuce-epollEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xbe5438c6, /10.254.10.24:60884 -> redis-cluster.amgjplayg.svc.cluster.local./10.254.51.82:6379, epid=0x1, chid=0x1] channelUnregistered()
```

</details>

<details>
<summary>Stack trace</summary>

```java
Caused by: org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisException: Cannot obtain initial Redis Cluster topology
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:109)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1595)
	... 124 common frames omitted
Caused by: io.lettuce.core.RedisException: Cannot obtain initial Redis Cluster topology
	at io.lettuce.core.cluster.RedisClusterClient.lambda$getPartitions$0(RedisClusterClient.java:329)
	at io.lettuce.core.cluster.RedisClusterClient.get(RedisClusterClient.java:941)
	at io.lettuce.core.cluster.RedisClusterClient.getPartitions(RedisClusterClient.java:329)
	at org.springframework.data.redis.connection.lettuce.ClusterConnectionProvider.getConnectionAsync(ClusterConnectionProvider.java:92)
	at org.springframework.data.redis.connection.lettuce.ClusterConnectionProvider.getConnectionAsync(ClusterConnectionProvider.java:40)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionProvider.getConnection(LettuceConnectionProvider.java:53)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.lambda$null$0(LettucePoolingConnectionProvider.java:97)
	at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.create(ConnectionPoolSupport.java:211)
	at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.create(ConnectionPoolSupport.java:201)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:70)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:122)
	at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:117)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:103)
	... 125 common frames omitted
Caused by: io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh$CannotRetrieveClusterPartitions: Cannot retrieve cluster partitions from [redis://redis-cluster.amgjplayg.svc.cluster.local.?timeout=100000000ns]

Details:
	[redis://redis-cluster.amgjplayg.svc.cluster.local.?timeout=100000000ns]: Unable to connect to [redis-cluster.amgjplayg.svc.cluster.local.:6379]: Connection initialization timed out. Command timed out after 100 millisecond(s)

	Suppressed: io.lettuce.core.RedisConnectionException: Unable to connect to [redis-cluster.amgjplayg.svc.cluster.local.:6379]: Connection initialization timed out. Command timed out after 100 millisecond(s)
		at io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh.lambda$openConnections$11(DefaultClusterTopologyRefresh.java:350)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
		at io.lettuce.core.AbstractRedisClient.lambda$null$5(AbstractRedisClient.java:458)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
		at io.lettuce.core.protocol.RedisHandshakeHandler.lambda$fail$4(RedisHandshakeHandler.java:131)
		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
		at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
		at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
		at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
		at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
		at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:756)
		at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731)
		at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
		at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
		at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)
		at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:611)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: io.lettuce.core.RedisCommandTimeoutException: Connection initialization timed out. Command timed out after 100 millisecond(s)
		at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:71)
		at io.lettuce.core.protocol.RedisHandshakeHandler.lambda$channelRegistered$0(RedisHandshakeHandler.java:62)
		at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
		at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
		at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
		... 4 common frames omitted
```

</details>

#### Expected behavior/code
If we increase the command timeout to 1s for example, the problem is gone, but... Is there any way to increase ONLY the initial connection setup timeout (HELLO commands) without modifying the global command timeout?

We are trying to use a customized `TimeoutOptions`, but it seems the timeout is being triggered inside `RedisHandShake` and our custom `TimeoutOptions.TimeoutSource` is never called:

```java
new TimeoutSource() {
      @Override
      public long getTimeout(final RedisCommand<?, ?, ?> command) {
        if (command.getType().equals(CommandType.HELLO)) {
          return 1000;
        }
        return 100;
      }
    };
```
#### Environment

- Lettuce version(s): 6.1.6.RELEASE

Thanks in advance!

**Comment by mp911de** [comment]
The connection init timeout is fetched from `RedisURI.getTimeout()`. The `TimeoutSource` isn't used to cancel the `HELLO` command as on a connection init timeout we not only cancel the command but close the entire connection.
