### ISSUE TITLE
Lettuce async APIs are not able to carry high load

### ISSUE THREAD

**Issue by pavanbhosle** [lettuce-io/lettuce-core#2034]
we are using Lettuce-core java client 6.1.5 and using various apis with thenaccespt to work asynchronously with db. We are seeing some inconsistency with these apis. thenaccespt is not invoked for many requests in the load testing scenarios. 
For example, if we sent 100000 requests (db writes/reads) then around  50-70% of the requests will be secceeded end to end. The rest of the requets are not suceeding because thenaccespt is not getting invoked for these. When we tried .exceptionally to see what was the reason, we are getting the connecetion close error as mentioned below:

2022/03/03 11:00:42.960 {Engine-Worker-8} [JUnitTest:testGetSingleElementFromMap] <redis.debug-log> (Debug) 'redis.debug-log' Redis debug: exception details from populateHgetResult:: io.lettuce.core.RedisException: Connection closed
	at io.lettuce.core.protocol.DefaultEndpoint.notifyDrainQueuedCommands(DefaultEndpoint.java:679)
	at io.lettuce.core.protocol.CommandHandler.channelInactive(CommandHandler.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.lettuce.core.protocol.RedisHandshakeHandler.channelInactive(RedisHandshakeHandler.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.lettuce.core.ChannelGroupListener.channelInactive(ChannelGroupListener.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

Below is the peice of code foe handling RedisFuture resonse of Get operation.

private void populateHgetResult(WorkItem workItem, FutureContext future) {
        MSG_debug.log("Hget result population");
        List<KeyValue<String, String>> listValue = new ArrayList<>();
        future.getOperationsresults().getFutureResultSelectedMapEntries().exceptionally(new Function<Throwable, List<KeyValue<String, String>>>() {
            @Override
            public List<KeyValue<String, String>> apply(Throwable throwable) {
                MSG_debug.log("apply called from populateHgetResult");
                if (throwable!=null) {
                    MSG_debug.log("throwable from populateHgetResult:: " + throwable.getMessage());
                    StringWriter sw = new StringWriter();
                    throwable.printStackTrace(new PrintWriter(sw));
                    String stackTrace = sw.toString();
                    MSG_debug.log("exception details from populateHgetResult:: " + stackTrace);
                    try {
                        mResultPI.putValue(workItem, null);
                    } catch (DispositionException e) {
                        MSG_Exception.log(e);
                    }
                }
                return listValue;
            }
        }).thenAccept(value -> {
            MSG_debug.log("Hget result recieved");
            if( null != value) {
                List<PairValue> pairValueList = new ArrayList<>();
                value.forEach(k -> {
                    try{
                        k.getKey();
                        k.getValue();
                        MSG_debug.log("HGET result now: " + k.getKey() + k.getValue());
                    }catch (NoSuchElementException ex){
                        MSG_Exception.log(ex);
                        return;
                    }
                    PairValue pair = new PairValue(k.getKey(), k.getValue());
                    pairValueList.add(pair);
                });
                MapValue mapValue = new MapValue(pairValueList, NORMAL_DefaultDictName);
                try {
                    mResultPI.putValue(workItem, mapValue);
                } catch (DispositionException e) {
                    MSG_Exception.log(e);
                }
            }
            MSG_debug.log("resuming workitem after getting response from db: populateHgetResult:: " + Thread.currentThread().getName());
            workItem.scheduleResume(future);
        });
    }
	
	
Please let us know if there is anyway to handle this case to achieve 100% success rate. 
Your response would be much appreciated. Thanks in advance.

**Comment by pavanbhosle** [comment]
please let me know if there is anything done for this quickly to fix this issue. or is it a limitation on lettuce client ? any suggestions ?

**Comment by pavanbhosle** [comment]
Any solution ? Please let me know. 

We are now using async connection pool. Here the frequency of the error is reduced. but still around 5000 requests are failing due to connection closed error in 100000 requets.

RedisURI redisURI ;
                RedisURI.Builder builder = RedisURI.builder();

                builder = RedisURI.Builder.redis(serverAddress, port);
                builder.withTimeout( java.time.Duration.ofMillis( 60000 ) );
                redisURI = builder.build();

                System.out.println("test with clientresource:: redisURI: " + redisURI);
                ClientResources clientResources = ClientResources.builder()
                        .nettyCustomizer(new NettyCustomizer() {
                            @Override
                            public void afterBootstrapInitialized(Bootstrap bootstrap) {
                                bootstrap.option(EpollChannelOption.TCP_KEEPIDLE, 15);
                                bootstrap.option(EpollChannelOption.TCP_KEEPINTVL, 10);
                                bootstrap.option(EpollChannelOption.TCP_KEEPCNT, 10);
                            }
                        })
                        .build();
                System.out.println("test with clientresource");

                RedisClusterClient clusterClient = RedisClusterClient.create(clientResources,  redisURI);
                
                clusterClient.getPartitions();
                SocketOptions socketOptions = SocketOptions.builder()
                        .keepAlive(true).connectTimeout(java.time.Duration.ofMillis( 300000 ) )
                        .build();

                ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                        .enableAdaptiveRefreshTrigger(ClusterTopologyRefreshOptions.RefreshTrigger.MOVED_REDIRECT, ClusterTopologyRefreshOptions.RefreshTrigger.PERSISTENT_RECONNECTS)
                        .adaptiveRefreshTriggersTimeout(java.time.Duration.ofMinutes(3))
                        .build();


                TimeoutOptions to = TimeoutOptions.builder().connectionTimeout().fixedTimeout(java.time.Duration.ofMillis( 300000 ) ).build();
                clusterClient.setOptions(ClusterClientOptions.builder().socketOptions( socketOptions).timeoutOptions(to)
                        .protocolVersion(ProtocolVersion.RESP2)
                        .autoReconnect(true)
                        .pingBeforeActivateConnection(true)
                        .build()

                );

        
                BoundedPoolConfig.Builder builder2 = BoundedPoolConfig.builder();
                builder2.maxTotal(maxTotal);
                final BoundedPoolConfig boundedPoolConfig = builder2.build();

                CompletionStage<BoundedAsyncPool<StatefulRedisClusterConnection<String, String>>> poolFuture = AsyncConnectionPoolSupport.createBoundedObjectPoolAsync(
                        () -> clusterClient.connectAsync(StringCodec.UTF8), boundedPoolConfig);

       

                poolFuture.thenAccept(value ->
                        pool2=value);

**Comment by pavanbhosle** [comment]
Any suggestions on this ?

**Comment by ovk-hbomax** [comment]
@pavanbhosle I am in a similar situation, trying out your code. Lets see if i can find out some meaningful response.

**Comment by mp911de** [comment]
Dumping a wall of code isn't helping to understand what's going on and I cannot reproduce the issue. `Connection closed` can only be caused by a client-side close invocation. When returning a connection back to the pool, that has experienced a failure (e.g. disconnect), then a subsequent successful reconnect may lead to such an exception.
