### ISSUE TITLE
Why is abnormal node not excluded? use RedisClusterClient.

### ISSUE THREAD

**Issue by SungTak** [lettuce-io/lettuce-core#2103]
##### Background Sample
- Redis Cluster
    - One of the eight nodes is in an abnormal state
    - example)
        - OK : 10.20.30.40:100,10.20.30.40:101, (...)
        - BAD : 10.20.30.41:100 (SLAVE)
- Seed Addresses 
    - Set only normal nodes
    - example)
        - 10.20.30.40:100,10.20.30.40:101, (...)

<details>
<summary>Stack trace</summary>

```java
[] 2022-05-26 20:06:09.174  WARN mycomputer --- [oEventLoop-13-6] i.l.c.c.t.ClusterTopologyRefresh         : Unable to connect to [10.20.30.41:100]: Connection refused: no further information: /10.20.30.41:100
```
```java
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 2 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:119)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:131)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:79)
	at com.xxx.xyz.sample.config.Sample.loadScript(Loader.java:27)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
    @Bean(destroyMethod = "shutdown")
    public RedisClusterClient redisClusterClient(ClientResources clientResources) {
        Iterable<RedisURI> redisURIs = Arrays.stream(seedAddresses.split(","))
            .map(node -> {
                String[] token = split(node, ":");
                assert token != null;
                RedisURI redisURI = RedisURI.create(token[0], Integer.parseInt(token[1]));
                redisURI.setPassword(password);
                return redisURI;
            })
            .collect(Collectors.toList());

        RedisClusterClient client = RedisClusterClient.create(clientResources, redisURIs);
        client.setOptions(clientOptions());
        return client;
    }

    @Bean(destroyMethod = "close")
    public StatefulRedisClusterConnection<String, String> redisClusterConnection(RedisClusterClient redisClusterClient) {
        StatefulRedisClusterConnection<String, String> connection = redisClusterClient.connect();
        connection.setReadFrom(ReadFrom.MASTER_PREFERRED);
        return connection;
    }

    @Bean("redisAdvancedClusterCommands")
    public RedisAdvancedClusterCommands<String, String> redisAdvancedClusterCommands(
        StatefulRedisClusterConnection<String, String> redisClusterConnection) {
        RedisAdvancedClusterCommands<String, String> commands = redisClusterConnection.sync();
        commands.setTimeout(Duration.ofSeconds(2));
        return redisClusterConnection.sync();
    }

    private ClusterClientOptions clientOptions() {
        return ClusterClientOptions.builder()
            .validateClusterNodeMembership(true)
            .autoReconnect(true)
            .socketOptions(SocketOptions
                .builder()
                .connectTimeout(Duration.ofSeconds(5))
                .tcpNoDelay(true)
                .keepAlive(true)
                .build())
            .topologyRefreshOptions(topologyRefreshOptions())
            .build();
    }

    private ClusterTopologyRefreshOptions topologyRefreshOptions() {
        return ClusterTopologyRefreshOptions
            .builder()
            .enablePeriodicRefresh(Duration.ofSeconds(30))
            .enableAllAdaptiveRefreshTriggers()
            .build();
    }
```
```java
    public String loadScript(RedisScript<Boolean> redisScript, RedisAdvancedClusterCommands<String, String> redisAdvancedClusterCommands) {
        return redisAdvancedClusterCommands.get(getKey()); // ERROR!
```

</details>

#### Expected behavior/code

not connect to bad node

#### Environment

- Lettuce version(s): Both 5.3.7.RELEASE AND 6.1.8.RELEASE
- Redis version: 5.0.4

#### Possible Solution

successful after changing lettcue connection timeout(5s to 1s) less than command timeout(2s)

```java
    private ClusterClientOptions clientOptions() {
        return ClusterClientOptions.builder()
            .validateClusterNodeMembership(true)
            .autoReconnect(true)
            .socketOptions(SocketOptions
                .builder()
                .connectTimeout(Duration.ofSeconds(1)) // fix
                .tcpNoDelay(true)
                .keepAlive(true)
                .build())
            .topologyRefreshOptions(topologyRefreshOptions())
            .build();
    }
```

#### Additional context

Is it correct to reduce the connection timeout?

**Comment by mp911de** [comment]
Yes, `connectTimeout(Duration.ofSeconds(1))` is the correct setting.
