### ISSUE TITLE
NPE in RedisStateMachine

### ISSUE THREAD

**Issue by schernolyas** [lettuce-io/lettuce-core#2104]
## Bug Report

Hi! I have faced with the blocking problem. Lettuce 4.4.6 is used.
My application use publishing and subscription feature.  I can't read the message because of this error.
Unfortunately, I can't debug because it occurs in productive environment.
I have developed the test to investigate this problem in my local environment .... Unsuccessfully.

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java

java.lang.NullPointerException
--
  | at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:431)
  | at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:233)
  | at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:133)
  | at com.lambdaworks.redis.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:97)
  | at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:266)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

```

</details>

#### Environment

- Lettuce version(s): [4.4.6.Final]
- Redis version: [4.*]

**Comment by schernolyas** [comment]
I think my problem in linked with https://github.com/lettuce-io/lettuce-core/issues/576
