### ISSUE TITLE
Redis 7 Sentinel - unknown subcommand 'SLAVES

### ISSUE THREAD

**Issue by PRAMITGit** [lettuce-io/lettuce-core#2113]
#### Current Behaviour
Our Spring boot app with lettuce was successfully  putting/fetching cache memory  with Redis(3 sentinel,1 master and 2 slaves) with version 6.2.8. After upgrading our Redis cluster to version 7.0.0 we are not able to connect to redis from application.

<details>
<summary>After version upgrade application is not able to connect to Redis .It's giving below error </summary>

```java
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR unknown subcommand 'SLAVES'. Try SENTINEL HELP.
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
        at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:757)
        at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)
        at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681)
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted

```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
public LettuceConnectionFactory redisConnectionFactory() {

			LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
					.readFrom(ReadFrom.REPLICA_PREFERRED)
					.build();
RedisSentinelConfiguration sentinelConfig = new RedisSentinelConfiguration();

			sentinelConfig.setPassword("mypassword");

			sentinelConfig.setSentinelPassword("mypassword");

                        sentinelConfig.master("master")
		        .sentinel("127.0.0.1", 26379)
		        .sentinel("127.0.0.1", 26380)
        	        .sentinel("127.0.0.1", 26381);		      

return new LettuceConnectionFactory(sentinelConfig, clientConfig);
}
```

</details>

#### Environment

- Lettuce version(s): implementation group: 'io.lettuce', name: 'lettuce-core', version: '6.1.8.RELEASE'
- Redis version:7.0.0

#### Additional context
Adding complete stack trace for reference.
```java
14:06:40.295 INFO  [http-nio-61080-exec-3]  c.s.r.user.controller.UserController - Enter to method saveUserDetails null
14:06:40.296 DEBUG [http-nio-61080-exec-3]  i.l.c.m.SentinelTopologyProvider - lookup topology for masterId redis-node-master
14:06:40.296 DEBUG [http-nio-61080-exec-3]  io.lettuce.core.RedisClient - Trying to get a Redis Sentinel connection for one of: [redis://***********@myip-sentinel1:port, redis://***********@sentinel2:26379, redis://***********@myip-sentinel2:port]
14:06:40.296 DEBUG [http-nio-61080-exec-3]  io.lettuce.core.RedisClient - Connecting to Redis Sentinel, address: redis://***********@myip-sentinel1:port
14:06:40.297 DEBUG [http-nio-61080-exec-3]  io.lettuce.core.RedisClient - Resolved SocketAddress myip-sentinel1:port using redis://***********@myip-sentinel1:port
14:06:40.297 DEBUG [http-nio-61080-exec-3]  io.lettuce.core.AbstractRedisClient - Connecting to Redis at myip-sentinel1:port
14:06:40.304 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, [id: 0x2f50b89d] (inactive), epid=0x3, chid=0x3] channelRegistered()
14:06:40.305 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] write(ctx, AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
14:06:40.306 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandEncoder - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port] writing command AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] Received: 120 bytes, 1 commands in the stack
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] Stack contains: 1 commands
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.RedisStateMachine - Decode done, empty stack: true
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] Completing command AsyncCommand [type=HELLO, output=GenericMapOutput [output={server=redis, version=7.0.0, proto=3, id=15, mode=sentinel}, error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] channelActive()
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] activateEndpointAndExecuteBufferedCommands 0 command(s) buffered
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] activating endpoint
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] flushCommands()
14:06:40.307 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] flushCommands() Flushing 0 commands
14:06:40.308 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.ConnectionWatchdog - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, last known addr=/myip-sentinel1:port] channelActive()
14:06:40.308 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] channelActive() done
14:06:40.308 DEBUG [lettuce-nioEventLoop-6-1]  io.lettuce.core.AbstractRedisClient - Connecting to Redis at myip-sentinel1:port: Success
14:06:40.308 DEBUG [lettuce-nioEventLoop-6-1]  io.lettuce.core.RedisChannelHandler - dispatching command SubscriptionCommand [type=SENTINEL, output=MapOutput [output=SubscriptionCommand [type=SENTINEL, output=MapOutput [output={}, error='null'], commandType=io.lettuce.core.protocol.Command], error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.308 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] write() writeAndFlush command SubscriptionCommand [type=SENTINEL, output=MapOutput [output=[channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3], error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.308 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] write(ctx, SubscriptionCommand [type=SENTINEL, output=MapOutput [output=[channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3], error='null'], commandType=io.lettuce.core.protocol.Command], promise)
14:06:40.308 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandEncoder - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port] writing command SubscriptionCommand [type=SENTINEL, output=MapOutput [output=[channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port], error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.309 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] write() done
14:06:40.309 DEBUG [lettuce-nioEventLoop-6-1]  io.lettuce.core.RedisChannelHandler - dispatching command SubscriptionCommand [type=SENTINEL, output=ListOfMapsOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.309 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] write() writeAndFlush command SubscriptionCommand [type=SENTINEL, output=ListOfMapsOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.309 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] write(ctx, SubscriptionCommand [type=SENTINEL, output=ListOfMapsOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], promise)
14:06:40.309 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandEncoder - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port] writing command SubscriptionCommand [type=SENTINEL, output=ListOfMapsOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.309 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] write() done
14:06:40.312 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] Received: 679 bytes, 2 commands in the stack
14:06:40.312 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] Stack contains: 2 commands
14:06:40.313 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.RedisStateMachine - Decode done, empty stack: true
14:06:40.313 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] Completing command SubscriptionCommand [type=SENTINEL, output=MapOutput [output={name=redis-node-master, ip=sentinel2, port=6379, runid=0b4fe8125bb0cf7c0f79f5dc2249e1a5e8d1cc2b, flags=master, link-pending-commands=0, link-refcount=1, last-ping-sent=0, last-ok-ping-reply=426, last-ping-reply=426, down-after-milliseconds=6000, info-refresh=5343, role-reported=master, role-reported-time=21429959, config-epoch=1, num-slaves=2, num-other-sentinels=2, quorum=2, failover-timeout=6000, parallel-syncs=1}, error='null'], commandType=io.lettuce.core.protocol.Command]
14:06:40.313 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] Stack contains: 1 commands
14:06:40.313 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.RedisStateMachine - Decode done, empty stack: true
14:06:40.313 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] Completing command SubscriptionCommand [type=SENTINEL, output=ListOfMapsOutput [output=[], error='ERR unknown subcommand 'SLAVES'. Try SENTINEL HELP.'], commandType=io.lettuce.core.protocol.Command]
14:06:40.313 DEBUG [lettuce-nioEventLoop-6-1]  io.lettuce.core.RedisChannelHandler - closeAsync()
14:06:40.313 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] closeAsync()
14:06:40.314 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] channelInactive()
14:06:40.314 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.DefaultEndpoint - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3] deactivating endpoint handler
14:06:40.314 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] channelInactive() done
14:06:40.314 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.ConnectionWatchdog - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, last known addr=/myip-sentinel1:port] channelInactive()
14:06:40.314 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.ConnectionWatchdog - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, last known addr=/myip-sentinel1:port] Reconnect scheduling disabled
14:06:40.314 DEBUG [lettuce-nioEventLoop-6-1]  i.l.core.protocol.CommandHandler - [channel=0xd7d885ad, /master-node:port -> /myip-sentinel1:port, epid=0x3, chid=0x3] channelUnregistered()
14:06:40.320 ERROR [http-nio-61080-exec-3]  o.s.b.w.s.support.ErrorPageFilter - Forwarding to error page from request [/api/user] due to exception [Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to redis-sentinel://***********@sentinel1,sentinel2,sentinel3?sentinelMasterId=redis-node-master]
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to redis-sentinel://***********@sentinel1,sentinel2,sentinel3?sentinelMasterId=redis-node-master
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.translateException(LettuceConnectionFactory.java:1553)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1461)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1247)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1230)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:979)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:359)
        at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
        at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
        at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:209)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:189)
        at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
        at org.springframework.data.redis.core.DefaultHashOperations.put(DefaultHashOperations.java:191)
        at com.spring.redis.user.controller.UserController.saveUserDetails(UserController.java:62)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to redis-sentinel://***********@sentinel1,sentinel2,sentinel3?sentinelMasterId=redis-node-master
        at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
        at io.lettuce.core.masterreplica.MasterReplica.getConnection(MasterReplica.java:261)
        at io.lettuce.core.masterreplica.MasterReplica.connect(MasterReplica.java:113)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.masterReplicaConnection(StandaloneConnectionProvider.java:159)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$0(StandaloneConnectionProvider.java:114)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:114)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1459)
        ... 70 common frames omitted
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR unknown subcommand 'SLAVES'. Try SENTINEL HELP.
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
        at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
        at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:757)
        at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)
        at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681)
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted

    ```

**Comment by PRAMITGit** [comment]
This is the issue from Redis which redis developer have addressed in Redis version 7.0.1 .So we have upgarded our redis to version 7.0.1 and the issue has been resolved.

Sharing the release note for version 7.0.1: 
https://raw.githubusercontent.com/redis/redis/7.0/00-RELEASENOTES 


Fixes for issues in previous release candidates of Redis 7.0
------------------------------------------------------------
* Re-add SENTINEL SLAVES command, missing in redis 7.0 (#10723)
