### ISSUE TITLE
NoSuchElementException in hmultiGet 

### ISSUE THREAD

**Issue by zafir-zhong** [lettuce-io/lettuce-core#2121]
# throw exception when get 100 users （use hmultiGet）
all fields can find in redis 
version lettuce-core：5.3.4-RELEASE

log （replace company package）
```java
2022-06-17 12:23:46.576|WARN  |27303|ConsumeMessageThread_14|xxx.yyyyy.module.commons.redis.RedisTools.hmget(RedisTools.java:573)|org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: java.util.NoSuchElementException
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273)
	at org.springframework.data.redis.connection.lettuce.LettuceHashCommands.convertLettuceAccessException(LettuceHashCommands.java:471)
	at org.springframework.data.redis.connection.lettuce.LettuceHashCommands.hMGet(LettuceHashCommands.java:322)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.hMGet(DefaultedRedisConnection.java:1150)
	at org.springframework.data.redis.core.DefaultHashOperations.lambda$multiGet$8(DefaultHashOperations.java:175)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultHashOperations.multiGet(DefaultHashOperations.java:175)
	at xxx.yyyyy.cache.utils.RedisUtils.hmultiGet(RedisUtils.java:472)
	at xxx.yyyyy.cache.utils.RedisUtils$$FastClassBySpringCGLIB$$837d1e61.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:100)
	at xxx.yyyyy.cache.lettuce.aspect.CacheAspect.around(CacheAspect.java:97)
	at sun.reflect.GeneratedMethodAccessor355.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at xxx.yyyyy.cache.utils.RedisUtils$$EnhancerBySpringCGLIB$$c63e3e91.hmultiGet(<generated>)
	at xxx.yyyyy.module.commons.redis.RedisTools.hmget(RedisTools.java:562)
	at xxx.yyyyy.module.service.cache.impl.UserCacheImpl.getMultiUserFromCacheByIds(UserCacheImpl.java:77)
	at xxx.yyyyy.module.service.dataflow.impl.UserDataFlowImpl.getMultiUserByIds(UserDataFlowImpl.java:102)
	at xxx.yyyyy.module.service.service.impl.UserServiceImpl.getUserListByIds(UserServiceImpl.java:3874)
	at xxx.yyyyy.module.service.service.impl.UserServiceImpl$$FastClassBySpringCGLIB$$dbed521.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at xxx.yyyyy.module.commons.validation.ModelValidationMethodInterceptor.invoke(ModelValidationMethodInterceptor.java:23)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at xxx.yyyyy.module.service.service.impl.UserServiceImpl$$EnhancerBySpringCGLIB$$6dd04048.getUserListByIds(<generated>)
	at xxx.yyyyy.module.dubborpc.service.impl.UserV2DubboFacadeImpl.getUserListByIds(UserV2DubboFacadeImpl.java:68)
	at xxx.yyyyy.module.dubborpc.service.impl.UserV2DubboFacadeImpl$$FastClassBySpringCGLIB$$13d3c0d0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at xxx.yyyyy.module.dubborpc.interceptor.PrometheusMonitorDubboPointCut.monitorAround(PrometheusMonitorDubboPointCut.java:56)
	at sun.reflect.GeneratedMethodAccessor1165.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at xxx.yyyyy.module.dubborpc.interceptor.FacadeLogAspect.around(FacadeLogAspect.java:59)
	at sun.reflect.GeneratedMethodAccessor1164.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at xxx.yyyyy.module.dubborpc.service.impl.UserV2DubboFacadeImpl$$EnhancerBySpringCGLIB$$ae744ad3.getUserListByIds(<generated>)
	at xxx.yyyyy.message.service.service.impl.MessageSendServiceImpl.getUsers(MessageSendServiceImpl.java:284)
	at xxx.yyyyy.message.service.service.impl.MessageSendServiceImpl.cutMessage(MessageSendServiceImpl.java:101)
	at xxx.yyyyy.message.service.service.impl.MessageSendServiceImpl.handleMessage(MessageSendServiceImpl.java:87)
	at xxx.yyyyy.message.service.mq.consumer.manager.MessageConsumerManager.consumeWholeMessage(MessageConsumerManager.java:283)
	at xxx.yyyyy.message.service.mq.consumer.manager.MessageConsumerManager.access$300(MessageConsumerManager.java:51)
	at xxx.yyyyy.message.service.mq.consumer.manager.MessageConsumerManager$2.lambda$consumeMessage$0(MessageConsumerManager.java:226)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at xxx.yyyyy.message.service.mq.consumer.manager.MessageConsumerManager$2.consumeMessage(MessageConsumerManager.java:218)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:412)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisException: java.util.NoSuchElementException
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:134)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:75)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:79)
	at com.sun.proxy.$Proxy244.hmget(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceHashCommands.hMGet(LettuceHashCommands.java:320)
	... 90 more
Caused by: java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(AbstractList.java:364)
	at io.lettuce.core.output.KeyValueListOutput.set(KeyValueListOutput.java:58)
	at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:457)
	at io.lettuce.core.protocol.RedisStateMachine.handleBytes(RedisStateMachine.java:274)
	at io.lettuce.core.protocol.RedisStateMachine.access$000(RedisStateMachine.java:41)
	at io.lettuce.core.protocol.RedisStateMachine$State$Type.lambda$static$5(RedisStateMachine.java:66)
	at io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:76)
	at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:166)
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:142)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:742)
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:706)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:692)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:622)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:591)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrenFastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by zafir-zhong** [comment]
trying to reproduce the problem in demo environment.

**Comment by zafir-zhong** [comment]
sorry, i need more time to reproduce it in  demo environment.but i still reproduce test situations.  i don't why it throw java.util.NoSuchElementException in io.lettuce.core.output.KeyValueListOutput.set(KeyValueListOutput.java:58)

**Comment by zafir-zhong** [comment]
fail to reproduce. i close it. sorry
