### ISSUE TITLE
java.util.AbstractList.add(AbstractList.java:148)

### ISSUE THREAD

**Issue by i3587616** [lettuce-io/lettuce-core#2147]
redis:
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数
        max-idle: 5 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    cluster:
      nodes:

#<dependency>
           # <groupId>org.springframework.boot</groupId>
           # <artifactId>spring-boot-starter-data-redis</artifactId>
          # <version>2.0.5</version>
        #</dependency>

wrong:
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_333]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_333]
	at io.lettuce.core.output.ArrayOutput.set(ArrayOutput.java:54) ~[lettuce-core-5.0.5.RELEASE.jar:?]
	at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:357) ~[lettuce-core-5.0.5.RELEASE.jar:?]
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:138) ~[lettuce-core-5.0.5.RELEASE.jar:?]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:660) ~[lettuce-core-5.0.5.RELEASE.jar:?]
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:624) ~[lettuce-core-5.0.5.RELEASE.jar:?]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:619) ~[lettuce-core-5.0.5.RELEASE.jar:?]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:539) ~[lettuce-core-5.0.5.RELEASE.jar:?]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:508) ~[lettuce-core-5.0.5.RELEASE.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	... 1 more

just :
    @Override
    public void set(long integer) {
        stack.peek().add(integer);
    } 
this peek() is AbstractList then wrong

**Comment by mp911de** [comment]
The list size is determined by a Redis response specifying the number of elements to expect. Can you provide a reproducer so we can diagnose the issue?

**Comment by i3587616** [comment]
redis is in docker .cluster .version is 7.0

**Comment by i3587616** [comment]
#<artifactId>lettuce-core</artifactId>
      #<version>6.1.8.RELEASE</version>
no problem .but 5.0.5  is wrong. i have old project and in use .

**Comment by i3587616** [comment]
#host: ****** # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6391 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
not use cluster use host is normal.
but use cluster is wrong.  @mp911de

**Comment by i3587616** [comment]
in <version>6.1.8.RELEASE</version>  use cluster is normal

**Comment by mp911de** [comment]
I cannot understand the actual problem and thus I cannot solve it, so closing the ticket.
