### ISSUE TITLE
After 2 hours of operation :cpu 100% BUG

### ISSUE THREAD

**Issue by Cutie-Sakura** [lettuce-io/lettuce-core#2149]
Stable reproduction, and the CPU instantly reaches 100% after the program runs for 2 hours;

`19:37:41.453 [lettuce-nioEventLoop-4-1] INFO  i.l.c.p.CommandHandler - [log,219] - null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
19:37:41.462 [lettuce-nioEventLoop-4-1] WARN  i.n.c.n.NioEventLoop - [select,790] - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@7aad3a58.
19:37:41.505 [lettuce-nioEventLoop-4-1] INFO  i.n.c.n.NioEventLoop - [rebuildSelector0,396] - Migrated 0 channel(s) to the new Selector.
19:37:41.604 [lettuce-eventExecutorLoop-1-1] INFO  i.l.c.p.ConnectionWatchdog - [log,173] - Reconnecting, last destination was /127.0.0.1:6379
19:37:41.643 [lettuce-nioEventLoop-4-2] INFO  i.l.c.p.ReconnectionHandler - [lambda$null$3,177] - Reconnected to 127.0.0.1:6379
19:37:41.646 [lettuce-nioEventLoop-4-2] WARN  i.n.c.n.NioEventLoop - [select,790] - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@49e15be8.
19:37:41.683 [lettuce-nioEventLoop-4-2] INFO  i.n.c.n.NioEventLoop - [rebuildSelector0,396] - Migrated 1 channel(s) to the new Selector.`
 
![image](https://user-images.githubusercontent.com/45060572/178392059-e16f4383-1903-4992-b78f-6583e76aadca.png)

6.1.8.RELEASE  and  5.1.3.RELEASE  all bug

**Comment by mp911de** [comment]
Looks like an infrastructure issue triggered by the Redis server. The high CPU usage seems to originate from the reconnects as consequence of an earlier connection reset. The driver works as designed.
