### ISSUE TITLE
CommandHandler's validateWrite method has a calculated overflow problem

### ISSUE THREAD

**Issue by Yanam** [lettuce-io/lettuce-core#2150]
#### Current Behavior

When the RequestQueueSize of ClientOptions is set to the range Integer.MAX_VALUE to Integer.MAX_VALUE-4, the execution of any redis command will throw an exception

<details>
<summary>Stack trace</summary>

```java
Caused by: io.lettuce.core.RedisException: Internal stack size exceeded: 2147483643. Commands are not accepted until the stack size drops.
	at io.lettuce.core.protocol.CommandHandler.validateWrite(CommandHandler.java:526)
	at io.lettuce.core.protocol.CommandHandler.addToStack(CommandHandler.java:496)
	at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:417)
	at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:387)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
	at io.lettuce.core.RedisHandshake.dispatch(RedisHandshake.java:221)


```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
    RedisClient redisClient = RedisClient.create("redis://127.0.0.1:6379/");
    ClientOptions clientOptions = ClientOptions.builder().requestQueueSize(Integer.MAX_VALUE-4).build();
    redisClient.setOptions(clientOptions);
    StatefulRedisConnection<String, String> connection = redisClient.connect();

    RedisCommands<String, String> syncCommands = connection.sync();
    String res = syncCommands.get("test");
```

</details>

#### Possible Solution

```java
public class CommandHandler extends ChannelDuplexHandler implements HasQueuedCommands {

...

  private void validateWrite(int commands) {

        if (usesBoundedQueues()) {
            
            // int allowedRequestQueueSize = clientOptions.getRequestQueueSize() + maxMaintenanceCommands;

            // fixes integer calculation overflow problem
            int allowedRequestQueueSize =  clientOptions.getRequestQueueSize() >= Integer.MAX_VALUE-maxMaintenanceCommands?  Integer.MAX_VALUE : clientOptions.getRequestQueueSize()+maxMaintenanceCommands;
            if (stack.size() + commands > allowedRequestQueueSize)

                throw new RedisException("Internal stack size exceeded: " + clientOptions.getRequestQueueSize()
                        + ". Commands are not accepted until the stack size drops.");
        }
    }

...
}
```

#### Additional context

None

**Comment by mp911de** [comment]
Do you want to submit a pull request?
