### ISSUE TITLE
tracing exception cause cpu 100

### ISSUE THREAD

**Issue by Ynge** [lettuce-io/lettuce-core#2169]
#### Current Behavior

if the nextSpan(context) call in writeSingleCommand method throws an Exception and the lettuce reconect logic call selectAsync(db), it will loop forever.

#### Expected behavior/code

I think it's best not to use tracing logic when reconnecting.

#### Environment

- Lettuce version(s): 5.1.3.RELEASE
- Redis version: 3.2

**Comment by mp911de** [comment]
Can you provide a bit more details such as stack traces?

**Comment by Ynge** [comment]
here is my stack traces:
----------------------------------------------
"lettuce-epollEventLoop-4-7" #7205 daemon prio=5 os_prio=0 tid=0x00007fad2c00e800 nid=0x1d8d runnable [0x00007fac58157000]
   java.lang.Thread.State: RUNNABLE
        at com.pacer.tracing.plugins.lettuce.PacerLettuceTracing$PacerLettuceTracingTracer.nextSpan(PacerLettuceTracing.java:81)
        at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:385)
        at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
        at io.lettuce.core.protocol.DefaultEndpoint.channelWriteAndFlush(DefaultEndpoint.java:342)
        at io.lettuce.core.protocol.DefaultEndpoint.writeToChannelAndFlush(DefaultEndpoint.java:282)
        at io.lettuce.core.protocol.DefaultEndpoint.write(DefaultEndpoint.java:142)
        at io.lettuce.core.protocol.DefaultEndpoint$RetryListener.requeueCommands(DefaultEndpoint.java:938)
        at io.lettuce.core.protocol.DefaultEndpoint$RetryListener.lambda$potentiallyRequeueCommands$0(DefaultEndpoint.java:925)
        at io.lettuce.core.protocol.DefaultEndpoint$RetryListener$$Lambda$660/1961271138.run(Unknown Source)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
