### ISSUE TITLE
codis : Unable to connect to xxx.xxx.xxx.xxx:19000

### ISSUE THREAD

**Issue by renguoqing123** [lettuce-io/lettuce-core#2191]
Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to connect to xxx.xxx.xxx.xxx:19000
at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:350)
at io.lettuce.core.RedisClient.connect(RedisClient.java:216)
at io.lettuce.core.RedisClient.connect(RedisClient.java:201)
at com.Lettuce.main(Lettuce.java:11)
Caused by: io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required
at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:747)
at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:682)
at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:599)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

**Comment by renguoqing123** [comment]
package com;

import io.lettuce.core.RedisClient;
import io.lettuce.core.RedisURI;
import io.lettuce.core.api.StatefulRedisConnection;
import io.lettuce.core.api.sync.RedisCommands;

public class Lettuce {
	public static void main(String[] args) {
		RedisClient client = RedisClient.create(getRedisUri());
		StatefulRedisConnection<String, String> connect = client.connect();
		RedisCommands<String, String> commands = connect.sync();
		commands.set("a", "1");
		String value = commands.get("a");
		connect.close();
	        client.shutdown();
	        System.out.println(value);
	}
	
	private static RedisURI getRedisUri() {
		RedisURI redisUri = RedisURI.Builder.redis("10.203.110.35")//codis is error
						.withPort(19000)
						.withPassword("SkoPUGFzczEyMzQ=".toCharArray())
						.withDatabase(14)
						.build();
		// RedisURI redisUri = RedisURI.Builder.redis("127.0.0.1")//redis is success
		// 				.withPort(6379)
		// 				.build();
		return redisUri;
	}
}

**Comment by mp911de** [comment]
Can you enable debug logging for the `io.lettuce.core` category to see what's going on? You Lettuce 6 tries to auto-discover the protocol version and you might want to configure `RESP2` via `ClientOptions` to disable protocol negotiation.

**Comment by renguoqing123** [comment]
> Can you enable debug logging for the `io.lettuce.core` category to see what's going on? You Lettuce 6 tries to auto-discover the protocol version and you might want to configure `RESP2` via `ClientOptions` to disable protocol negotiation.

The current version is 6.1.8, the version is downgraded by 5.3.7, and the program is running normally

**Comment by mp911de** [comment]
Yeah, that confirms my diagnosis that the protocol negotiation response is different from Redis's and that setting the protocol to RESP2 will fix the issue.
