### ISSUE TITLE
io.lettuce.core.rediscommandexecutionexception: moved 15596 10.2.1**.4*:6379

### ISSUE THREAD

**Issue by sarapranavit** [lettuce-io/lettuce-core#2225]
#### Current Behavior

Facing Issue was RedisCommandExecutionException
io.lettuce.core.rediscommandexecutionexception: moved 15596 10.2.1**.4*:6379
Not occuring all the times, But freqently facing this isssue

<details>
<summary>Stack trace</summary>

io.lettuce.core.RedisCommandExecutionException: MOVED 15596 10.2.1**.4*:6379
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:135)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:122)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy31.del(Unknown Source)
	at com.hidglobal.sis.credential.conversion.service.UnifiedReservationRedisService.delMultipleKeys(UnifiedReservationRedisService.java:74)
	at com.orgname.credential.conversion.api.Handler.handleRequest(Handler.java:45)
	at com.orgname.credential.conversion.api.Handler.handleRequest(Handler.java:19)
	at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:903)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:349)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:70)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
Caused by: io.lettuce.core.RedisCommandExecutionException: MOVED 15596 10.3.197.40:6379
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:135)
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:108)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:654)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:614)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

</details>

#### Code 

<details>
<summary>Input Code</summary>

``` 
public AbstractRedisClient getClient(String host, String port) {
        LOG.info("redis-uri" + "redis://"+host+":"+port);
        return RedisClient.create("redis://"+host+":"+port);
    }

    /**
     * Returns the Redis connection using the Lettuce-Redis-Client
     *
     * @return RedisClient
     */
    public RedisClient getConnection(String host, String port) {
        LOG.info("redis-Host " + host);
        LOG.info("redis-Port " + port);
        RedisClient redisClient = (RedisClient) getClient(host, port);
        redisClient.setDefaultTimeout(Duration.ofSeconds(10));
        return redisClient;
    }

private RedisCommands<String, String> getRedisCommands() {
        StatefulRedisConnection<String, String> statefulConnection = openConnection();
        if(statefulConnection != null)
          return statefulConnection.sync();
        else
          return null;
      }
    
      public StatefulRedisConnection<String, String> openConnection() {
    
        if(connection != null && connection.isOpen()) {
          return connection;
        }
        //String redisHost = "sisptest2ec.je6eii.clustercfg.use1.cache.amazonaws.com";
        String redisPort = "6379";
        String redisHost = environment.getProperty("REDIS_HOST");
        //String redisPort = environment.getProperty("REDIS_PORT");
        LOG.info("Host: {}", redisHost);
        LOG.info("Port: {}", redisPort);
        UnifiedReservationRedisConfig lettuceRedisConfig = new UnifiedReservationRedisConfig();
        String redisUri = "redis://"+redisHost+":"+redisPort;
        redisClient = lettuceRedisConfig.getConnection(redisHost, redisPort);
    
        ConnectionFuture<StatefulRedisConnection<String, String>> future = redisClient
            .connectAsync(StringCodec.UTF8, RedisURI.create(redisUri));
        try {
          connection = future.get();
        } catch(InterruptedException | ExecutionException exception) {
            LOG.info(exception.getMessage());
          closeConnectionsAsync();
          connection = null;
          Thread.currentThread().interrupt();
        }
        return connection;
      }
    
      private void closeConnectionsAsync() {
        LOG.info("Close redis connection");
        if(connection != null && connection.isOpen()) {
          connection.closeAsync();
        }
        if(redisClient != null) {
          redisClient.shutdownAsync();
        }
      }
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

#### Possible Solution

Kindly help to solve this issue

**Comment by mp911de** [comment]
Please make yourself familiar with the Lettuce client, specifically `RedisClusterClient` to connect to Redis Clusters.
