### ISSUE TITLE
Command timed out

### ISSUE THREAD

**Issue by liming19964** [lettuce-io/lettuce-core#2230]
## Bug Report
I operate Redis in cluster mode,when i execute the code ,i will get RedisCommandTimeoutException after a period of time..

#### Current Behavior
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveRedisConnection.lambda$translateException$0(LettuceReactiveRedisConnection.java:293)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6536)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:247)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onError(RedisPublisher.java:890)
	at io.lettuce.core.RedisPublisher$State.onError(RedisPublisher.java:687)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onError(RedisPublisher.java:344)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.onError(RedisPublisher.java:800)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.completeExceptionally(RedisPublisher.java:794)
	at io.lettuce.core.cluster.ClusterCommand.completeExceptionally(ClusterCommand.java:97)
	at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:167)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	... 8 more

#### Input Code

i use foreach to replace datasource
// your code here;
   @Test
    public void testTimeOut() {
        for (int i = 0; i < 25000; i++) {
            Mono.just("1")
                    .flatMap(m -> {
                        final List<Mono<Tuple3<Long, Long, Boolean>>> list = new ArrayList<>();
                        final ReactiveListOperations<String, String> opsForList = redisTemplate.opsForList();
                        for (int i2 = 0; i2 < 200; i2++) {
                            final Mono<Long> leftPush = opsForList.leftPush("1", "1");
                            final ReactiveValueOperations<String, String> opsForValue = redisTemplate.opsForValue();
                            final Mono<Long> increment = opsForValue.increment("2").switchIfEmpty(Mono.just(0L));
                            final Mono<Boolean> expire = redisTemplate.expire("2", Duration.ofSeconds(10L))
                                    .switchIfEmpty(Mono.just(false));
                            list.add(Mono.zip(leftPush, increment, expire));
                        }
                        return Mono.zip(list, r -> r).flatMap(r -> {
                            return Mono.just("0");
                        });
                    }).doOnError(Throwable::printStackTrace)
                    .map(value -> {
                        for (int i2 = 0; i2 < 200; i2++) {

                        }
                        return Mono.just("1");
                    })
                    .subscribe();
        }
        System.out.println("end");
    }

#### Expected behavior/code

no RedisCommandTimeoutException

#### Environment
- spring-boot-starter-data-redis-reactive version: 2.2.12.RELEASE
- Lettuce version(s): 5.2.2.RELEASE
- Redis version: 6.0.6

#### Additional context

when i use spring-boot-starter-data-redis-reactive version: 2.1.2.RELEASE (Lettuce version(s): 5.1.3.RELEASE),i will not get RedisCommandTimeoutException.I found that it was because there was no call  CommandExpiryWriter.potentiallyExpire().
So , could give me some suggestions。Thank you!

**Comment by mp911de** [comment]
The reference documentation covers generic timeout questions.
