### ISSUE TITLE
High client side latency + timeouts under moderate load of traffic while ElastiCache Redis usage is super low

### ISSUE THREAD

**Issue by dasdjsakji2o13djsakj** [lettuce-io/lettuce-core#2245]
#### Current Behavior

We are experiencing high client side latency (over 8 secs) and a big amount timeouts for Sorted Set ZRANGE commands from Redis while metrics showing Redis usage is super low. We are testing with around 400 requests per second, and getting constant timeouts. We have a Redis cluster with 3 shards, and each shard has 2 replicas. While read happens, we use REPLICA_PREFERRED option to read from Redis. While this happened, Redis Engine CPU usage is below 4%, connection number is around 130 for each instance, and all I/O and network metrics look completely fine. No SwapUsage, evictions or anything. Each instance has 4 cores and 64Gb of memory. We have no idea why it is not able to process all the requests we sent as Redis usage is so low.
<details>
<summary>Stack trace</summary>

```java
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 8 second(s)
at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:53) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
at io.lettuce.core.internal.Futures.awaitOrCancel(Futures.java:246) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:130) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
at com.sun.proxy.$Proxy77.eval(Unknown Source) ~[?:?]
at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:215) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
at com.sun.proxy.$Proxy77.eval(Unknown Source) ~[?:?]
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java

        final DefaultClientResources clientResources = DefaultClientResources.builder()
                                                                             .reconnectDelay(Delay.fullJitter(
                                                                                     Duration.ofSeconds(1),
                                                                                     Duration.ofSeconds(5),
                                                                                     500, TimeUnit.MILLISECONDS))
                                                                             .dnsResolver(new DirContextDnsResolver())
                                                                             .build();

        final ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder()
                                                                              .validateClusterNodeMembership(false)
                                                                              .pingBeforeActivateConnection(true)
                                                                              .suspendReconnectOnProtocolFailure(false)
                                                                              .autoReconnect(true)
                                                                              .topologyRefreshOptions(clusterTopologyRefreshOptions)
                                                                              .socketOptions(SocketOptions.builder()
                                                                                                          .connectTimeout(Duration.ofSeconds(5))
                                                                                                          .keepAlive(true)
                                                                                                          .build())
                                                                              .timeoutOptions(TimeoutOptions.builder()
                                                                                                            .fixedTimeout(Duration.ofSeconds(8))
                                                                                                            .build())
                                                                              .build();

        final GenericObjectPool<StatefulRedisClusterConnection<String, String>> pool =
                ConnectionPoolSupport.createGenericObjectPool(redisClusterClient::connect, new GenericObjectPoolConfig());
        pool.setMaxTotal(15);

        try (StatefulRedisClusterConnection<String, String> connection = pool.borrowObject()) {
            connection.async().eval(...)
         }
```

</details>

#### Expected behavior/code

We expect TPS to be a lot higher, at least 10 times higher 

#### Environment

- Lettuce version(s): lettuce-core-6.0.1.RELEASE
- Redis version: 6.2.6

**Comment by dasdjsakji2o13djsakj** [comment]
Since we use Eval, i also inspected average Eval latency, which is around 190 microseconds. In theory 190 * 400 = 76 milliseconds, so the actual TPS should be a lot higher. But somehow we are experiencing timeouts.
