### ISSUE TITLE
io.netty.channel.epoll.Native.epollWawit hangs forever after network turbulence

### ISSUE THREAD

**Issue by tellmewhattodo** [lettuce-io/lettuce-core#2251]
## Bug Report

io.netty.channel.epoll.Native.epollWawit hangs forever

#### Current Behavior

when our Redis network got broken for a few minutes and then recovered, I found some lettuce event-loop thread hangs like this:

```java
"lettuce-epollEventLoop-7-1" #152 daemon prio=5 os_prio=0 cpu=16731.73ms elapsed=298011.78s tid=0x00007fbe9cc90000 nid=0xbb runnable  [0x00007fbec9dfc000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:114)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:241)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:258)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)
```

#### Expected behavior/code

If there is some way out to let lettuce recover it self automatically 

#### Environment

- Lettuce version(s):5.0.5.RELEASE
- Redis version:4.0

#### Possible Solution

I have no idea.

**Comment by mp911de** [comment]
`epollWait0` is waiting for further activity from the network layer. It's located within netty and nothing we can address from our side.
