### ISSUE TITLE
RedisCommandTimeoutException could lead to memory leak issues.

### ISSUE THREAD

**Issue by mengdalida** [lettuce-io/lettuce-core#2336]
## Bug Report

We found memory leaks in our pre-production environment with Netty, and after investigation we discovered that there were a high number of RedisCommandTimeoutException errors caused by a short execution time configured. This error can lead to increasing "io.netty.buffer.PooledUnsafeDirectByteBuf" over time.

#### Error Version
5.2.2.RELEASE

#### Test Code
```java
// your code here;
t2eRedisTemplate.execute(script, keyList,LocalDateTime.now().toString(), expireSec.toString());
```

#### Test Result
% jmap -histo:live 93663|grep 'io.netty.buffer.PooledUnsafeDirectByteBuf'
  81:           427          37576  io.netty.buffer.PooledUnsafeDirectByteBuf
4635:             1             16  io.netty.buffer.PooledUnsafeDirectByteBuf$1
% jmap -histo:live 93663|grep 'io.netty.buffer.PooledUnsafeDirectByteBuf'
  50:           815          71720  io.netty.buffer.PooledUnsafeDirectByteBuf
4635:             1             16  io.netty.buffer.PooledUnsafeDirectByteBuf$1

<details>
Caused by: io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 millisecond(s)
        at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:126)
        at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy203.evalsha(Unknown Source)
        at org.springframework.data.redis.connection.lettuce.LettuceScriptingCommands.evalSha(LettuceScriptingCommands.java:193)
        ... 63 common frames omitted
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 millisecond(s)
        at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
        at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:167)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted

</details>

**Comment by mp911de** [comment]
Have you tried upgrading to Lettuce 6? With Lettuce 6, we rewrote the connection and associated memory handling so that these issues should no longer occur. Also, a disconnected connection queues commands until reconnect. The command queue requires memory on its own and you should limit the request queue to avoid uncontrolled memory usage.

**Comment by mengdalida** [comment]
> Have you tried upgrading to Lettuce 6? With Lettuce 6, we rewrote the connection and associated memory handling so that these issues should no longer occur. Also, a disconnected connection queues commands until reconnect. The command queue requires memory on its own and you should limit the request queue to avoid uncontrolled memory usage.

I tested with 6.2.1.RELEASE and this problem has been fixed.
