### ISSUE TITLE
RedisCommandTimeoutException in spring-boot-autoconfigure

### ISSUE THREAD

**Issue by lawruban** [lettuce-io/lettuce-core#2340]
## Bug Report

We are using Redis auto configuration for caching and http sessions and seeing intermittent command timeout exception in production env.  We have not written any custom connection pooling for the redis connections and using out of the box spring data redis & lettuce.  We have added the redis.pool size is 50 but as per the spring documentation, Lettuce is not using this configuration and looks like uses the default commons-pool. 

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
rg.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.await(LettuceConnection.java:1077)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.lambda$doInvoke$4(LettuceConnection.java:930)
	at org.springframework.data.redis.connection.lettuce.LettuceInvoker$Synchronizer.invoke(LettuceInvoker.java:673)
	at org.springframework.data.redis.connection.lettuce.LettuceInvoker$DefaultSingleInvocationSpec.getOrElse(LettuceInvoker.java:598)
	at org.springframework.data.redis.connection.lettuce.LettuceInvoker$SingleInvocationSpec.orElse(LettuceInvoker.java:385)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.set(LettuceStringCommands.java:140)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.set(DefaultedRedisConnection.java:321)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.lambda$put$0(DefaultRedisCacheWriter.java:109)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.execute(DefaultRedisCacheWriter.java:308)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.put(DefaultRedisCacheWriter.java:106)
	at org.springframework.data.redis.cache.RedisCache.put(RedisCache.java:168)
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doPut(AbstractCacheInvoker.java:87)
	at org.springframework.cache.interceptor.CacheAspectSupport$CachePutRequest.apply(CacheAspectSupport.java:837)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:430)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
spring:
  session:
    store-type: redis
  redis:
    host: redis-app.redis.cache.windows.net
    password: '
    port: 6380
    ssl: true
    timeout: 5000
    pool:
      max-active: 50
      max-idle: 20
      max-wait: 5000
      min-idle: 20
  cache:
    redis:
      key-prefix: ":prod-220421:"
      use-key-prefix: true
      time-to-live: 30m
```

</details>

#### Environment

- Lettuce version(s): [Default version from spring-boot-starter-data-redis]
- Redis version: 4
- Environment : Azure cloud - standard 26GB primary/secondary configuration
- Spring boot version : 2.7.8

**Comment by mp911de** [comment]
Check out the [reference documentation](https://lettuce.io/core/release/reference/#faq.timeout).
