### ISSUE TITLE
Overriding Cluster partitions not working when upgrading 6.1.10 -> 6.2.x

### ISSUE THREAD

**Issue by Sykomaniac** [lettuce-io/lettuce-core#2357]
## Bug Report

For local unit/integration tests we make use of Test Containers and the Bitnami Redis Cluster image (version 6.2). The tests are configured to override the assignment of slots to a single partition (so we have a redis cluster running in a single docker node) 

```java
final RedisClusterNode clusterNode = new RedisClusterNode();
clusterNode.setUri(RedisURI.create(redisContainer.getHost(), redisContainer.getMappedPort(6379)));
clusterNode.setSlots(IntStream.range(1, 16384).boxed().collect(Collectors.toList()));

final Partitions partitions = new Partitions();
partitions.add(clusterNode);

clusterClient.setPartitions(partitions);
```
The above is only set when running tests. 

For completeness test container setup below.
```java
    private static final GenericContainer<?> redisContainer = new GenericContainer<>(
                    DockerImageName.parse("bitnami/redis-cluster:6.2"))
            .withEnv("ALLOW_EMPTY_PASSWORD", "yes")
            .withEnv("REDIS_CLUSTER_REPLICAS", "0")
            .withEnv("REDIS_NODES", "127.0.0.1 127.0.0.1 127.0.0.1")
            .withEnv("REDIS_CLUSTER_CREATOR", "yes")
            .withEnv("REDIS_CLUSTER_DYNAMIC_IPS", "no")
            .withEnv("REDIS_CLUSTER_ANNOUNCE_IP", "127.0.0.1")
            .withExposedPorts(6379);
```

#### Current Behavior

Upgrading to Lettuce 6.2.X provides the following error:

```
java.util.concurrent.ExecutionException: io.lettuce.core.cluster.PartitionSelectorException: Cannot determine a partition for slot 14612.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)

```

#### Expected behavior/code

That my tests are able to run and execute successfully as they can do with Lettuce 6.1.X

#### Environment

- Lettuce version(s): 6.2.0.RELEASE - 6.2.3.RELEASE 
- Redis version: 6.2

#### Additional context

I've tried to look at the changes in the release of 6.2.0 but can't figure out what changes I need to make to my code to make this work again. Any thoughts or help would be appreciated.

**Comment by Sykomaniac** [comment]
My guess would be this change caused the issue? https://github.com/lettuce-io/lettuce-core/commit/6c8d844a89d349e7db9a7c14da534403bc10a4c3

**Comment by Sykomaniac** [comment]
It was indeed that commit. Setting the following:
```java
clusterNode.setFlags(Set.of(RedisClusterNode.NodeFlag.UPSTREAM));
```
Allowed my test to succeed as before
