### ISSUE TITLE
java.lang.IllegalStateException: A unix domain socket connection requires epoll or kqueue and neither is available

### ISSUE THREAD

**Issue by Jinnrry** [lettuce-io/lettuce-core#2372]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
2023-03-29 19:31:19 "Caused by: java.lang.IllegalStateException: A unix domain socket connection requires epoll or kqueue and neither is available",
2023-03-29 19:31:19 "at io.lettuce.core.internal.LettuceAssert.assertState(LettuceAssert.java:236) ~[?:?]",
2023-03-29 19:31:19 "at io.lettuce.core.resource.Transports$NativeTransports.assertDomainSocketAvailable(Transports.java:124) ~[?:?]",
2023-03-29 19:31:19 "at io.lettuce.core.ConnectionBuilder.configureBootstrap(ConnectionBuilder.java:250) ~[?:?]",
2023-03-29 19:31:19 "at io.lettuce.core.AbstractRedisClient.connectionBuilder(AbstractRedisClient.java:293) ~[?:?]",
2023-03-29 19:31:19 "at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:322) ~[?:?]",
2023-03-29 19:31:19 "at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:287) ~[?:?]",
2023-03-29 19:31:19 "at io.lettuce.core.RedisClient.connect(RedisClient.java:216) ~[?:?]",
2023-03-29 19:31:19 "at io.lettuce.core.RedisClient.connect(RedisClient.java:201) ~[?:?]",
2023-03-29 19:31:19 "at com.xxx.xxx.Main.lambda$new$0(Main.java:32) ~[?:?]",
2023-03-29 19:31:19 "at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]",
2023-03-29 19:31:19 "at com.xiaoju.b2b.eshotel.Main.<init>(Main.java:31) ~[?:?]",
2023-03-29 19:31:19 "at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]",
2023-03-29 19:31:19 "at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]",
2023-03-29 19:31:19 "at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]",
2023-03-29 19:31:19 "at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]",
2023-03-29 19:31:19 "at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]",
2023-03-29 19:31:19 "at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:605) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:556) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.0.jar:7.6.0]",
2023-03-29 19:31:19 "... 6 more"] }
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
        RedisClient client = RedisClient.create("redis-socket:///var/run/redis.sock");

        StatefulRedisConnection<String, String> connection = AccessController.doPrivileged(
                (PrivilegedAction<StatefulRedisConnection<String, String>>) () -> client.connect());

        RedisCommands<String, String> commands = connection.sync();
```

</details>

#### Environment

- Lettuce version(s): [6.2.3.RELEASE]
- Redis version: [7.0.9]
- OS version:[ubuntu 22.04]

#### Additional context

I am developing an ElasticSearch plugin and this query needs to read Redis data in ES. To optimize network performance, I am using the uds method of connection. But now the redis connection code always reports this error.

**Comment by mp911de** [comment]
And what exactly do you not understand from the error message? Socket operations require native netty libraries, see https://github.com/lettuce-io/lettuce-core/wiki/Native-Transports
