### ISSUE TITLE
After restarting the redis cluster of Kubernetes, lettuce still connects to the old IP

### ISSUE THREAD

**Issue by disabilites** [lettuce-io/lettuce-core#2430]
## Bug Report

I tried the solution in a similar issue, but it didn't work

My redis cluster is deployed on Kubernetes, with a total of 6 nodes

When I restart the cluster, lettuce always tries to reconnect to the previous IP

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
2023-06-28 01:55:09.350  INFO 1 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.2.2:6379
2023-06-28 01:55:09.350 [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was /172.20.2.2:6379
2023-06-28 01:55:13.330  INFO 1 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.3.125:6379
2023-06-28 01:55:13.330  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.3.125:6379
2023-06-28 01:55:13.330 [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was /172.20.3.125:6379
2023-06-28 01:55:13.330 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was /172.20.3.125:6379
2023-06-28 01:55:13.332  INFO 1 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.3.125:6379
2023-06-28 01:55:13.332 [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was /172.20.3.125:6379
2023-06-28 01:55:13.334  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.3.125:6379
2023-06-28 01:55:13.334 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was /172.20.3.125:6379
2023-06-28 01:55:13.338  WARN 1 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.3.125:6379]: Connection refused: /172.20.3.125:6379
2023-06-28 01:55:13.338 [lettuce-nioEventLoop-6-1] Cannot reconnect to [172.20.3.125:6379]: Connection refused: /172.20.3.125:6379
2023-06-28 01:55:13.340  WARN 1 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.3.125:6379]: Connection refused: /172.20.3.125:6379
2023-06-28 01:55:13.340 [lettuce-nioEventLoop-6-1] Cannot reconnect to [172.20.3.125:6379]: Connection refused: /172.20.3.125:6379
2023-06-28 01:55:19.538  WARN 1 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.2:6379]: connection timed out: /172.20.2.2:6379
2023-06-28 01:55:19.538 [lettuce-nioEventLoop-6-1] Cannot reconnect to [172.20.2.2:6379]: connection timed out: /172.20.2.2:6379
2023-06-28 01:55:19.630  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.2:6379
2023-06-28 01:55:19.630 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was 172.20.2.2:6379
2023-06-28 01:55:19.744  WARN 1 --- [ioEventLoop-6-1] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [redis-cluster-2.redis-service:6379]: redis-cluster-2.redis-service: Name or service not known
2023-06-28 01:55:19.744 [lettuce-nioEventLoop-6-1] Unable to connect to [redis-cluster-2.redis-service:6379]: redis-cluster-2.redis-service: Name or service not known
2023-06-28 01:55:19.829  WARN 1 --- [ioEventLoop-6-2] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [redis-cluster-3.redis-service:6379]: redis-cluster-3.redis-service: Name or service not known
2023-06-28 01:55:19.829 [lettuce-nioEventLoop-6-2] Unable to connect to [redis-cluster-3.redis-service:6379]: redis-cluster-3.redis-service: Name or service not known
2023-06-28 01:55:19.834  WARN 1 --- [ioEventLoop-6-1] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [redis-cluster-4.redis-service:6379]: redis-cluster-4.redis-service: Name or service not known
2023-06-28 01:55:19.834 [lettuce-nioEventLoop-6-1] Unable to connect to [redis-cluster-4.redis-service:6379]: redis-cluster-4.redis-service: Name or service not known
2023-06-28 01:55:19.835  WARN 1 --- [ioEventLoop-6-2] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [redis-cluster-5.redis-service:6379]: redis-cluster-5.redis-service: Name or service not known
2023-06-28 01:55:19.835 [lettuce-nioEventLoop-6-2] Unable to connect to [redis-cluster-5.redis-service:6379]: redis-cluster-5.redis-service: Name or service not known
2023-06-28 01:55:19.841  WARN 1 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.2:6379]: java.util.concurrent.CancellationException
2023-06-28 01:55:19.841 [lettuce-nioEventLoop-6-1] Cannot reconnect to [172.20.2.2:6379]: java.util.concurrent.CancellationException
2023-06-28 01:55:20.429  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.2.220:6379
2023-06-28 01:55:20.429 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was /172.20.2.220:6379
2023-06-28 01:55:20.430  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.2.220:6379
2023-06-28 01:55:20.430 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was /172.20.2.220:6379
2023-06-28 01:55:20.431  INFO 1 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was /172.20.2.220:6379
2023-06-28 01:55:20.431 [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was /172.20.2.220:6379
2023-06-28 01:55:20.439  INFO 1 --- [ioEventLoop-6-2] i.l.core.protocol.ReconnectionHandler    : Reconnected to 172.20.2.148:6379
2023-06-28 01:55:20.439 [lettuce-nioEventLoop-6-2] Reconnected to 172.20.2.148:6379
2023-06-28 01:55:20.440  WARN 1 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.220:6379]: Connection refused: /172.20.2.220:6379
2023-06-28 01:55:20.440 [lettuce-nioEventLoop-6-1] Cannot reconnect to [172.20.2.220:6379]: Connection refused: /172.20.2.220:6379
2023-06-28 01:55:20.441  WARN 1 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.220:6379]: Connection refused: /172.20.2.220:6379
2023-06-28 01:55:20.441 [lettuce-nioEventLoop-6-1] Cannot reconnect to [172.20.2.220:6379]: Connection refused: /172.20.2.220:6379
2023-06-28 01:55:23.333  WARN 1 --- [ioEventLoop-6-2] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.100:6379]: connection timed out: /172.20.2.100:6379
2023-06-28 01:55:23.333 [lettuce-nioEventLoop-6-2] Cannot reconnect to [172.20.2.100:6379]: connection timed out: /172.20.2.100:6379
2023-06-28 01:55:23.336  WARN 1 --- [ioEventLoop-6-2] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.100:6379]: connection timed out: /172.20.2.100:6379
2023-06-28 01:55:23.336 [lettuce-nioEventLoop-6-2] Cannot reconnect to [172.20.2.100:6379]: connection timed out: /172.20.2.100:6379
2023-06-28 01:55:23.430  INFO 1 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.100:6379
2023-06-28 01:55:23.430  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.100:6379
2023-06-28 01:55:23.430 [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was 172.20.2.100:6379
2023-06-28 01:55:23.430 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was 172.20.2.100:6379
2023-06-28 01:55:23.436  INFO 1 --- [ioEventLoop-6-1] i.l.core.protocol.ReconnectionHandler    : Reconnected to 172.20.2.148:6379
2023-06-28 01:55:23.436 [lettuce-nioEventLoop-6-1] Reconnected to 172.20.2.148:6379
2023-06-28 01:55:23.641  INFO 1 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2023-06-28 01:55:23.641 [AsyncResolver-bootstrap-executor-0] Resolving eureka endpoints via configuration
2023-06-28 01:55:26.930  INFO 1 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.100:6379
2023-06-28 01:55:26.930 [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was 172.20.2.100:6379
2023-06-28 01:55:30.730  INFO 1 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.220:6379
2023-06-28 01:55:30.730  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.220:6379
2023-06-28 01:55:30.730 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was 172.20.2.220:6379
2023-06-28 01:55:30.730 [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was 172.20.2.220:6379
2023-06-28 01:55:33.437  WARN 1 --- [ioEventLoop-6-2] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.101:6379]: connection timed out: /172.20.2.101:6379
2023-06-28 01:55:33.437 [lettuce-nioEventLoop-6-2] Cannot reconnect to [172.20.2.101:6379]: connection timed out: /172.20.2.101:6379
2023-06-28 01:55:33.530  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.101:6379
2023-06-28 01:55:33.530 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was 172.20.2.101:6379
2023-06-28 01:55:33.830  INFO 1 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.101:6379
2023-06-28 01:55:33.830 [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was 172.20.2.101:6379
2023-06-28 01:55:36.932  WARN 1 --- [ioEventLoop-6-2] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.101:6379]: connection timed out: /172.20.2.101:6379
2023-06-28 01:55:36.932 [lettuce-nioEventLoop-6-2] Cannot reconnect to [172.20.2.101:6379]: connection timed out: /172.20.2.101:6379
2023-06-28 01:55:37.029  INFO 1 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.20.2.101:6379
2023-06-28 01:55:37.029 [lettuce-eventExecutorLoop-1-1] Reconnecting, last destination was 172.20.2.101:6379
2023-06-28 01:55:37.108  WARN 1 --- [ioEventLoop-6-2] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.220:6379]: No route to host: /172.20.2.220:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /172.20.2.220:6379
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.NoRouteToHostException: No route to host
        ... 11 common frames omitted
2023-06-28 01:55:37.108 [lettuce-nioEventLoop-6-2] Cannot reconnect to [172.20.2.220:6379]: No route to host: /172.20.2.220:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /172.20.2.220:6379
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.NoRouteToHostException: No route to host
        ... 11 common frames omitted
2023-06-28 01:55:37.223  WARN 1 --- [ioEventLoop-6-1] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.3.125:6379]: No route to host: /172.20.3.125:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /172.20.3.125:6379
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.NoRouteToHostException: No route to host
        ... 11 common frames omitted
2023-06-28 01:55:37.223 [lettuce-nioEventLoop-6-1] Cannot reconnect to [172.20.3.125:6379]: No route to host: /172.20.3.125:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /172.20.3.125:6379
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.NoRouteToHostException: No route to host
        ... 11 common frames omitted
2023-06-28 01:55:38.139  WARN 1 --- [ioEventLoop-6-2] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [redis-cluster-2.redis-service:6379]: redis-cluster-2.redis-service: Name or service not known
2023-06-28 01:55:38.139 [lettuce-nioEventLoop-6-2] Unable to connect to [redis-cluster-2.redis-service:6379]: redis-cluster-2.redis-service: Name or service not known
2023-06-28 01:55:38.141  WARN 1 --- [ioEventLoop-6-1] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [redis-cluster-3.redis-service:6379]: redis-cluster-3.redis-service: Name or service not known
2023-06-28 01:55:38.141 [lettuce-nioEventLoop-6-1] Unable to connect to [redis-cluster-3.redis-service:6379]: redis-cluster-3.redis-service: Name or service not known
2023-06-28 01:55:38.142  WARN 1 --- [ioEventLoop-6-2] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [redis-cluster-4.redis-service:6379]: redis-cluster-4.redis-service: Name or service not known
2023-06-28 01:55:38.142 [lettuce-nioEventLoop-6-2] Unable to connect to [redis-cluster-4.redis-service:6379]: redis-cluster-4.redis-service: Name or service not known
2023-06-28 01:55:40.177  WARN 1 --- [ioEventLoop-6-2] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect to [172.20.2.220:6379]: No route to host: /172.20.2.220:6379
```
</details>

<details>
<summary>Redis Config</summary>

```java
	@Bean
	public LettuceConnectionFactory redisConnectionFactory() {

		RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration(redisProperties.getCluster().getNodes());
		redisClusterConfiguration.setPassword(RedisPassword.of(redisProperties.getPassword()));

		GenericObjectPoolConfig genericObjectPoolConfig = new GenericObjectPoolConfig();
		//支持自适应集群拓扑刷新和静态刷新源
		ClusterTopologyRefreshOptions clusterTopologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
				.enableAllAdaptiveRefreshTriggers()
				.enablePeriodicRefresh()
				.dynamicRefreshSources(false)
				.build();

		ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder()
				.validateClusterNodeMembership(false)
				.topologyRefreshOptions(clusterTopologyRefreshOptions)
				.build();

		LettuceClientConfiguration lettuceClientConfiguration = LettucePoolingClientConfiguration.builder()
				.poolConfig(genericObjectPoolConfig)
				.clientOptions(clusterClientOptions)
				.build();

		return new LettuceConnectionFactory(redisClusterConfiguration, lettuceClientConfiguration);

	}
```

</details>

172.20.2.2、172.20.3.125、172.20.2.220、172.20.2.100、172.20.2.101 is previous IP
redis-cluster-2.redis-service、redis-cluster-3.redis-service、redis-cluster-4.redis-service、redis-cluster-5.redis-service is service name of Kubernetes

#### Expected behavior

Can automatically connect to the restarted redis cluster

#### Environment

- Lettuce version(s): 6.1.8.RELEASE
- Redis version: 6.2.4
- Spingboot version: 2.0.3.RELEASE

**Comment by mp911de** [comment]
`redis-cluster-3.redis-service: Name or service not known` says that the topology refresh cannot resolve the DNS name and therefore the topology refresh cannot obtain the new IP addresses from the cluster.

**Comment by disabilites** [comment]
> `redis-cluster-3.redis-service: Name or service not known` says that the topology refresh cannot resolve the DNS name and therefore the topology refresh cannot obtain the new IP addresses from the cluster.

Is there any solution?

**Comment by mp911de** [comment]
Since Lettuce doesn't control your infrastructure, you will need to solve the issue on your side. I'm not a Kubernetes expert so I cannot tell why the name isn't resolvable. Reducing the DNS Cache TTL might help.

**Comment by disabilites** [comment]
> Since Lettuce doesn't control your infrastructure, you will need to solve the issue on your side. I'm not a Kubernetes expert so I cannot tell why the name isn't resolvable. Reducing the DNS Cache TTL might help.

Ok sir, thanks for your reply

**Comment by coinzz** [comment]
@disabilites was this problem solved with DNS Caching? We had a similar problem that our cluster has new ip-adresses after restart. 
It was reachable with the DNS name, but we had to configure: `spring.data.redis.lettuce.cluster.refresh.adaptive=true`. Is this the correct way to refresh IP-Addresses, or are there any downfalls @mp911de? So far it seems to work.
