### ISSUE TITLE
can not release Connection

### ISSUE THREAD

**Issue by kiddingYang** [lettuce-io/lettuce-core#2460]
## Bug Report

the Connection not be released, cpu too high 

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
at io.lettuce.core.protocol.SharedLock.lockWritersExclusive(SharedLock.java:124)
    at io.lettuce.core.protocol.SharedLock.doExclusive(SharedLock.java:102)
    at io.lettuce.core.protocol.DefaultEndpoint.doExclusive(DefaultEndpoint.java:599)
    at io.lettuce.core.protocol.DefaultEndpoint.cancelBufferedCommands(DefaultEndpoint.java:625)
    at io.lettuce.core.protocol.DefaultEndpoint.close(DefaultEndpoint.java:493)
    at io.lettuce.core.RedisChannelHandler.close(RedisChannelHandler.java:111)
    at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.destroyObject(ConnectionPoolSupport.java:230)
    at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:927)
    at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:590)
    at io.lettuce.core.support.ConnectionPoolSupport$1.returnObject(ConnectionPoolSupport.java:134)
    at io.lettuce.core.support.ConnectionPoolSupport$1.returnObject(ConnectionPoolSupport.java:120)
    at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.release(LettucePoolingConnectionProvider.java:120)
    at org.springframework.data.redis.connection.lettuce.LettuceConnection.close(LettuceConnection.java:433)
    at org.springframework.data.redis.core.RedisConnectionUtils.releaseConnection(RedisConnectionUtils.java:214)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:234)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
    at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
    at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:231)
    at org.springframework.data.redis.core.DefaultBoundHashOperations.entries(DefaultBoundHashOperations.java:172)
    at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:429)
    at org.springframework.session.data.redis.RedisOperationsSessionRepository.findById(RedisOperationsSessionRepository.java:398)
    at org.springframework.session.data.redis.RedisOperationsSessionRepository.findById(RedisOperationsSessionRepository.java:245)
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getRequestedSession(SessionRepositoryFilter.java:364)
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getRequestedSessionId(SessionRepositoryFilter.java:354)
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:237)
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:197)
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryResponseWrapper.onResponseCommitted(SessionRepositoryFilter.java:185)
    at org.springframework.session.web.http.OnCommittedResponseWrapper.doOnResponseCommitted(OnCommittedResponseWrapper.java:227)
    at org.springframework.session.web.http.OnCommittedResponseWrapper.access$000(OnCommittedResponseWrapper.java:38)
    at org.springframework.session.web.http.OnCommittedResponseWrapper$SaveContextServletOutputStream.flush(OnCommittedResponseWrapper.java:494)
    at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.flush(OnCommittedResponseWrapper.java:514)
    at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.flush(OnCommittedResponseWrapper.java:514)

```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
private void lockWritersExclusive() {

        if (exclusiveLockOwner == Thread.currentThread()) {
            writers.decrementAndGet();
            return;
        }

        synchronized (this) {
            for (;;) {

                if (writers.compareAndSet(0, -1)) {
                    exclusiveLockOwner = Thread.currentThread();
                    return;
                }
            }
        }
    }
```

</details>

#### Environment

- Lettuce version(s): 5.04

**Comment by mp911de** [comment]
Lettuce 5 is out of maintenance. Please upgrade to version 6 and recheck if the problem persists.
