### ISSUE TITLE
Lettuce does not establish a new connection, when a master node of redis goes down

### ISSUE THREAD

**Issue by sakurafly123** [lettuce-io/lettuce-core#2473]
#### Current Behavior
During the operation of the redis cluster, manually stop a master node, lettuce is not connected to the new master node, and write data successfully

<details>
<summary>Stack trace</summary>

```java
lettuce-nioEventLoop-4-3" #18 daemon prio=5 os_prio=0 tid=0x0000019d319d1800 nid=0x3208 waiting on condition [0x0000009b588fd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000751e28630> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1709)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3334)
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1788)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at io.lettuce.core.cluster.topology.RefreshFutures.awaitAll(RefreshFutures.java:54)
	at io.lettuce.core.cluster.topology.AsyncConnections.optionalGet(AsyncConnections.java:118)
	at io.lettuce.core.cluster.topology.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:93)
	at io.lettuce.core.cluster.RedisClusterClient.doLoadPartitions(RedisClusterClient.java:865)
	at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:845)
	at io.lettuce.core.cluster.RedisClusterClient.reloadPartitions(RedisClusterClient.java:784)
	at RedisAsyncFunction.lambda$execute2$1(RedisAsyncFunction.java:103)
	at RedisAsyncFunction$$Lambda$119/992086987.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at io.lettuce.core.protocol.AsyncCommand.doCompleteExceptionally(AsyncCommand.java:139)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:59)
	at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:63)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:654)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:614)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"lettuce-nioEventLoop-4-2" #17 daemon prio=5 os_prio=0 tid=0x0000019d319cb800 nid=0x5ee8 waiting on condition [0x0000009b587fd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000751e25730> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1709)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3334)
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1788)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at io.lettuce.core.cluster.topology.RefreshFutures.awaitAll(RefreshFutures.java:54)
	at io.lettuce.core.cluster.topology.AsyncConnections.optionalGet(AsyncConnections.java:118)
	at io.lettuce.core.cluster.topology.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:93)
	at io.lettuce.core.cluster.RedisClusterClient.doLoadPartitions(RedisClusterClient.java:865)
	at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:845)
	at io.lettuce.core.cluster.RedisClusterClient.reloadPartitions(RedisClusterClient.java:784)
	at RedisAsyncFunction.lambda$execute2$1(RedisAsyncFunction.java:103)
	at RedisAsyncFunction$$Lambda$119/992086987.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at io.lettuce.core.protocol.AsyncCommand.doCompleteExceptionally(AsyncCommand.java:139)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:59)
	at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:63)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:654)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:614)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"lettuce-nioEventLoop-4-1" #16 daemon prio=5 os_prio=0 tid=0x0000019d319ce800 nid=0x1364 waiting on condition [0x0000009b585fd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000751e21700> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1709)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3334)
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1788)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at io.lettuce.core.cluster.topology.RefreshFutures.awaitAll(RefreshFutures.java:54)
	at io.lettuce.core.cluster.topology.AsyncConnections.optionalGet(AsyncConnections.java:118)
	at io.lettuce.core.cluster.topology.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:93)
	at io.lettuce.core.cluster.RedisClusterClient.doLoadPartitions(RedisClusterClient.java:865)
	at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:845)
	at io.lettuce.core.cluster.RedisClusterClient.reloadPartitions(RedisClusterClient.java:784)
	at RedisAsyncFunction.lambda$execute2$1(RedisAsyncFunction.java:103)
	at RedisAsyncFunction$$Lambda$119/992086987.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at io.lettuce.core.protocol.AsyncCommand.doCompleteExceptionally(AsyncCommand.java:139)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:59)
	at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:63)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:654)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:614)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here; 
public class RedisAsyncFunction {

    public static final Logger logger = LoggerFactory.getLogger(RedisAsyncFunction.class);

    private final String address;

    private final int port;

    private final int maxRetryTimes =5;

    private RedisClusterClient clusterClient;


    private StatefulRedisClusterConnection<String, String> connection;

    private RedisAdvancedClusterAsyncCommands<String, String> commands;


    ScheduledThreadPoolExecutor scheduledThreadPoolExecutor = new ScheduledThreadPoolExecutor(1);

    public RedisAsyncFunction(String address, int port) {
        this.address = address;
        this.port = port;
        connectRedis();
    }

    private void connectRedis() {
        List<RedisURI> nodeList = Collections.singletonList(RedisURI
                .builder()
                .withHost(address)
                .withPort(port)
                .build());

        this.clusterClient = RedisClusterClient.create(nodeList);

        ClusterTopologyRefreshOptions clusterTopologgeryRefreshOptions
                = ClusterTopologyRefreshOptions.builder()
                .refreshPeriod(Duration.ofSeconds(10)) 

                .enableAllAdaptiveRefreshTriggers()
                .build();

        this.clusterClient.setOptions(ClusterClientOptions.builder()
                .topologyRefreshOptions(clusterTopologgeryRefreshOptions)
                .pingBeforeActivateConnection(true)
                .validateClusterNodeMembership(false)
                .build());
        this.connection = this.clusterClient.connect();
        this.connection.setTimeout(Duration.ofSeconds(2));
        this.commands = this.connection.async();
    }

    void execute(){
         for (int i = 0; i < 10000000; i++) {
            String key = "test"+i;
            String value = "value"+i;
            RedisFuture<String> responseFuture = commands.set(key, value, SetArgs.Builder.px(600000));
            responseFuture.whenComplete(  (result, throwable) -> {
               if (throwable!=null){
                   // this.clusterClient.reloadPartitions();
                   logger.error("error={}",throwable.getMessage());
               }else {
                   logger.info("success={}",result);
               }
            });
        }
    }

    void execute2(){
        
        for (int i = 0; i < 10000000; i++) {
            String key = "test"+i;
            String value = "value"+i;
            RedisFuture<String> responseFuture = commands.set(key, value, SetArgs.Builder.px(600000));
            responseFuture.whenComplete(  (result, throwable) -> {
               if (throwable!=null){
                   this.clusterClient.reloadPartitions();
                   logger.error("error={}",throwable.getMessage());
               }else {
                   logger.info("success={}",result);
               }
            });
        }
    }

 
    public String getAddress() {
        return address;
    }

    public int getPort() {
        return port;
    }

    public int getMaxRetryTimes() {
        return maxRetryTimes;
    }

    public RedisClusterClient getClusterClient() {
        return clusterClient;
    }

    public void setClusterClient(RedisClusterClient clusterClient) {
        this.clusterClient = clusterClient;
    }



    public void close() {
        logger.info("start close ...");
        if (null != connection) {
            try {
                connection.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        if (clusterClient != null) {
            clusterClient.shutdown();
        }
        logger.info("end close.");
    }
}

LettuceTest.java
public class LettuceTest {
    public static final Logger logger = LoggerFactory.getLogger(LettuceTest.class);
    private static String  address =  "127.0.0.1";
    private static int port = 6379;

    public static void main(String[] args) {
        RedisAsyncFunction redisAsyncFunction = new RedisAsyncFunction(address, port);
        redisAsyncFunction.execute2();


}

```

</details>

#### Environment

- Lettuce version(s): 
    <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>5.3.0.RELEASE</version>
        </dependency>
- Redis version: 
   redis-cluster   5.3.0

#### Possible Solution

When I fail this.clusterClient.reloadPartitions() is not called;

**Comment by mp911de** [comment]
If you block the event loop through `RedisAsyncFunction`, then threads are blocked and can no longer react to network events. Please either use the Async API or offload your work onto a dedicated thread pool to not block event loop threads.

**Comment by sakurafly123** [comment]
t's not that I'm blocking the network thread, it's that when I fail, I call the function reloadPartition(), which blocks itself when reconnecting the connection
