### ISSUE TITLE
RedisCommandTimeoutException 

### ISSUE THREAD

**Issue by flyletc** [lettuce-io/lettuce-core#2495]
#### Current Behavior
Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
<details>

      Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
      org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
              at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
              Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below:
      Error has been observed at the following site(s):
              *__checkpoint ⇢ springfox.boot.starter.autoconfigure.SwaggerUiWebFluxConfiguration$CustomWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.ui.LoginPageGeneratingWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
              *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
              *__checkpoint ⇢ HTTP POST "/system/api/System/GetPermission" [ExceptionHandlingWebHandler]
      Original Stack Trace:
                      at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
                      at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
                      at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
                      at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
                      at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:272)
                      at org.springframework.data.redis.connection.lettuce.LettuceConnection.await(LettuceConnection.java:1063)
                      at org.springframework.data.redis.connection.lettuce.LettuceConnection.lambda$doInvoke$4(LettuceConnection.java:920)
                      at org.springframework.data.redis.connection.lettuce.LettuceInvoker$Synchronizer.invoke(LettuceInvoker.java:665)
                      at org.springframework.data.redis.connection.lettuce.LettuceInvoker.just(LettuceInvoker.java:94)
                      at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:55)
                      at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:278)
                      at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:58)
                      at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:61)
                      at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:223)
                      at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190)
                      at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
                      at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:54)
                      at cn.csdas.gateway.service.RedisService.getRealPermission(RedisService.java:98)
                      at cn.csdas.gateway.filter.global.PermissionFilter.filter(PermissionFilter.java:79)
                      at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:137)
                      at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44)
                      at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:117)
                      at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
                      at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                      at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
                      at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
                      at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
                      at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:165)
                      at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
                      at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredComplete(FluxUsingWhen.java:392)
                      at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527)
                      at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
                      at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:824)
                      at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
                      at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
                      at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)
                      at reactor.core.publisher.FluxArray$ArraySubscription.slowPath(FluxArray.java:138)
                      at reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:100)
                      at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
                      at reactor.core.publisher.FluxMerge.subscribe(FluxMerge.java:70)
                      at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                      at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:384)
                      at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
                      at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
                      at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:368)
                      at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:276)
                      at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
                      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
                      at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onComplete(RedisPublisher.java:896)
                      at io.lettuce.core.RedisPublisher$State.onAllDataRead(RedisPublisher.java:698)
                      at io.lettuce.core.RedisPublisher$State$3.read(RedisPublisher.java:608)
                      at io.lettuce.core.RedisPublisher$State$3.onDataAvailable(RedisPublisher.java:565)
                      at io.lettuce.core.RedisPublisher$RedisSubscription.onDataAvailable(RedisPublisher.java:326)
                      at io.lettuce.core.RedisPublisher$RedisSubscription.onAllDataRead(RedisPublisher.java:341)
                      at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:778)
                      at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)
                      at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
                      at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:65)
                      at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
                      at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746)
                      at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681)
                      at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
                      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                      at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
                      at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
                      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
                      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
                      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                      at java.lang.Thread.run(Thread.java:750)

</details>

#### Input Code

<details>

            List<RedisNodeInfo> redisNodeInfos = redisAttributeConfig.getRedisNoes();
            Set<RedisNode> redisNodes = redisNodeInfos.stream().map(x ->{
                RedisNode redisNode = new RedisNode(x.getHost(),x.getPort());
                return redisNode;
            }).collect(Collectors.toSet());
            RedisClusterConfiguration clusterConfig = new RedisClusterConfiguration();
            clusterConfig.setClusterNodes(redisNodes);
            clusterConfig.setPassword(redisAttributeConfig.getPassword());
            clusterConfig.setMaxRedirects(6);

            ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                    .enableAllAdaptiveRefreshTriggers()
                    .adaptiveRefreshTriggersTimeout(Duration.ofSeconds(25))
                    .enablePeriodicRefresh(Duration.ofSeconds(20))
                    .build();

            SocketOptions socketOptions = SocketOptions.builder().keepAlive(true).connectTimeout(Duration.ofSeconds(60)).build();

            ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder()
                    .timeoutOptions(TimeoutOptions.enabled(Duration.ofSeconds(20)))
                    .topologyRefreshOptions(topologyRefreshOptions)
                    .autoReconnect(true)
                    .cancelCommandsOnReconnectFailure(true)
                    .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                    .pingBeforeActivateConnection(true)
                    .socketOptions(socketOptions)
                    .build();

            LettucePoolingClientConfiguration  lettucePoolingClientConfiguration = LettucePoolingClientConfiguration .builder()
                    .poolConfig(poolConfig)
                    .clientOptions(clusterClientOptions)
                    .build();
            factory = new LettuceConnectionFactory(clusterConfig,lettucePoolingClientConfiguration);
           factory.setShareNativeConnection (false);
           factory.afterPropertiesSet();

</details>

#### Expected behavior/code

I hope not to timeout

#### Environment

- Lettuce version(s): [e.g. 6.1.8.RELEASE]
- springBoot version(s)：2.6.8
- Redis version: 6.12 (cluster：Three Masters and Three Slaves)

#### redis.conf

      bind 172.168.50.107
      port 6371
      requirepass 1234
      masterauth 1234
      protected-mode no
      daemonize no
      appendonly yes
      cluster-enabled yes
      cluster-config-file nodes.conf
      cluster-node-timeout 15000
      timeout 0
      tcp-keepalive 10

**Comment by mp911de** [comment]
See https://lettuce.io/core/release/reference/index.html#faq.timeout
