### ISSUE TITLE
'Hello 3 auth ? ?'  ERR unknown command 

### ISSUE THREAD

**Issue by echojun186** [lettuce-io/lettuce-core#2516]
#### Current Behavior

When using Lettuce, the following error message may appear. Using redis-cli to execute `hello 3 auth username password` is normal. What is the reason for this and how can it be resolved? This problem is more common than when it appears

<details>
<summary>Stack trace</summary>
io.lettuce.core.RedisCommandExecutionException: ERR unknown command 
at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147) 
at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116) 
at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) 
at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111) 
at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63) 
at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746) 
at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681) 
at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) 
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
at io.netty.channel.DefaultChannelPipeline HeadContext.channelRead(DefaultChannelPipeline.java:1410) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) 
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) 
at io.netty.channel.epoll.AbstractEpollStreamChannel EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) 
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) 
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) 
at io.netty.util.concurrent.SingleThreadEventExecutor 4.run(SingleThreadEventExecutor.java:997) 
at io.netty.util.internal.ThreadExecutor...

</details>

#### Input Code

<details>
<summary>Input Code</summary>

HELLO 3 AUTH ? ?

</details>

#### Environment
- spring-boot-starter-data-redis version:[3.0.10]
- Lettuce version(s): [6.2.6.RELEASE]
- Redis version: [6.0]

**Comment by mp911de** [comment]
Can you reliably reproduce the issue?

**Comment by echojun186** [comment]
Yes, the local environment can stably replicate. There is no error reported in the application log, OpenTelemetry's trace reported an error.

**Comment by echojun186** [comment]
> Can you reliably reproduce the issue?

Yes, the local environment can stably replicate. There is no error reported in the application log, OpenTelemetry's trace reported an error.

**Comment by mp911de** [comment]
Can you record a wireshark trace to find out about the differences upon Lettuce connect vs. the `redis-cli` behavior?

**Comment by echojun186** [comment]
> Referenc

The cause of this problem has been found. We are using Alibaba Cloud's cloud native Redis, which does not support the hello command in its proxy mode. Thank you.

**Comment by echojun186** [comment]
Resolved
