### ISSUE TITLE
Netty IllegalReferenceCountException, this exception leads to redis command disorder

### ISSUE THREAD

**Issue by throws-exceptions** [lettuce-io/lettuce-core#2542]
#### Current Behavior

We found that at some point a netty error was thrown, but the error was occasional on the line and not reproducible in the test environment, but the error caused the redis command to mess up. The reason for the error is that it is thrown at the end of the channelRead. But the previous command had already read the stack, thrown the error, and then caught the exception and pulled the stack again, causing all the subsequent commands to have the value of the read and fetched error

<details>
<summary>Stack trace</summary>

```java
level: WARN

line: 220

logger: CommandHandler

msg: null Unexpected exception during request: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[netty-buffer-4.1.79.Final.jar:4.1.79.Final]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:601) ~[lettuce-core-6.1.9.RELEASE.jar:6.1.9.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.79.Final.jar:4.1.79.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_261]

thread: lettuce-nioEventLoop-15-5
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

Simple commands like get/set normally using reactive commands

</details>

#### Environment

Lettuce version(s): 6.1.9
Redis version: 4.0.8 (Sentinel) 1M2S

#### Possible Solution

We can now only catch on the finally side by overriding the channelRead method, but that's only for immediate use

**Comment by mp911de** [comment]
Thanks for letting us know. This is pretty weird because the code block in which we call `release` checks for `refCnt != 0` already. That's similar to checking for `null` and then running into a `NullPointerException`.

**Comment by throws-exceptions** [comment]
I noticed that the nonVolatileRawCnt may not correspond to the refCnt obtained in channelRead in some cases.
```java
private int nonVolatileRawCnt(T instance) {
        // TODO: Once we compile against later versions of Java we can replace the Unsafe usage here by varhandles.
        final long offset = unsafeOffset();
        return offset != -1 ? PlatformDependent.getInt(instance, offset) : updater().get(instance);
    }
```

The above code is the obtained refcnt to be released when release,However, the channelRead judgment is performed using the following code
```java
public final int refCnt(T instance) {
        return realRefCnt(updater().get(instance));
    }
```
Let's see if it has anything to do with this? We are not reproducing this problem at the moment



> Thanks for letting us know. This is pretty weird because the code block in which we call `release` checks for `refCnt != 0` already. That's similar to checking for `null` and then running into a `NullPointerException`.

**Comment by mp911de** [comment]
Generally, buffers should be accessed single-threaded. Also, the netty execution model assigns a single event loop thread per channel. I am under the impression that there is more concurrent access going on and Lettuce is the place where race conditions pop up. Not because our code is wrong, just because of the timing.

**Comment by throws-exceptions** [comment]
> Generally, buffers should be accessed single-threaded. Also, the netty execution model assigns a single event loop thread per channel. I am under the impression that there is more concurrent access going on and Lettuce is the place where race conditions pop up. Not because our code is wrong, just because of the timing.

If this race occurs, all subsequent instructions will be derailed. Is there a better solution to this? For now, I'm using code coverage to just catch the exception

**Comment by qinchunabng** [comment]
We encountered the same problem. But we use methods provided by spring-boot. And we have set a pool setting. Does lettuce pool related to this problem. In this situation, how to solve the problem?

**Comment by NicoSchmidt1703** [comment]
I see the same issue on my instances. 
Yesterday 4 instances of my spring-boot service were active. Only one had this error. 

Here is an example of my traffic. At the same time where I this errors occur in my log the cpu spikes to near than 100%.
![image](https://github.com/lettuce-io/lettuce-core/assets/56245904/a64682a7-2e42-4c1b-a2e5-84b8de512daa)

<details><summary>Stacktrace</summary>
<p>
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:294)		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)		at java.base/java.lang.Thread.run(Thread.java:1583)Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)	at io.netty.buffer.AbstractByteBuf.checkNewCapacity(AbstractByteBuf.java:1432)	at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:105)	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:305)	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1103)	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:105)	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)	at java.base/java.lang.Thread.run(Thread.java:1583)


</p>
</details> 

AND 

<details><summary>Stacktrace</summary>
<p>

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
		at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
		at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
		at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:599)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
		at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)
		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:1583)

</p>
</details> 


There is also an warning a few ms later:
<details><summary>Stacktrace</summary>
<p>


io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:906)	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:822)	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:803)	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:941)	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:937)	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:957)	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1263)	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)	at java.base/java.lang.Thread.run(Thread.java:1583)

</p>
</details> 

Netty is 4.1.107.Final (newest)
reactor netty 1.1.16 (also newest)
lettuce-core 6.3.1.RELEASE

running on spring boot 3.2.3, kotlin (coroutines-reactor) 1.9.23 on corretto 21.0.1.12.1

**Comment by mp911de** [comment]
Do you see any preceeding errors? `CommandHandler.channelRead(…)` is guarded multiple times against `IllegalReferenceCountException` by checking `input.refCnt() == 0`.

It looks as if a concurrent process would operate on the same byte buffer.

**Comment by tishun** [comment]
@mp911de could this be the underlying issue https://github.com/netty/netty/issues/12777
Seems unrelated to the Lettuce driver?
