### ISSUE TITLE
connect(..) failed: Can't assign requested address

### ISSUE THREAD

**Issue by Ethan-1994** [lettuce-io/lettuce-core#2543]
Using pipeline operations without using connection pooling, as the thread unsafe create method can create multiple connections and even report errors during high concurrency

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
 connect(..) failed: Can't assign requested address
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.netty.channel.unix.Socket.connect(Socket.java:312)
	at io.netty.channel.kqueue.AbstractKQueueChannel.doConnect0(AbstractKQueueChannel.java:719)
	at io.netty.channel.kqueue.KQueueSocketChannel.doConnect0(KQueueSocketChannel.java:96)
	at io.netty.channel.kqueue.AbstractKQueueChannel.doConnect(AbstractKQueueChannel.java:704)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.connect(AbstractKQueueChannel.java:550)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
for (int i = 0; i < 50; i++) {
            new Thread(() -> {
                for (int j = 0; j < 2000; j++) {
                    transformersRedisClient.zRemoveByPipeline("keys", values);
                }
                System.out.println("222222222222222222222");
            },"t"+i).start();
        }
```

</details>

#### Expected behavior/code

One connect should always be maintained

#### Environment

- Lettuce version(s): 6.1.10.RELEASE
- Redis version: [e.g. 4.0.9]](spring-data-redis-core:0.0.8-RELEASE)

#### Additional context
make method doGetAsyncDedicatedConnection() in LettuceConnection thread safe
```java
private StatefulConnection<byte[], byte[]> getOrCreateDedicatedConnection() {

		if (asyncDedicatedConn == null) {
			asyncDedicatedConn = doGetAsyncDedicatedConnection();
		}

		return asyncDedicatedConn;
	}
```

**Comment by mp911de** [comment]
`Can't assign requested address` is an infrastructure failure where you run out of local ports to open connections. This can happen when you quickly open and close connections. Either use a long-lived connection or a connection pool.
