### ISSUE TITLE
Command timed while establishing the connection

### ISSUE THREAD

**Issue by arielzach** [lettuce-io/lettuce-core#2544]
#### Current Behavior

When the client attempts to connect to the cache, it times out while executing a command, which seems to be something internally triggered by the library. With this error, the application is not starting, and as a result, no commands are being executed. The only thing visible is the attached stack trace.

There are no errors in the cache, and at the time when we experienced these issues, there were other instances connected to the cache.

Do you have any idea what is causing this error?

<details>
<summary>Stack trace</summary>

```java

io.lettuce.core.RedisConnectionException: Unable to establish a connection to Redis Cluster
	at io.lettuce.core.cluster.RedisClusterClient.lambda$assertInitialPartitions$26(RedisClusterClient.java:926)
	at io.lettuce.core.cluster.RedisClusterClient.get(RedisClusterClient.java:945)
	at io.lettuce.core.cluster.RedisClusterClient.assertInitialPartitions(RedisClusterClient.java:925)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:401)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:378)
Caused by: io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh$CannotRetrieveClusterPartitions: Cannot retrieve cluster partitions from [rediss://clustercfg.xxx.pxoqnz.use1.cache.amazonaws.com:6379]

[rediss://clustercfg.xxx.cache.amazonaws.com:6379]: Command timed out after 50 millisecond(s)
Suppressed: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 50 millisecond(s)
at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:59)
at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:176)
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
    RedisURI redisUri = RedisURI.Builder.redis(host).withPort(conf.getPort()).build();

    redisUri.setSsl(conf.getSslEnabled());
    if (conf.getAuthEnabled()) {
      RedisCredentialsProvider credentialsProvider =
          new StaticCredentialsProvider(conf.getUser(), conf.getPassword().toCharArray());
      redisUri.setCredentialsProvider(credentialsProvider);
    }

    DefaultClientResources clientResources =
        DefaultClientResources.builder()
            .reconnectDelay(
                Delay.fullJitter(
                    Duration.ofMillis(100), // minimum 100 millisecond delay
                    Duration.ofSeconds(1), // maximum 1 second delay
                    100,
                    TimeUnit.MILLISECONDS)) // 100 millisecond base
            .dnsResolver(new DirContextDnsResolver()) // Does not cache DNS lookups
            .build();

    ClusterTopologyRefreshOptions topologyRefreshOptions =
        ClusterTopologyRefreshOptions.builder()
            .enableAllAdaptiveRefreshTriggers()
            .adaptiveRefreshTriggersTimeout(
                Duration.ofSeconds(Constants.CACHE_CLIENT_ADAPTIVE_REFRESH_TIMEOUT_SECONDS))
            .dynamicRefreshSources(true)
            .closeStaleConnections(true)
            .build();

    Predicate<RedisClusterNode> connectedNodes =
        redisClusterNode -> {
          return redisClusterNode.getFlags().stream().noneMatch(FAILURE_NODE_FLAGS::contains);
        };

    RedisClusterClient redisClient = RedisClusterClient.create(clientResources, redisUri);
    redisClient.setOptions(
        ClusterClientOptions.builder()
            .nodeFilter(connectedNodes)
            .socketOptions(
                SocketOptions.builder()
                    .connectTimeout(Duration.ofMillis(conf.getConnectTimeout()))
                    .build())
            .timeoutOptions(
                TimeoutOptions.builder().fixedTimeout(Duration.ofMillis(conf.getTimeout())).build())
            .autoReconnect(true)
            .validateClusterNodeMembership(true)
            .pingBeforeActivateConnection(true)
            .topologyRefreshOptions(topologyRefreshOptions)
            .build());

    StatefulRedisClusterConnection<String, String> connection = redisClient.connect();
    connection.setReadFrom(ReadFrom.MASTER_PREFERRED);
    return connection;
```

</details>

#### Expected behavior/code

Perhaps, if an error occurs during the client's bootstrap, you could retry.

#### Environment

- Lettuce version(s): 6.2.4.RELEASE
- Redis version: 7.0.7

**Comment by arielzach** [comment]
The problem is that the internal commands: CLUSTER, INFO, HELLO, CLIENT are being executed with the timeout (in our case, 50ms) defined for commands. We will use timeoutSource in the config.

```java
    RedisClusterClient redisClient = RedisClusterClient.create(clientResources, redisUri);
    redisClient.setOptions(
        ClusterClientOptions.builder()
            .nodeFilter(connectedNodes)
            .socketOptions(
                SocketOptions.builder()
                    .connectTimeout(Duration.ofMillis(conf.getConnectTimeout()))
                    .build())
            .timeoutOptions(
                TimeoutOptions.builder()
                    .timeoutSource(
                        new TimeoutOptions.TimeoutSource() {
                          @Override
                          public long getTimeout(RedisCommand<?, ?, ?> command) {
                            if ((command.getType() == CommandType.CLUSTER)
                                || (command.getType() == CommandType.INFO)
                                || (command.getType() == CommandType.HELLO)
                                || (command.getType() == CommandType.CLIENT)) {
                              return Duration.ofMillis(1000).toNanos();
                            } else {
                              return Duration.ofMillis(50).toNanos();
                            }
                          }
                        })
                    .build())
            .autoReconnect(true)
            .validateClusterNodeMembership(true)
            .pingBeforeActivateConnection(true)
            .topologyRefreshOptions(topologyRefreshOptions)
            .build());
```
