### ISSUE TITLE
Do Scan In Redis Cluster ( while one of the master nodes failed ), and I got an RedisConnectionException

### ISSUE THREAD

**Issue by OceanFot** [lettuce-io/lettuce-core#2616]
# My problem
I got a Redis Cluster with 6 nodes ( 3 masters and 3 slaves ). 
After I stopped one of the master nodes, this Redis has 4 master nodes ( one of them has "fail" tag ) and 2 slaves.

Then I use "scan" to search the cluster, I got a RedisConnectionException ( obviously because of the failed master nodes ).

How should I deal with this situation? Should I add extra args when I use "scan"?  
Thanks for your apply.

## Redis Cluster info
![image](https://github.com/lettuce-io/lettuce-core/assets/28134206/21c84e6e-2eb9-4e81-bc59-524064361e38)

## environment and dependencies
jdk: 1.8
Redis version: 5.0.0

```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <version>2.4.13</version>
        </dependency>
        <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>6.3.1.RELEASE</version>
        </dependency>
```

## My code 
```java
private static void testRedisInLettuce(LettuceConnectionFactory factory) {
    RedisClusterConnection conn = factory.getClusterConnection();
    Cursor<byte[]> scan = null;
    try {
        scan = conn.scan(ScanOptions.scanOptions().match("*sea*").count(100).build());
        log.info("init - CursorId = {}, position = {}", scan.getCursorId(), scan.getPosition());
        while (scan.hasNext()) {
            log.info("CursorId = {}, position = {}, key = {}", scan.getCursorId(), scan.getPosition(), new String(scan.next()));
        }
    } catch (Exception e) {
        log.error("exception: ", e);
        if (null != scan && !scan.isClosed()) {
            try {
                scan.close();
            } catch (IOException ioEx) {
                log.error("scan.close error: ", ioEx);
            }
        }
    }
}
```

**Comment by OceanFot** [comment]
# My Exception
```text
io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.3.233:7001
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.cluster.PooledClusterConnectionProvider.getConnection(PooledClusterConnectionProvider.java:466)
	at io.lettuce.core.cluster.PooledClusterConnectionProvider.getConnection(PooledClusterConnectionProvider.java:409)
	at io.lettuce.core.cluster.StatefulRedisClusterConnectionImpl.getConnection(StatefulRedisClusterConnectionImpl.java:168)
	at io.lettuce.core.cluster.api.StatefulRedisClusterConnection.getConnection(StatefulRedisClusterConnection.java:86)
	at io.lettuce.core.cluster.RedisAdvancedClusterAsyncCommandsImpl.clusterScan(RedisAdvancedClusterAsyncCommandsImpl.java:687)
	at io.lettuce.core.cluster.RedisAdvancedClusterAsyncCommandsImpl.clusterScan(RedisAdvancedClusterAsyncCommandsImpl.java:618)
	at io.lettuce.core.cluster.RedisAdvancedClusterAsyncCommandsImpl.scan(RedisAdvancedClusterAsyncCommandsImpl.java:581)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:122)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy6.scan(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands$1.doScan(LettuceKeyCommands.java:266)
	at org.springframework.data.redis.connection.lettuce.LettuceScanCursor.scanAndProcessState(LettuceScanCursor.java:81)
	at org.springframework.data.redis.connection.lettuce.LettuceScanCursor.doScan(LettuceScanCursor.java:62)
	at org.springframework.data.redis.core.ScanCursor.scan(ScanCursor.java:88)
	at org.springframework.data.redis.core.ScanCursor.hasNext(ScanCursor.java:182)
	at com.di.ctc.test.SimpleTest.testRedisInLettuce(SimpleTest.java:245)
	at com.di.ctc.test.SimpleTest.main(SimpleTest.java:72)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.3.233:7001
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.cluster.PooledClusterConnectionProvider.lambda$getConnectionAsync$6(PooledClusterConnectionProvider.java:433)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$6(AbstractRedisClient.java:454)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.3.233:7001
	at io.lettuce.core.internal.Exceptions.bubble(Exceptions.java:83)
	... 23 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.3.233:7001
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mp911de** [comment]
`Connection refused` is an infrastructure problem where either a firewall rejects the connection or the server isn't running. Neither the driver nor Spring Data can do something about it.

**Comment by OceanFot** [comment]
> `Connection refused` is an infrastructure problem where either a firewall rejects the connection or the server isn't running. Neither the driver nor Spring Data can do something about it.

I already know the node is failed, I mean should I or lettuce filter out the failed nodes before exec scan command?

**Comment by OceanFot** [comment]
> > `Connection refused` is an infrastructure problem where either a firewall rejects the connection or the server isn't running. Neither the driver nor Spring Data can do something about it.
> 
> I already know the node is failed, I mean should I or lettuce filter out the failed nodes before exec scan command?

Sorry that maybe I didn't make myself clear...  I mean shouldn't I or spring or lettuce filter out the failed node here?  
io.lettuce.core.cluster.ClusterScanSupport  -- line 181
![image](https://github.com/lettuce-io/lettuce-core/assets/28134206/7ae69873-efb5-4c0c-8ccf-41b74c1fb6e5)

**Comment by OceanFot** [comment]
The Redis is still working normally and all slots are assigned, for it has 3 active master nodes.
![image](https://github.com/lettuce-io/lettuce-core/assets/28134206/6665832a-7e17-43da-99b7-5256f22998bf)

**Comment by mp911de** [comment]
You can configure a `nodeFilter` at `ClusterClientOptions` to filter failed nodes. Lettuce uses `CLUSTER NODES` to determine the flags.

**Comment by OceanFot** [comment]
> You can configure a `nodeFilter` at `ClusterClientOptions` to filter failed nodes. Lettuce uses `CLUSTER NODES` to determine the flags.

I got it! Thanks a lot!

**Comment by zhaokaiping-github** [comment]
> nodeFilter

How to fix it？

**Comment by OceanFot** [comment]
> > nodeFilter
> 
> How to fix it？

```java
        // filter out failed Redis node(s) 
        io.lettuce.core.cluster.ClusterClientOptions clusterClientOptions = ClusterClientOptions.builder()
                .nodeFilter(node -> !node.getFlags().contains(io.lettuce.core.cluster.models.partitions.RedisClusterNode.NodeFlag.FAIL))
                .build();
        LettuceClientConfiguration clientConfig = LettucePoolingClientConfiguration.builder()
                .clientOptions(clusterClientOptions)
                .build();
        LettuceConnectionFactory lettuce = new LettuceConnectionFactory(clusterConf, clientConfig);
        lettuce.afterPropertiesSet();

```
