### ISSUE TITLE
com.lambdaworks.redis.RedisException: java.io.IOException: Connection reset by peer when execute handler in thread Thread

### ISSUE THREAD

**Issue by christ258** [lettuce-io/lettuce-core#496]
hi,i used 4.2.2.Final,When connecting two redisServer in a JVM, would sometimes throw an exception，like this

```
com.lambdaworks.redis.RedisException: java.io.IOException: Connection reset by peer when execute handler in thread Thread[taskExecutorPreReg-203,5,main], printStackTrace com.lambdaworks.redis.RedisException: java.io.IOException: Connection reset by peer
        at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:109)
        at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:77)
        at com.lambdaworks.redis.cluster.StatefulRedisClusterConnectionImpl$ClusterFutureSyncInvocationHandler.handleInvocation(StatefulRedisClusterConnectionImpl.java:330)
        at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:54)
        at com.sun.proxy.$Proxy26.smembers(Unknown Source)
```

I see RedisException extends RuntimeException，And when the set and get no exception is thrown，How be to return a responsibility excuse me?
My setting is

```
<bean` id="redisCluster1" class="com.lambdaworks.redis.support.RedisClusterClientFactoryBean">
        <property name="uri" value="redis://${redis.cluster.host1}:${redis.cluster.port1}"/>
  </bean>
<bean id="redisCluster2" class="com.lambdaworks.redis.support.RedisClusterClientFactoryBean">
        <property name="uri" value="redis://${redis.cluster.host2}:${redis.cluster.port2}"/>
 </bean>
```

Looking forward to your reply

**Comment by mp911de** [comment]
`java.io.IOException: Connection reset by peer` is a regular exception that the Redis server closed the connection during command sending/receiving. Do you have the full stack trace for me?

**Comment by christ258** [comment]
`ProtocolExcutorHandlerDelegate.run-[ERROR] Something wrong com.lambdaworks.redis.RedisException: java.io.IOException: Connection reset by peer when execute handler in thread Thread[taskExecutorPreReg-203,5,main], printStackTrace com.lambdaworks.redis.RedisException: java.io.IOException: Connection reset by peer
        at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:109)
        at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:77)
        at com.lambdaworks.redis.cluster.StatefulRedisClusterConnectionImpl$ClusterFutureSyncInvocationHandler.handleInvocation(StatefulRedisClusterConnectionImpl.java:330)
        at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:54)
        at com.sun.proxy.$Proxy26.smembers(Unknown Source)
        at com.asiainno.garuda.connector.chatroom.cache.service.ChatRoomCacheService.getShutUpUids(ChatRoomCacheService.java:120)
        at com.asiainno.garuda.connector.chatroom.protobuf.service.ServerMessageService.register(ServerMessageService.java:255)
        at com.asiainno.garuda.connector.chatroom.protobuf.process.MessageServiceProcess.register(MessageServiceProcess.java:49)
        at com.asiainno.garuda.connector.chatroom.protobuf.handler.ProtocolServerTaskHandler.handlePresenceRegister(ProtocolServerTaskHandler.java:84)
        at com.asiainno.garuda.connector.chatroom.protobuf.handler.ProtocolExcutorHandlerDelegate$PresenceRegisterEventRunnable.run(ProtocolExcutorHandlerDelegate.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer`

That is all, others is myself coding，If my guess is that with connecting two redisServer in one JVM，Or RedisClusterClient ‘s setting will changed ?

Looking forward to your reply

**Comment by mp911de** [comment]
Actually, `Caused by: java.io.IOException: Connection reset by peer` should have its own stack trace part which is not visible here. I wanted to see the involved calls because `Connection reset by peer` might happen but it's uncommon.

**Comment by christ258** [comment]
My code is:
`
<bean` id="redisCluster1" class="com.lambdaworks.redis.support.RedisClusterClientFactoryBean">
        <property name="uri" value="redis://${redis.cluster.host1}:${redis.cluster.port1}"/>
  </bean>
<bean id="redisCluster2" class="com.lambdaworks.redis.support.RedisClusterClientFactoryBean">
        <property name="uri" value="redis://${redis.cluster.host2}:${redis.cluster.port2}"/>
 </bean>

public class ChatRoomCacheService implement InitializingBean,DisposableBean {
//    private final Logger logger = LoggerFactory.getLogger(ChatRoomCacheService.class);

    @Autowired(required = false)
    private RedisClusterClient redisClusterClient;

    private RedisAdvancedClusterCommands<byte[], byte[]> syncCommands;

public boolean removeShutUpUid(Long roomId, Long uid) {
        return syncCommands.srem(KeyUtil.buildShutUpKey(roomId).getBytes(),String.valueOf(uid).getBytes()) == 1?true:false;
    }

    public Set<Long> getShutUpUids(Long roomId) {
        Set<byte[]> set = syncCommands.smembers(KeyUtil.buildShutUpKey(roomId).getBytes());
        Set<Long> result = Sets.newHashSet();
        if(!CollectionUtils.isEmpty(set)){
            for(byte[] bytes : set){
                result.add(Long.valueOf(new String(bytes, Charset.defaultCharset())));
            }
        }
        return result;
    }

    public boolean checkShutUpUid(Long roomId, Long uid) {
        return syncCommands.sismember(KeyUtil.buildShutUpKey(roomId).getBytes(),String.valueOf(uid).getBytes());
    }

@Override
    public void afterPropertiesSet() throws Exception {
        if(redisClusterClient != null) {
            ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                    .enablePeriodicRefresh(true)
                    .refreshPeriod(10, TimeUnit.MINUTES)
                    .enableAllAdaptiveRefreshTriggers()
                    .build();
            redisClusterClient.setOptions(ClusterClientOptions.builder()
                    .topologyRefreshOptions(topologyRefreshOptions)
                    .maxRedirects(5000)
                    .pingBeforeActivateConnection(true)
                    .build());
        }
        StatefulRedisClusterConnection<byte[], byte[]> connection = redisClusterClient.connect(ByteArrayCodec.INSTANCE);
        syncCommands = connection.sync();
        Assert.notNull(syncCommands);
    }

    @Override
    public void destroy() throws Exception {
        syncCommands.getStatefulConnection().close();
        redisClusterClient.shutdown();
    }

    public void setRedisClusterClient(RedisClusterClient redisClusterClient) {
        this.redisClusterClient = redisClusterClient;
    }
}
`
But i used two redisService for connecting two redisServer，

**Comment by mp911de** [comment]
I wasn't talking about your code. I wanted to see the stack trace of `Caused by: java.io.IOException: Connection reset by peer` that should contain some Java I/O, netty and lettuce calls. Maybe there is a bug in lettuce and the stack trace is the only piece that could give me a hint.

**Comment by christ258** [comment]
that is all of printStackTrace，and I guess netty client Strategy problem？

**Comment by mp911de** [comment]
I'm not sure I follow regarding your questions. I can't reliably tell what the issue is without seeing where the `IOException` originates. You might also want to check your logs whether you see further exceptions. Alternatively, you can enable debug logging by setting the logger level of `com.lambdaworks` to `DEBUG` but it will impact application performance.

**Comment by christ258** [comment]
My guess is that the network is not stable, but I have a question, why `com.lambdaworks` method have abnormal thrown runtimeException,is to do so for the sake of what? if the network network is not stable, we can through what configuration to reduce runtimeException

**Comment by mp911de** [comment]
I'm not sure I understand your question. Lettuce throws `RedisException` for all exceptions caused by command execution or while catching other exceptions during sending/receiving commands. I don't know why the stack trace of `IOException` is missing.

**Comment by christ258** [comment]
I guess finish it, This looks like a network problem, I change the network, Then there was no, But I want to know, if the network is not stable, how can we avoid the problem?

**Comment by stalary** [comment]
> @mp911de Exception:org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer
> at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
> at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
> at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
> at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
> at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:257)
> at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:718)
> at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:63)
> at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:210)
> at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:52)
> at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:59)
> at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
> at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
> at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
> at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:48)
> at one.top.eos.chain.utils.redis.RedisUtil.get(RedisUtil.java:97)
> at one.top.eos.chain.job.BlockNodeAnalysisJob.saveNode(BlockNodeAnalysisJob.java:116)
> at one.top.eos.chain.job.BlockNodeAnalysisJob.filterNodes(BlockNodeAnalysisJob.java:149)
> at one.top.eos.chain.job.BlockNodeAnalysisJob.execute(BlockNodeAnalysisJob.java:66)
> at com.xxl.job.core.thread.JobThread.run(JobThread.java:124)
> Caused by: io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer
> at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:125)
> at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:62)
> at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
> at com.sun.proxy.$Proxy198.get(Unknown Source)
> at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:61)
> ... 12 more
> Caused by: java.io.IOException: Connection reset by peer
> at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
> at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
> at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
> at sun.nio.ch.IOUtil.read(IOUtil.java:192)
> at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
> at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
> at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
> at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
> at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
> at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
> at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
> at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
> at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> at java.lang.Thread.run(Thread.java:748)

I had the same problem

**Comment by SudBisht** [comment]
I am getting the same issue while accessing remote Redis Server, below is the stacktrace

`org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to x.x.x.x:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1106)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1085)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedReactiveConnection(LettuceConnectionFactory.java:876)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:377)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:91)
	at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:56)
	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3852)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:123)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to x.x.x.x:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:235)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:204)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:113)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:113)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1104)
	... 15 common frames omitted
Caused by: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer`

**Comment by loveNY4ever** [comment]
It's not common，happened when to delete redis

cause:org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.convertLettuceAccessException(LettuceKeyCommands.java:817)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.del(LettuceKeyCommands.java:131)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.del(DefaultedRedisConnection.java:69)
	at org.springframework.data.redis.core.RedisTemplate.lambda$delete$2(RedisTemplate.java:709)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.delete(RedisTemplate.java:709)
	at io.terminus.taurus.server.manager.FeaturePermissionManager.createFeaturePermission(FeaturePermissionManager.java:70)
	at io.terminus.taurus.server.manager.PermissionManager.createPermission(PermissionManager.java:48)
	at io.terminus.taurus.api.facade.PermissionFacadeImpl.createPermission(PermissionFacadeImpl.java:36)
	at io.terminus.taurus.api.facade.PermissionFacadeImpl$$FastClassBySpringCGLIB$$6087893a.invoke(&lt;generated&gt;)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at io.terminus.taurus.api.TaurusServerApiAop.doApi(TaurusServerApiAop.java:67)
	at sun.reflect.GeneratedMethodAccessor326.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.terminus.taurus.api.facade.PermissionFacadeImpl$$EnhancerBySpringCGLIB$$32452250.createPermission(&lt;generated&gt;)
	at io.terminus.taurus.api.http.admin.openapi.AclPermissionOpenApiController.createPermission(AclPermissionOpenApiController.java:57)
	at sun.reflect.GeneratedMethodAccessor695.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at io.terminus.draco.web.autoconfig.filter.UserCenterLoginContextFilter.doFilter(UserCenterLoginContextFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at io.terminus.session.AFSessionFilter.doFilter(AFSessionFilter.java:241)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle$original$MmFSgNR3(ServletHandler.java:533)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle$original$MmFSgNR3$accessor$pVxkIrhr(ServletHandler.java)
	at org.eclipse.jetty.servlet.ServletHandler$auxiliary$D6hiy6u6.call(Unknown Source)
	at io.terminus.spot.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:91)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:129)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy199.del(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.del(LettuceKeyCommands.java:129)
	... 106 more
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by tisla005** [comment]
I am getting this same issue, was there a solution for this?
