### ISSUE TITLE
ReconnectionHandler.error-[ERROR] Cannot initialize channel

### ISSUE THREAD

**Issue by christ258** [lettuce-io/lettuce-core#509]
```
ReconnectionHandler.error-[ERROR] Cannot initialize channel.
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at com.lambdaworks.redis.protocol.ReconnectionHandler.reconnect(ReconnectionHandler.java:87)
        at com.lambdaworks.redis.protocol.ConnectionWatchdog.reconnect(ConnectionWatchdog.java:258)
        at com.lambdaworks.redis.protocol.ConnectionWatchdog.run(ConnectionWatchdog.java:243)
        at com.lambdaworks.redis.protocol.ConnectionWatchdog$2.lambda$run$393(ConnectionWatchdog.java:198)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:41)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```

After running for a long time, That is too many error message like that, Then netstat redis's port, That is too many connection, About more than 6000, Please take some helper

**Comment by mp911de** [comment]
Please post the complete exception and which version of lettuce you're using.

**Comment by christ258** [comment]
`<dependency>
          <groupId>biz.paluch.redis</groupId>
          <artifactId>lettuce</artifactId>
          <version>4.3.1.Final</version>
      </dependency>`

That is all of printstack message

**Comment by mp911de** [comment]
I can't proceed without knowing where `NullPointerException` therefore closing this issue.

**Comment by christ258** [comment]
I get it, When Redis server refuse client‘s connection, lettuce will reconnect all times, And lettuce's netty will too many client.
