### ISSUE TITLE
Connection pool deadlock

### ISSUE THREAD

**Issue by DarkSeraphim** [lettuce-io/lettuce-core#531]
One the GenericObjectPool is drained, it will block and wait for a new connection (default behaviour, which is also something I like to keep). The problem is that it will never fire, since it will block _inside_ a synchronized method you override, which also blocks any returnObject calls which would normally free a resource and stop the wait.

To reproduce: [gist](https://gist.github.com/DarkSeraphim/4bb840ef91def47d9446bf41649b9992)
Version: current 5.x branch

**Comment by mp911de** [comment]
There's no need to have `borrowObject` and `returnObject` synchronized, the underlying pool implementations handle synchronization properly. Thanks for the bug report, that's fixed now.

**Comment by qwqmobile** [comment]
hi,  could you pls confirm whether the follow bug is  #531.
There is about 100 redis clusters. After upgrading lettuce from 4.2.2.final to 4.4.3.final, the RedisCommandTimeoutException was gotten and the server stoped to wait "currentChannel.pipeline().fireUserEventTriggered(new ConnectionEvents.PrepareClose())" and "currentChannel.pipeline().fireUserEventTriggered(new ConnectionEvents.Close())".  

The dumped stack is as follows，
"ClusterRebalancer-0" #71 prio=5 os_prio=0 tid=0x00007fdf7fc36800 nid=0x3ea1 in Object.wait() [0x00007fdf241c0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:274)
	- locked <0x00000007606b00f8> (a io.netty.channel.DefaultChannelPromise)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
	at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:410)
	at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:125)
	at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:30)
	at com.lambdaworks.redis.protocol.CommandHandler.close(CommandHandler.java:1110)
	at com.lambdaworks.redis.cluster.ClusterNodeCommandHandler.close(ClusterNodeCommandHandler.java:101)
	at com.lambdaworks.redis.RedisChannelHandler.close(RedisChannelHandler.java:106)
	- locked <0x00000007606b0120> (a com.lambdaworks.redis.StatefulRedisConnectionImpl)
	at com.lambdaworks.redis.cluster.topology.Connections.close(Connections.java:117)
	at com.lambdaworks.redis.cluster.topology.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:102)
	at com.lambdaworks.redis.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:850)
	at com.lambdaworks.redis.cluster.RedisClusterClient.initializePartitions(RedisClusterClient.java:824)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectClusterImpl(RedisClusterClient.java:570)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connect(RedisClusterClient.java:356)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connect(RedisClusterClient.java:333)
	at com.amazon.redisnanny.admin.ClusterRebalancer.rebalanceAndCleanUpCluster(ClusterRebalancer.java:179)
	at com.amazon.redisnanny.admin.ClusterRebalancer.rebalanceCluster(ClusterRebalancer.java:117)
	at com.amazon.redisnanny.admin.ClusterRebalancer$$Lambda$19/221033168.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Could you give me some advices?
Thanks in advance.

**Comment by mp911de** [comment]
The 4.x line is no longer maintained. Please upgrade to 5.2.1.RELEASE.

**Comment by qwqmobile** [comment]
ok, 3ks

**Comment by qwqmobile** [comment]
Now I have upgraded to 5.0.0.release and it's deployed to three services which each has six clusters and runs about a week, there are two services that got the RedisCommandTimeoutException and the dumped stack is as follows
"ClusterRebalancer-0" #70 prio=5 os_prio=0 tid=0x00007f22bb280000 nid=0x5762 in Object.wait() [0x00007f22577f5000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:274)
        - locked <0x0000000736c20fe0> (a io.netty.channel.DefaultChannelPromise)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
        at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:410)
        at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:125)
        at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:30)
        at io.lettuce.core.protocol.DefaultEndpoint.close(DefaultEndpoint.java:484)
        at io.lettuce.core.cluster.ClusterNodeEndpoint.close(ClusterNodeEndpoint.java:70)
        at io.lettuce.core.RedisChannelHandler.close(RedisChannelHandler.java:111)
        - locked <0x0000000736c21058> (a io.lettuce.core.StatefulRedisConnectionImpl)
        at io.lettuce.core.cluster.topology.Connections.close(Connections.java:117)
        at io.lettuce.core.cluster.topology.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:101)
        at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:787)
        at io.lettuce.core.cluster.RedisClusterClient.initializePartitions(RedisClusterClient.java:761)
        at io.lettuce.core.cluster.RedisClusterClient.connectClusterImpl(RedisClusterClient.java:500)
        at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:339)
        at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:316)
        at com.amazon.redisnanny.admin.ClusterRebalancer.rebalanceAndCleanUpCluster(ClusterRebalancer.java:179)
        at com.amazon.redisnanny.admin.ClusterRebalancer.rebalanceCluster(ClusterRebalancer.java:117)
        at com.amazon.redisnanny.admin.ClusterRebalancer$$Lambda$19/385041270.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"RedisHealthMonitor-0" #69 prio=5 os_prio=0 tid=0x00007f22bb283800 nid=0x5761 in Object.wait() [0x00007f22578f7000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:274)
        - locked <0x0000000736c16e30> (a io.netty.channel.DefaultChannelPromise)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
        at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:410)
        at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:125)
        at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:30)
        at io.lettuce.core.protocol.DefaultEndpoint.close(DefaultEndpoint.java:484)
        at io.lettuce.core.RedisChannelHandler.close(RedisChannelHandler.java:111)
        - locked <0x0000000736c16e58> (a io.lettuce.core.StatefulRedisConnectionImpl)
        at com.amazon.redisnanny.admin.RedisHealthMonitor.metricsCollect(RedisHealthMonitor.java:163)
        at com.amazon.redisnanny.admin.RedisHealthMonitor$$Lambda$18/265644189.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"RedisConsistencyMonitor-0" #68 prio=5 os_prio=0 tid=0x00007f22bb281000 nid=0x5760 in Object.wait() [0x00007f22579f8000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:274)
        - locked <0x0000000736c17030> (a io.netty.channel.DefaultChannelPromise)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
        at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:410)
        at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:125)
        at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:30)
        at io.lettuce.core.protocol.DefaultEndpoint.close(DefaultEndpoint.java:484)
        at io.lettuce.core.RedisChannelHandler.close(RedisChannelHandler.java:111)
        - locked <0x0000000736c17058> (a io.lettuce.core.StatefulRedisConnectionImpl)
        at com.amazon.redisnanny.utils.RedisCommandsUtils.closeConnections(RedisCommandsUtils.java:76)
        at com.amazon.redisnanny.provider.LettuceClient.getClusterTopology(LettuceClient.java:70)
        at com.amazon.redisnanny.provider.ReplicationInfoCollector.getReplicationInfo(ReplicationInfoCollector.java:35)
        at com.amazon.redisnanny.admin.RedisConsistencyMonitor.metricsCollect(RedisConsistencyMonitor.java:136)
        at com.amazon.redisnanny.admin.RedisConsistencyMonitor$$Lambda$17/972335044.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


Could you pls give me some advices? Thanks in advance.

**Comment by qwqmobile** [comment]
Could  you please tell me whether lettuce 4.4 or 5.0 is compatible with redis 3.2.8?
Thank you in advance.
