### ISSUE TITLE
Possible memory issue with command handler (or message listeners)

### ISSUE THREAD

**Issue by RovoMe** [lettuce-io/lettuce-core#534]
During outage-testing some backend components (databases, Redis, ...) for our applications we noticed that from time to time applications crashed with OutOfDirectMemory errors thrown by Netty. As Netty uses direct allocated memory to bypass garbage collection and improve througput we were not able to learn which objects filled up the memory directly from the heapdump. As a consequence we added the following startup properties to our application to prevent Netty from allocating direct memory: 
```
-Dio.netty.allocator.type=unpooled 
-Dio.netty.noPreferDirect=true 
-Dio.netty.recycler.maxCapacity.default=0 
-Dio.netty.recycler.maxCapacity=0 
-Dio.netty.maxDirectMemory=0 
-Dio.netty.leakDetectionLevel=advanced 
-XX:+HeapDumpOnOutOfMemoryError
```

We use Lettuce 4.3.1.Final, Netty 4.1.9.Final and Spring-Data-Redis 1.8.0.RELEASE. We use Redis as queue in order to pass messages between applications and also maintain a self-written Apache Camel component which uses the Lettuce' `RedisClient` internally.

Our 23 applications all run on Ubuntu 14.04.5 LTS AWS instances and make up for roughly 120 connections to the Redis-Server in total. One of the instances runs a Redis-Server in version 2.8.4 locally (for outage tests only) and during the test we constantly started and stopped the Redis-Server via `sudo /etc/init.d/redis-server start` and `sudo /etc/init.d/redis-server stop` commands with some delays in between to give the application time to recover.

On performing our outage tests again with these settings after a couple of hours we ran into the following exception:

```
2017-05-04 15:00:26 - [WARN ] c.l.redis.protocol.CommandHandler        -  - Unexpected exception during request: io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Direct buffer memory [            ] [              ] [lettuce-nioEventLoop-7-3] 
io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Direct buffer memory
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at com.lambdaworks.redis.protocol.CommandHandler.writeBatch(CommandHandler.java:592)
	at com.lambdaworks.redis.protocol.CommandHandler.write(CommandHandler.java:540)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at com.lambdaworks.redis.protocol.CommandHandler.writeAndFlush(CommandHandler.java:509)
	at com.lambdaworks.redis.protocol.CommandHandler.flushCommands(CommandHandler.java:497)
	at com.lambdaworks.redis.protocol.CommandHandler.activateCommandHandlerAndExecuteBufferedCommands(CommandHandler.java:739)
	at com.lambdaworks.redis.protocol.CommandHandler.channelActive(CommandHandler.java:659)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at com.lambdaworks.redis.ChannelGroupListener.channelActive(ChannelGroupListener.java:41)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at com.lambdaworks.redis.PlainChannelInitializer$1.channelActive(PlainChannelInitializer.java:104)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1322)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:902)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:693)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:760)
	at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:750)
	at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:260)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:231)
	at io.netty.buffer.PoolArena.reallocate(PoolArena.java:397)
	at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:284)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:265)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1078)
	at com.lambdaworks.redis.protocol.CommandArgs$ByteBufferArgument.writeByteBuffer(CommandArgs.java:399)
	at com.lambdaworks.redis.protocol.CommandArgs$KeyArgument.encode(CommandArgs.java:548)
	at com.lambdaworks.redis.protocol.CommandArgs.encode(CommandArgs.java:344)
	at com.lambdaworks.redis.protocol.Command.encode(Command.java:120)
	at com.lambdaworks.redis.protocol.AsyncCommand.encode(AsyncCommand.java:160)
	at com.lambdaworks.redis.protocol.CommandEncoder.encode(CommandEncoder.java:91)
	at com.lambdaworks.redis.protocol.CommandEncoder.encode(CommandEncoder.java:82)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 43 common frames omitted
```

which also generated a heap dump which is summarized below.

![mappings2_dev_oom](https://cloud.githubusercontent.com/assets/1712331/25750309/98e5fe8e-31b1-11e7-8aaa-eb137c994fee.png)

As can be seen from the image below at the time the application crashed with an OutOfMemoryError, more than 12 million instances of `com.lambdaworks.redis.protocol.CommandArgs$KeyArgument` objects where available in the memory counting up to roughly 300 MB of heap memory used.

An image of the largest objects view on the heap reveals that the `commandBuffer` is holding plenty of `PubSubCommandArgs` objects.

![mappings2_dev_biggestobjects](https://cloud.githubusercontent.com/assets/1712331/25750890/7a8f8a52-31b3-11e7-9197-d53fabca0061.png)

On analyzing the path to GC root view from JProfiler we see that both, our Apache Camel component, which uses RedisClient internally, and Spring Data Redis RedisConnectionFactory branch into the command Method of AsyncCommand. The difference between these two invocations though is, that we have only a handful of Apache Camel objects in the heap profile while almost all other entries (at least for the couple hundred entries I've checked) are strongly referenced by `lettuce-nioEventLoop`.

![mappings2_dev_path-to-gc-root](https://cloud.githubusercontent.com/assets/1712331/25753774/23bf3bf0-31bd-11e7-87f0-8116a7f1fa51.png)

This indicates that there may be an issue on consuming commands via the PubSubCommandHandler or Spring Data Rests listeners, which we use also, in cases of connection issues. 

If you need the heap dump (~766 MB) or our Redis Spring configuration ping back.

**Comment by mp911de** [comment]
Hi @RovoMe,

Thanks for the very detailed ticket. 

`CommandHandler.commandBuffer` buffers commands during Redis unavailability (if Redis goes down or you experience a network partition). It's unbounded by default. Depending on the load that happened while Redis was down, the `commandBuffer` can fill up quickly. Once the connection gets restored, `commandBuffer` is replayed (at least the commands which are not canceled).

You can limit the number of commands getting queued by setting [`ClientOptions.requestQueueSize`](https://github.com/lettuce-io/lettuce-core/wiki/Client-options).

The image showing the 23 instances of `PubSubArgs` isn't worrying me as the number of buffered commands increases with each command triggered during Redis unavailability. Each of your Redis Pub/Sub messages is about 14.7MB in size. If you didn't set `-XX:MaxDirectMemorySize`, the default direct buffer memory size is 64MB.
Encoding all commands for sending these in a single write seems to hit the limit and therefore it crashes. If I follow the idea, it's likely that each Redis shutdown iteration adds more commands to the buffer and reconnect is never able to send all commands in a single batch.

I'd like to know more about the object root for the majority of `KeyArgument`. The number of `KeyArgument`'s should somehow correlate with the number of `PubSubArgs` instances except if there are connections lingering around.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by RovoMe** [comment]
Sorry for the late delay though we were busy releasing new versions of our software and fixing the mess after updating plenty of external dependencies. 

We updated the client configuration of the Pub/Sub command handler to throw away any incoming (or left over) commands while Redis is currently down as the commands aren't the most important stuff in the application anyway. We've therefore added the following lines to the configuration:

```
RedisClient client = pool.getClient();
client.setOptions(ClientOptions.builder()
                               .cancelCommandsOnReconnectFailure(true)
                               .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                               .build());
```

though we have to test it again and see if it fixes the issue. I hope I'll find time tomorrow.

Regarding your question of the object root for the majority of `KeyArgument` instances, we can send you the complete heap dump if you like. In that case we'd prefer some secure channel to exchange the file as the heapdump contains some sensitive data even though it contains only development related credentials.

**Comment by mp911de** [comment]
No worries – Setting `disconnectedBehavior` or increasing direct memory limits will address your issue.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
