### ISSUE TITLE
Asynchronous string set hangs indefinitely

### ISSUE THREAD

**Issue by IcyTotem** [lettuce-io/lettuce-core#542]
Hi, I am using lettuce 5.0.0.Beta1. I have some code that uses counters to make frequency estimations. The code polls, sets and increments integer or floating point values. However, once I call an asynchronous set, it hangs indefinitely.
It produces the following log from cli monitor:

```
1495198663.168116 [0 127.0.0.1:52554] "GET" "nnn.net#/IE8#referer#entropy"
1495198663.170460 [0 127.0.0.1:52554] "GET" "nnn.net#/IE8#referer#www.google.com"
1495198663.171878 [0 127.0.0.1:52554] "INCR" "nnn.net#/IE8#referer#www.google.com"
1495198663.173119 [0 127.0.0.1:52554] "SADD" "nnn.net#/IE8#referer#possibleValues" "www.google.com"
1495198663.176016 [0 127.0.0.1:52554] "SMEMBERS" "nnn.net#/IE8#referer#possibleValues"
1495198663.177475 [0 127.0.0.1:52554] "GET" "nnn.net#/IE8#referer#www.google.com"
1495198666.394139 [0 127.0.0.1:52554] "GET" "nnn.net#/IE8#referer#www.google.com"
< here SET is invoked in java code >
```

After the seventh request, the client hangs and after a long delay, it launches a 
`com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out`.

I have written a [test case](https://gist.github.com/IcyTotem/ea84236ee0a89cb902c15c66a647b567) to reproduce the problem. This test case hangs and fails after a timeout with the following stacktrace:

```
Exception in thread "Thread-0" Exception in thread "Thread-1" com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:113)
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:92)
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:63)
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy8.incr(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:113)
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:92)
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:63)
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy8.incr(Unknown Source)
```

If you remove the calls to `async.set`, the test will succeed. At least, it did in my case. Notice that my original code wasn't multithreaded.

**Comment by mp911de** [comment]
Thanks for the code sample. Your code runs into an encoding error. 

In your code you erase generics with 

```
StatefulRedisConnection<String, String> connection = client.connect();
RedisStringCommands sync = connection.sync();
```

and then you pass an `Integer` value with

```
 async.set("check" + i, 0);
```

Your connection uses a `String` codec so it expects `String` keys and values. Using `Integer` causes an `EncoderException`. As soon as you add a completion listener to the future (`whenComplete(…)` or similar) you can obtain the error:

```
io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
```

**Comment by IcyTotem** [comment]
Thanks, I fixed this. However the error was so cryptic and the mistake so trivial it took me an hour to figure out. I used it as fire&forget so I never got an encoder error.

**Comment by mp911de** [comment]
That's the idea behind fire and forget.
