### ISSUE TITLE
set command throw IllegalStateException

### ISSUE THREAD

**Issue by craigwu9** [lettuce-io/lettuce-core#555]
- lettuce  version : 4.1.3-SNAPSHOT
- Contextual information: I have a service need periodically update a value in a Redis cluster。Redis cluster is used official version 3.0.0.
- Don't know how to reproduce. Just  got a exception, and I don't know why yet. From the exception, I know the exception command is set.   I checked the source, find out the set command's output is StatusOutput, and the StatusOutput did not support set(long). That's why the exception thrown. But I don't know why a set command read a integer return value. 

I create a pull request, just set the illegal value to the exception, so when the exception arise, I can know what the exactly value the server returned. 

pull request: #554

And I hope someone can help to find out what exactly reason is. 
exception stack:
```
com.lambdaworks.redis.RedisException: java.lang.IllegalStateException
        at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:109)
        at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:77)
        at com.lambdaworks.redis.cluster.StatefulRedisClusterConnectionImpl$ClusterFutureSyncInvocationHandler.handleInvocation(StatefulRedisClusterConnectionImpl.java:343)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at com.sun.proxy.$Proxy93.set(Unknown Source)
        at com.gomeplus.gax.utils.RedisUtil.setWithExpire(RedisUtil.java:63)
        at com.gomeplus.gax.propellor.dao.impl.PromotionRedisDaoImpl.update(PromotionRedisDaoImpl.java:27)
        at com.gomeplus.gax.propellor.dao.impl.PromotionRedisDaoImpl$$FastClassBySpringCGLIB$$394a8888.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at com.gomeplus.gax.propellor.dao.impl.PromotionRedisDaoImpl$$EnhancerBySpringCGLIB$$af4cc3b0.update(<generated>)
        at com.gomeplus.gax.propellor.schedule.service.PromotionCrontabService.getTopics2Redis(PromotionCrontabService.java:171)
        at com.gomeplus.gax.propellor.crontab.crontabBean.PromotionCrontab.cronPromotion(PromotionCrontab.java:23)
        at com.gomeplus.gax.propellor.crontab.AllCrontab.cronPromotion(AllCrontab.java:34)
        at sun.reflect.GeneratedMethodAccessor378.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: null
        at com.lambdaworks.redis.output.CommandOutput.set(CommandOutput.java:63)
        at com.lambdaworks.redis.protocol.RedisStateMachine.lambda$safeSet$333(RedisStateMachine.java:178)
        at com.lambdaworks.redis.protocol.RedisStateMachine$$Lambda$14/1990122957.run(Unknown Source)
        at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:195)
        at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:178)
        at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:118)
        at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:162)
        at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:141)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        ... 1 common frames omitted
```

**Comment by mp911de** [comment]
Thanks for your detailed bug report. `StatusOutput` does not support `set(long)` because it's not accepted as valid output.

It looks like the protocol got out of sync which might happen with earlier Lettuce versions. Please upgrade to Lettuce 4.3.2 and optionally enable debug logging (you can also introduce the change to your code locally and use the patched version for a while).

The changes from your PR won't work because buffers aren't usually heap buffers but default to off-heap buffers that are not backed by an array. I think introducing this change might actually cause more issues than benefit because binary data can easily pollute log output.

**Comment by mp911de** [comment]
Thanks for your detailed bug report. `StatusOutput` does not support `set(long)` because it's not accepted as valid output.

It looks like the protocol got out of sync which might happen with earlier Lettuce versions. Please upgrade to Lettuce 4.3.2 and optionally enable debug logging (you can also introduce the change to your code locally and use the patched version for a while).

The changes from your PR won't work because buffers aren't usually heap buffers but default to off-heap buffers that are not backed by an array. I think introducing this change might actually cause more issues than benefit because binary data can easily pollute log output.

**Comment by craigwu9** [comment]
OK, I will upgrade to 4.3.2 to try

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
