### ISSUE TITLE
java.lang.OutOfMemoryError when using Lettuce in cluster

### ISSUE THREAD

**Issue by nshaham** [lettuce-io/lettuce-core#560]
Hi I am using Lettuce 4.3.2.Final, Spring version 4.2.5, java8, Tomcat8 , netty 4.1.12 
running on Amazon Linux AMI release 2016.09 2 CPUs

see Maven dependency

```xml
<dependency>
    	<groupId>biz.paluch.redis</groupId>
    	<artifactId>lettuce</artifactId>
    	<version>4.3.2.Final</version>
</dependency> 
<dependency>
    	<groupId>io.netty</groupId>
    	<artifactId>netty-all</artifactId>
    	<version>4.1.12.Final</version>
</dependency>
<dependency>
        <groupId>org.springframework.data</groupId>
        <artifactId>spring-data-redis</artifactId>
        <version>1.7.1.RELEASE</version>
 </dependency>
<dependency>
	<groupId>redis.clients</groupId>
	<artifactId>jedis</artifactId>
	<version>2.8.1</version>
</dependency>
```
My beans definition code is:

```java
	 @Bean(destroyMethod = "shutdown")
	    ClientResources clientResources() {
	        return DefaultClientResources.create();
	    }

	    @Bean(destroyMethod = "shutdown")
	    RedisClusterClient redisClusterClient(ClientResources clientResources) {
	    	
	    	String redisNodes = getEnviorment().getProperty("redis.recommender.server.nodes");
	        List<RedisURI> listOfRedisURI = new ArrayList<RedisURI>();
			String[] nodes = redisNodes.split(",");
			for (int i = 0; i < nodes.length; i++) {
				listOfRedisURI.add(RedisURI.create(nodes[i].split(":")[0], Integer.parseInt(nodes[0].split(":")[1])));
			}
			return RedisClusterClient.create(clientResources, listOfRedisURI);
	    }

	    @Bean(destroyMethod = "close")
	    StatefulRedisClusterConnection<String, String> clusterConnection(RedisClusterClient clusterClient) {
	        return clusterClient.connect();
	    }
```

This is an example of a few functions code I have:

```java
@Autowired
@Qualifier("redisClusterClient")
private RedisClusterClient redisClusterClient;
....
....
public String getRecommenderNameForUser(String partnerId,String userId) {
		return redisClusterClient.connect().sync().get("UserAlgo:" + partnerId + "_" + userId);
}

public List<KeyValue<String, String>> getArticlesFromRedis(Collection<String> articleKeys){
		return redisClusterClient.connect().sync().mget(articleKeys.toArray(new String[0]));
}

public List<Object> putAlgoContentInRedis(List<Map<String,Object>> articles, String algoId, String filterParams, int mTTL) {
		
		String rKey = "Algo_content:" +filterParams + "_"+algoId;
		ScoredValue[] arr = new ScoredValue[articles.size()];
		int i = 0;
		for (Map<String, Object> map : articles){
			long score   = (long)map.get("row_num");
			String value = ((UUID)map.get("id")).toString();
			arr[i++] = ScoredValue.just(score, value);
		}
		redisClusterClient.connect().sync().zadd(rKey, arr);
		redisClusterClient.connect().sync().expire(rKey, mTTL*60);
		return null;
	}
```

When I use my application I get the following warnings::

```
28-Jun-2017 15:38:23.795 WARNING [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application
[mediaApi] appears to have started a thread named [lettuce-eventExecutorLoop-1-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 io.netty.util.concurrent.SingleThreadEventExecutor.confirmShutdown(SingleThreadEventExecutor.java:705)
 io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:70)
 io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
 java.lang.Thread.run(Thread.java:745)
```

And after a while I get OutOfMemory error and application is not responsive.
at this time CPU is 100%

```
28-Jun-2017 12:14:17.524 SEVERE [http-nio-8080-exec-41] org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun
 java.lang.OutOfMemoryError: GC overhead limit exceeded
        at sun.nio.cs.UTF_8.newDecoder(UTF_8.java:68)
        at java.lang.StringCoding$StringDecoder.<init>(StringCoding.java:131)
        at java.lang.StringCoding$StringDecoder.<init>(StringCoding.java:122)
        at java.lang.StringCoding.decode(StringCoding.java:187)
        at java.lang.String.<init>(String.java:426)
        at java.lang.String.<init>(String.java:491)
        at java.io.UnixFileSystem.canonicalize0(Native Method)
        at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:172)
        at java.io.File.getCanonicalPath(File.java:618)
        at org.apache.catalina.webresources.AbstractFileResourceSet.file(AbstractFileResourceSet.java:69)
        at org.apache.catalina.webresources.DirResourceSet.getResource(DirResourceSet.java:101)
        at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:280)
        at org.apache.catalina.webresources.CachedResource.validateResource(CachedResource.java:95)
        at org.apache.catalina.webresources.Cache.getResource(Cache.java:69)
        at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:215)
```

I am probably doing something wrong.
It seems that resources are not released.
Can you help ?

Many Thanks
Shaham

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the lettuce version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Your code does not contain any obviously wrong things. It looks like as if your available memory is not sufficient. The garbage collector spends too much time attempting to free memory and that's the cause why you run into that exception.

I don't know about memory consumption of your application vs. the available memory. You should find out how much memory your application requires. If you find the amount is unreasonable high, then start investigating (heap dump is a good starting point) what exhausts your memory.

A minor improvement to your dependencies: You declare two Redis clients (Jedis and Lettuce). You should use only one in your application.

See also:

* https://plumbr.eu/outofmemoryerror/gc-overhead-limit-exceeded

**Comment by nshaham** [comment]
Thanks for your answer.
I will look for memory settings and report back.

**Comment by mp911de** [comment]
Any update on this ticket?

**Comment by nshaham** [comment]
Yes,
I had some application code problems.
I am now using the clusterConnection (StatefulRedisClusterConnection) bean directly like this:
**clusterConnection**.sync().zadd(rKey, arr);
instead of:
**redisClusterClient**.**connect(**).sync().zadd(rKey, arr);
Now it looks stable and running OK.
Thanks very much.
Shaham

**Comment by mp911de** [comment]
Thanks for the update.
