### ISSUE TITLE
Sync transactions return array of unexpected size

### ISSUE THREAD

**Issue by nikolayspb** [lettuce-io/lettuce-core#571]
Lettuce 4.3.3. I run this code in a single thread. 
I even started to use a dedicated RedisClient for txConnection.

```
 StatefulRedisConnection<String, MyValue> txConnection
 RedisCommands<String, MyValue> txCommands = txConnection.sync();  

 private void tx (String dataKey) {
     txCommands.multi();
     txCommands.get(dataKey);
     txCommands.del(dataKey);
     List<Object> result = txCommands.exec();
     System.out.println(result);
}
```

These are some unexpected results I can get

```
[OK, MyValue, 1] 
[1, null, 0] 
[OK, null, 0]
[OK, OK, null, 0]
[null, 0]
[1, OK, null, 0]
[1, 1, 1, null, 0] 
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, null, 0]
[1, 1, 1, null, 0]
```

**Comment by mp911de** [comment]
Care to craft a reproducible test case (Gist of a unit test)?

**Comment by nikolayspb** [comment]
Actually I was having 4.2.2 driver and 4.0.49 netty. And I was not aware of it.
Now I have updated to 4.3.3. And 80% of time get result [MyValue, 1] which is good.
20% of time I get [null, 0] which probably stands for absent value for key.

However, I have seen  [null, null, 0] once so far and once:

```
Caused by: java.lang.IllegalStateException: null
        at com.lambdaworks.redis.output.CommandOutput.set(CommandOutput.java:75)
        at com.lambdaworks.redis.output.MultiOutput.set(MultiOutput.java:59)
        at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:396)
        at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:176)
        at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:218)
        at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:200)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
```

Sorry I would not be able to extract that piece code out of commercial software until weekends, at least.

**Comment by mp911de** [comment]
It's not required to extract code from a software. I'm happy with a short snippet that reproduces the issue.

**Comment by nikolayspb** [comment]
And what is actually expected size of array in this code? How would you say it should look for success (we found a key) and non-success case?

Now I am relying on index, but rather iterate all of items and checking with instanceof MyValue.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by nikolayspb** [comment]
Yes, please. I think it was related to that ping issue. But I am not going to use Tx now.
