### ISSUE TITLE
GEOPOS fails with a single member in the var args

### ISSUE THREAD

**Issue by FerhatSavci** [lettuce-io/lettuce-core#591]
Hi,

Using 4.4.0, GEOPOS works when invoked for multiple members but throws an exception when invoked for a single member. (Same situation for the async interface, too).

## Reproduction code

```
        RedisClient client = RedisClient.create("redis://localhost:6379");
        RedisGeoCommands<String, String> sync = client.connect().sync();
        
        System.out.println(sync.geoadd("team", 33.0, 34.0, "m1"));
        System.out.println(sync.geoadd("team", 33.1, 34.0, "m2"));
        System.out.println(sync.geoadd("team", 33.0, 34.3, "m3"));
        
        
        System.out.println(sync.geopos("team", "m1", "m2")); // Works
        System.out.println(sync.geopos("team", "m1")); // com.lambdaworks.redis.RedisException: java.lang.UnsupportedOperationException
        
        System.out.println(sync.georadiusbymember("team", "m1", 50, GeoArgs.Unit.km));
```

## Logs (output from above code)
```
1
1
1
[(32.99999803304672, 34.00000062127011), (33.10000151395798, 34.00000062127011)]
Exception in thread "main" com.lambdaworks.redis.RedisException: java.lang.UnsupportedOperationException
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:130)
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:96)
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:61)
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy0.geopos(Unknown Source)
	at tr.com.cs.redis.geo.test.Main.main(Main.java:27)
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.lambdaworks.redis.output.ListSubscriber.onNext(ListSubscriber.java:47)
	at com.lambdaworks.redis.output.GeoCoordinatesListOutput.set(GeoCoordinatesListOutput.java:55)
	at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:429)
	at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:233)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:313)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:257)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mp911de** [comment]
Related to #589

**Comment by mp911de** [comment]
Thanks, that's fixed now.
