### ISSUE TITLE
Connecting to sentinels on localhost with Debug level logging causes Exception

### ISSUE THREAD

**Issue by zoltan-toth-mw** [lettuce-io/lettuce-core#594]
Connecting to sentinels on localhost with Debug level logging causes Exception.
On info level the app connects to the sentinels and everything is good.

Lettuce version : 4.4.0.Final

## Logs
15:43:34.311 [main] DEBUG com.lambdaworks.redis.RedisClient - Trying to get a Redis Sentinel connection for one of: [RedisURI [host='127.0.0.1', port=26381], RedisURI [host='127.0.0.1', port=26380], RedisURI [host='127.0.0.1', port=26379]]
Exception in thread "main" java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
	at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:254)
	at com.lambdaworks.redis.resource.SocketAddressResolver.resolve(SocketAddressResolver.java:49)
	at com.lambdaworks.redis.RedisClient.connectSentinel(RedisClient.java:783)
	at com.lambdaworks.redis.RedisClient.connectSentinel(RedisClient.java:662)
	at com.lambdaworks.redis.RedisClient.lookupRedis(RedisClient.java:1018)
	at com.lambdaworks.redis.RedisClient.getSocketAddress(RedisClient.java:962)
	at com.lambdaworks.redis.RedisClient.lambda$getSocketAddressSupplier$6(RedisClient.java:1005)
	at com.lambdaworks.redis.ConnectionBuilder.socketAddress(ConnectionBuilder.java:123)
	at com.lambdaworks.redis.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:281)
	at com.lambdaworks.redis.RedisClient.connectStatefulAsync(RedisClient.java:525)
	at com.lambdaworks.redis.RedisClient.connectStandaloneAsync(RedisClient.java:487)
	at com.lambdaworks.redis.RedisClient.connectStandalone(RedisClient.java:465)
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:382)
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:369)

**Comment by mp911de** [comment]
This issue duplicates #588.
