### ISSUE TITLE
Handle 'Redis is loading the dataset in memory' inside the driver

### ISSUE THREAD

**Issue by nikolayspb** [lettuce-io/lettuce-core#625]
Hello Mark,

Should not Lettuce driver handle this exception and retry when Redis server becomes available?
Not propagating this exception to a client.

```
java.util.concurrent.CompletionException: com.lambdaworks.redis.RedisCommandExecutionException: LOADING Redis is loading the dataset in memory
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:953)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:800)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.lambdaworks.redis.RedisCommandExecutionException: LOADING Redis is loading the dataset in memory
	at com.lambdaworks.redis.protocol.AsyncCommand.completeResult(AsyncCommand.java:119)
	at com.lambdaworks.redis.protocol.AsyncCommand.complete(AsyncCommand.java:110)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:287)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:259)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:934)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:397)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
```

**Comment by mp911de** [comment]
No. That’s a valid error message that needs to be propagated to the caller. The only error responses that are handled by the client are move/ask redirections in Redis Cluster. Both are actually not errors but rather well-defined protocol indicators.

Am 10. Okt. 2017, 19:25 +0200 schrieb Nikolay Kuznetsov <notifications@github.com>:

**Comment by nikolayspb** [comment]
I don't agree. What client can do with this exception? I think most clients would have to implement boiler plate queue for later retrying.

**Comment by mp911de** [comment]
It strongly depends on your use-case. You can at least:

* Propagate the error and cancel a request
* Do something meaningful (i.e. set the healthcheck status to `DOWN`)
* Retry

Lettuce has no details on when `LOADING` is finishing. Unconditional retrying introduces a layer of unnecessary complexity and load on Redis that would head towards an opinionated handling – or additional configuration options that are hard to explain.

**Comment by Hronom** [comment]
Have created issue on Redis tracker, please support it.
To make Redis open TCP port only when it's ready.

**Comment by mp911de** [comment]
We introduced recently dedicated exceptions for Lua scripting to represent `NOSCRIPT` and `BUSY`, maybe we could do here the same to simplify client-side handling of that kind of Redis responses.

**Comment by Hronom** [comment]
@mp911de Well I use Jedis in my Spring Boot app because it has autoconfiguration in Spring. However Jedis also not handle this issue.

It seems like this issue more related to Redis. Redis must not open tcp port if it not ready yes.

**Comment by perlun** [comment]
For the record, `io.lettuce.core.RedisLoadingException` is being thrown if this happens with the current version of Lettuce ([4.5.0 or greater](https://github.com/lettuce-io/lettuce-core/releases/tag/4.5.0.Final)).

The issue that was tracking the implementation is https://github.com/lettuce-io/lettuce-core/issues/682.
