### ISSUE TITLE
Cannot close connection when refreshing topology

### ISSUE THREAD

**Issue by dangtranhoang** [lettuce-io/lettuce-core#656]
Hi,

Could you please check this log?

```
21:50:58,891 WARN  [lettuce-eventExecutorLoop-8-3] cluster.ClusterTopologyRefreshScheduler     - Cannot refresh Redis Cluster topology
java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208)
	at java.base/java.util.TreeMap$ValueIterator.next(TreeMap.java:1253)
	at io.lettuce.core.cluster.topology.Connections.close(Connections.java:116)
	at io.lettuce.core.cluster.topology.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:101)
	at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:787)
	at io.lettuce.core.cluster.RedisClusterClient.reloadPartitions(RedisClusterClient.java:732)
	at io.lettuce.core.cluster.ClusterTopologyRefreshScheduler$ClusterTopologyRefreshTask.run(ClusterTopologyRefreshScheduler.java:197)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

After above log appear 2 times, we start seeing following log

```
21:52:58,930 WARN  [lettuce-eventExecutorLoop-8-1] cluster.ClusterTopologyRefreshScheduler     - Cannot refresh Redis Cluster topology
io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='127.0.0.1', port=7000], RedisURI [host='127.0.0.1', port=7001], RedisURI [host='127.0.0.1', port=7002], RedisURI [host='127.0.0.1', port=7003], RedisURI [host='127.0.0.1', port=7004], RedisURI [host='127.0.0.1', port=7005]]
	at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:790)
	at io.lettuce.core.cluster.RedisClusterClient.reloadPartitions(RedisClusterClient.java:732)
	at io.lettuce.core.cluster.ClusterTopologyRefreshScheduler$ClusterTopologyRefreshTask.run(ClusterTopologyRefreshScheduler.java:197)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

And the config is

```
ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
.refreshPeriod(Duration.ofSeconds(5))
.adaptiveRefreshTriggersTimeout(Duration.ofSeconds(5))
.enablePeriodicRefresh().enableAllAdaptiveRefreshTriggers().build();
```

**Redis cluster with password**
**Lettuce version: 5.0.0.RELEASE**
**JDK version: 9.0.1**
**Redis 4.0.2**

Thanks

**Comment by dangtranhoang** [comment]
Hi,
It seems this issue will be solve if I enable `pingBeforeActivateConnection` property.

**Comment by mp911de** [comment]
Thanks for the bug report. It's a bug in `Connections.close(…)`.

**Comment by mp911de** [comment]
That's fixed now and available in the snapshot builds.

**Comment by roottraveller** [comment]
> pingBeforeActivateConnection

This does not solve the above error for me.
