### ISSUE TITLE
RedisStateMachine.readLine fails with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mp911de** [lettuce-io/lettuce-core#658]
```
Caused by: java.lang.IndexOutOfBoundsException: readerIndex: 5 (expected: 0 <= readerIndex <= writerIndex(0))
	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:103)
	at com.lambdaworks.redis.protocol.RedisStateMachine.readLine(RedisStateMachine.java:315)
	at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:175)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:406)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:292)
```

**Comment by mp911de** [comment]
Won't fix as the issue is related to the connection design that interferes with reconnects.
