### ISSUE TITLE
MasterSlave getNodeSpecificViews NPE with sync API

### ISSUE THREAD

**Issue by boughtonp** [lettuce-io/lettuce-core#659]
I'm trying to get automatic failover working in a Master/Slave with Sentinel environment.

Using the method shown in Example 2 here:
https://github.com/lettuce-io/lettuce-core/wiki/Master-Slave

When killing the master node, after a bunch of reconnect attempts, Lettuce appears to be trying to identify the new master from Sentinel, but gives the following error...

```
2017-12-01 20:37:29 ERROR MasterSlave:181 - Error during background refresh
java.lang.NullPointerException
	at com.lambdaworks.redis.masterslave.MasterSlaveTopologyRefresh.getNodeSpecificViews(MasterSlaveTopologyRefresh.java:113)
	at com.lambdaworks.redis.masterslave.MasterSlaveTopologyRefresh.getNodes(MasterSlaveTopologyRefresh.java:78)
	at com.lambdaworks.redis.masterslave.MasterSlave.lambda$connectSentinel$0(MasterSlave.java:176)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at com.lambdaworks.redis.masterslave.SentinelTopologyRefresh.lambda$null$2(SentinelTopologyRefresh.java:149)
	at com.lambdaworks.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at com.lambdaworks.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at com.lambdaworks.io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at com.lambdaworks.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at com.lambdaworks.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

Using lettuce-4.4.1.Final-shaded.jar on JDK 1.8.0_144, testing against Redis 3.2 on Windows (but will be running against Redis 4 on Centos), working with the sync API.

**Comment by mp911de** [comment]
That's fixed now.

**Comment by boughtonp** [comment]
Testing with the snapshot at https://oss.sonatype.org/content/repositories/snapshots/biz/paluch/redis/lettuce/4.4.3-SNAPSHOT/

The NPE has gone, but Lettuce is not switching to the new master.

Should this be automated, or is it necessary to listen for channelInactive event and re-connect manually?

**Comment by mp911de** [comment]
Thanks for giving the snapshot build a try and your feedback. It's intended that Lettuce switches to the new master. It should continue working the same way as it works when connecting through `RedisClient` with a sentinel URI. It's a bug if the newly promoted master is not used. Care to file a ticket along with a description what you tried and how your Redis setup looks like?

**Comment by boughtonp** [comment]
Sorry, I just realised I had the wrong URI from checking something else. Now that I've corrected it back to the appropriate sentinel URI it is switching as expected.

**Comment by mp911de** [comment]
Thanks for your feedback.
