### ISSUE TITLE
Lettuce trusts the first sentinel's response to who the master is.

### ISSUE THREAD

**Issue by boughtonp** [lettuce-io/lettuce-core#661]
I'm not sure if this is a bug in Lettuce or in Redis/Sentinel or just a weird quirk.

Our setup is master with two slaves, and a sentinel on each machine, (i.e. M1+S1,R2+S2,R3+S3), all Redis 4.0.2 connected via Lettuce 4.4.3 snapshot.

We encountered a situation whereby Lettuce was connecting to a slave (R2) even when ReadFrom was set to MASTER, then issuing a setex and failing because it was connected to a readonly slave.

From what I could tell, M1,R2,R3,S1,S3 all agreed on the master being M1, but because the URI happened to be `redis-sentinel://S2,S1,S3/0##redis-cluster` and Lettuce [only asks the first in the list](https://github.com/lettuce-io/lettuce-core/blob/4.4.x/src/main/java/com/lambdaworks/redis/masterslave/MasterSlave.java#L149), it was asking S2 sentinel who the master was, and getting the incorrect reply of R2.

(In case it's relevant, running `SENTINEL master redis-cluster` was reporting flags of `"s_down,master"` on that node - possibly a previous failover didn't fully cleanup.)

Moving the master's sentinel IP to be first in the URI solved the problem, and repairing the config on S2 allowed either order to work.

Should Lettuce keep checking sentinels until it has a quorum agreement on which node is the master?
Or is this entirely the job of Redis/Sentinel, and there's a bug there which allowed the incorrect sentinel config to persist?

**Comment by mp911de** [comment]
Thanks for reporting the issue. There are a couple of things in there, let me untangle:

1. Lettuce attempts to connect to all sentinels in the order they get returned by `RedisURI.getSentinels()`. The mentioned method takes the first URI but really, sentinels are within the URI. The method is a bit unfortunate because it suggests the possibility of having multiple Sentinel URIs passed through `Iterable`.
2. The actual Sentinel connect happens in [`RedisClient.connectSentinel(…)`](https://github.com/lettuce-io/lettuce-core/blob/5929335a6ddd2843cf4983196a85bcc80490b3d3/src/main/java/com/lambdaworks/redis/RedisClient.java#L775).
3. Lettuce doesn't check in Sentinel Master/Slave mode for the server's role. It obtains topology details from [Sentinel](https://github.com/lettuce-io/lettuce-core/blob/5929335a6ddd2843cf4983196a85bcc80490b3d3/src/main/java/com/lambdaworks/redis/masterslave/SentinelTopologyProvider.java#L83-L84) and assumes details are in sync. Connecting in Master/Slave mode without Sentinel lets Lettuce figure out the currently connected server role and the topology from `INFO` command. Lettuce trusts Sentinel – if it wouldn't then we would have much bigger issues. 

Changing how Lettuce connects to a Redis master isn't something we should change. Adding a quorum check increases the time until you're able to use the connection. Asking more than one machine causes actually more issues than contributing to be a cure: 

* What if there is never a quorum
* What if a node is down and cannot report its state

I see it entirely as part of Sentinel's responsibility to report the correct topology. We read masters and slaves from Sentinel, as your client is running probably on a different machine, it might have a different network view (connectivity). If Sentinel reports a master is down, but you're still able to connect, then something's not right about that state. We could deny establishing a connection, but that would effectively prevent you from using Redis whereas we don't know how your application is going to interact with Redis.

Does this make sense?

**Comment by boughtonp** [comment]
Thanks for the clarification, that does all make sense.



On the connection startup front, I've found another oddity where I can't see what's going on.

In short, the problem is Lettuce is connecting to master but also the slaves, and in particular to R3 which is a slave with priority 0 - it's purpose is a witness server, and the application shouldn't connect to it.

10.0.173.50 = M1/S1 , 10.0.173.55 = R2 , 192.168.5.245 = R3

Filtered logs:
> 20:59:23 DEBUG RedisClient:784 - Connecting to Redis Sentinel, address: /10.0.173.50:16379
> 20:59:23 DEBUG RedisClient:287 - Connecting to Redis at /10.0.173.50:16379
> 20:59:23 DEBUG RedisClient:312 - Connecting to Redis at /10.0.173.50:16379: Success
> 20:59:24 DEBUG RedisClient:287 - Connecting to Redis at /10.0.173.50:6379
> 20:59:24 DEBUG RedisClient:312 - Connecting to Redis at /10.0.173.50:6379: Success
> 20:59:24 DEBUG RedisClient:287 - Connecting to Redis at /192.168.5.245:6379
> 20:59:24 DEBUG RedisClient:287 - Connecting to Redis at /10.0.173.55:6379
> 20:59:24 DEBUG RedisClient:312 - Connecting to Redis at /192.168.5.245:6379: Success
> 20:59:24 DEBUG RedisClient:312 - Connecting to Redis at /10.0.173.55:6379: Success
> 20:59:24 DEBUG RedisClient:287 - Connecting to Redis at /10.0.173.50:16379
> 20:59:24 DEBUG RedisClient:312 - Connecting to Redis at /10.0.173.50:16379: Success
> 20:59:24 DEBUG RedisClient:287 - Connecting to Redis at /10.0.173.55:16379
> 20:59:25 DEBUG RedisClient:312 - Connecting to Redis at /10.0.173.55:16379: Success
> 20:59:25 DEBUG RedisClient:287 - Connecting to Redis at /10.0.173.50:6379
> 20:59:25 DEBUG RedisClient:312 - Connecting to Redis at /10.0.173.50:6379: Success


Behind the firewall, the R3 connection attempt causes a timeout...
```
java.util.concurrent.CompletionException: com.lambdaworks.io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.5.245:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.lambdaworks.redis.AbstractRedisClient.lambda$initializeChannelAsync$1(AbstractRedisClient.java:305)
	at com.lambdaworks.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at com.lambdaworks.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at com.lambdaworks.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at com.lambdaworks.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at com.lambdaworks.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at com.lambdaworks.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:269)
	at com.lambdaworks.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at com.lambdaworks.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at com.lambdaworks.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at com.lambdaworks.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at com.lambdaworks.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at com.lambdaworks.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at com.lambdaworks.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.lambdaworks.io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.5.245:6379
	at com.lambdaworks.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	... 8 more
```

I'm not following where/why the slaves are being called, but I'm hoping there's a way to stop the connection to R3, since the timeout delay adds to the application startup time.

Thanks.

**Comment by mp911de** [comment]
That's a different issue. In short: Lettuce connects to all known nodes to verify connectivity and to get a response time (`PING`) for nearest node reads.

Closing this ticket as there is nothing left to do here.
