### ISSUE TITLE
Is there a way not initializing 'SyncCommandsImpl' when calling 'connect()'?

### ISSUE THREAD

**Issue by NickNYU** [lettuce-io/lettuce-core#677]
### Env: 
* os name="Linux" 
* arch="amd64" 
* version="3.10.0-229.11.1.el7.x86_64" 
* available-processors="4" 

### Lettuce Version:
4.3.2.Final

### Stack Dumps:
```
57: "globalExecutor-11" Id=133 BLOCKED on [I@6d593694 owned by "globalExecutor-10" Id=132
at java.lang.Class.getDeclaredConstructors0(Native Method)
- blocked on [I@6d593694
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
at java.lang.Class.getConstructor0(Class.java:3075)
at java.lang.Class.getConstructor(Class.java:1825)
at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:729)
at com.lambdaworks.redis.RedisChannelHandler.syncHandler(RedisChannelHandler.java:230)
at com.lambdaworks.redis.StatefulRedisConnectionImpl.newRedisSyncCommandsImpl(StatefulRedisConnectionImpl.java:93)
at com.lambdaworks.redis.StatefulRedisConnectionImpl.&lt;init&gt;(StatefulRedisConnectionImpl.java:78)
...

58: "globalExecutor-12" Id=134 BLOCKED on [I@6d593694 owned by "globalExecutor-10" Id=132
at java.lang.Class.getDeclaredConstructors0(Native Method)
- blocked on [I@6d593694
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
at java.lang.Class.getConstructor0(Class.java:3075)
at java.lang.Class.getConstructor(Class.java:1825)
at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:729)
at com.lambdaworks.redis.RedisChannelHandler.syncHandler(RedisChannelHandler.java:230)
at com.lambdaworks.redis.StatefulRedisConnectionImpl.newRedisSyncCommandsImpl(StatefulRedisConnectionImpl.java:93)
at com.lambdaworks.redis.StatefulRedisConnectionImpl.&lt;init&gt;(StatefulRedisConnectionImpl.java:78)
```

Hi experts,

I was wondering if there's a way to avoid initializing 'sync' when building a connection.

> Code is as below when establishing a connection to redis.
> The init process for 'sync', which, calling a `newRedisSyncCommandsImpl()` take couple of million-seconds, and would defenitely block other threads if you are establishing bunch of connections during your application's warm up time.

```Java
public StatefulRedisConnectionImpl(RedisChannelWriter<K, V> writer, RedisCodec<K, V> codec, long timeout, TimeUnit unit) {
        super(writer, timeout, unit);

        this.codec = codec;
        this.async = newRedisAsyncCommandsImpl();
        this.sync = newRedisSyncCommandsImpl();
        this.reactive = newRedisReactiveCommandsImpl();
    }
```

By digging deeper, it would be found that, it is actual the 'Proxy' that takes time and would locked by certain thread. As below:

```Java
protected <T> T syncHandler(Object asyncApi, Class<?>... interfaces) {
        FutureSyncInvocationHandler<K, V> h = new FutureSyncInvocationHandler<>((StatefulConnection) this, asyncApi, interfaces);
        return (T) Proxy.newProxyInstance(AbstractRedisClient.class.getClassLoader(), interfaces, h);
    }
```

So, my question is, that is there a way skipping the init process for 'sync' and get the 'Redis Connection' as well.

Thanks

Nick Zhu

**Comment by mp911de** [comment]
Lettuce allocates all API facades eagerly to prevent race conditions and synchronization in the later stage where connections are actually used. You're hitting Java's behavior that prevents parallel class initialization.

To answer your actual question: No, there's no possibility to skip initialization. 

Out of curiosity, why are you initializing multiple connections and why is warming time an issue to you?

**Comment by NickNYU** [comment]
Thank you, @mp911de 

I did so because I was trying to monitor bunch of redis servers(perhaps around 4000) through ping, and the application started with connecting those redis instances through lettuce

According to you reply, I think I'm going to optimize my code to avoid the parallel class initialization

**Comment by mp911de** [comment]
I'd suggest a more light-weight approach for your use case, maybe look into Jedis or implement the `PING` yourself by just using a tiny protocol sequence with Java sockets directly. Lettuce might come with too many features for this specific use case.
