### ISSUE TITLE
RedisCommandTimeoutException causing our production service unstable.

### ISSUE THREAD

**Issue by vchavan79** [lettuce-io/lettuce-core#683]
We are using Lettuce 4.3.2.Final to connect Azure Redis cache with below configurations.
Connection: Single Connection, Non-clustered, SSL and Sync. We are observing very frequent RedisCommandTimeoutException Command timed out (more than 15k exceptions in this month) for different commands which is causing our production service unstable.
Please note:
1. We have enabled Debug logs for com.lambdaworks.redis.protocol.ConnectionWatchdog and com.lambdaworks.redis.protocol but it is not helping.
2. We are using mget calls but the data we read is very minimum
3. This gets auto resolved and we are unable to do the RCA 
4. Redis cache server and application are healthy during the time frame when error/exception occurred. 
5. We observed connection reset happened around same time, but dont this this is the root cause because timeout occurring even though there is no connection reset
Can you please help us to understand possible reason for this exception? Also help to enable more logs that can give more insights on what is happening in library?

Sample stack trace is as below,
```
com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:113) ~[lettuce-4.3.2.Final.jar!/:?]
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:92) ~[lettuce-4.3.2.Final.jar!/:?]
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:63) ~[lettuce-4.3.2.Final.jar!/:?]
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-4.3.2.Final.jar!/:?]
	at com.sun.proxy.$Proxy119.mget(Unknown Source) ~[?:?]
	at no.vipps.common.cache.client.StandaloneRedisLettuceClient.mget(StandaloneRedisLettuceClient.java:105) ~[vipps-ms-common-cache-3.0.jar!/:3.0]
	at no.vipps.common.cache.service.RedisCacheServiceImpl.mget(RedisCacheServiceImpl.java:315) ~[vipps-ms-common-cache-3.0.jar!/:3.0]
```

**Comment by mp911de** [comment]
Lettuce 4 can run into issues with frequent reconnects. It has a shared Netty handler that gets reused across multiple TCP connections (usually, each connection has its own handler instance) and in cases, where a reconnect is faster than the actual disconnect processing, commands can get mixed up.

Getting rid of frequent connection resets should improve the overall behavior but that's something between the operating system and the Redis servers, maybe the Microsoft support is able to help there.

Can you upgrade to Lettuce 5? The next major version fixes that issue.

**Comment by vchavan79** [comment]
Thanks @mp911de  for your inputs. One strange thing we observed in logs and need your inputs.
Please see below logs for Connectionwatchdog and ReconnectionHandler.

**ConnectionWatchdog**
2018-01-24T06:54:38,928 thrId="[lettuce-eventExecutorLoop-1-2]" lLv="INFO" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ConnectionWatchdog" jMess=[[Reconnecting, last destination was cache-service/0.0.0.0:6380]]
2018-01-24T06:55:00,118 thrId="[lettuce-eventExecutorLoop-1-3]" lLv="INFO" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ConnectionWatchdog" jMess=[[Reconnecting, last destination was cache-service/0.0.0.0:6380]]
2018-01-24T06:55:10,119 thrId="[lettuce-eventExecutorLoop-1-3]" lLv="WARN" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ConnectionWatchdog" jMess=[[Cannot connect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 10000 MILLISECONDS]]
2018-01-24T06:55:10,217 thrId="[lettuce-eventExecutorLoop-1-4]" lLv="INFO" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ConnectionWatchdog" jMess=[[Reconnecting, last destination was cache-service/0.0.0.0:6380]]
2018-01-24T06:55:20,223 thrId="[lettuce-eventExecutorLoop-1-4]" lLv="WARN" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ConnectionWatchdog" jMess=[[Cannot connect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 10000 MILLISECONDS]]
2018-01-24T06:55:20,318 thrId="[lettuce-eventExecutorLoop-1-5]" lLv="INFO" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ConnectionWatchdog" jMess=[[Reconnecting, last destination was cache-service/0.0.0.0:6380]]
2018-01-24T06:57:59,420 thrId="[lettuce-eventExecutorLoop-1-6]" lLv="INFO" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ConnectionWatchdog" jMess=[[Reconnecting, last destination was cache-service/0.0.0.0:6380]]
2018-01-24T06:58:04,401 thrId="[lettuce-eventExecutorLoop-1-6]" lLv="ERROR" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ReconnectionHandler" jMess=[[Cannot initialize channel.]]
java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_131]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_131]
	at com.lambdaworks.redis.protocol.ReconnectionHandler.reconnect(ReconnectionHandler.java:102) ~[lettuce-4.3.2.Final.jar!/:?]
	at com.lambdaworks.redis.protocol.ConnectionWatchdog.reconnect(ConnectionWatchdog.java:287) ~[lettuce-4.3.2.Final.jar!/:?]
	at com.lambdaworks.redis.protocol.ConnectionWatchdog.run(ConnectionWatchdog.java:272) ~[lettuce-4.3.2.Final.jar!/:?]
	at com.lambdaworks.redis.protocol.ConnectionWatchdog$2.lambda$run$0(ConnectionWatchdog.java:225) ~[lettuce-4.3.2.Final.jar!/:?]
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source) ~[netty-handler-4.1.9.Final.jar!/:4.1.9.Final]
2018-01-24T06:58:04,401 thrId="[lettuce-eventExecutorLoop-1-6]" lLv="WARN" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ConnectionWatchdog" jMess=[[Cannot connect: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException]]

**ReconnectionHandler**
2018-01-24T06:55:27,364 thrId="[lettuce-eventExecutorLoop-1-5]" lLv="INFO" threadContext=[{}] jLoc="com.lambdaworks.redis.protocol.ReconnectionHandler" jMess=[[Reconnected to cache-service/0.0.0.0:6380]]

If you see these logs in watchdosg logs at 2018-01-24T06:55:20,318 thread id lettuce-eventExecutorLoop-1-5 is  Reconnecting and in handler logs at 2018-01-24T06:55:27,364 thread id lettuce-eventExecutorLoop-1-5 reconnected to cache. But again at 2018-01-24T06:57:59,420 thread id lettuce-eventExecutorLoop-1-6 trying to reconnect and it failed. 

Is this normal behavior?  Please note I have replaced actual cache name and ip in log with dummy values as this is production log .

**Comment by mp911de** [comment]
You're running in a lot of reconnects in a very short time. You can enable the debug log of `ConnectionWatchdog` to receive the actual time of disconnect. I don't know what's up with the servers, but in any case, you should investigate what's going on, even with tools like Wireshark to see what's happening on TCP level.

From my experience, reconnects should happen at most 1 to 2 times a day assuming your Redis server isn't crashing.

Lettuce uses a thread-pool to dispatch reconnect jobs and reconnect jobs may hit different threads even for the very same connection.

**Comment by s-aravind-flipkart** [comment]
Hi,
Even I'm facing a lot of timeouts I tried using 5.0 version of lettuce. I'm using the lettuce async connection to connect. When I start my application it seems like the connection is not established so I tried running the following function 
    private void checkIfHostsAreReachable() {
         AsyncExecutions ping = asyncConnection.async().all().commands().ping();
         Collection<RedisClusterNode> nodes = ping.nodes();
         nodes.stream().forEach(redisClusterNode -> ping.get(redisClusterNode));
    }
On my tcp connection side I see lot of timeouts as such Please let me know how could I load all the connections at my bootstrap.

**Comment by s-aravind-flipkart** [comment]
I'm seeing a timeout the connection is established.

**Comment by mp911de** [comment]
@s-aravind-flipkart Care to file a new issue along with some logs and stack traces?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
