### ISSUE TITLE
Lettuce master slave connection not work with Azure redis standard tier which has master slave replication

### ISSUE THREAD

**Issue by warrenzhu25** [lettuce-io/lettuce-core#728]
Azure redis standard and premium tier provide master slave replication by exposing one load balance endpoint. Requests to such endpoint will always be forwarded to master node. I suppose this should work with Standalone Master/Slave node according to https://github.com/lettuce-io/lettuce-core/wiki/Master-Slave, but got exceptions as below

```
Exception in thread "main" com.lambdaworks.redis.RedisConnectionException: Unable to establish a connection to Redis Cluster
	at com.lambdaworks.redis.masterslave.AsyncConnections.get(AsyncConnections.java:80)
	at com.lambdaworks.redis.masterslave.MasterSlaveTopologyRefresh.getNodes(MasterSlaveTopologyRefresh.java:76)
	at com.lambdaworks.redis.masterslave.MasterSlave.connectMasterSlave(MasterSlave.java:224)
	at com.lambdaworks.redis.masterslave.MasterSlave.connect(MasterSlave.java:118)
	at lettuce.LettuceTest.main(LettuceTest.java:25)
	Suppressed: com.lambdaworks.redis.RedisConnectionException: Unable to connect to RedisURI [host='warren-eus3.redis.cache.windows.net', port=6380]
		at com.lambdaworks.redis.masterslave.MasterSlaveTopologyRefresh.lambda$getConnections$0(MasterSlaveTopologyRefresh.java:160)
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
		at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
		at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
		at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
		at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
		at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.util.concurrent.CompletionException: com.lambdaworks.redis.RedisException: java.io.IOException: An existing connection was forcibly closed by the remote host
		at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
		at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
		... 5 more
	Caused by: com.lambdaworks.redis.RedisException: java.io.IOException: An existing connection was forcibly closed by the remote host
		at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:130)
		at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:96)
		at com.lambdaworks.redis.AbstractRedisAsyncCommands.auth(AbstractRedisAsyncCommands.java:80)
		at com.lambdaworks.redis.RedisClient.lambda$connectStatefulAsync$1(RedisClient.java:531)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
		... 6 more
	Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
		at sun.nio.ch.SocketDispatcher.read0(Native Method)
		at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
		at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
		at sun.nio.ch.IOUtil.read(IOUtil.java:192)
		at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
		at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
		at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
		at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
		... 3 more
```

But I can use normal `StatefulRedisConnection`, which worked fine.

Several questions regarding this:

1. Did I use Master\Slave the right way?
2. What's the difference between normal and master/slave connection?
3. Why such exception is thrown?

**Comment by mp911de** [comment]
Azure Redis prefers SSL connections and Lettuce does not support Master/Slave with SSL because Redis itself isn't aware of SSL ports. We introduced a change with #684 to retain SSL flags on the actual RedisURI if someone wants to use SSL with Master/Slave.

The difference between `MasterSlave.connect(…)` and `RedisClient.connect(…)` is that `MasterSlave` connections perform read routing themselves to slave nodes whereas `RedisClient.connect(…)` just operates on the node it is connected to.

I honestly do not know how Azure implemented Master/Slave with SSL. Lettuce uses details from `INFO REPLICATION` to determine node roles and addresses of the nodes.

I think the exception is thrown because the host you want to connect to (at port 6780) expects a SSL handshake and the client connected in plaintext mode.

You might want to use the current snapshot build (`4.4.3.SNAPSHOT`) to re-test with SSL enabled.
