### ISSUE TITLE
Creating a connection if Redis is not available yet

### ISSUE THREAD

**Issue by mrvisser** [lettuce-io/lettuce-core#742]
My application needs to continue running if Redis is unavailable. Part of that involves being able to startup successfully if Redis is unavailable, and be able to connect to Redis when/if it comes back.

I can get almost all of the way there using the default reconnect functionality that comes built in with lettuce. If I issue a command and it fails, I can continue normally. However I'm finding that if my application starts up, the following throws an exception:

```scala
val defaultClientResources = ClientOptions.builder()
      .cancelCommandsOnReconnectFailure(true)
      .disconnectedBehavior(DisconnectedBehavior.REJECT_COMMANDS)
      .build()
val client = RedisClient.create(defaultClientResources, "redis://localhost")
client.setOptions(defaultClientOptions)
val connection = client.connect() // Throws if Redis is not available!
```

This throws with:

```
Exception in thread "main" com.lambdaworks.redis.RedisConnectionException: Unable to connect to localhost/127.0.0.1:6379
	at com.lambdaworks.redis.RedisConnectionException.create(RedisConnectionException.java:45)
	at com.lambdaworks.redis.AbstractRedisClient.getConnection(AbstractRedisClient.java:263)
	at com.lambdaworks.redis.RedisClient.connectStandalone(RedisClient.java:466)
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:382)
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:369)
	at i.f.a.Application$.start(Application.scala:86)
	at AppMain$.main(AppMain.scala:11)
	at AppMain.main(AppMain.scala)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:225)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	... 11 more
```

What I perceive my ideal scenario to be is that I would still get a `StatefulRedisConnection` regardless if it was actually able to connect to the Redis server, however its built-in reconnect functionality would be in progress.

Without that type of operation, I'm forced to roll my own "try and reconnect" logic to get my initial connection.

Does anything like this exist with Lettuce? I haven't been able to pinpoint anything in the docs.

Thanks for the great Redis library!

**Comment by mp911de** [comment]
Thanks for using Lettuce, appreciate your feedback.

You can create `RedisClient`/`RedisClusterClient` upon application startup regardless of Redis availability. Calling `.connect()` initiates the actual connection and fails if Redis is not available.

You could do different things. Feasibility depends on how you've built your application:

1. Use a DI container to lazily create components. Depending on how the container manages components, you're able to start up but calling functionality that involves Redis interaction will fail.
2. Wrap `StatefulRedisConnection` within a Java Proxy with an `InvocationHandler` attached: This way you're able to pass `StatefulRedisConnection` around and the only bit you need is keeping state in the invocation handler to obtain a connection and delegate calls.
3. Use Connection-Pooling: While I'm not a huge fan of connection pooling, it could address your use-case. You can create a pool without pre-allocating objects and fetch a connection when necessary.

All mentioned approaches defer the actual connection to the time where you want to interact with Redis.

**Comment by mrvisser** [comment]
Thanks @mp911de, looks like my perceived ideal interface isn't available -- creating a connection that needs to reconnect later is not synonymous with having a connection that needs to reconnect later.

I started down the route of your suggestions 1 & 2 (both of which essentially lazily create a connection), however I found myself running into: "Well, what if this connection fails? I have to delay and reconnect, and reject all commands until connection is successful" -- which I imagine is exactly what the client is doing behind the scenes in the case where were were _initially_ able to connect to Redis, but later lost connection.

Would it be bad if `autoReconnect` is enabled, `connect()` always succeeds and initiates the reconnect behaviour? Maybe this is just food for thought in #622 .

**Comment by blackmichael** [comment]
I'm curious about how to go about solving this issue. My application is similar in which it needs to start up and run healthy without any coupling to the connection status with Redis. If redis is down to begin with, or goes down during the app instance's lifecycle, it should not impact the app.

Using a lazy instantiation of the connection works for redis being down upon app startup, but doesn't suffice when redis goes down afterwards.

**Comment by mrvisser** [comment]
We set autoReconnect to true and set it to reject commands on failure. Then we catch errors that come from any redis operations and gracefully degrade.

Lazy instantiationis one thing but if instantiation fails you need to roll your own back off and retry logic.

**Comment by mp911de** [comment]
Closing this one as there is nothing we can do here right now.
