### ISSUE TITLE
Warning when refreshing topology

### ISSUE THREAD

**Issue by theliro** [lettuce-io/lettuce-core#756]
Our application is getting intermittently this warning (every several hours). Looks like it is related to the issue #656 but the stack trace looks bit different. We cannot upgrade yet to any newer 5.0.* versions. Can it be a bug?

<pre>
WARN  io.lettuce.core.cluster.ClusterTopologyRefreshScheduler [lettuce-eventExecutorLoop-1-4] [|] [] [] [] - Cannot refresh Redis Cluster topology
java.util.ConcurrentModificationException: null
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) ~[na:1.8.0_121]
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247) ~[na:1.8.0_121]
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242) ~[na:1.8.0_121]
	at io.lettuce.core.cluster.topology.Connections.requestClients(Connections.java:98) ~[lettuce-core-5.0.1.RELEASE.jar:na]
	at io.lettuce.core.cluster.topology.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:71) ~[lettuce-core-5.0.1.RELEASE.jar:na]
	at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:787) ~[lettuce-core-5.0.1.RELEASE.jar:na]
	at io.lettuce.core.cluster.RedisClusterClient.reloadPartitions(RedisClusterClient.java:732) ~[lettuce-core-5.0.1.RELEASE.jar:na]
	at io.lettuce.core.cluster.ClusterTopologyRefreshScheduler$ClusterTopologyRefreshTask.run(ClusterTopologyRefreshScheduler.java:197) ~[lettuce-core-5.0.1.RELEASE.jar:na]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73) [netty-common-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) [netty-common-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.17.Final.jar:4.1.17.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
</pre>

Lettuce version: 5.0.1.RELEASE
JDK version: 8.0.121

Thanks

**Comment by mp911de** [comment]
Thanks for reporting the issue. It's a synchronization error.

**Comment by mp911de** [comment]
Have you customized `SocketOptions` or `RedisURI.getTimeout` regarding connection/command timeouts?

**Comment by mp911de** [comment]
There's a snapshot version (`5.0.4.BUILD-SNAPSHOT`) available that contains a fix for this issue. Care to give the snapshot a spin?

**Comment by theliro** [comment]
Yes, you are right. Both places (SocketOptions.connectionTimeout, RedisURI.getTimeout) contain our customizations. Thanks for the quick fix. It is not straightforward to test it but we will give it a try. When is the new version planned for release?

**Comment by mp911de** [comment]
If you make sure that connection timeout is less than the command timeout (by a second or so to be on the safe side), you shouldn't see that issue. 

Not quite sure about the release date. Lettuce 5.0.2.RELEASE is being picked up by Spring Boot today. If the workaround with connection timeouts works, I'd schedule a release for the end of April.

**Comment by theliro** [comment]
connection_timeout=2000, read_timeout=1000. So exactly the other way around. We will go with your suggestion and see how is going.
