### ISSUE TITLE
More than 20000 "java.lang.IndexOutOfBoundsException" exceptions threw in PROD env every day.

### ISSUE THREAD

**Issue by yourchanges** [lettuce-io/lettuce-core#810]
#### ENV:
spring boot : 2.0.3.RELEASE
java : 1.8
lettuce-core 5.0.4.RELEASE
redis: 3.2.8

#### Current Behavior
More than 20000 "java.lang.IndexOutOfBoundsException" exceptions threw in PROD env every day.
Any method, such as: stringRedisTemplate.opsForValue(), called, the exception threw out.

Any ideas to help us to solve this problem?

**Full exception stack:**
```
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: java.lang.IndexOutOfBoundsException: writerIndex(2147483647) + minWritableBytes(7194) exceeds maxCapacity(2147483647): PooledUnsafeDirectByteBuf(ridx: 2147288050, widx: 2147483647, cap: 2147483647)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:257) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:718) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.mGet(LettuceStringCommands.java:116) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.mGet(DefaultedRedisConnection.java:224) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.mGet(DefaultStringRedisConnection.java:710) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.core.DefaultValueOperations.lambda$multiGet$4(DefaultValueOperations.java:142) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at org.springframework.data.redis.core.DefaultValueOperations.multiGet(DefaultValueOperations.java:142) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	at com.ch999.web.jiuji.service.impl.ProductServiceImpl.getProductInRedisByPpids(ProductServiceImpl.java:245) ~[classes!/:0.0.1]
	at com.ch999.web.jiuji.service.impl.ProductServiceImpl.getProductInRedisWithPrice(ProductServiceImpl.java:406) ~[classes!/:0.0.1]
	at com.ch999.web.jiuji.service.impl.ProductServiceImpl.getDisplayProductInRedis(ProductServiceImpl.java:482) ~[classes!/:0.0.1]
	at com.ch999.web.jiuji.service.impl.ProductServiceImpl$$FastClassBySpringCGLIB$$3821c501.invoke(<generated>) ~[classes!/:0.0.1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at com.ch999.web.jiuji.service.impl.ProductServiceImpl$$EnhancerBySpringCGLIB$$d6688e8.getDisplayProductInRedis(<generated>) ~[classes!/:0.0.1]
	at com.ch999.web.jiuji.service.impl.ProductSearchServiceImpl.searchList(ProductSearchServiceImpl.java:414) ~[classes!/:0.0.1]
	at com.ch999.web.jiuji.service.impl.ProductSearchServiceImpl$$FastClassBySpringCGLIB$$f0bd5539.invoke(<generated>) ~[classes!/:0.0.1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	**at com.alicp.jetcache.anno.method.CacheHandler.invokeOrigin(CacheHandler.java:201) ~[jetcache-anno-2.5.1.jar!/:?]**
	at com.alicp.jetcache.anno.method.CacheHandler.access$000(CacheHandler.java:21) ~[jetcache-anno-2.5.1.jar!/:?]
	at com.alicp.jetcache.anno.method.CacheHandler$1.load(CacheHandler.java:158) ~[jetcache-anno-2.5.1.jar!/:?]
	at com.alicp.jetcache.CacheLoader.apply(CacheLoader.java:31) ~[jetcache-core-2.5.1.jar!/:?]
	at com.alicp.jetcache.CacheUtil.lambda$createProxyLoader$0(CacheUtil.java:70) ~[jetcache-core-2.5.1.jar!/:?]
	at com.alicp.jetcache.AbstractCache.computeIfAbsentImpl(AbstractCache.java:146) ~[jetcache-core-2.5.1.jar!/:?]
	at com.alicp.jetcache.AbstractCache.computeIfAbsent(AbstractCache.java:102) ~[jetcache-core-2.5.1.jar!/:?]
	at com.alicp.jetcache.Cache.computeIfAbsent(Cache.java:311) ~[jetcache-core-2.5.1.jar!/:?]
	at com.alicp.jetcache.SimpleProxyCache.computeIfAbsent(SimpleProxyCache.java:93) ~[jetcache-core-2.5.1.jar!/:?]
	at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:168) ~[jetcache-anno-2.5.1.jar!/:?]
	at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:92) ~[jetcache-anno-2.5.1.jar!/:?]
	at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:84) ~[jetcache-anno-2.5.1.jar!/:?]
	at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:68) ~[jetcache-anno-2.5.1.jar!/:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at com.ch999.web.jiuji.service.impl.ProductSearchServiceImpl$$EnhancerBySpringCGLIB$$65fb01f0.searchList(<generated>) ~[classes!/:0.0.1]
	at com.ch999.web.jiuji.api.ProductApi.search(ProductApi.java:204) [classes!/:0.0.1]
	at sun.reflect.GeneratedMethodAccessor1069.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) [spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158) [spring-boot-actuator-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126) [spring-boot-actuator-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111) [spring-boot-actuator-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) [spring-boot-actuator-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: io.lettuce.core.RedisException: java.lang.IndexOutOfBoundsException: writerIndex(2147483647) + minWritableBytes(7194) exceeds maxCapacity(2147483647): PooledUnsafeDirectByteBuf(ridx: 2147288050, widx: 2147483647, cap: 2147483647)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:125) ~[lettuce-core-5.0.4.RELEASE.jar!/:?]
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:62) ~[lettuce-core-5.0.4.RELEASE.jar!/:?]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-5.0.4.RELEASE.jar!/:?]
	at com.sun.proxy.$Proxy402.mget(Unknown Source) ~[?:?]
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.mGet(LettuceStringCommands.java:114) ~[spring-data-redis-2.0.8.RELEASE.jar!/:2.0.8.RELEASE]
	... 99 more
```

**Comment by yourchanges** [comment]
Does this related to the config properties "requestQueueSize"?  the error msg contains "exceeds maxCapacity(2147483647)"

**Comment by yourchanges** [comment]
We use kryo to se/de the data, and seems the exception cased by netty-io buffer index out of bounds:

netty-io related codes:
```
if (minWritableBytes > maxCapacity - writerIndex) {
throw new IndexOutOfBoundsException(String.format(
"writerIndex(%d) + minWritableBytes(%d) exceeds maxCapacity(%d): %s",
writerIndex, minWritableBytes, maxCapacity, this));
}
```

**Comment by mp911de** [comment]
Do you have more details on the stack trace or a debug log? Right now, we don't see where the issue was caused. Please run your JVM with `-XX:-OmitStackTraceInFastThrow` to retain stack traces for JVM-builtin exceptions.

The buffer reached its maximal limit of 2GB (2,147,483,648) and it can't read beyond that. What's the average size of the payload (keys/values)?

**Comment by yourchanges** [comment]
here are two jvm node dump files:

[https://github.com/yourchanges/clicker/blob/master/tmp.zip?raw=true](https://github.com/yourchanges/clicker/blob/master/tmp.zip?raw=true)

The average size of the payload :

1. the key is just simple string, the size smaller than 128 bytes
2. the average size of the value  is < 200 KB

there is no permit to add "-XX:-OmitStackTraceInFastThrow" for us.

The dump files generated by a auto-bot script withou "-XX:-OmitStackTraceInFastThrow" , similar like:

```
jstack $PID > $DUMP_DIR/jstack-$PID-$DUMP_DATE.dump 2>&1
	echo -e ".\c"
	
	jinfo $PID > $DUMP_DIR/jinfo-$PID-$DUMP_DATE.dump 2>&1
	echo -e ".\c"
	
	jstat -gcutil $PID > $DUMP_DIR/jstat-gcutil-$PID-$DUMP_DATE.dump 2>&1
	echo -e ".\c"
	
	jstat -gccapacity $PID > $DUMP_DIR/jstat-gccapacity-$PID-$DUMP_DATE.dump 2>&1
	echo -e ".\c"
	
	jmap $PID > $DUMP_DIR/jmap-$PID-$DUMP_DATE.dump 2>&1
	echo -e ".\c"
	
	jmap -F -heap $PID > $DUMP_DIR/jmap-heap-$PID-$DUMP_DATE.dump 2>&1
	echo -e ".\c"
	
	jmap -F -histo $PID > $DUMP_DIR/jmap-histo-$PID-$DUMP_DATE.dump 2>&1
	echo -e ".\c"
	
	if [ -r /usr/sbin/lsof ]; then
	   /usr/sbin/lsof -p $PID > $DUMP_DIR/lsof-$PID-$DUMP_DATE.dump
	   echo -e ".\c"
	fi

```

**Comment by mp911de** [comment]
The attached dumps do not help as they don't reveal where the `IndexOutOfBoundsException` happened. We can't do anything without that detail right now.

I think the only actionable item is to reduce the number of keys in your `MGET` request to see whether that has some effect.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by yourchanges** [comment]
Thank you, we move back to jedis to avoid this problem.

Mark Paluch <notifications@github.com> 于2018年7月23日周一 下午5:50写道：

**Comment by dileepbapat** [comment]
io/netty/buffer/AbstractByteBuf.java:117, writerIndex steadily keep increasing when lettuce is used with Spring boot (@Cachable annotation) cache type redis and rest are default 

once writerIndex reaches max 2147483647 it starts throwing the exception
```
java.lang.IndexOutOfBoundsException: writerIndex(2147483644) + minWritableBytes(1842) exceeds maxCapacity(2147483647): PooledUnsafeDirectByteBuf(ridx: 2147269192, widx: 2147483644, cap: 2147483647)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:276)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:265)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1079)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1072)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1062)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:506)
```

btw, test just uses same request repeating so there will be cache put only in the beginning later its just read.  

let me know if you need any specific info

**Comment by dileepbapat** [comment]
io.lettuce.core.protocol.CommandHandler#buffer this is buffer that keeps growing

**Comment by mp911de** [comment]
@dileepbapat Which Lettuce version are you using? I think it would make sense to file a new ticket for this one.
