### ISSUE TITLE
SETHOOK: Problem with arguments: ERR invalid argument '89.050032'

### ISSUE THREAD

**Issue by robmir44** [lettuce-io/lettuce-core#811]
Hello,

I have created via an Interface a new customer command: 
```
@Command("SETHOOK ?0 ?1 NEARBY ?2 FENCE POINT ?3 ?4")
List<Object> setHookIntersect(String webHook, String addr, String key, double Lon, double Lat);

```

Then i try to call it, see the example below, but I get each time an exception (see below):
`List<Object> xyz              = commands.setHookIntersect("myHook", "http://127.0.0.1:1001", "fleet", 89.050032, 32.102624);
`
```
Exception in thread "main" io.lettuce.core.RedisCommandExecutionException: ERR invalid argument '89.050032'
	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:85)
	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:46)
	at io.lettuce.core.dynamic.AsyncExecutableCommand.dispatchCommand(AsyncExecutableCommand.java:81)
	at io.lettuce.core.dynamic.AsyncExecutableCommand.execute(AsyncExecutableCommand.java:53)
	at io.lettuce.core.dynamic.RedisCommandFactory$CommandFactoryExecutorMethodInterceptor.invoke(RedisCommandFactory.java:227)
	at io.lettuce.core.dynamic.intercept.MethodInterceptorChain$MethodInterceptorContext.proceed(MethodInterceptorChain.java:117)
	at io.lettuce.core.dynamic.intercept.MethodInterceptorChain$PooledMethodInvocation.proceed(MethodInterceptorChain.java:194)
	at io.lettuce.core.dynamic.intercept.DefaultMethodInvokingInterceptor.invoke(DefaultMethodInvokingInterceptor.java:45)
	at io.lettuce.core.dynamic.intercept.MethodInterceptorChain$MethodInterceptorContext.proceed(MethodInterceptorChain.java:117)
	at io.lettuce.core.dynamic.intercept.MethodInterceptorChain.invoke(MethodInterceptorChain.java:79)
	at io.lettuce.core.dynamic.intercept.InvocationProxyFactory$InterceptorChainInvocationHandler.handleInvocation(InvocationProxyFactory.java:101)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
```
Could you tell me what is the Problem? thanks

**Comment by mp911de** [comment]
I can't tell you where your problem is as I don't know (I'm not familiar with) Tile 38. You might want to enable `TRACE` logging for `io.lettuce.core.protocol` to retrieve the command string that is sent to Tile 38 and see whether it matches the protocol specification.

**Comment by robmir44** [comment]
Thanks for the comment, but how can I activate this logger?

**Comment by mp911de** [comment]
That's something to configure in your logging configuration. For e.g. logback that would be `<logger name="io.lettuce.core.protocol" level="trace" />`

**Comment by robmir44** [comment]
Hello mp911de,

here my trace:

11:28:56.097 [lettuce-nioEventLoop-4-1] DEBUG i.l.core.protocol.CommandHandler - [channel=0x76e69822, /127.0.0.1:58046 -> localhost/127.0.0.1:9851, chid=0x1] write(ctx, AsyncCommand [type=SETHOOK, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], promise)
11:28:56.098 [lettuce-nioEventLoop-4-1] DEBUG i.l.core.protocol.CommandEncoder - [channel=0x76e69822, /127.0.0.1:58046 -> localhost/127.0.0.1:9851] writing command AsyncCommand [type=SETHOOK, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
11:28:56.098 [main] DEBUG i.l.core.protocol.DefaultEndpoint - [channel=0x76e69822, /127.0.0.1:58046 -> localhost/127.0.0.1:9851, epid=0x1] write() done
11:28:56.098 [lettuce-nioEventLoop-4-1] TRACE i.l.core.protocol.CommandEncoder - [channel=0x76e69822, /127.0.0.1:58046 -> localhost/127.0.0.1:9851] Sent: *9
$7
SETHOOK
$6
myHook
$21
http://127.0.0.1:1001
$6
NEARBY
$5
fleet
$5
FENCE
$5
POINT
$9
49.050032
$9
12.102624
11:28:56.099 [lettuce-nioEventLoop-4-1] DEBUG i.l.core.protocol.CommandHandler - [channel=0x76e69822, /127.0.0.1:58046 -> localhost/127.0.0.1:9851, chid=0x1] Received: 35 bytes, 1 commands in the stack
11:28:56.099 [lettuce-nioEventLoop-4-1] TRACE i.l.core.protocol.CommandHandler - [channel=0x76e69822, /127.0.0.1:58046 -> localhost/127.0.0.1:9851, chid=0x1] Buffer: -ERR invalid argument '49.050032'
11:28:56.099 [lettuce-nioEventLoop-4-1] DEBUG i.l.core.protocol.CommandHandler - [channel=0x76e69822, /127.0.0.1:58046 -> localhost/127.0.0.1:9851, chid=0x1] Stack contains: 1 commands
11:28:56.099 [lettuce-nioEventLoop-4-1] DEBUG i.l.core.protocol.RedisStateMachine - Decode AsyncCommand [type=SETHOOK, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
11:28:56.099 [lettuce-nioEventLoop-4-1] DEBUG i.l.core.protocol.RedisStateMachine - Decoded AsyncCommand [type=SETHOOK, output=ArrayOutput [output=[], error='ERR invalid argument '49.050032''], commandType=io.lettuce.core.protocol.Command], empty stack: true

**Comment by mp911de** [comment]
Cool, now make sure that the sent command

```
*9
$7
SETHOOK
$6
myHook
$21
http://127.0.0.1:1001
$6
NEARBY
$5
fleet
$5
FENCE
$5
POINT
$9
49.050032
$9
12.102624
```

is what Tile38 expects. Happy to improve if there's something we can do to optimize for compatibility.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
