### ISSUE TITLE
GEP/PUT call hangs forever

### ISSUE THREAD

**Issue by Vishal-Nagpure** [lettuce-io/lettuce-core#814]
Hi,

Recently we experience an intermittent issue with Redis cache during GET/PUT data from Redis. We took the thread dump and can see all the consumers are in waiting state in GET call of redis and service no longer serve new requests. The reason why threads are waiting is because of NETTY which is getting used by lettuce client. Please see the stacktrace below.

```at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:261)
    at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135)
    at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28)
    at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:347)
    at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:123)
    at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:28)
    at com.lambdaworks.redis.protocol.CommandHandler.close(CommandHandler.java:895)
       local variable: com.lambdaworks.redis.protocol.CommandHandler#1
    at com.lambdaworks.redis.cluster.ClusterDistributionChannelWriter.close(ClusterDistributionChannelWriter.java:168)
    at com.lambdaworks.redis.RedisChannelHandler.close(RedisChannelHandler.java:91)
       local variable: com.lambdaworks.redis.cluster.StatefulRedisClusterConnectionImpl#2
    at org.springframework.data.redis.connection.lettuce.LettuceConnection.returnDedicatedAsyncConnection(LettuceConnection.java:417)
    at org.springframework.data.redis.connection.lettuce.LettuceConnection.close(LettuceConnection.java:430)
       local variable: org.springframework.data.redis.connection.lettuce.LettuceClusterConnection#1
    at org.springframework.data.redis.connection.lettuce.LettuceClusterConnection.close(LettuceClusterConnection.java:1549)
    at org.springframework.data.redis.core.RedisConnectionUtils.releaseConnection(RedisConnectionUtils.java:212)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:217)
       local variable: org.springframework.dao.QueryTimeoutException#1
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:157)
    at org.springframework.data.redis.cache.RedisCache.get(RedisCache.java:172)
       local variable: org.springframework.data.redis.cache.RedisCacheKey#1
    at com.company.epmp.common.caching.redis.MonitorableRedisCache.get(MonitorableRedisCache.java:81)
    at org.springframework.data.redis.cache.RedisCache.get(RedisCache.java:133)
    at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:71)
    at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:537)
    at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:503)
       local variable: java.lang.String#125761
       local variable: java.util.LinkedList$ListItr#1
       local variable: org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext#1
    at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:389)
       local variable: org.springframework.cache.interceptor.CacheInterceptor$1#1
       local variable: org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContexts#1
    at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
    at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:115)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
       local variable: org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation#1
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
       local variable: com.company.epmp.scsem.services.event.hydration.DefaultDeviceMDRGateway$$EnhancerBySpringCGLIB$$20dc2bfd#1
       local variable: org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor#62
       local variable: com.product.services.event.hydration.DefaultDeviceMDRGateway#1
```

```java
final LettuceConnectionFactory lettuceConnectionFactory = new LettuceConnectionFactory(new RedisClusterConfiguration(redisClusterNodes));
      lettuceConnectionFactory.setTimeout(10000);
      lettuceConnectionFactory.setUseSsl(true);
      lettuceConnectionFactory.setVerifyPeer(false);
      lettuceConnectionFactory.setStartTls(false);
      lettuceConnectionFactory.afterPropertiesSet();
```

#### Environment

- Lettuce version(s): 4.2.2.Final

**Comment by mp911de** [comment]
Please upgrade to a newer version, the latest version of Lettuce 4 is `4.4.5.Final`. A full thread dump would be helpful as the excerpt does not show anything that is useful.

**Comment by Vishal-Nagpure** [comment]
I have attached thread dump. Please search for a.b.load.queue-5 to get the entire trace.
[thread_dump.txt](https://github.com/lettuce-io/lettuce-core/files/2201128/thread_dump.txt)

**Comment by mp911de** [comment]
Thanks a lot. The dump shows that the netty event loop threads are blocked with creating connections to cluster nodes. It seems that your cluster is reconfigured and sending `ASK` and `MOVED` redirections. Lettuce in version 4.2 uses blocking connect methods and that's why all netty event loop threads are exhausted. Upgrading to a newer version will solve the issue. 

There's nothing else that you could do here nor we can fix from our side as the fix is included already in a newer version.
