### ISSUE TITLE
Cannot assign requested address while establishing connection

### ISSUE THREAD

**Issue by Vishal-Nagpure** [lettuce-io/lettuce-core#815]
Hi,

I can see an intermittent issue connecting to Redis with below stacktrace. I am not adding/removing the nodes of the cluster during these operations. Any idea why is this happening?

```AMQPpqrMessageListener - 
org.springframework.data.redis.RedisConnectionFailureException: Redis connection failed; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /100.122.144.245:6379
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:62)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:334)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.exists(LettuceConnection.java:897)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:57)
	at com.sun.proxy.$Proxy82.exists(Unknown Source)
	at org.springframework.data.redis.cache.RedisCache$AbstractRedisCacheCallback.waitForLock(RedisCache.java:601)
	at org.springframework.data.redis.cache.RedisCache$AbstractRedisCacheCallback.doInRedis(RedisCache.java:564)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:207)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:157)
	at org.springframework.data.redis.cache.RedisCache.evict(RedisCache.java:273)
	at org.springframework.data.redis.cache.RedisCache.evict(RedisCache.java:262)
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doEvict(AbstractCacheInvoker.java:98)
	at org.springframework.cache.interceptor.CacheAspectSupport.performCacheEvict(CacheAspectSupport.java:480)
	at org.springframework.cache.interceptor.CacheAspectSupport.processCacheEvicts(CacheAspectSupport.java:463)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:421)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:115)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.product.xyz.abc.services.pqr.hydration.DefaultDevicelmnGateway$$EnhancerBySpringCGLIB$$80ac2548.removeDeviceInfoFromCache(<generated>)
	at com.product.xyz.abc.services.pqr.domainpqrhandlers.DevicepqrHandler.handle(DevicepqrHandler.java:44)
	at com.product.xyz.abc.services.pqr.domainpqrhandlers.DevicepqrHandler$$FastClassBySpringCGLIB$$decf7d39.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:115)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.product.xyz.abc.services.pqr.domainpqrhandlers.DevicepqrHandler$$EnhancerBySpringCGLIB$$6ee320a1.handle(<generated>)
	at com.product.xyz.host.executors.amqppqr.AMQPpqrMessageListener.onMessage(AMQPpqrMessageListener.java:116)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:891)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:782)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:102)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:198)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1311)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:752)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1254)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1224)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:102)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1470)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /100.122.144.245:6379
	at com.lambdaworks.redis.AbstractRedisClient.initializeChannel(AbstractRedisClient.java:250)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectStateful0(RedisClusterClient.java:679)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectStateful(RedisClusterClient.java:643)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectClusterImpl(RedisClusterClient.java:523)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connect(RedisClusterClient.java:335)
	at org.springframework.data.redis.connection.lettuce.LettuceClusterConnection.doGetAsyncDedicatedConnection(LettuceClusterConnection.java:1234)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.getDedicatedConnection(LettuceConnection.java:3996)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.getConnection(LettuceConnection.java:3956)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.exists(LettuceConnection.java:895)
	... 50 common frames omitted
Caused by: java.net.SocketException: Cannot assign requested address: /100.122.144.245:6379
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:203)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1226)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:549)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:534)
	at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:549)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:534)
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:549)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:534)
	at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:549)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:534)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:516)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:970)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:215)
	at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:166)
	at io.netty.util.concurrent.SingleThreadpqrExecutor.runAllTasks(SingleThreadpqrExecutor.java:408)
	at io.netty.channel.nio.NiopqrLoop.run(NiopqrLoop.java:402)
	at io.netty.util.concurrent.SingleThreadpqrExecutor$2.run(SingleThreadpqrExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 common frames omitted
```
Input Code
```
final LettuceConnectionFactory lettuceConnectionFactory = new LettuceConnectionFactory(new RedisClusterConfiguration(redisClusterNodes));
      lettuceConnectionFactory.setTimeout(10000);
      lettuceConnectionFactory.setUseSsl(true);
      lettuceConnectionFactory.setVerifyPeer(false);
      lettuceConnectionFactory.setStartTls(false);
      lettuceConnectionFactory.afterPropertiesSet();
```

#### Environment

- Lettuce version(s): 4.2.2.Final

**Comment by mp911de** [comment]
Spring Data Redis does not share/hold an open connection across multiple Redis operation calls. Therefore, cluster connections are quickly established/closed which causes that you run out of ephemeral ports. You can upgrade either to Spring Data Redis 2.0 and use pooling, or wait until version 2.1 is released as it keeps a cluster connection open. There's nothing else that you could do.

**Comment by Vishal-Nagpure** [comment]
I think ephemeral ports have sufficient range. When I use the same version of spring-data-redis (1.8.10.RELEASE) with Jedis, I do not see this issue. Why do you think ephemeral ports are getting exhausted?

**Comment by mp911de** [comment]
See my previous comment: 

> Cluster connections are quickly established/closed which causes that you run out of ephemeral ports.

To fix this:

> You can upgrade either to Spring Data Redis 2.0 and use pooling, or wait until version 2.1 is released as it keeps a cluster connection open. There's nothing else that you could do.
