### ISSUE TITLE
Could not generate CGLIB subclass of class io.lettuce.core.support.ConnectionPoolSupport$1

### ISSUE THREAD

**Issue by peerit12** [lettuce-io/lettuce-core#843]
#### Current Behavior

I am current using lettuce for the redis cache implementation.

#### Input Code

Tried to use connection pooling support for redis connection

but got this exception

Unable to register MBean [clusterConnection] with key 'clusterConnection'; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class io.lettuce.core.support.ConnectionPoolSupport$1: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null

GenericObjectPool<StatefulRedisClusterConnection<String, Object>> pool = ConnectionPoolSupport
    			.createGenericObjectPool(()->clusterClient.connect(new SerializedObjectCodec()),genericPollConfig );

I was using this code for creating connection poll.

Please suggest some solution

**Comment by mp911de** [comment]
What are you trying to achieve and why do you want to subclass an anonymous inner class?

**Comment by peerit12** [comment]
I am trying to create connection pool for redis connection.For creating connection pool I am using ConnectionPoolSupport of lettuce-core

I want my GenericObjectPool to  store pool of 
StatefulRedisClusterConnection<String, Object>

want to get StatefulRedisClusterConnection Object from this pool.

ERROR  org.springframework.boot.SpringApplication.reportFailure - Application run failed
org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [clusterConnection] with key 'clusterConnection'; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class io.lettuce.core.support.ConnectionPoolSupport$1: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.lambda$registerBeans$2(MBeanExporter.java:551) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jmx.export.MBeanExporter$$Lambda$934/663716901.accept(Unknown Source) ~[na:na]
	at java.util.HashMap.forEach(HashMap.java:1280) ~[na:1.8.0_45]
	at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:551) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.afterSingletonsInstantiated(MBeanExporter.java:434) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:777) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at com.franconnect.multitenant.SkyTenantsConfigApplication.main(SkyTenantsConfigApplication.java:55) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [fcsky-common-multitenant-config-0.0.1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [fcsky-common-multitenant-config-0.0.1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [fcsky-common-multitenant-config-0.0.1.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [fcsky-common-multitenant-config-0.0.1.jar:na]
Caused by: org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class io.lettuce.core.support.ConnectionPoolSupport$1: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:208) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.registerLazyInit(MBeanExporter.java:708) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:596) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 23 common frames omitted
Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:345) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_45]
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:480) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:337) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:58) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:205) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 26 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 39 common frames omitted
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_45]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_45]
	... 44 common frames omitted

**Comment by mp911de** [comment]
I'm not sure we can do something about this issue here. Care to post your boot config? Currently, we cannot see why Spring is trying to create a proxy around `ConnectionPoolSupport$1`

`ConnectionPoolSupport$1` is not defined `final`, according to

```
RedisClient client = RedisClient.create();

GenericObjectPool<StatefulRedisConnection<String, String>> pool = ConnectionPoolSupport
		.createGenericObjectPool(client::connect, new GenericObjectPoolConfig());

System.out.println(Modifier.isFinal(pool.getClass().getModifiers()));
```

**Comment by peerit12** [comment]
So how do i proceed further please suggest any solution.
I am currently using SpringBoot  springBootVersion = '2.0.3.RELEASE'
if any other information you need then please let me know

**Comment by mp911de** [comment]
Please provide a project that is able to reproduce the issue (Ideally using start.spring.io). Currently, we cannot see why Spring is trying to create a proxy around `ConnectionPoolSupport$1`?

**Comment by peerit12** [comment]
[redis-sample.zip](https://github.com/lettuce-io/lettuce-core/files/2366480/redis-sample.zip)

I have uploaded my project . please use redis host in application.properties
when you try to run this application then shows the same error

**Comment by mp911de** [comment]
Closing this one as we cannot do anything further here.
