### ISSUE TITLE
Failed to submit a listener notification task. Event loop shut down?

### ISSUE THREAD

**Issue by LiLong329** [lettuce-io/lettuce-core#848]
## Bug Report
2018-09-17 14:23:57.268 ERROR 18436 --- [ool-1-thread-36] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?

Exception in thread "pool-1-thread-18" org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.util.concurrent.CancellationException
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:53)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:43)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:257)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:718)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.incrBy(LettuceStringCommands.java:351)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.incrBy(DefaultedRedisConnection.java:294)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.incrBy(DefaultStringRedisConnection.java:538)
	at org.springframework.data.redis.core.DefaultValueOperations.lambda$increment$0(DefaultValueOperations.java:82)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
	at org.springframework.data.redis.core.DefaultValueOperations.increment(DefaultValueOperations.java:82)
	at com.example.redislettucedemo.RedisLettuceDemoApplicationTests.lambda$null$0(RedisLettuceDemoApplicationTests.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
Exception in thread "pool-1-thread-19" Exception in thread "pool-1-thread-17" org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.util.concurrent.CancellationException

Exception in thread "pool-1-thread-2" Exception in thread "pool-1-thread-6" org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is java.lang.IllegalStateException: Pool not open

#### Current Behavior

A clear and concise description of the behavior.

#### Input Code

- Java/Kotlin/Scala/Groovy/… or Repo link if applicable:

```java
// your code here;



 @Test
    public void get() {
        ExecutorService executorService = Executors.newFixedThreadPool(20);
        IntStream.range(0, 300).forEach(i ->
                executorService.execute(() -> stringRedisTemplate.opsForValue().increment("kk:t1", 1))
        );
        final String k1 = stringRedisTemplate.opsForValue().get("kk:t1");
        System.out.println("[字符缓存结果] - [{}]" + k1);
    }

如果固定线程池的话，并发请求超过线程池容量就会出异常，如果使用jedis连接池就不会，不知道怎么解决，请指教
```

#### Expected behavior/code

A clear and concise description of what you expected to happen (or code).

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

#### Additional context

Add any other context about the problem here. Do not add code as screenshots.

**Comment by mp911de** [comment]
The issue happens because the test does not await task completion and keeps executing Redis commands after the test is completed. Nothing we can do here, please fix your test.

**Comment by LiLong329** [comment]
Problem solving, Junit unit testing does not support multithreading.

Thank you.

**Comment by min90** [comment]
Just for the sake of it, I had the same issue with my test blocking due to not closing the eventloop group properly. I managed to solve it by using shutdownAsync(), because of the quiet period and timeout before closing down.
