### ISSUE TITLE
ClassCastException occurs when executing RedisClusterClient::connectPubSub with global timeout feature

### ISSUE THREAD

**Issue by be-hase** [lettuce-io/lettuce-core#895]
#### Current Behavior

In lettuce 5.1.1, an error occurs under the following conditions.

- Set global timeout at `ClusterClientOptions`
- Execute `RedisClusterClient::connectPubSub()`

```
java.lang.ClassCastException: io.lettuce.core.protocol.CommandExpiryWriter cannot be cast to io.lettuce.core.cluster.ClusterDistributionChannelWriter

	at io.lettuce.core.cluster.StatefulRedisClusterPubSubConnectionImpl.getClusterDistributionChannelWriter(StatefulRedisClusterPubSubConnectionImpl.java:205)
	at io.lettuce.core.cluster.StatefulRedisClusterPubSubConnectionImpl.setPartitions(StatefulRedisClusterPubSubConnectionImpl.java:168)
	at io.lettuce.core.cluster.RedisClusterClient.connectClusterPubSubAsync(RedisClusterClient.java:663)
	at io.lettuce.core.cluster.RedisClusterClient.connectPubSub(RedisClusterClient.java:422)
	at io.lettuce.core.cluster.RedisClusterClient.connectPubSub(RedisClusterClient.java:393)

```

#### Input Code

```java
final ClusterClientOptions clusterClientOptions =
        ClusterClientOptions.builder()
                            .timeoutOptions(TimeoutOptions.enabled(Duration.ofSeconds(5)))
                            .build();

final RedisClusterClient redisClusterClient =
        RedisClusterClient.create(RedisURI.builder()
                                          .withHost("....")
                                          .withPort(...)
                                          .withPassword("...")
                                          .build());
redisClusterClient.setOptions(clusterClientOptions);

redisClusterClient.connectPubSub();
```

#### Environment

- Lettuce version(s): 5.1.1.RELEASE
- Redis version: 4.0.10

**Comment by mp911de** [comment]
Thanks for the report. That's fixed now.

**Comment by be-hase** [comment]
Thanks :)
