### ISSUE TITLE
Lettuce fail to connect to redis, when one of the master nodes goes to fail state.

### ISSUE THREAD

**Issue by vinaycn** [lettuce-io/lettuce-core#909]
## Bug Report

Lettuce fail to connect to redis, when one of the master nodes goes to fail state.

#### Current Behavior

I have redis cluster running in the docker container. When I manually stop the master  container, redis cluster will try to bring up that master or promote. For reason after container is up it goes to fail state. And then lettuce fails to connect to redis.

#### Input Code

@Bean(destroyMethod = "shutdown") public ClientResources clientResources ()
    {
        return DefaultClientResources.create();
    }

    @Bean(destroyMethod = "shutdown")
    public RedisClusterClient redisClusterClient (
        ClientResources clientResources)
    {
        RedisClusterClient redisClusterClient = null;
        if (!redisproperties.isRedisUseMock()) {

            String firstNode = redisproperties.getRedisHostName();
            StringBuilder uri = new StringBuilder();
            uri.append("redis://").append(redisproperties.getRedisPassword()).append("@").append(
                firstNode);

            ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder().enablePeriodicRefresh(
                Duration.ofMinutes(5)).
                enableAllAdaptiveRefreshTriggers().build();

            redisClusterClient = RedisClusterClient.create(clientResources,
                uri.toString());
            redisClusterClient.setOptions(ClusterClientOptions.builder().autoReconnect(
                true).cancelCommandsOnReconnectFailure(true).disconnectedBehavior(
                ClientOptions.DisconnectedBehavior.REJECT_COMMANDS).topologyRefreshOptions(
                topologyRefreshOptions).
                build());

        }
        return redisClusterClient;
    }

    @Bean(destroyMethod = "close")
    public StatefulRedisClusterConnection<String, String> clusterConnection (
        RedisClusterClient redisClusterClient)
    {

        StatefulRedisClusterConnection<String, String> statefulRedisClusterConnection = null;
        if(!redisproperties.isRedisUseMock()) {

            try {
                statefulRedisClusterConnection = redisClusterClient.connect();
            }
            catch (RedisException e) {
                //redis configuration not available during start up time
                logger.error("unable to connect to redis cluster during the start up " + e);
            }

        }
        return statefulRedisClusterConnection;
    }

#### Expected behavior/code

Even though one of the master node is failing. Lettuce should try to connect to other master nodes which will be available.

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

#### Additional context

018-10-31 03:48:11.389 DEBUG 66 --- [nio-8092-exec-8] c.a.m.o.c.OAuthStatusCheckController     : Entering OAuth Status Check API
2018-10-31 03:48:13.214  INFO 66 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.18.0.5:6379
2018-10-31 03:48:13.217  WARN 66 --- [ioEventLoop-4-1] i.l.c.c.topology.ClusterTopologyRefresh  : Unable to connect to 172.18.0.5:6379

java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.18.0.5:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:329)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:616)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.18.0.5:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 11 common frames omitted

2018-10-31 03:48:13.218  WARN 66 --- [ioEventLoop-4-3] i.l.c.c.topology.ClusterTopologyRefresh  : Unable to connect to 172.18.0.4:6379

java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.18.0.4:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:329)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:616)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.18.0.4:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 11 common frames omitted

2018-10-31 03:48:13.220  WARN 66 --- [ioEventLoop-4-2] i.l.core.protocol.ConnectionWatchdog     : Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.18.0.5:6379
2018-10-31 03:48:21.389 DEBUG 66 --- [nio-8092-exec-9] c.a.m.oauth.security.filter.CorsFilter   : Got origin as [null]
2018-10-31 03:48:21.389 DEBUG 66 --- [nio-8092-exec-9] c.a.m.o.s.f.BasicAuthenticationFilter    :  in com.ariba.matrix.oauth.security.filter.BasicAuthenticationFilter.doFilter
2018-10-31 03:48:21.390 DEBUG 66 --- [nio-8092-exec-9] c.a.m.o.c.OAuthStatusCheckController     : Entering OAuth St

**Comment by mp911de** [comment]
What is the value of `firstNode`? The log shows connection refused to `172.18.0.4` and `172.18.0.5`. How do these hosts relate to a single container that was shut down?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
