### ISSUE TITLE
Call to xdel() blocks until xreadgroup() block time has passed. 

### ISSUE THREAD

**Issue by rainhacker** [lettuce-io/lettuce-core#917]
#### Current Behavior

Call to xdel() blocks until xreadgroup() block time has passed. 

In the below example, say in iteration#1  of the while loop one message is read from the stream. processMessage() is called for that message which after some processing, xdel() is called. By that time say the while loop is already in iteration#2 and there is nothing in the stream so it blocks. xdel() is not executed until the 'block' time of xreadgroup() has passed.

I simulated this in Redis command line and I'm able to execute XDEL when XREADGROUP blocked waiting for messages in the stream.

Also, behavior related to this issue - call to xdel() from async() connection does not delete the message in this scenario.
#### Input Code

- Java/Kotlin/Scala/Groovy/… or Repo link if applicable:

```java
while (true) {       
                //block on stream for 1 min before retry
                List<StreamMessage<String, String>> messages = conn.sync()
                        .xreadgroup(consumer,
                                XReadArgs.Builder.count(1500).block(60000),
                                XReadArgs.StreamOffset.lastConsumed(streamName));
   
                executor.submit(() -> processMessage(messages);
        }

void processMessage( List<StreamMessage<String, String>> messages) {
//    This line blocks until xreadgroup() block time of 1min has passed
Long numDel = conn.sync()
                .xdel(streamName, messageIds.toArray(new String[]{}));
}

```
```
StackTrace when xdel() is blocked:
"Thread-2" #60 daemon prio=5 os_prio=0 tid=0x000000002382e000 nid=0x57c8 waiting on condition [0x000000003604e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076dfabfb0> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1775)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.lambdaworks.redis.protocol.AsyncCommand.await(AsyncCommand.java:82)
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:116)
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:96)
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:61)
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy18.xdel(Unknown Source)
	at com.bfm.rdc.MessageHandler.processMessage(MessageHandler.java:176)
	at com.bfm.rdc.MessageHandler.lambda$pollMessages$1(MessageHandler.java:104)
	at com.bfm.rdc.MessageHandler$$Lambda$86/1528387629.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x000000076b8e8e38> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```
#### Expected behavior/code

xdel() execution should not be blocked if block time is specified in xreadgroup()

#### Environment

- Lettuce version(s):  4.5.0.Final
- Redis version: 5.0

#### Additional context

Add any other context about the problem here. Do not add code as screenshots.

**Comment by mp911de** [comment]
If I understand you correctly, you're using the same connection for `XREAD` and `XDEL`.

If so, then the observed behavior works as designed. Lettuce connections represent single transport connections to Redis. If a connection is blocked by a blocking command (such as `XREAD` with a timeout, `BLPOP`, …), then the connection cannot progress to a subsequent command until the blocking command receives a response.

**Comment by rainhacker** [comment]
@mp911de Thanks for the prompt response and clarification. 

Yes, I'm using the same connection to call both xreadgroup() and xdel(). Your explanation makes sense to me as when I tried from command line, I had to start a second redis-cli to fire XDEL, which is a separate connection.
