### ISSUE TITLE
Connection Closed Prematurely Problem

### ISSUE THREAD

**Issue by MickMo** [lettuce-io/lettuce-core#919]
#### Current Behavior

Lettuce throw RedisConnectionException: Connection closed prematurely after I manually restart redis cluster.

I already read this https://github.com/spring-cloud/spring-cloud-gateway/issues/473
and it seems like a reactor-netty problem.

mylog:
```67 Caused by: io.lettuce.core.RedisCommandExecutionException: CLUSTERDOWN The cluster is down
68     at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:118)
69     at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:109)
70     at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:57)
71     at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:63)
72     at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:601)
73     at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:559)
74     at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:511)
75     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
76     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
77     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
78     at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
79     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
80     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
81     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
82     at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
83     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
84     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
85     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
86     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
87     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
88     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
89     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
90     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
91     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
92     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
93     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
94     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
95     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
96     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
97     ... 1 common frames omitted
98 2018-11-13T14:52:37.362 [http-nio-3038-exec-15] [ERROR] c.f.s.o.o.OrderService - msg: "head":{"channelCode":"21006","apiId":"304","transactionId":"cyMAS022018111314523703335","reqTime":"20181113145237","sign":"C9A70F92FB7B5BAA7566018C2B0455C8","version":1.0"},body:{"channelNo":"cyMAS022018111314523703335","phone":"13797116755","salesId":"100043","salesName":"VIPCard","dealType":"0","acceptTime":"20181113145237","amount":"0","isPay":"0","prodInfo":[{"prodId":"200003","prodName":"VIPCard","serverNum":"13797116755","quantity":"1"}]}
99 2018-11-13T14:52:37.362 [http-nio-3038-exec-15] [INFO] c.f.c.o.o.OrderAcceptController - OrderAcceptReq [cyMAS022018111314523703335|304|1.0|21006|cyMAS022018111314523703335|null|221.176.66.95|0|13797116755|100043|200003|VIPCard|VIPCard],OrderAcceptResp [cyMAS022018111314523703335|9999|server inner error.|0|12]
100 2018-11-13T14:52:37.362 [http-nio-3038-exec-15] [INFO] c.f.c.o.o.OrderAcceptController - accept order return: {"contractRoot":{"head":{"sign":"4daa37c61bb38d163444b1a56ecaa858","reqTime":"20181113145237","transactionId":"cyMAS022018111314523703335"},"body":{"payPrmts2":"","orderNo":"0","payPrmts3":"","requestId":"","resultCode":"9999","payWay":"","payOrganization":"","payPrmts1":"","resultMsg":"server inner error."}}}
101 2018-11-13T14:52:37.362 [http-nio-3038-exec-15] [INFO] c.f.c.o.o.OrderAcceptController - deal order end. transId: cyMAS022018111314523703335, cost time: 12ms
102 2018-11-13T14:52:37.918 [lettuce-eventExecutorLoop-1-5] [INFO] i.l.c.p.ConnectionWatchdog - Reconnecting, last destination was 10.250.0.96:7006
103 2018-11-13T14:52:37.918 [lettuce-nioEventLoop-6-4] [INFO] i.l.c.p.DefaultEndpoint - [channel=0x6c0b504a, /10.250.0.70:55809 -> /10.250.0.98:7013, epid=0x4b01] Closing channel because endpoint is already closed
104 2018-11-13T14:52:37.918 [lettuce-nioEventLoop-6-4] [WARN] i.l.c.p.ConnectionWatchdog - Cannot reconnect: io.lettuce.core.RedisConnectionException: Connection closed prematurely
105 io.lettuce.core.RedisConnectionException: Connection closed prematurely
106     at io.lettuce.core.PlainChannelInitializer$1.channelInactive(PlainChannelInitializer.java:80)
107     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
108     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
109     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
110     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
111     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
112     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
113     at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
114     at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
115     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
116     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
117     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
118     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
119     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
120     at java.lang.Thread.run(Thread.java:745)
121 2018-11-13T14:52:38.218 [lettuce-eventExecutorLoop-1-7] [INFO] i.l.c.p.ConnectionWatchdog - Reconnecting, last destination was /10.250.0.98:7013
122 2018-11-13T14:52:38.218 [lettuce-eventExecutorLoop-1-6] [INFO] i.l.c.p.ConnectionWatchdog - Reconnecting, last destination was 10.250.0.96:7004
123 2018-11-13T14:52:38.218 [lettuce-eventExecutorLoop-1-8] [INFO] i.l.c.p.ConnectionWatchdog - Reconnecting, last destination was /10.250.0.98:7018
124 2018-11-13T14:52:38.219 [lettuce-nioEventLoop-6-7] [INFO] i.l.c.p.DefaultEndpoint - [channel=0x0e6908a3, /10.250.0.70:58399 -> /10.250.0.96:7001, epid=0x4b0f] Closing channel because endpoint is already closed
125 2018-11-13T14:52:38.219 [lettuce-nioEventLoop-6-5] [INFO] i.l.c.p.DefaultEndpoint - [channel=0x2241eca3, /10.250.0.70:42877 -> /10.250.0.97:7009, epid=0x49c9] Closing channel because endpoint is already closed
126 2018-11-13T14:52:38.219 [lettuce-nioEventLoop-6-6] [WARN] i.l.c.p.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /10.250.0.96:7005
127 2018-11-13T14:52:38.219 [lettuce-nioEventLoop-6-7] [WARN] i.l.c.p.ConnectionWatchdog - Cannot reconnect: io.lettuce.core.RedisConnectionException: Connection closed prematurely
128 io.lettuce.core.RedisConnectionException: Connection closed prematurely
129     at io.lettuce.core.PlainChannelInitializer$1.channelInactive(PlainChannelInitializer.java:80)
130     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
131     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
132     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
133     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
134     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
135     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
136     at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
137     at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
138     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
139     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
140     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
141     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
142     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
143     at java.lang.Thread.run(Thread.java:745)
144 2018-11-13T14:52:38.219 [lettuce-nioEventLoop-6-5] [WARN] i.l.c.p.ConnectionWatchdog - Cannot reconnect: io.lettuce.core.RedisConnectionException: Connection closed prematurely
145 io.lettuce.core.RedisConnectionException: Connection closed prematurely
146     at io.lettuce.core.PlainChannelInitializer$1.channelInactive(PlainChannelInitializer.java:80)
147     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
148     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
149     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
150     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
151     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
152     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
153     at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)```

**Comment by mp911de** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

`CLUSTERDOWN` isn't something that Lettuce can handle because it indicates an underlying Redis problem with the cluster setup/communication. If the client cannot retrieve topology details or successfully connect at startup, it gives up on connecting.

**Comment by MickMo** [comment]
Thank you for replying.
I understand that if Redis Cluster go down,Lettuce can do nothing about it.
but what I experience is after Reids Cluster restart,my application work fine ,but it keep giving my a warming about `RedisConnectionException: Connection closed prematurely`.
so I Google it and find this https://github.com/spring-cloud/spring-cloud-gateway/issues/473
seems like there is a new version of Reactor Netty to fix it.
I want to know it's there any update of lettuce to fixed this?or it have nothing to do with lettuce?

**Comment by mp911de** [comment]
Rest assured, this isn't a netty issue. Lettuce is raising the exception itself (see [`PlainChannelInitializer`](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/PlainChannelInitializer.java#L80)).

Closing this one as it has been answered.
