### ISSUE TITLE
Error : Command INCR accepts 1 parameters but method declares 2 parameter(s)

### ISSUE THREAD

**Issue by GhaziTriki** [lettuce-io/lettuce-core#925]
#### Current Behavior

Assuming we have declared a an increment command. An exception is raised.

```

Caused by: io.lettuce.core.dynamic.CommandMethodSyntaxException: Command INCR accepts 1 parameters but method declares 2 parameter(s). Offending method: public abstract java.lang.Long org.bigbluebutton.common2.redis.commands.RecordingCommands.incrementRecords(java.lang.String)
    at io.lettuce.core.dynamic.DefaultCommandMethodVerifier.validateParameters(DefaultCommandMethodVerifier.java:109)
    at io.lettuce.core.dynamic.DefaultCommandMethodVerifier.validate(DefaultCommandMethodVerifier.java:71)
    at io.lettuce.core.dynamic.ExecutableCommandLookupStrategySupport$DefaultCommandFactoryResolver.resolveRedisCommandFactory(ExecutableCommandLookupStrategySupport.java:74)
    at io.lettuce.core.dynamic.ExecutableCommandLookupStrategySupport.resolveCommandFactory(ExecutableCommandLookupStrategySupport.java:48)
    at io.lettuce.core.dynamic.AsyncExecutableCommandLookupStrategy.resolveCommandMethod(AsyncExecutableCommandLookupStrategy.java:47)
    at io.lettuce.core.dynamic.RedisCommandFactory$CompositeCommandLookupStrategy.resolveCommandMethod(RedisCommandFactory.java:273)
    at io.lettuce.core.dynamic.RedisCommandFactory$BatchAwareCommandLookupStrategy.resolveCommandMethod(RedisCommandFactory.java:321)
    at io.lettuce.core.dynamic.RedisCommandFactory$CommandFactoryExecutorMethodInterceptor.<init>(RedisCommandFactory.java:212)
    at io.lettuce.core.dynamic.RedisCommandFactory.getCommands(RedisCommandFactory.java:192)
```

#### Input Code

```java
public interface RecordingCommands extends Commands {
    @Command("INCR ?0")
    Long incrementRecords(String key);
}
```

#### Expected behavior/code

The code above should work without raising any exception.

#### Environment

- Lettuce version(s): 5.1.2-RELEASE
- Redis version: Redis 3.0.6 (00000000/0) 64 bit

**Comment by mp911de** [comment]
The problem is that `DefaultCommandMethodVerifier` counts the parameters given by the method signature and adds any parameter bind markers to that. Therefore, it ends up with twice as many arguments.
