### ISSUE TITLE
Cannot create multiple redis cluster client(both with async pool) in one application.

### ISSUE THREAD

**Issue by lujia-zhang** [lettuce-io/lettuce-core#928]
#### Current Behavior
We tried to create two redis cluster client instance (both with async connection pooling) but the second one will always failed on exceptions:
```
2018-11-21 15:16:06,423 [pool-5-thread-1] ERROR 1288168431 - [lettuce - ClusterPipeline] Failed to flush pending commands.
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot allocate object
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_91]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_91]
	at com.houzz.common.nvpdb.LettuceRedisClusterPipeline.sync(LettuceRedisClusterPipeline.java:146) [common-nvpdb-1.0.jar:?]
	at com.houzz.ads.logging.AdEventLogger.logAdEvent(AdEventLogger.java:128) [adserver-1.0.jar:?]
	at com.houzz.ads.server.AdEngine.serveAds(AdEngine.java:183) [adserver-1.0.jar:?]
	at com.houzz.common.thriftgen.adsservice.AdServer$Processor$serveAds.getResult(AdServer.java:175) [common-thriftgen-1.0.jar:?]
	at com.houzz.common.thriftgen.adsservice.AdServer$Processor$serveAds.getResult(AdServer.java:160) [common-thriftgen-1.0.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.server.Invocation.run(Invocation.java:18) [libthrift-0.9.3.jar:0.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Cannot allocate object
	at io.lettuce.core.support.BoundedAsyncPool.lambda$makeObject0$7(BoundedAsyncPool.java:208) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_91]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778) ~[?:1.8.0_91]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140) ~[?:1.8.0_91]
	at io.lettuce.core.support.BoundedAsyncPool.makeObject0(BoundedAsyncPool.java:203) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.BoundedAsyncPool.acquire0(BoundedAsyncPool.java:184) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.BoundedAsyncPool.acquire(BoundedAsyncPool.java:138) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.AsyncConnectionPoolSupport$1.acquire(AsyncConnectionPoolSupport.java:118) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at com.houzz.common.lettuce.RedisCluster.getConnection(RedisCluster.java:109) ~[common-lettuce-1.0.jar:?]
	at com.houzz.common.nvpdb.LettuceRedisClusterPipeline.<init>(LettuceRedisClusterPipeline.java:47) ~[common-nvpdb-1.0.jar:?]
	at com.houzz.common.nvpdb.LettuceRedisClusterNvpdb.pipelined(LettuceRedisClusterNvpdb.java:113) ~[common-nvpdb-1.0.jar:?]
	at com.houzz.ads.logging.AdEventLogger.logAdEvent(AdEventLogger.java:123) ~[adserver-1.0.jar:?]
	... 10 more
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to [RedisURI [host='192.168.10.236', port=7000], RedisURI [host='192.168.10.159', port=7000], RedisURI [host='192.168.10.11', port=7000]]
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.cluster.RedisClusterClient.lambda$transformAsyncConnectionException$32(RedisClusterClient.java:1139) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.DefaultConnectionFuture.lambda$thenCompose$1(DefaultConnectionFuture.java:252) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_91]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778) ~[?:1.8.0_91]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140) ~[?:1.8.0_91]
	at io.lettuce.core.DefaultConnectionFuture.thenCompose(DefaultConnectionFuture.java:249) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.cluster.RedisClusterClient.transformAsyncConnectionException(RedisClusterClient.java:1136) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.cluster.RedisClusterClient.connectAsync(RedisClusterClient.java:374) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at com.houzz.common.lettuce.RedisCluster.lambda$new$0(RedisCluster.java:98) ~[common-lettuce-1.0.jar:?]
	at io.lettuce.core.support.AsyncConnectionPoolSupport$RedisPooledObjectFactory.create(AsyncConnectionPoolSupport.java:157) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.BoundedAsyncPool.makeObject0(BoundedAsyncPool.java:203) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.BoundedAsyncPool.acquire0(BoundedAsyncPool.java:184) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.BoundedAsyncPool.acquire(BoundedAsyncPool.java:138) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.AsyncConnectionPoolSupport$1.acquire(AsyncConnectionPoolSupport.java:118) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at com.houzz.common.lettuce.RedisCluster.getConnection(RedisCluster.java:109) ~[common-lettuce-1.0.jar:?]
	at com.houzz.common.nvpdb.LettuceRedisClusterPipeline.<init>(LettuceRedisClusterPipeline.java:47) ~[common-nvpdb-1.0.jar:?]
	at com.houzz.common.nvpdb.LettuceRedisClusterNvpdb.pipelined(LettuceRedisClusterNvpdb.java:113) ~[common-nvpdb-1.0.jar:?]
	at com.houzz.ads.logging.AdEventLogger.logAdEvent(AdEventLogger.java:123) ~[adserver-1.0.jar:?]
	... 10 more
Caused by: java.lang.IllegalStateException: Partitions not initialized. Initialize via RedisClusterClient.getPartitions().
	at io.lettuce.core.cluster.RedisClusterClient.connectClusterAsync(RedisClusterClient.java:562) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.cluster.RedisClusterClient.connectAsync(RedisClusterClient.java:374) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at com.houzz.common.lettuce.RedisCluster.lambda$new$0(RedisCluster.java:98) ~[common-lettuce-1.0.jar:?]
	at io.lettuce.core.support.AsyncConnectionPoolSupport$RedisPooledObjectFactory.create(AsyncConnectionPoolSupport.java:157) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.BoundedAsyncPool.makeObject0(BoundedAsyncPool.java:203) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.BoundedAsyncPool.acquire0(BoundedAsyncPool.java:184) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.BoundedAsyncPool.acquire(BoundedAsyncPool.java:138) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at io.lettuce.core.support.AsyncConnectionPoolSupport$1.acquire(AsyncConnectionPoolSupport.java:118) ~[lettuce-core-5.1.2.RELEASE.jar:?]
	at com.houzz.common.lettuce.RedisCluster.getConnection(RedisCluster.java:109) ~[common-lettuce-1.0.jar:?]
	at com.houzz.common.nvpdb.LettuceRedisClusterPipeline.<init>(LettuceRedisClusterPipeline.java:47) ~[common-nvpdb-1.0.jar:?]
	at com.houzz.common.nvpdb.LettuceRedisClusterNvpdb.pipelined(LettuceRedisClusterNvpdb.java:113) ~[common-nvpdb-1.0.jar:?]
	at com.houzz.ads.logging.AdEventLogger.logAdEvent(AdEventLogger.java:123) ~[adserver-1.0.jar:?]
	... 10 more```

#### Input Code

How we config redis client:
```java
        ClientResources res = DefaultClientResources.create();
        clusterClient = RedisClusterClient.create(res, redisClusterURIs);
        clusterClient.setDefaultTimeout(Duration.ofSeconds(params.getDefaultTimeoutSecond()));
        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enableAllAdaptiveRefreshTriggers()
                .adaptiveRefreshTriggersTimeout(Duration.ofSeconds(adaptiveRefreshTimeout))
                .build();
        clusterClient.setOptions(ClusterClientOptions.builder()
                .autoReconnect(true)
                .cancelCommandsOnReconnectFailure(true)
                .disconnectedBehavior(ClusterClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                .topologyRefreshOptions(topologyRefreshOptions)
                .build());

        BoundedPoolConfig poolConfig = BoundedPoolConfig.builder()
                .maxTotal(12)
                .testOnAcquire()
                .build();
        pool = AsyncConnectionPoolSupport.createBoundedObjectPool(
                () -> clusterClient.connectAsync(StringCodec.UTF8), poolConfig);
```

#### Expected behavior/code

I'd like to know the root cause for this.

#### Environment

- Lettuce version(s): 5.1.2.RELEASE
- Redis version: 3.2.8

**Comment by mp911de** [comment]
You need to load partitions once before you can use asynchronous `RedisClusterClient` connect methods.

This is, because partition refresh is a synchronous (blocking) process that needs to run before connecting to the cluster. Please call `RedisClusterClient.getPartitions()` after initializing `RedisClusterClient`. This call will fetch the partitions and optionally activate topology refresh. Afterwards, you're good to use async connect methods.
