### ISSUE TITLE
Caused by: io.lettuce.core.RedisCommandInterruptedException: Command interrupted

### ISSUE THREAD

**Issue by happywzc** [lettuce-io/lettuce-core#935]
## Bug Report

```
org.springframework.data.redis.RedisSystemException: Redis command interrupted; nested exception is io.lettuce.core.RedisCommandInterruptedException: Command interrupted
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:62)
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
        at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
        at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
        at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.set(LettuceStringCommands.java:180)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.set(DefaultedRedisConnection.java:281)
        at org.springframework.data.redis.connection.DefaultStringRedisConnection.set(DefaultStringRedisConnection.java:955)
        at org.springframework.data.redis.connection.DefaultStringRedisConnection.set(DefaultStringRedisConnection.java:2329)
        at com.wisers.crawler40.spider.commons.redis.RedisServer$1.doInRedis(RedisServer.java:67)
        at com.wisers.crawler40.spider.commons.redis.RedisServer$1.doInRedis(RedisServer.java:64)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
        at com.wisers.crawler40.spider.commons.redis.RedisServer.set(RedisServer.java:64)
        at com.wisers.crawler40.spider.node.utils.ReportErrorMsgUtil.reportErrorMsg(ReportErrorMsgUtil.java:109)
        at com.wisers.crawler40.spider.parser.task.ParserTaskImpl.logParserResult(ParserTaskImpl.java:181)
        at com.wisers.crawler40.spider.parser.task.ParserTaskImpl.lambda$doTask$0(ParserTaskImpl.java:93)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.wisers.crawler40.spider.parser.task.ParserTaskImpl.doTask(ParserTaskImpl.java:74)
        at com.wisers.crawler40.spider.node.task.SpiderTaskImpl.callBack(SpiderTaskImpl.java:529)
        at com.wisers.crawler40.spider.node.task.SpiderTaskImpl.getHttpResult(SpiderTaskImpl.java:322)
        at com.wisers.crawler40.spider.node.task.SpiderTaskImpl.doTask(SpiderTaskImpl.java:117)
        at com.wisers.crawler40.spider.node.task.MonitorSpiderTaskImpl.lambda$doTask$0(MonitorSpiderTaskImpl.java:112)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.lettuce.core.RedisCommandInterruptedException: Command interrupted
        at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:87)
        at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:112)
        at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy56.set(Unknown Source)
        at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.set(LettuceStringCommands.java:178)
        ... 22 more
Caused by: java.lang.InterruptedException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:83)
        ... 27 more
```
#### Current Behavior

A clear and concise description of the behavior.

#### Input Code

- Java/Kotlin/Scala/Groovy/… or Repo link if applicable:

```java
public boolean set(String key, String value, String nxxx, long time) {
    final String key1 = keyPrefix(key);
    RedisStringCommands.SetOption option= RedisStringCommands.SetOption.upsert();
    if(nxxx.equalsIgnoreCase("NX")){
      option=RedisStringCommands.SetOption.ifAbsent();
    }else if(nxxx.equalsIgnoreCase("XX")){
      option=RedisStringCommands.SetOption.ifPresent();
    }
    final RedisStringCommands.SetOption option1=option;

    return  stringRedisTemplate.execute( new RedisCallback<Boolean>() {
      public Boolean doInRedis(RedisConnection connection) throws DataAccessException {
        StringRedisConnection stringRedisConn = (StringRedisConnection)connection;
        return stringRedisConn.set(key1,value,Expiration.seconds(time),option1);
      }
    },true);
  }
```

#### Expected behavior/code

A clear and concise description of what you expected to happen (or code).

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

#### Additional context

Add any other context about the problem here. Do not add code as screenshots.

**Comment by mp911de** [comment]
`InterruptedException` is an exception that is raised by the JVM as soon as `Thread.interrupt()` gets called (typically invoked during application shutdown).

Closing this one as there's nothing we can do about, in fact, everything is working as expected.

**Comment by hxing-Do** [comment]
the result Thread.currentThread().isInterrupted()  is false
