### ISSUE TITLE
How to map remote host & port to localhost using Lettuce 

### ISSUE THREAD

**Issue by lujia-zhang** [lettuce-io/lettuce-core#941]
Hi, we're using Lettuce as our RedisCluster client but for dev environment, we're using magic_proxy to map remote redis cluster hosts and ports to localhost, eg:
```
28000:192.168.10.236:7000
28001:192.168.10.236:7001
28002:192.168.10.236:7002
28003:192.168.10.236:7003
28004:192.168.10.236:7004
28005:192.168.10.236:7005

38000:192.168.10.159:7000
38001:192.168.10.159:7001
38002:192.168.10.159:7002
38003:192.168.10.159:7003
38004:192.168.10.159:7004
38005:192.168.10.159:7005
...
```
It very important to have the ability to test locally with the rediscluster running in staging environment. I can use a list of urls like `[localhost:28000, localhost:38000]` as the initial url to create the redis client, but  the client cannot refresh the topology and can cannot handle redirections. Is there a way I can create a host_port_mapping using Lettuce? eg. Everytime when Lettuce trying to connect to a node, we use a host_port_map_helper to map the remote urls to localhost:port? Following is the exception I got:

```
    2018-11-28 15:51:53,075 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.cluster.topology.ClusterTopologyRefresh - Unable to connect to 192.168.10.159:7004
    java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.10.62:7004
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:329)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:269)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.10.62:7004
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        ... 8 more
    2018-11-28 15:51:53,075 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.cluster.topology.ClusterTopologyRefresh - Unable to connect to 192.168.10.34:7005
    java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.10.34:7005
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:329)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:269)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.10.34:7005
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        ... 8 more
```

**Comment by mp911de** [comment]
We exposed with Lettuce 5.1 (#689) the `MappingSocketAddressResolver` API that allows you to customize how a `RedisURI` is resolved to a `SocketAddress`. I attached an example of how to use and create `SocketAddressResolver` for mapping purposes. You can also extend `SocketAddressResolver` if you desire customization beyond the mapping `Function`.

```java
MappingSocketAddressResolver resolver = MappingSocketAddressResolver.create(DnsResolvers.UNRESOLVED,  
    hostAndPort -> {
    
        if(hostAndPort.getHostText().startsWith("192.168")){
            return HostAndPort.of("localhost", hostAndPort.getPort());
        }

        return hostAndPort;
    });

ClientResources clientResources = ClientResources.builder()
            .socketAddressResolver(resolver)
            .build();

RedisClusterClient.create(clientResources, redisUri);
```

**Comment by lujia-zhang** [comment]
@mp911de Thank you so much for the information. This works perfect for me!

**Comment by hero-zhanghao** [comment]
@mp911de HI，I am using spring boot data redis to connect to the redis cluster, and I have encountered this problem, but I don't know how to apply the scheme you proposed, could you please help me?Thank you very much.

**Comment by mp911de** [comment]
Spring Boot allows configuration of a `ClientResources` bean, see https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.java#L59.

**Comment by hero-zhanghao** [comment]
Thank you very much. It's a perfect solution to my problem!
