### ISSUE TITLE
Getting Command time out Exception Frequently 

### ISSUE THREAD

**Issue by chinmayvenkat** [lettuce-io/lettuce-core#946]
## Bug Report

while I Implemented synchronous execution for standalone/Sentinel , I am Getting Redis Command time out issue while I am implementing SET AND MAP Implementations . for normal set/get methods are working fine 
#### Current Behavior

when I implement the SET AND MAP Implementations I am getting the Redis Command time out issues continuously 
#### Input Code

- Java/Kotlin/Scala/Groovy/… or Repo link if applicable:

```java
// Pool I am using 
protected GenericObjectPoolConfig genericPoolConfiguration(int connections) {
		GenericObjectPoolConfig config = new GenericObjectPoolConfig();
		config.setMinIdle(8);
		config.setTestWhileIdle(true);
		config.setMaxTotal(connections);
		config.setMaxIdle(config.getMaxTotal()/2);
		config.setMinEvictableIdleTimeMillis(8000);
		config.setTimeBetweenEvictionRunsMillis(3000);
		return config;
	}
------------------------------------------------------------------------
client 
---------------------------------------------
RedisClient client = RedisClient.create();
		client.setOptions(ClientOptions.builder().autoReconnect(true).cancelCommandsOnReconnectFailure(false).suspendReconnectOnProtocolFailure(false).disconnectedBehavior(DisconnectedBehavior.ACCEPT_COMMANDS).build());
		
			List<String> connectionParams = splitHostsAndPorts(redisSentinelsCrossDc);
		 pool = ConnectionPoolSupport
	               .createGenericObjectPool(() -> MasterSlave.connect(client, codec,
	       				RedisURI.Builder.sentinel(connectionParams.get(0),Integer.parseInt(connectionParams.get(1)), redisMasterCrossDc).withSentinel(connectionParams.get(2),Integer.parseInt(connectionParams.get(3))).withSentinel(connectionParams.get(4),Integer.parseInt(connectionParams.get(5))).build()), genericPoolConfiguration(connections));
========================================
Example method 
====================================
public void addToSET(K key, V value) {
		long startTime = new Date().getTime();
		try (StatefulRedisConnection<K,V> connection = getConnection()) {
				RedisCommands<K,V> syncCommands = connection.sync();
				syncCommands.sadd(key, value);		
		}catch (Exception e) {
			logger.error("Error While Executing key : {} from addToSET : {} ",key,e);
		}finally{
			if(logger.isDebugEnabled()) {
				logger.debug("Time Taken to Execute key : {} from addToSET : {} ",key,(new Date().getTime()-startTime));
			}
		}	
	}

```

#### Expected behavior/code

it  is getting Command time out exception
#### Environment

- Lettuce version(s): [e.g. 5.1.3.RELEASE]
- Redis version: [e.g. 5.0.2]

#### Additional context

Add any other context about the problem here. Do not add code as screenshots.

**Comment by mp911de** [comment]
Can you provide a reproducer for timeouts? According to the description above, the code provided here is not the one that causes timeouts.

**Comment by chinmayvenkat** [comment]
[pool-36-thread-10] ERROR com.vistara.redis.RedisConnection - Error While Executing rediskey : API_STATS:INTG_UID_CATEGORY_MAP : mapKey : VISTARA : mapValue : INTERNAL_INTEGRATION  from setMap : {}
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
        at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
        at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
        at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy219.hset(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor266.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:191)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy219.hset(Unknown Source)
        at com.vistara.redis.RedisConnection.setMap(RedisConnection.java:368)
        at com.vistara.util.api.stats.APIStatsUtil.addToIntgUIDCategoryMap(APIStatsUtil.java:325)
        at com.vistara.util.api.stats.APIStatsUtil.getIntgBucketKeyField(APIStatsUtil.java:302)
        at com.vistara.api.util.stats.APIInstance.getAPIRequestCounters(APIInstance.java:126)
        at com.vistara.api.util.stats.APIInstance.call(APIInstance.java:80)
        at com.vistara.api.util.stats.APIInstance.call(APIInstance.java:39)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
-----------------------------------------------------------------------------------------------------
LettuceFutures.awaitOrCancel(LettuceFutures.java:114) it throws exception

**Comment by chinmayvenkat** [comment]
I am using multithreading to call methods

**Comment by mp911de** [comment]
These above are stack traces which do not help to reproduce the issue. Please provide code that is able to reliably reproduce the mentioned timeout.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?
