### ISSUE TITLE
lettuce-core-5.0.5.RELEASE io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by decaoxiansheng** [lettuce-io/lettuce-core#958]
The exception stack information as follows
```
exception: io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer, dubbo version: 2.5.3, current host: 10.1.0.11
1
io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer
        at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:125)
        at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:118)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy55.mget(Unknown Source)
。。。。。。。。。。。。。。
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

**Comment by decaoxiansheng** [comment]
Has been modified.Thank you!

**Comment by mp911de** [comment]
Thank you. There's nothing unusual in `IOException: Connection reset by peer`. In this case, the connection was disconnected while the client was reading data from the transport. See [this post](https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean) for further details. You might want to investigate why this happened by checking your Redis server and the components that are involved between the client and your Redis server (such as network components).
