### ISSUE TITLE
NullPointerException and OutOfMemoryError

### ISSUE THREAD

**Issue by jinshubao** [lettuce-io/lettuce-core#969]
```
2019-01-17 10:18:28.237  INFO 20530 --- [lettuce-eventExecutorLoop-1-11] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was 172.16.0.60:6379
2019-01-17 10:18:28.238 DEBUG 20530 --- [lettuce-eventExecutorLoop-1-11] io.lettuce.core.RedisClient              : Resolved SocketAddress 172.16.0.60:6379 using RedisURI [host='172.16.0.60', port=6379]
2019-01-17 10:18:28.238 DEBUG 20530 --- [lettuce-eventExecutorLoop-1-11] i.l.core.protocol.ReconnectionHandler    : Reconnecting to Redis at 172.16.0.60:6379
2019-01-17 10:18:28.239 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.CommandHandler  : [channel=0xe5d971d9, [id: 0x4fec3f01] (inactive), chid=0x62] channelRegistered()
2019-01-17 10:18:28.239 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.CommandHandler  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, chid=0x62] channelActive()
2019-01-17 10:18:28.240 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, epid=0x2] activateEndpointAndExecuteBufferedCommands 47 command(s) buffered
2019-01-17 10:18:28.240 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, epid=0x2] activating endpoint
2019-01-17 10:18:28.240 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.RedisChannelHandler      : dispatching command AsyncCommand [type=AUTH, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:18:28.240 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, epid=0x2] write() writeAndFlush command AsyncCommand [type=AUTH, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:18:28.240 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.CommandHandler  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, chid=0x62] write(ctx, AsyncCommand [type=AUTH, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
2019-01-17 10:18:28.240 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.CommandEncoder  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379] writing command AsyncCommand [type=AUTH, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:18:28.240 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, epid=0x2] write() done
2019-01-17 10:18:39.693 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.CommandHandler  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, chid=0x62] Storing exception in AsyncCommand [type=AUTH, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:18:40.536 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.CommandHandler  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, chid=0x62] Unexpected exception during request: java.lang.OutOfMemoryError: GC overhead limit exceeded

java.lang.OutOfMemoryError: GC overhead limit exceeded

2019-01-17 10:18:40.537 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.CommandHandler  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, chid=0x62] Received: 5 bytes, 0 commands in the stack
2019-01-17 10:18:40.537 DEBUG 20530 --- [lettuce-nioEventLoop-4-2] i.l.core.protocol.RedisStateMachine      : Decode null
2019-01-17 10:18:40.537  WARN 20530 --- [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.CommandHandler  : [channel=0xe5d971d9, /172.16.0.56:54672 -> /172.16.0.60:6379, chid=0x62] Unexpected exception during request: java.lang.NullPointerException

java.lang.NullPointerException: null
	at io.lettuce.core.protocol.RedisStateMachine.safeSetSingle(RedisStateMachine.java:391)
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:124)
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:77)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:704)
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:100)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:556)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

2019-01-17 10:19:00.001 DEBUG 20530 --- [pool-8-thread-1] io.lettuce.core.RedisChannelHandler      : dispatching command AsyncCommand [type=SMEMBERS, output=ValueSetOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:19:00.001 DEBUG 20530 --- [pool-8-thread-1] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, epid=0x1] write() writeAndFlush command AsyncCommand [type=SMEMBERS, output=ValueSetOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:19:00.001 DEBUG 20530 --- [pool-8-thread-1] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, epid=0x1] write() done
2019-01-17 10:19:00.002 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.CommandHandler  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, chid=0x1] write(ctx, AsyncCommand [type=SMEMBERS, output=ValueSetOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], promise)
2019-01-17 10:19:00.002 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.CommandEncoder  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379] writing command AsyncCommand [type=SMEMBERS, output=ValueSetOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:19:00.002 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.CommandHandler  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, chid=0x1] Received: 4 bytes, 1 commands in the stack
2019-01-17 10:19:00.002 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.CommandHandler  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, chid=0x1] Stack contains: 1 commands
2019-01-17 10:19:00.002 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine      : Decode AsyncCommand [type=SMEMBERS, output=ValueSetOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:19:00.002 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine      : Decoded AsyncCommand [type=SMEMBERS, output=ValueSetOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], empty stack: true
2019-01-17 10:19:00.003 DEBUG 20530 --- [pool-8-thread-1] io.lettuce.core.RedisChannelHandler      : dispatching command AsyncCommand [type=DEL, output=IntegerOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:19:00.003 DEBUG 20530 --- [pool-8-thread-1] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, epid=0x1] write() writeAndFlush command AsyncCommand [type=DEL, output=IntegerOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:19:00.003 DEBUG 20530 --- [pool-8-thread-1] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, epid=0x1] write() done
2019-01-17 10:19:00.003 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.CommandHandler  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, chid=0x1] write(ctx, AsyncCommand [type=DEL, output=IntegerOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
2019-01-17 10:19:00.003 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.CommandEncoder  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379] writing command AsyncCommand [type=DEL, output=IntegerOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:19:00.003 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.CommandHandler  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, chid=0x1] Received: 4 bytes, 1 commands in the stack
2019-01-17 10:19:00.003 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.CommandHandler  : [channel=0x3daf8e88, /172.16.0.56:46386 -> /172.16.0.60:6379, chid=0x1] Stack contains: 1 commands
2019-01-17 10:19:00.003 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine      : Decode AsyncCommand [type=DEL, output=IntegerOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
2019-01-17 10:19:00.003 DEBUG 20530 --- [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine      : Decoded AsyncCommand [type=DEL, output=IntegerOutput [output=0, error='null'], commandType=io.lettuce.core.protocol.Command], empty stack: true
```

#### Environment

- Lettuce version(s): [5.1.2.RELEASE]
- Redis version: [3.2.8]

看了5.1.2.RELEASE版本和5.1.3.RELEASE版本的源码，都存在NPE.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by jinshubao** [comment]
不好意思，给你们造成困扰，超时的问题已经解决了，没有设置会话保持引起的。
但是`RedisStateMachine `确实存在NPE的问题，

```

/**
 * State machine that decodes redis server responses encoded according to the <a href="http://redis.io/topics/protocol">Unified
 * Request Protocol (RESP)</a>.
 *
 * @author Will Glozer
 * @author Mark Paluch
 * @author Helly Guo
 */
public class RedisStateMachine {

    //省略其他代码

    /**
     * Decode a command using the input buffer.
     *
     * @param buffer Buffer containing data from the server.
     * @param output Current command output.
     * @return true if a complete response was read.
     */
    public boolean decode(ByteBuf buffer, CommandOutput<?, ?, ?> output) {
        return decode(buffer, null, output);
    }

    /**
     * Attempt to decode a redis response and return a flag indicating whether a complete response was read.
     *
     * @param buffer Buffer containing data from the server.
     * @param command the command itself
     * @param output Current command output.
     * @return true if a complete response was read.
     */
    public boolean decode(ByteBuf buffer, RedisCommand<?, ?, ?> command, CommandOutput<?, ?, ?> output) {
        int length, end;
        ByteBuffer bytes;

        if (debugEnabled) {
            logger.debug("Decode {}", command);
        }

        if (isEmpty(stack)) {
            add(stack, new State());
        }

        if (output == null) {
            return isEmpty(stack);
        }

        loop:

        while (!isEmpty(stack)) {
            State state = peek(stack);

            if (state.type == null) {
                if (!buffer.isReadable()) {
                    break;
                }
                state.type = readReplyType(buffer);
                buffer.markReaderIndex();
            }

            switch (state.type) {
                case SINGLE:
                    if ((bytes = readLine(buffer)) == null) {
                        break loop;
                    }

                    if (!QUEUED.equals(bytes)) {
                        //command为null
                        safeSetSingle(output, bytes, command);
                    }
                    break;
                case ERROR:
                    if ((bytes = readLine(buffer)) == null) {
                        break loop;
                    }
                    //command为null
                    safeSetError(output, bytes, command);
                    break;
                case INTEGER:
                    if ((end = findLineEnd(buffer)) == -1) {
                        break loop;
                    }
                    long integer = readLong(buffer, buffer.readerIndex(), end);
                    //command为null
                    safeSet(output, integer, command);
                    break;
                case BULK:
                    if ((end = findLineEnd(buffer)) == -1) {
                        break loop;
                    }
                    length = (int) readLong(buffer, buffer.readerIndex(), end);
                    if (length == -1) {
                        //command为null
                        safeSet(output, null, command);
                    } else {
                        state.type = BYTES;
                        state.count = length + 2;
                        buffer.markReaderIndex();
                        continue loop;
                    }
                    break;
                case MULTI:
                    if (state.count == -1) {
                        if ((end = findLineEnd(buffer)) == -1) {
                            break loop;
                        }
                        length = (int) readLong(buffer, buffer.readerIndex(), end);
                        state.count = length;
                        buffer.markReaderIndex();
                        //command为null
                        safeMulti(output, state.count, command);
                    }

                    if (state.count <= 0) {
                        break;
                    }

                    state.count--;
                    addFirst(stack, new State());

                    continue loop;
                case BYTES:
                    if ((bytes = readBytes(buffer, state.count)) == null) {
                        break loop;
                    }
                    //command为null
                    safeSet(output, bytes, command);
                    break;
                default:
                    throw new IllegalStateException("State " + state.type + " not supported");
            }

            buffer.markReaderIndex();
            remove(stack);

            output.complete(size(stack));
        }

        if (debugEnabled) {
            logger.debug("Decoded {}, empty stack: {}", command, isEmpty(stack));
        }

        return isEmpty(stack);
    }


    //省略其他代码
    
    /**
     * Safely sets {@link CommandOutput#set(long)}. Completes a command exceptionally in case an exception occurs.
     *
     * @param output
     * @param integer
     * @param command
     */
    protected void safeSet(CommandOutput<?, ?, ?> output, long integer, RedisCommand<?, ?, ?> command) {

        try {
            output.set(integer);
        } catch (Exception e) {
            //command为null时NPE
            command.completeExceptionally(e);
        }
    }

    /**
     * Safely sets {@link CommandOutput#set(ByteBuffer)}. Completes a command exceptionally in case an exception occurs.
     *
     * @param output
     * @param bytes
     * @param command
     */
    protected void safeSet(CommandOutput<?, ?, ?> output, ByteBuffer bytes, RedisCommand<?, ?, ?> command) {

        try {
            output.set(bytes);
        } catch (Exception e) {
            //command为null时NPE
            command.completeExceptionally(e);
        }
    }

    /**
     * Safely sets {@link CommandOutput#set(ByteBuffer)}. Completes a command exceptionally in case an exception occurs.
     *
     * @param output
     * @param bytes
     * @param command
     */
    protected void safeSetSingle(CommandOutput<?, ?, ?> output, ByteBuffer bytes, RedisCommand<?, ?, ?> command) {

        try {
            output.set(bytes);
        } catch (Exception e) {
            //command为null时NPE
            command.completeExceptionally(e);
        }
    }

    /**
     * Safely sets {@link CommandOutput#multi(int)}. Completes a command exceptionally in case an exception occurs.
     *
     * @param output
     * @param count
     * @param command
     */
    protected void safeMulti(CommandOutput<?, ?, ?> output, int count, RedisCommand<?, ?, ?> command) {

        try {
            output.multi(count);
        } catch (Exception e) {
            //command为null时NPE
            command.completeExceptionally(e);
        }
    }

    /**
     * Safely sets {@link CommandOutput#setError(ByteBuffer)}. Completes a command exceptionally in case an exception occurs.
     *
     * @param output
     * @param bytes
     * @param command
     */
    protected void safeSetError(CommandOutput<?, ?, ?> output, ByteBuffer bytes, RedisCommand<?, ?, ?> command) {

        try {
            output.setError(bytes);
        } catch (Exception e) {
            //command为null时NPE
            command.completeExceptionally(e);
        }
    }

}

```

**Comment by mp911de** [comment]
Sorry, this issue tracker is English-only, we do not understand Chinese.
