### ISSUE TITLE
getTopologyRefreshSource() should filter nodes with FAIL flag

### ISSUE THREAD

**Issue by alessandrosimi-sa** [lettuce-io/lettuce-core#985]
#### Current Behavior

A redis cluster client with `dynamicRefreshSources` enabled uses failed nodes to retrieve partitions.
This has no impact on the topology refresh but it creates noise in the log.
```
ClusterTopologyRefresh - Unable to connect to 127.0.0.1:8079
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:8079
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:329)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
```

#### Input Code

The `getTopologyRefreshSource()` method in the `RedisClusterClient` class.
```java
protected Iterable<RedisURI> getTopologyRefreshSource() {

    boolean initialSeedNodes = !useDynamicRefreshSources();

    Iterable<RedisURI> seed;
    if (initialSeedNodes || partitions == null || partitions.isEmpty()) {
        seed = this.initialUris;
    } else {
        List<RedisURI> uris = new ArrayList<>();
        for (RedisClusterNode partition : TopologyComparators.sortByUri(partitions)) {
            uris.add(partition.getUri());
        }
        seed = uris;
    }
    return seed;
}
```
should filter out the `RedisClusterNode` with FAILED flag.

#### Expected behavior/code

```java
for (RedisClusterNode partition : TopologyComparators.sortByUri(partitions)) if (!partition.is(NodeFlag.FAIL)) {
    uris.add(partition.getUri());
}
```

#### Environment

- Lettuce version(s): 5.1.4.RELEASE
- Redis version: 5.x

**Comment by mp911de** [comment]
Thanks for reporting. The `FAIL` flag is set from the perspective of other Redis servers, not from the perspective of the client. So while one server cannot reach another one, this isn't necessarily true from the client perspective.

`RedisClusterClient.getTopologyRefreshSource()` is a `protected` template method that can be overridden by subclasses if the application requires customization. So this customization should happen in your code/subclass.

Closing this ticket for now without change because this is a specific request about client behavior and you're the first one asking for this change. We will revisit the ticket if there is more demand for this feature.
