### ISSUE TITLE
Cancel ClusterTopologyRefreshTask in RedisClusterClient.shutdownAsync()

### ISSUE THREAD

**Issue by johnsiu** [lettuce-io/lettuce-core#989]
#### Current Behavior

Periodically seeing this exception after shutting down RedisClusterClient
```
SEVERE: Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:845)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:756)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at io.lettuce.core.AbstractRedisClient.initializeChannelAsync0(AbstractRedisClient.java:323)
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync$0(AbstractRedisClient.java:294)
	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:137)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2070)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:138)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:138)
	at reactor.core.publisher.LambdaMonoSubscriber.onSubscribe(LambdaMonoSubscriber.java:87)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:172)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:172)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3694)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:3800)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3688)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3655)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3627)
	at io.lettuce.core.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:289)
	at io.lettuce.core.cluster.RedisClusterClient.connectStatefulAsync(RedisClusterClient.java:711)
	at io.lettuce.core.cluster.RedisClusterClient.connectToNodeAsync(RedisClusterClient.java:499)
	at io.lettuce.core.cluster.RedisClusterClient$NodeConnectionFactoryImpl.connectToNodeAsync(RedisClusterClient.java:1174)
	at io.lettuce.core.cluster.topology.ClusterTopologyRefresh.getConnections(ClusterTopologyRefresh.java:212)
	at io.lettuce.core.cluster.topology.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:81)
	at io.lettuce.core.cluster.RedisClusterClient.doLoadPartitions(RedisClusterClient.java:871)
	at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:844)
	at io.lettuce.core.cluster.RedisClusterClient.reloadPartitions(RedisClusterClient.java:790)
	at io.lettuce.core.cluster.ClusterTopologyRefreshScheduler$ClusterTopologyRefreshTask.run(ClusterTopologyRefreshScheduler.java:204)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
- Issue 1
When RedisClusterClient.shutdownAsync() is called, any scheduled clusterTopologyRefresh is not cancelled. That's because the logic to cancel the ScheduledFuture is only in RedisClusterClient.shutdown(), but not RedisClusterClient.shutdownAsync(). This causes the task to leak after the caller called the latter method to shut down the cluster client.

- Issue 2
Even if RedisClusterClient.shutdown() is used, we could still have a leak because there is a race condition where an in progress refresh could reactivate and reschedule the clusterTopologyRefresh task when the cluster client is being shutdown or has already shutdown. The input code below illustrates how to reproduce this issue. A very short refresh period is purposely used to make this issue much easier to reproduce. The race condition can happen even for long refresh period.

#### Input Code

```java
    RedisClusterClient client = RedisClusterClient.create(DefaultClientResources.create(),
        REDIS_URI);

    client.setOptions(ClusterClientOptions.builder()
        .topologyRefreshOptions(ClusterTopologyRefreshOptions.builder()
            .enablePeriodicRefresh(Duration.ofMillis(1))
            .build())
        .build());

    client.connect();

    client.shutdown();
```

#### Environment

- Lettuce version(s): 5.1.4.RELEASE
- Redis version: 4.0.11

#### Possible Solution

For issue 1, we could override AbstractRedisClient's shutdownAsync() in RedisClusterClient to cancel the refresh task similar to what RedisClusterClient.shutdown() is doing.

For issue 2, in RedisClusterClient.activateTopologyRefreshIfNeeded(), we could first check whether the client is being shutdown or has already shutdown before scheduling the clusterTopologyRefreshScheduler.

**Comment by mp911de** [comment]
Thanks a lot for reporting the issue. Have you tried using different quiet timeouts? Topology refresh is non-atomic and interrupts can happen at any arbitrary place.

**Comment by johnsiu** [comment]
Thanks for the quick reply.

I understand that Topology refresh is non-atomic, but the the expectation in that there should not be any  scheduled  clusterTopologyRefreshScheduler left uncancelled after RedisClusterClient shutdown. This causes exception spam because the uncancelled task still runs periodically and fails each time.

Playing with the graceful shutdown quiet timeout didn't help with issue 1 and 2.

**Comment by mp911de** [comment]
We will fix the cancellation in `shutdownAsync` as this is an obvious bug. For the topology refresh itself, we can only add additional guards to check whether the evenloop is active and not progress with further activity.

Netty guarantees connection disposal if the related eventloop is shut down, so Lettuce isn't creating connections that linger around.

**Comment by mp911de** [comment]
That's fixed now.
